# **Step 1 — Food Loss and Waste Data Exploration & Validation**

**Purpose:** profile the FAO Food Loss and Waste dataset, identify data-quality risks, validate geographic and commodity codes against authoritative references, and produce reviewable reports without silently changing the source data.

## ***Import libraries***

In [165]:
import pandas as pd
import numpy as np
from pathlib import Path
from IPython.display import display
import matplotlib.pyplot as plt

## ***Read the dataset***

In [166]:
# Locate the source CSV without hard-coding one working directory.
# You can override this with an environment variable named FOOD_LOSS_DATA_PATH.
import os
from pathlib import Path
import pandas as pd
from IPython.display import display

DATA_FILENAME = "World-food-waste.csv"
configured_path = os.getenv("FOOD_LOSS_DATA_PATH")

candidate_paths = []
if configured_path:
    candidate_paths.append(Path(configured_path).expanduser())

cwd = Path.cwd()
candidate_paths.extend([
    cwd / DATA_FILENAME,
    cwd / "data-set" / DATA_FILENAME,
    cwd.parent / "data-set" / DATA_FILENAME,
    cwd / ".." / "data-set" / DATA_FILENAME,
    cwd / "data" / DATA_FILENAME,
    cwd.parent / "data" / DATA_FILENAME,
])

DATA_PATH = next((candidate.resolve() for candidate in candidate_paths
                  if candidate.exists() and candidate.is_file()), None)

if DATA_PATH is None:
    checked = "\n".join(f"- {candidate}" for candidate in candidate_paths)
    raise FileNotFoundError(
        f"Could not locate {DATA_FILENAME}. Set FOOD_LOSS_DATA_PATH or place "
        f"the CSV in one of the expected locations:\n{checked}"
    )

world_food_loss = pd.read_csv(DATA_PATH, low_memory=False)
print(f"Loaded: {DATA_PATH}")
print(f"Shape: {world_food_loss.shape}")
display(world_food_loss.head(3))

Loaded: D:\My_projects\data-engineer\waste-food-project\data-set\World-food-waste.csv
Shape: (31465, 18)

,m49_code,country,region,cpc_code,commodity,year,loss_percentage,loss_percentage_original,loss_quantity,activity,food_supply_stage,treatment,cause_of_loss,sample_size,method_data_collection,reference,url,notes
0,1,World,NaN,0111,Wheat,2022,1.0,1%,NaN,Processing,Processing,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived product is wheat flour
1,1,World,NaN,0112,Maize (corn),2022,0.5,0.5%,NaN,Processing,Processing,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived product is maize flour.
2,1,World,NaN,0112,Maize (corn),2022,2.0,2%,NaN,Processing,Processing,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived product is Maize (corn) grits.

## **Understand Columns**

![Food Loss Image](../images/columns.jpg)

## **Expected Problems**

### Validation principles
- **Profile first:** inspect data types, missingness, uniqueness, duplicates, and distributions.
- **Validate against references:** distinguish invalid codes from valid codes paired with the wrong label.
- **Flag, do not silently repair:** normalization is for comparison; original values remain unchanged.
- **Keep provenance:** record the reference source, retrieval date, rule, and review outcome.
- **Treat anomalies as review candidates:** outliers, rare values, and missing references are not automatically errors.

![Food Loss Image](../images/expected-problems.jpg)

## ***Data set overview***

In [167]:
print("=" * 60)
print("DATASET OVERVIEW")
print("=" * 60)

print("Shape:", world_food_loss.shape)
print("Number of rows:", world_food_loss.shape[0])
print("Number of columns:", world_food_loss.shape[1])
print("Memory usage (MB):", round(world_food_loss.memory_usage(deep=True).sum() / (1024 ** 2), 2))

display(world_food_loss.sample(min(5, len(world_food_loss)), random_state=42))

============================================================
DATASET OVERVIEW
============================================================
Shape: (31465, 18)
Number of rows: 31465
Number of columns: 18
Memory usage (MB): 25.66

,m49_code,country,region,cpc_code,commodity,year,loss_percentage,loss_percentage_original,loss_quantity,activity,food_supply_stage,treatment,cause_of_loss,sample_size,method_data_collection,reference,url,notes
27126,826,United Kingdom of Great Britain and Northern I...,NaN,01312,Bananas,2014,1.50,0–3%,NaN,Packaging,Packing,NaN,NaN,NaN,Survey,"Carlos Mena, Leon A. Terry, Adrian Williams; L...",NaN,NaN
17402,51,Armenia,NaN,01199.90,Other cereals n.e.,2012,4.17,4.17%,600,NaN,Whole supply chain,NaN,NaN,NaN,FAO's annual Agriculture Production Questionna...,FAO Sources,NaN,NaN
2320,180,Democratic Republic of the Congo,NaN,0118,Millet,2017,2.50,2.5,NaN,Winnowing,Farm,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN
25378,768,Togo,NaN,0114,Sorghum,2020,3.60,3.6,NaN,"Shelling, Threshing",NaN,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN
10883,384,Côte d'Ivoire,NaN,0112,Maize (corn),2021,4.00,4,NaN,Drying,Farm,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN

## ***Analysis Columns***

In [168]:
print("COLUMN NAMES")
print(world_food_loss.columns.tolist())

print("\nDATA TYPES")
print(world_food_loss.dtypes)

print("\nDATASET INFO")
world_food_loss.info()

print("\nNUMERIC SUMMARY")
display(world_food_loss.describe().T)

print("\nALL COLUMNS SUMMARY")
display(world_food_loss.describe(include="all").T)

COLUMN NAMES
['m49_code', 'country', 'region', 'cpc_code', 'commodity', 'year', 'loss_percentage', 'loss_percentage_original', 'loss_quantity', 'activity', 'food_supply_stage', 'treatment', 'cause_of_loss', 'sample_size', 'method_data_collection', 'reference', 'url', 'notes']

DATA TYPES
m49_code                      int64
country                         str
region                          str
cpc_code                        str
commodity                       str
year                          int64
loss_percentage             float64
loss_percentage_original        str
loss_quantity                   str
activity                        str
food_supply_stage               str
treatment                       str
cause_of_loss                   str
sample_size                     str
method_data_collection          str
reference                       str
url                             str
notes                           str
dtype: object

DATASET INFO
<class 'pandas.DataFrame'>
RangeIndex: 31465 entries, 0 to 31464
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   m49_code                  31465 non-null  int64
 1   country                   31465 non-null  str
 2   region                    2036 non-null   str
 3   cpc_code                  31465 non-null  str
 4   commodity                 31465 non-null  str
 5   year                      31465 non-null  int64
 6   loss_percentage           31465 non-null  float64
 7   loss_percentage_original  31465 non-null  str
 8   loss_quantity             5050 non-null   str
 9   activity                  24095 non-null  str
 10  food_supply_stage         28074 non-null  str
 11  treatment                 1787 non-null   str
 12  cause_of_loss             1098 non-null   str
 13  sample_size               1862 non-null   str
 14  method_data_collection    31429 non-null  str
 15  reference                 31392 non-null  str
 16  url                       22123 non-null  str
 17  notes                     1534 non-null   str
dtypes: float64(1), int64(2), str(15)
memory usage: 4.3 MB

NUMERIC SUMMARY

,count,mean,std,min,25%,50%,75%,max
m49_code,31465.0,471.301637,260.948893,1.0,233.00000,454.00,710.00,894.0
year,31465.0,2010.610774,6.220568,2000.0,2005.00000,2011.00,2016.00,2026.0
loss_percentage,31465.0,4.683186,6.359491,0.0,1.49833,2.65,4.55,65.0

ALL COLUMNS SUMMARY

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
m49_code,31465.0,NaN,NaN,NaN,471.301637,260.948893,1.0,233.0,454.0,710.0,894.0
country,31465,159,United States of America,1716,NaN,NaN,NaN,NaN,NaN,NaN,NaN
region,2036,378,Western Cape Province,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cpc_code,31465,196,0112,6090,NaN,NaN,NaN,NaN,NaN,NaN,NaN
commodity,31465,213,Maize (corn),6090,NaN,NaN,NaN,NaN,NaN,NaN,NaN
year,31465.0,NaN,NaN,NaN,2010.610774,6.220568,2000.0,2005.0,2011.0,2016.0,2026.0
loss_percentage,31465.0,NaN,NaN,NaN,4.683186,6.359491,0.0,1.49833,2.65,4.55,65.0
loss_percentage_original,31465,5995,2.5,2309,NaN,NaN,NaN,NaN,NaN,NaN,NaN
loss_quantity,5050,3429,1000,74,NaN,NaN,NaN,NaN,NaN,NaN,NaN
activity,24095,180,Storage,6072,NaN,NaN,NaN,NaN,NaN,NaN,NaN
food_supply_stage,28074,20,Farm,10103,NaN,NaN,NaN,NaN,NaN,NaN,NaN
treatment,1787,764,Boro rice,57,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cause_of_loss,1098,406,Physical Losses,87,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sample_size,1862,266,933,159,NaN,NaN,NaN,NaN,NaN,NaN,NaN
method_data_collection,31429,11,Modelled Estimates,19497,NaN,NaN,NaN,NaN,NaN,NaN,NaN
reference,31392,328,"APHLIS, (2021), APHLIS",18922,NaN,NaN,NaN,NaN,NaN,NaN,NaN
url,22123,948,https://www.ers.usda.gov/data-products/food-av...,1196,NaN,NaN,NaN,NaN,NaN,NaN,NaN
notes,1534,586,Loss percentages obtained by dividing indicate...,72,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## ***Analysis Missing values in Data-set***

In [169]:
missing_report = pd.DataFrame({
    "missing_count": world_food_loss.isna().sum(),
    "missing_percentage": world_food_loss.isna().mean().mul(100),
    "non_missing_count": world_food_loss.notna().sum(),
    "unique_non_null": world_food_loss.nunique(dropna=True)
})

missing_report = missing_report.sort_values(
    by="missing_percentage",
    ascending=False
)

display(missing_report)

,missing_count,missing_percentage,non_missing_count,unique_non_null
cause_of_loss,30367,96.510408,1098,406
notes,29931,95.124742,1534,586
treatment,29678,94.320674,1787,764
sample_size,29603,94.082314,1862,266
region,29429,93.529318,2036,378
loss_quantity,26415,83.950421,5050,3429
url,9342,29.690132,22123,948
activity,7370,23.422851,24095,180
food_supply_stage,3391,10.777054,28074,20
reference,73,0.232004,31392,328
method_data_collection,36,0.114413,31429,11
m49_code,0,0.000000,31465,157
country,0,0.000000,31465,159
loss_percentage,0,0.000000,31465,4629
cpc_code,0,0.000000,31465,196
loss_percentage_original,0,0.000000,31465,5995
commodity,0,0.000000,31465,213
year,0,0.000000,31465,27

### ***Show "NA", "N/A", "NULL", "NONE", "UNKNOWN", "MISSING", "-" in string data-types***

In [170]:

missing_tokens = {
    "NA", "N/A", "NULL", "NONE",
    "UNKNOWN", "MISSING", "-", "NAN"
}

text_df = world_food_loss.select_dtypes(
    include=["object", "string"]
)

results = []

for col in text_df.columns:
    values = text_df[col].astype("string").str.strip()

    empty_count = values.eq("").sum()

    token_count = values.str.upper().isin(
        missing_tokens
    ).sum()

    actual_missing_count = values.isna().sum()

    results.append({
        "column": col,
        "empty_string_count": int(empty_count),
        "missing_token_count": int(token_count),
        "actual_missing_count": int(actual_missing_count)
    })

missing_report = (
    pd.DataFrame(results)
    .set_index("column")
    .sort_values(
        "actual_missing_count",
        ascending=False
    )
)

display(missing_report)

,empty_string_count,missing_token_count,actual_missing_count
column,,,
cause_of_loss,0,0,30367
notes,0,0,29931
treatment,0,0,29678
sample_size,0,6,29603
region,0,0,29429
loss_quantity,0,0,26415
url,0,0,9342
activity,0,0,7370
food_supply_stage,0,0,3391
reference,0,0,73
method_data_collection,0,0,36
commodity,0,0,0
loss_percentage_original,0,0,0
country,0,0,0
cpc_code,0,0,0

## ***Show duplicated and unique data***

In [171]:
unique_report = pd.DataFrame({
    "unique_count": world_food_loss.nunique(dropna=True),
    "unique_with_nan": world_food_loss.nunique(dropna=False),
    "dtype": world_food_loss.dtypes.astype(str),
    "is_constant": world_food_loss.nunique(dropna=True).le(1)
})

display(unique_report.sort_values("unique_count"))

                          unique_count  unique_with_nan    dtype  is_constant
method_data_collection              11               12      str        False
food_supply_stage                   20               21      str        False
year                                27               27    int64        False
m49_code                           157              157    int64        False
country                            159              159      str        False
activity                           180              181      str        False
cpc_code                           196              196      str        False
commodity                          213              213      str        False
sample_size                        266              267      str        False
reference                          328              329      str        False
region                             378              379      str        False
cause_of_loss                      406              407      str        False
notes                              586              587      str        False
treatment                          764              765      str        False
url                                948              949      str        False
loss_quantity                     3429             3430      str        False
loss_percentage                   4629             4629  float64        False
loss_percentage_original          5995             5995      str        False

In [172]:
# Select categorical and text columns
categorical_cols = world_food_loss.select_dtypes(
    include=["object", "string", "category"]
).columns

# Store column profiling results
column_profile = []

for col in categorical_cols:
    column_profile.append({
        "Column Name": col,
        "Data Type": str(world_food_loss[col].dtype),
        "Unique Values": world_food_loss[col].nunique(dropna=True),
        "Most Frequent Value": (
            world_food_loss[col].mode(dropna=True).iloc[0]
            if not world_food_loss[col].mode(dropna=True).empty
            else None
        ),
        "Most Frequent Count": (
            world_food_loss[col].value_counts(dropna=True).iloc[0]
            if not world_food_loss[col].value_counts(dropna=True).empty
            else 0
        )
    })

# Display the summary table
profile_df = pd.DataFrame(column_profile)

display(
    profile_df.style
    .set_caption("Categorical Columns Profile")
    .format(precision=2)
    .background_gradient(subset=["Unique Values"], cmap="Blues")
    .set_properties(**{
        "text-align": "left",
        "padding": "8px"
    })
)

In [173]:
print("Fully duplicated rows:", world_food_loss.duplicated().sum())

print(
    "Duplicated rows including all copies:",
    world_food_loss.duplicated(keep=False).sum()
)

duplicates = world_food_loss[
    world_food_loss.duplicated(keep=False)
].sort_values(by=world_food_loss.columns.tolist())

display(duplicates.head(20))

Fully duplicated rows: 180
Duplicated rows including all copies: 339

,m49_code,country,region,cpc_code,commodity,year,loss_percentage,loss_percentage_original,loss_quantity,activity,food_supply_stage,treatment,cause_of_loss,sample_size,method_data_collection,reference,url,notes
16249,50,Bangladesh,NaN,0113,Rice,2010,1.30,1.3,NaN,NaN,Processing,NaN,NaN,NaN,Modelled Estimates,Mst. Esmat Ara Begum; Mohammad Ismail Hossain;...,http://www.setscholars.org/index.php/ijarbae,NaN
16252,50,Bangladesh,NaN,0113,Rice,2010,1.30,1.3,NaN,NaN,Processing,NaN,NaN,NaN,Modelled Estimates,Mst. Esmat Ara Begum; Mohammad Ismail Hossain;...,http://www.setscholars.org/index.php/ijarbae,NaN
16123,50,Bangladesh,NaN,01312,Bananas,2010,3.20,3.2,NaN,NaN,Retail,NaN,NaN,100,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16125,50,Bangladesh,NaN,01312,Bananas,2010,3.20,3.2,NaN,NaN,Retail,NaN,NaN,100,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16121,50,Bangladesh,NaN,01312,Bananas,2010,5.10,5.1,NaN,NaN,Trader,NaN,NaN,100,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16122,50,Bangladesh,NaN,01312,Bananas,2010,5.10,5.1,NaN,NaN,Trader,NaN,NaN,100,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16120,50,Bangladesh,NaN,01312,Bananas,2010,7.70,7.7,NaN,NaN,Farm,NaN,NaN,100,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16126,50,Bangladesh,NaN,01312,Bananas,2010,7.70,7.7,NaN,NaN,Farm,NaN,NaN,100,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16124,50,Bangladesh,NaN,01312,Bananas,2010,8.60,8.6,NaN,NaN,Wholesale,NaN,NaN,100,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16130,50,Bangladesh,NaN,01312,Bananas,2010,8.60,8.6,NaN,NaN,Wholesale,NaN,NaN,100,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16166,50,Bangladesh,NaN,01319,"Other tropical and subtropical fruits, n.e.c.",2010,5.11,5.11,NaN,NaN,Trader,NaN,NaN,100,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16168,50,Bangladesh,NaN,01319,"Other tropical and subtropical fruits, n.e.c.",2010,5.11,5.11,NaN,NaN,Trader,NaN,NaN,100,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16165,50,Bangladesh,NaN,01319,"Other tropical and subtropical fruits, n.e.c.",2010,5.14,5.14,NaN,NaN,Retail,NaN,NaN,100,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16167,50,Bangladesh,NaN,01319,"Other tropical and subtropical fruits, n.e.c.",2010,5.14,5.14,NaN,NaN,Retail,NaN,NaN,100,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16164,50,Bangladesh,NaN,01319,"Other tropical and subtropical fruits, n.e.c.",2010,6.10,6.1,NaN,NaN,Wholesale,NaN,NaN,75,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16171,50,Bangladesh,NaN,01319,"Other tropical and subtropical fruits, n.e.c.",2010,6.10,6.1,NaN,NaN,Wholesale,NaN,NaN,75,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16169,50,Bangladesh,NaN,01319,"Other tropical and subtropical fruits, n.e.c.",2010,8.51,8.51,NaN,NaN,Farm,NaN,NaN,120,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16176,50,Bangladesh,NaN,01319,"Other tropical and subtropical fruits, n.e.c.",2010,8.51,8.51,NaN,NaN,Farm,NaN,NaN,120,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16180,50,Bangladesh,NaN,01323,Oranges,2010,4.00,4,NaN,NaN,Wholesale,NaN,NaN,50,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16184,50,Bangladesh,NaN,01323,Oranges,2010,4.00,4,NaN,NaN,Wholesale,NaN,NaN,50,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN

## ***Describe numeric data***

In [174]:
numeric_cols = world_food_loss.select_dtypes(
    include=np.number
).columns

numeric_report = pd.DataFrame(index=numeric_cols)

numeric_report["missing"] = world_food_loss[numeric_cols].isna().sum()
numeric_report["unique"] = world_food_loss[numeric_cols].nunique()
numeric_report["min"] = world_food_loss[numeric_cols].min()
numeric_report["max"] = world_food_loss[numeric_cols].max()
numeric_report["mean"] = world_food_loss[numeric_cols].mean()
numeric_report["median"] = world_food_loss[numeric_cols].median()
numeric_report["std"] = world_food_loss[numeric_cols].std()
numeric_report["negative_count"] = world_food_loss[numeric_cols].lt(0).sum()

display(numeric_report)

,missing,unique,min,max,mean,median,std,negative_count
m49_code,0,157,1.0,894.0,471.301637,454.00,260.948893,0
year,0,27,2000.0,2026.0,2010.610774,2011.00,6.220568,0
loss_percentage,0,4629,0.0,65.0,4.683186,2.65,6.359491,0

## ***Show ouliers***

In [175]:
outlier_rows = []

for col in numeric_cols:
    series = world_food_loss[col].dropna()

    if series.empty:
        continue

    q1 = series.quantile(0.25)
    q3 = series.quantile(0.75)
    iqr = q3 - q1

    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr

    mask = (world_food_loss[col] < lower_bound) | (
        world_food_loss[col] > upper_bound
    )

    outlier_rows.append({
        "column": col,
        "lower_bound": lower_bound,
        "upper_bound": upper_bound,
        "outlier_count": int(mask.sum()),
        "outlier_percentage": round(mask.mean() * 100, 2)
    })

outlier_report = pd.DataFrame(outlier_rows)
display(outlier_report)

,column,lower_bound,upper_bound,outlier_count,outlier_percentage
0,m49_code,-482.500000,1425.500000,0,0.0
1,year,1988.500000,2032.500000,0,0.0
2,loss_percentage,-3.079175,9.127505,3555,11.3

## ***Show final columns***

In [176]:

columns_df = pd.DataFrame({
    "Column Number": range(1, len(world_food_loss.columns) + 1),
    "Column Name": world_food_loss.columns.tolist(),
    "Data Type": world_food_loss.dtypes.astype(str).values
})

display(columns_df)

    Column Number               Column Name Data Type
0               1                  m49_code     int64
1               2                   country       str
2               3                    region       str
3               4                  cpc_code       str
4               5                 commodity       str
5               6                      year     int64
6               7           loss_percentage   float64
7               8  loss_percentage_original       str
8               9             loss_quantity       str
9              10                  activity       str
10             11         food_supply_stage       str
11             12                 treatment       str
12             13             cause_of_loss       str
13             14               sample_size       str
14             15    method_data_collection       str
15             16                 reference       str
16             17                       url       str
17             18                     notes       str

## ***Check on columns***

### **Check on m49_code**

In [177]:
# Country-to-M49 code inventory; create the output folder first.
from pathlib import Path

m49_report_dir = Path("reports") / "m49"
m49_report_dir.mkdir(parents=True, exist_ok=True)

res = world_food_loss.groupby("country", dropna=False)["m49_code"].unique()
res.to_csv(m49_report_dir / "country_m49_codes.csv")

print(f"Saved: {(m49_report_dir / 'country_m49_codes.csv').resolve()}")

Saved: D:\My_projects\data-engineer\waste-food-project\notebooks\reports\m49\country_m49_codes.csv

#### **Repeated codes in diff countries**

In [178]:
code_names = (
    world_food_loss[['m49_code', 'country']]
    .dropna()
    .drop_duplicates()
)

repeated_codes = code_names[
    code_names.duplicated('m49_code', keep=False)
].sort_values('m49_code')

display(repeated_codes)

       m49_code                                            country
2215        158                          Taiwan, Province of China
2217        158                                       China,Taiwan
27050       826  United Kingdom of Great Britain and Northern I...
27086       826                                     United Kingdom

#### **Missing values , datatype and unique values**

In [179]:
print("Missing values:", world_food_loss['m49_code'].isna().sum())
print("Data type:", world_food_loss['m49_code'].dtype)
print("Unique codes:", world_food_loss['m49_code'].nunique())

Missing values: 0
Data type: int64
Unique codes: 157

#### **Same country has many codes ?**

In [180]:
country_codes = (
    world_food_loss.groupby('country')['m49_code']
    .nunique(dropna=True)
)

multiple_codes = country_codes[country_codes > 1]

display(multiple_codes)

Series([], Name: m49_code, dtype: int64)

#### **Check invalid codes**

In [181]:
import requests
from io import StringIO

# 1) The three reference links
links = {
    "UN_M49_Overview":
        "https://unstats.un.org/unsd/methodology/m49/overview/",

    "UN_M49_Methodology":
        "https://unstats.un.org/unsd/methodology/m49/",

    "GitHub_ISO_Regional_Codes":
        "https://raw.githubusercontent.com/lukes/ISO-3166-Countries-with-Regional-Codes/master/all/all.csv",
}

def normalize_name(value):
    """Normalize names for comparison."""
    if pd.isna(value):
        return ""
    return " ".join(str(value).strip().casefold().split())

def normalize_code(value):
    """Normalize numeric codes to 3-digit strings."""
    if pd.isna(value):
        return ""

    value = str(value).strip()

    # Handle codes read as values such as 15.0
    if value.endswith(".0"):
        value = value[:-2]

    if value.isdigit():
        return value.zfill(3)

    return value


# 2) Read the official UN overview table
response = requests.get(links["UN_M49_Overview"], timeout=30)
response.raise_for_status()

un_tables = pd.read_html(StringIO(response.text))

un_reference = next(
    table for table in un_tables
    if "Country or Area" in table.columns
    and "M49 Code" in table.columns
)

# Country/area name -> country/area M49 code
country_reference = pd.DataFrame({
    "name": un_reference["Country or Area"],
    "code": un_reference["M49 Code"],
    "source": "UN M49 Overview",
    "record_type": "country_or_area",
})

# Geographic aggregate name -> its corresponding geographic code
region_columns = [
    ("Global Name", "Global Code", "global"),
    ("Region Name", "Region Code", "region"),
    ("Sub-region Name", "Sub-region Code", "sub_region"),
    (
        "Intermediate Region Name",
        "Intermediate Region Code",
        "intermediate_region",
    ),
]

region_frames = []

for name_col, code_col, record_type in region_columns:
    if name_col in un_reference.columns and code_col in un_reference.columns:
        region_frames.append(pd.DataFrame({
            "name": un_reference[name_col],
            "code": un_reference[code_col],
            "source": "UN M49 Overview",
            "record_type": record_type,
        }))

un_regions = pd.concat(region_frames, ignore_index=True)

# 3) Read the second UN page and the GitHub CSV
# Keep the raw downloaded data so we can inspect the actual columns.
methodology_response = requests.get(
    links["UN_M49_Methodology"], timeout=30
)
methodology_response.raise_for_status()

methodology_tables = pd.read_html(StringIO(methodology_response.text))

github_response = requests.get(
    links["GitHub_ISO_Regional_Codes"], timeout=30
)
github_response.raise_for_status()

github_reference = pd.read_csv(StringIO(github_response.text), dtype=str)

# GitHub uses ISO numeric country-code and separate regional-code columns.
github_frames = [
    pd.DataFrame({
        "name": github_reference["name"],
        "code": github_reference["country-code"],
        "source": "GitHub",
        "record_type": "country_or_area",
    }),
    pd.DataFrame({
        "name": github_reference["region"],
        "code": github_reference["region-code"],
        "source": "GitHub",
        "record_type": "region",
    }),
    pd.DataFrame({
        "name": github_reference["sub-region"],
        "code": github_reference["sub-region-code"],
        "source": "GitHub",
        "record_type": "sub_region",
    }),
    pd.DataFrame({
        "name": github_reference["intermediate-region"],
        "code": github_reference["intermediate-region-code"],
        "source": "GitHub",
        "record_type": "intermediate_region",
    }),
]

github_all = pd.concat(github_frames, ignore_index=True)

# 4) Combine reference pairs from all three links
# The methodology page is also searched for tables containing
# a country/area name and an M49 code.
methodology_frames = []

for table in methodology_tables:
    lower_columns = {
        str(col).strip().casefold(): col for col in table.columns
    }

    name_col = lower_columns.get("country or area")
    code_col = lower_columns.get("m49 code")

    if name_col is None:
        name_col = lower_columns.get("country or area")
    if code_col is None:
        code_col = lower_columns.get("m49 code")

    if name_col is not None and code_col is not None:
        methodology_frames.append(pd.DataFrame({
            "name": table[name_col],
            "code": table[code_col],
            "source": "UN M49 Methodology",
            "record_type": "country_or_area_or_region",
        }))

methodology_reference = (
    pd.concat(methodology_frames, ignore_index=True)
    if methodology_frames
    else pd.DataFrame(
        columns=["name", "code", "source", "record_type"]
    )
)

reference = pd.concat(
    [
        country_reference,
        un_regions,
        methodology_reference,
        github_all,
    ],
    ignore_index=True,
)

# 5) Normalize reference data
reference["name_key"] = reference["name"].map(normalize_name)
reference["code_key"] = reference["code"].map(normalize_code)

reference = reference[
    (reference["name_key"] != "")
    & (reference["code_key"] != "")
].drop_duplicates(
    subset=["name_key", "code_key", "source", "record_type"]
)

# 6) Normalize the unmatched records from your dataset
unmatched = world_food_loss[["country", "m49_code"]].drop_duplicates().copy()

unmatched["name_key"] = unmatched["country"].map(normalize_name)
unmatched["code_key"] = unmatched["m49_code"].map(normalize_code)

# 7) Check whether each exact name + code pair exists in each source
results = []

for _, row in unmatched.iterrows():
    matches = reference[
        (reference["name_key"] == row["name_key"])
        & (reference["code_key"] == row["code_key"])
    ]

    matched_sources = sorted(matches["source"].unique().tolist())

    results.append({
        "country": row["country"],
        "m49_code": row["code_key"],
        "found_in": ", ".join(matched_sources) if matched_sources else "",
        "match_count": len(matches),
        "status": (
            "FOUND"
            if not matches.empty
            else "NOT FOUND - REVIEW"
        ),
    })

validation = pd.DataFrame(results)

# Show only pairs that were not found in any reference
still_unmatched = validation[
    validation["status"] == "NOT FOUND - REVIEW"
]

print("All checked pairs:")
display(validation.sort_values(["status", "country"]))

print("\nStill unmatched after checking all three links:")
display(still_unmatched)

# Optional: inspect the exact reference records for a specific name
# Example:
# display(reference[reference["name_key"] == normalize_name("Taiwan, Province of China")])

# Optional: save the reports
validation.to_csv("../report/m49/m49_validation_all.csv", index=False)
still_unmatched.to_csv("../report/m49/m49_still_unmatched.csv", index=False)

All checked pairs:

,country,m49_code,found_in,match_count,status
67,Afghanistan,004,"GitHub, UN M49 Methodology, UN M49 Overview",3,FOUND
25,Africa,002,"GitHub, UN M49 Methodology, UN M49 Overview",3,FOUND
146,Albania,008,"GitHub, UN M49 Methodology, UN M49 Overview",3,FOUND
6,Algeria,012,"GitHub, UN M49 Methodology, UN M49 Overview",3,FOUND
35,Angola,024,"GitHub, UN M49 Methodology, UN M49 Overview",3,FOUND
...,...,...,...,...,...
98,Netherlands,528,,0,NOT FOUND - REVIEW
42,Palestine,275,,0,NOT FOUND - REVIEW
149,The former Yugoslav Republic of Macedonia,807,,0,NOT FOUND - REVIEW
145,Turkey,792,,0,NOT FOUND - REVIEW
152,United Kingdom,826,,0,NOT FOUND - REVIEW

Still unmatched after checking all three links:

,country,m49_code,found_in,match_count,status
19,"China,Taiwan",158,,0,NOT FOUND - REVIEW
42,Palestine,275,,0,NOT FOUND - REVIEW
98,Netherlands,528,,0,NOT FOUND - REVIEW
145,Turkey,792,,0,NOT FOUND - REVIEW
149,The former Yugoslav Republic of Macedonia,807,,0,NOT FOUND - REVIEW
152,United Kingdom,826,,0,NOT FOUND - REVIEW

In [182]:


# Known name variations and their current official UN M49 names.
name_mapping = {
    "Palestine": "State of Palestine",
    "Netherlands": "Netherlands (Kingdom of the)",
    "Turkey": "Türkiye",
    "The former Yugoslav Republic of Macedonia": "North Macedonia",
    "United Kingdom":
        "United Kingdom of Great Britain and Northern Ireland",
}

# Expected M49 codes for these names.
expected_codes = {
    "State of Palestine": "275",
    "Netherlands (Kingdom of the)": "528",
    "Türkiye": "792",
    "North Macedonia": "807",
    "United Kingdom of Great Britain and Northern Ireland": "826",
}

# Review only the rows that were unmatched.
review = still_unmatched.copy()

review["m49_code"] = (
    review["m49_code"].astype(str).str.replace(r"\.0$", "", regex=True).str.zfill(3)
)

review["suggested_official_name"] = review["country"].map(name_mapping)

review["expected_code"] = review["suggested_official_name"].map(
    expected_codes
)

review["review_result"] = "MANUAL REVIEW REQUIRED"

# Name aliases whose codes agree with the current official reference.
valid_alias = (
    review["suggested_official_name"].notna()
    & (review["m49_code"] == review["expected_code"])
)

review.loc[valid_alias, "review_result"] = (
    "CODE MATCHES - NAME ALIAS"
)

# Taiwan entry requires checking the dataset's original source.
taiwan_mask = review["country"].eq("China,Taiwan")

review.loc[taiwan_mask, "suggested_official_name"] = pd.NA
review.loc[taiwan_mask, "expected_code"] = pd.NA
review.loc[taiwan_mask, "review_result"] = (
    "VERIFY AGAINST ORIGINAL DATA SOURCE"
)

display(
    review[
        [
            "country",
            "m49_code",
            "suggested_official_name",
            "expected_code",
            "review_result",
        ]
    ]
)

,country,m49_code,suggested_official_name,expected_code,review_result
19,"China,Taiwan",158,NaN,NaN,VERIFY AGAINST ORIGINAL DATA SOURCE
42,Palestine,275,State of Palestine,275,CODE MATCHES - NAME ALIAS
98,Netherlands,528,Netherlands (Kingdom of the),528,CODE MATCHES - NAME ALIAS
145,Turkey,792,Türkiye,792,CODE MATCHES - NAME ALIAS
149,The former Yugoslav Republic of Macedonia,807,North Macedonia,807,CODE MATCHES - NAME ALIAS
152,United Kingdom,826,United Kingdom of Great Britain and Northern I...,826,CODE MATCHES - NAME ALIAS

#### **Check country-code consistency**

In [183]:

import pandas as pd
import requests
from io import StringIO

# =========================================================
# 1. Three reference links
# =========================================================

links = {
    "UN_M49_Overview":
        "https://unstats.un.org/unsd/methodology/m49/overview/",

    "UN_M49_Methodology":
        "https://unstats.un.org/unsd/methodology/m49/",

    "GitHub_ISO_Regional_Codes":
        "https://raw.githubusercontent.com/lukes/ISO-3166-Countries-with-Regional-Codes/master/all/all.csv",
}

# =========================================================
# 2. Helper functions
# =========================================================

def normalize_name(series):
    return (
        series.astype("string")
        .str.strip()
        .str.casefold()
        .str.replace(r"\s+", " ", regex=True)
    )

def normalize_code(series):
    return (
        series.astype("string")
        .str.strip()
        .str.replace(r"\.0$", "", regex=True)
        .str.zfill(3)
    )

def download(url):
    response = requests.get(
        url,
        timeout=30,
        headers={"User-Agent": "Mozilla/5.0"}
    )
    response.raise_for_status()
    return response

# =========================================================
# 3. Official UN M49 Overview
# =========================================================

response = download(links["UN_M49_Overview"])
tables = pd.read_html(StringIO(response.text))

un_table = next(
    table for table in tables
    if "Country or Area" in table.columns
    and "M49 Code" in table.columns
)

# Country/area codes
country_ref = pd.DataFrame({
    "name": un_table["Country or Area"],
    "code": un_table["M49 Code"],
    "record_type": "country_or_area",
    "source": "UN M49 Overview",
})

# Geographic region codes: match each name to its own code column
region_frames = []

region_columns = [
    ("Global Name", "Global Code", "global"),
    ("Region Name", "Region Code", "region"),
    ("Sub-region Name", "Sub-region Code", "sub_region"),
    (
        "Intermediate Region Name",
        "Intermediate Region Code",
        "intermediate_region",
    ),
]

for name_col, code_col, record_type in region_columns:
    if name_col in un_table.columns and code_col in un_table.columns:
        region_frames.append(pd.DataFrame({
            "name": un_table[name_col],
            "code": un_table[code_col],
            "record_type": record_type,
            "source": "UN M49 Overview",
        }))

un_regions = pd.concat(region_frames, ignore_index=True)

# =========================================================
# 4. Download the UN methodology page
# =========================================================

methodology_response = download(links["UN_M49_Methodology"])
methodology_tables = pd.read_html(
    StringIO(methodology_response.text)
)

methodology_frames = []

for table in methodology_tables:
    table = table.copy()
    table.columns = [str(col).strip() for col in table.columns]

    if "Country or Area" in table.columns:
        code_col = next(
            (
                col for col in table.columns
                if str(col).strip().casefold() == "m49 code"
            ),
            None
        )

        if code_col is not None:
            methodology_frames.append(pd.DataFrame({
                "name": table["Country or Area"],
                "code": table[code_col],
                "record_type": "country_or_area",
                "source": "UN M49 Methodology",
            }))

un_methodology = (
    pd.concat(methodology_frames, ignore_index=True)
    if methodology_frames
    else pd.DataFrame(
        columns=["name", "code", "record_type", "source"]
    )
)

# =========================================================
# 5. Download GitHub reference (ISO, not M49)
# =========================================================

github_response = download(links["GitHub_ISO_Regional_Codes"])
github = pd.read_csv(StringIO(github_response.text), dtype=str)

github_ref = pd.DataFrame({
    "name": github["name"],
    "code": github["country-code"],
    "record_type": "ISO_country_code",
    "source": "GitHub ISO reference",
})

# =========================================================
# 6. Build separate reference tables
# =========================================================

def prepare_reference(frame):
    frame = frame.copy()
    frame["name_key"] = normalize_name(frame["name"])
    frame["code_key"] = normalize_code(frame["code"])

    return frame.dropna(
        subset=["name_key", "code_key"]
    ).drop_duplicates(
        subset=["name_key", "code_key", "record_type", "source"]
    )

official_countries = prepare_reference(
    pd.concat(
        [country_ref, un_methodology],
        ignore_index=True
    )
)

official_regions = prepare_reference(un_regions)
github_ref = prepare_reference(github_ref)

# =========================================================
# 7. Prepare dataset
# =========================================================

data = world_food_loss[["country", "m49_code"]].copy()
data["name_key"] = normalize_name(data["country"])
data["actual_code"] = normalize_code(data["m49_code"])

# =========================================================
# 8. Validate country/area pairs against official M49
# =========================================================

valid_country_pairs = (
    official_countries[["name_key", "code_key"]]
    .drop_duplicates()
    .rename(columns={"code_key": "expected_code"})
)

checked = data.merge(
    valid_country_pairs.assign(pair_found=True),
    left_on=["name_key", "actual_code"],
    right_on=["name_key", "expected_code"],
    how="left",
    validate="many_to_one",
)

checked["pair_found"] = checked["pair_found"].eq(True)

known_country_names = set(official_countries["name_key"].dropna())
known_region_names = set(official_regions["name_key"].dropna())

checked["country_name_found"] = checked["name_key"].isin(
    known_country_names
)
checked["region_name_found"] = checked["name_key"].isin(
    known_region_names
)

checked["status"] = "NAME NOT FOUND - REVIEW"

checked.loc[
    checked["country_name_found"],
    "status"
] = "COUNTRY NAME FOUND - CHECK CODE"

checked.loc[
    checked["pair_found"],
    "status"
] = "VALID COUNTRY/AREA NAME + M49 CODE"

# Check geographic aggregate pairs separately
valid_region_pairs = (
    official_regions[["name_key", "code_key"]]
    .drop_duplicates()
)

region_pair_index = set(
    zip(valid_region_pairs["name_key"], valid_region_pairs["code_key"])
)

is_region_pair = pd.Series(
    [
        (name, code) in region_pair_index
        for name, code in zip(
            checked["name_key"], checked["actual_code"]
        )
    ],
    index=checked.index,
)

checked.loc[
    is_region_pair,
    "status"
] = "VALID GEOGRAPHIC REGION CODE"

checked.loc[
    checked["region_name_found"]
    & ~is_region_pair
    & ~checked["pair_found"],
    "status"
] = "REGION NAME FOUND - CHECK REGION CODE"

# =========================================================
# 9. Display report
# =========================================================

report = checked[
    [
        "country",
        "m49_code",
        "actual_code",
        "country_name_found",
        "region_name_found",
        "pair_found",
        "status",
    ]
].drop_duplicates()

display(report)

print("\nStatus summary:")
display(
    report["status"]
    .value_counts()
    .rename_axis("status")
    .reset_index(name="number_of_pairs")
)


# =========================================================
# 10. Show only unresolved issues
# =========================================================

issues = report[
    ~report["status"].str.startswith("VALID", na=False)
].copy()

print("\nRows requiring review:")
display(issues)

# Save issues to CSV
issues.to_csv(
    "../report/m49/m49_country_code_issues.csv",
    index=False
)

print(f"\nNumber of rows requiring review: {len(issues)}")
print("Issues report saved successfully.")

,country,m49_code,actual_code,country_name_found,region_name_found,pair_found,status
0,World,1,001,True,True,True,VALID GEOGRAPHIC REGION CODE
29,Myanmar,104,104,True,False,True,VALID COUNTRY/AREA NAME + M49 CODE
42,Burundi,108,108,True,False,True,VALID COUNTRY/AREA NAME + M49 CODE
551,Western Africa,11,011,True,True,True,VALID GEOGRAPHIC REGION CODE
555,Belarus,112,112,True,False,True,VALID COUNTRY/AREA NAME + M49 CODE
...,...,...,...,...,...,...,...
27857,United States of America,840,840,True,False,True,VALID COUNTRY/AREA NAME + M49 CODE
29573,Burkina Faso,854,854,True,False,True,VALID COUNTRY/AREA NAME + M49 CODE
30340,Uzbekistan,860,860,True,False,True,VALID COUNTRY/AREA NAME + M49 CODE
30352,Venezuela (Bolivarian Republic of),862,862,True,False,True,VALID COUNTRY/AREA NAME + M49 CODE
30699,Zambia,894,894,True,False,True,VALID COUNTRY/AREA NAME + M49 CODE

Status summary:

                               status  number_of_pairs
0  VALID COUNTRY/AREA NAME + M49 CODE              137
1        VALID GEOGRAPHIC REGION CODE               14
2             NAME NOT FOUND - REVIEW                8

Rows requiring review:

,country,m49_code,actual_code,country_name_found,region_name_found,pair_found,status
2215,"Taiwan, Province of China",158,158,False,False,False,NAME NOT FOUND - REVIEW
2217,"China,Taiwan",158,158,False,False,False,NAME NOT FOUND - REVIEW
6891,Palestine,275,275,False,False,False,NAME NOT FOUND - REVIEW
10879,Côte d'Ivoire,384,384,False,False,False,NAME NOT FOUND - REVIEW
17946,Netherlands,528,528,False,False,False,NAME NOT FOUND - REVIEW
25890,Turkey,792,792,False,False,False,NAME NOT FOUND - REVIEW
26887,The former Yugoslav Republic of Macedonia,807,807,False,False,False,NAME NOT FOUND - REVIEW
27086,United Kingdom,826,826,False,False,False,NAME NOT FOUND - REVIEW

Number of rows requiring review: 8
Issues report saved successfully.

### **Check on column Country**

#### **Show missing values**

In [184]:
import re
import unicodedata
from difflib import get_close_matches

countries = world_food_loss["country"].copy()



def normalize_name(value):
    if pd.isna(value):
        return ""
    value = unicodedata.normalize("NFKC", str(value))
    return re.sub(r"\s+", " ", value.strip().casefold())

In [185]:
missing_countries = world_food_loss[
    world_food_loss["country"].isna()
]

print("Missing country values:", len(missing_countries))
display(missing_countries)

Missing country values: 0

Empty DataFrame
Columns: [m49_code, country, region, cpc_code, commodity, year, loss_percentage, loss_percentage_original, loss_quantity, activity, food_supply_stage, treatment, cause_of_loss, sample_size, method_data_collection, reference, url, notes]
Index: []

#### **Show diff names for same country**

In [186]:
import pandas as pd
import unicodedata
import re

# Prepare the official UN M49 reference
un_reference = un_table[["Country or Area", "M49 Code"]].copy()

un_reference["m49_code"] = pd.to_numeric(
    un_reference["M49 Code"].astype(str).str.strip(),
    errors="coerce"
)

un_reference = un_reference.dropna(subset=["m49_code"])
un_reference["m49_code"] = un_reference["m49_code"].astype("int64")
un_reference["official_name"] = un_reference["Country or Area"].astype(str)
un_reference["normalized_official_name"] = (
    un_reference["official_name"].map(normalize_name)
)

# Keep all official names for each M49 code
official_names_by_code = (
    un_reference.groupby("m49_code")["official_name"]
    .apply(lambda names: sorted(set(names)))
    .to_dict()
)

# Prepare dataset country names
dataset_names = (
    world_food_loss[["country", "m49_code"]]
    .dropna(subset=["country", "m49_code"])
    .drop_duplicates()
    .copy()
)

dataset_names["m49_code"] = pd.to_numeric(
    dataset_names["m49_code"], errors="coerce"
)

dataset_names = dataset_names.dropna(subset=["m49_code"])
dataset_names["m49_code"] = dataset_names["m49_code"].astype("int64")
dataset_names["normalized_country"] = (
    dataset_names["country"].map(normalize_name)
)

# Match each dataset name against official names sharing its M49 code
dataset_names["official_names"] = dataset_names["m49_code"].map(
    official_names_by_code
)

dataset_names["official_names"] = dataset_names["official_names"].apply(
    lambda names: names if isinstance(names, list) else []
)

dataset_names["status"] = dataset_names.apply(
    lambda row: (
        "No official M49 code match"
        if not row["official_names"]
        else (
            "Exact name match"
            if row["normalized_country"] in [
                normalize_name(name) for name in row["official_names"]
            ]
            else "Name differs from official reference"
        )
    ),
    axis=1
)

# Display rows that need review
results = dataset_names[
    dataset_names["status"] != "Exact name match"
].copy()

results = results.rename(columns={
    "country": "dataset_country"
})

display(
    results[
        ["dataset_country", "m49_code", "official_names", "status"]
    ].sort_values(["status", "m49_code", "dataset_country"])
)

,dataset_country,m49_code,official_names,status
6891,Palestine,275,[State of Palestine],Name differs from official reference
10879,Côte d'Ivoire,384,[Côte d’Ivoire],Name differs from official reference
17946,Netherlands,528,[Netherlands (Kingdom of the)],Name differs from official reference
25890,Turkey,792,[Türkiye],Name differs from official reference
26887,The former Yugoslav Republic of Macedonia,807,[North Macedonia],Name differs from official reference
27086,United Kingdom,826,[United Kingdom of Great Britain and Northern ...,Name differs from official reference
0,World,1,[],No official M49 code match
2750,Africa,2,[],No official M49 code match
551,Western Africa,11,[],No official M49 code match
1939,Northern Africa,15,[],No official M49 code match
3562,Northern America,21,[],No official M49 code match
8757,Southern Asia,34,[],No official M49 code match
9063,South-Eastern Asia,35,[],No official M49 code match
18013,Australia and New Zealand,53,[],No official M49 code match
1292,Asia,142,[],No official M49 code match
1293,Central Asia,143,[],No official M49 code match
1413,Western Asia,145,[],No official M49 code match
1944,Europe,150,[],No official M49 code match
2217,"China,Taiwan",158,[],No official M49 code match
2215,"Taiwan, Province of China",158,[],No official M49 code match
2754,Sub-Saharan Africa,202,[],No official M49 code match
13058,Latin America and the Caribbean,419,[],No official M49 code match

#### **Check on diff upper and lower names**

In [187]:
case_issues = world_food_loss[
    world_food_loss["country"].notna()
    & world_food_loss["country"].ne(
        world_food_loss["country"].str.title()
    )
][["country", "m49_code"]].drop_duplicates()

print("Names with non-standard capitalization:", len(case_issues))
display(case_issues)

Names with non-standard capitalization: 17

                                                 country  m49_code
2215                           Taiwan, Province of China       158
2223                    Democratic Republic of the Congo       180
10688                         Iran (Islamic Republic of)       364
10879                                      Côte d'Ivoire       384
12998              Democratic People's Republic of Korea       408
13002                                  Republic of Korea       410
13052                   Lao People's Democratic Republic       418
13058                    Latin America and the Caribbean       419
18013                          Australia and New Zealand        53
21411                              Saint Kitts and Nevis       659
21422                   Bolivia (Plurinational State of)        68
25878                                Trinidad and Tobago       780
26887          The former Yugoslav Republic of Macedonia       807
27050  United Kingdom of Great Britain and Northern I...       826
27227                        United Republic of Tanzania       834
27857                           United States of America       840
30352                 Venezuela (Bolivarian Republic of)       862

#### **Check on spaces**

In [188]:
country_text = world_food_loss["country"].astype("string")

outer_spaces = world_food_loss[
    country_text.notna()
    & country_text.ne(country_text.str.strip())
][["country", "m49_code"]]

internal_spaces = world_food_loss[
    country_text.notna()
    & country_text.str.contains(r"\s{2,}", regex=True, na=False)
][["country", "m49_code"]]

print("Leading/trailing spaces:", len(outer_spaces))
display(outer_spaces.drop_duplicates())

print("Repeated internal spaces:", len(internal_spaces))
display(internal_spaces.drop_duplicates())

Leading/trailing spaces: 0

Empty DataFrame
Columns: [country, m49_code]
Index: []

Repeated internal spaces: 0

Empty DataFrame
Columns: [country, m49_code]
Index: []

#### **Discovering mixed geographic regions with countries**

In [189]:
region_columns = [
    ("Global Name", "Global Code"),
    ("Region Name", "Region Code"),
    ("Sub-region Name", "Sub-region Code"),
    ("Intermediate Region Name", "Intermediate Region Code"),
]

region_frames = []

for name_col, code_col in region_columns:
    if name_col in un_table.columns and code_col in un_table.columns:
        temp = un_table[[name_col, code_col]].dropna().copy()
        temp.columns = ["region_name", "region_code"]
        region_frames.append(temp)

regions = pd.concat(region_frames, ignore_index=True).drop_duplicates()

region_names = set(
    regions["region_name"].map(normalize_name)
)

geographic_regions = world_food_loss[
    world_food_loss["country"].notna()
    & world_food_loss["country"].map(normalize_name).isin(region_names)
][["country", "m49_code"]].drop_duplicates()

print("Geographic region names found in country:",
      len(geographic_regions))

display(geographic_regions)

Geographic region names found in country: 14

                               country  m49_code
0                                World         1
551                     Western Africa        11
1292                              Asia       142
1293                      Central Asia       143
1413                      Western Asia       145
1939                   Northern Africa        15
1944                            Europe       150
2750                            Africa         2
2754                Sub-Saharan Africa       202
3562                  Northern America        21
8757                     Southern Asia        34
9063                South-Eastern Asia        35
13058  Latin America and the Caribbean       419
18013        Australia and New Zealand        53

### **Check on region**

#### **Show missins values**

In [190]:

def normalize_region(value):
    if pd.isna(value):
        return None

    value = unicodedata.normalize("NFKC", str(value))
    value = re.sub(r"\s+", " ", value.strip())
    return value.casefold()

df_region = world_food_loss.copy()

df_region["_region_normalized"] = (
    df_region["region"].map(normalize_region)
)

df_region["_country_normalized"] = (
    df_region["country"].map(normalize_region)
)

In [191]:
missing_region_report = (
    df_region.groupby(
        ["m49_code", "country"],
        dropna=False
    )
    .agg(
        total_rows=("region", "size"),
        missing_regions=("region", lambda s: s.isna().sum())
    )
    .reset_index()
)

missing_region_report["missing_percentage"] = (
    missing_region_report["missing_regions"]
    / missing_region_report["total_rows"]
    * 100
).round(2)

display(
    missing_region_report[
        missing_region_report["missing_regions"] > 0
    ].sort_values("missing_percentage", ascending=False)
)

,m49_code,country,total_rows,missing_regions,missing_percentage
0,1,World,29,29,100.00
1,2,Africa,4,4,100.00
2,4,Afghanistan,30,30,100.00
3,8,Albania,2,2,100.00
4,11,Western Africa,4,4,100.00
...,...,...,...,...,...
22,76,Brazil,43,17,39.53
99,504,Morocco,47,12,25.53
119,626,Timor-Leste,36,9,25.00
81,410,Republic of Korea,40,7,17.50
58,275,Palestine,51,4,7.84

#### **Inconsistent Region Names and Different Regions per Country**

In [192]:
# Point 2: Inconsistent Region Names + Different Regions per Country

region_name_variants = (
    df_region.dropna(subset=["region"])
    .groupby("_region_normalized")
    .agg(
        original_names=(
            "region",
            lambda s: sorted(s.astype(str).unique().tolist())
        ),
        occurrences=("region", "size")
    )
    .reset_index()
)

region_name_variants["number_of_variants"] = (
    region_name_variants["original_names"].str.len()
)

# Get all distinct regions recorded for each country
country_regions = (
    df_region.dropna(subset=["country", "region"])
    .groupby(["m49_code", "country"])
    .agg(
        different_regions=(
            "region",
            lambda s: sorted(s.astype(str).unique().tolist())
        ),
        different_regions_count=("region", "nunique")
    )
    .reset_index()
)

# Identify region names that differ only in formatting/capitalization
inconsistent_names = region_name_variants[
    region_name_variants["number_of_variants"] > 1
].copy()

# Link those names to countries using the normalized region
variant_country_details = (
    df_region.dropna(subset=["country", "region"])
    .merge(
        inconsistent_names[
            ["_region_normalized", "original_names", "number_of_variants"]
        ],
        on="_region_normalized",
        how="inner"
    )
    .groupby(["m49_code", "country"])
    .agg(
        inconsistent_region_names=(
            "original_names",
            lambda groups: sorted({
                name
                for group in groups
                for name in group
            })
        ),
        inconsistent_region_count=(
            "_region_normalized", "nunique"
        )
    )
    .reset_index()
)

# Combine both reports
point_2_report = country_regions.merge(
    variant_country_details,
    on=["m49_code", "country"],
    how="left"
)

display(
    point_2_report[
        [
            "m49_code",
            "country",
            "different_regions_count",
            "different_regions",
            "inconsistent_region_count",
            "inconsistent_region_names"
        ]
    ].sort_values(
        ["inconsistent_region_count", "country"],
        ascending=[False, True],
        na_position="last"
    )
)

,m49_code,country,different_regions_count,different_regions,inconsistent_region_count,inconsistent_region_names
9,231,Ethiopia,23,[Adami Tulu - Jido Kombolcha and Adama Distric...,2.0,"[Amhara Region, Amhara region, Southern Natio..."
12,288,Ghana,34,[? Sites: coastal and transition ecological zo...,2.0,"[Bawku, Wa Tamale, Yendi, and Techiman, Bawku..."
6,156,China,38,"[Anhui, Beijing, Beijing, Xinfadi and Jinxiuda...",1.0,"[Xiasha Town, Xiasha town]"
0,50,Bangladesh,32,[4 Upazillas of Chapai Nowabgonj and 2 Upazill...,NaN,NaN
7,204,Benin,1,[Parakou (Borgou)],NaN,NaN
1,76,Brazil,3,"[Bahia, Rio Grande do Sul, State of Bahia, Sla...",NaN,NaN
2,116,Cambodia,1,"[Kandal Province, and wholesalers and retailer...",NaN,NaN
3,120,Cameroon,2,"[Boyo, Yaoundé]",NaN,NaN
5,152,Chile,1,[North Patagonia Region],NaN,NaN
8,218,Ecuador,3,"[El Carchi, El Carchi, Imbabura, and Pichincha...",NaN,NaN
42,818,Egypt,11,"[Bani Suef, Beni Suef (Middle Egypt), Dakahlia...",NaN,NaN
10,232,Eritrea,3,"[Asheray, Hamelmalo, Teraemini]",NaN,NaN
13,320,Guatemala,2,"[Chimaltenango, Escuintla, Guatemala, Quetzalt...",NaN,NaN
14,340,Honduras,1,"[Choluteca, Copan, El Paraiso, Francisco Moraz...",NaN,NaN
15,356,India,43,"[Ajana, Akbarpur, Anadhra Pradesh, Andhra Prad...",NaN,NaN
16,360,Indonesia,7,"[Central Java, East Java Province, Jambi, Sung...",NaN,NaN
17,364,Iran (Islamic Republic of),1,[North Eastern],NaN,NaN
18,400,Jordan,1,[National average],NaN,NaN
19,404,Kenya,17,"[Dry Mid Altitude Zone, Dry Transitional Zone,...",NaN,NaN
21,422,Lebanon,2,"[Mount Lebanon - Kesrwan, Mount Lebanon, Akkar...",NaN,NaN
22,430,Liberia,15,"[Bomi, Bong, Gbarpolu, Grand Bassa, Grand Cape...",NaN,NaN
23,454,Malawi,2,"[Namingongo, Zulu]",NaN,NaN
24,504,Morocco,16,"[Ait Baamrane, Rhamna, Bensilmane, CAM Ben Sli...",NaN,NaN
25,508,Mozambique,8,"[Gaza province, Manica and Tete provinces, Man...",NaN,NaN
26,524,Nepal,28,"[Bhairahwa, Nepal to Gorakhpur, India, Bhirgao...",NaN,NaN
27,554,New Zealand,1,[Fiji Export Market],NaN,NaN
28,562,Niger,2,"[Dosso, Maradi, and Zinder regions, Niamey]",NaN,NaN
29,566,Nigeria,13,"[Benue, Benue, Plateau and Taraba regions, Del...",NaN,NaN
30,586,Pakistan,6,"[Balochistan - Quetta, Pishin and Mastung dist...",NaN,NaN
11,275,Palestine,4,"[Qabatiya and Hebron, Qalqilya and Tulkarem, W...",NaN,NaN
31,591,Panama,1,[Chiriqui],NaN,NaN
32,604,Peru,4,"[Assam, Junin and Ayacucho, Lima, Selva and Co...",NaN,NaN
33,608,Philippines,10,"[Bataan, Blumentritt, Calabarzon, Divisoria, L...",NaN,NaN
20,410,Republic of Korea,1,"[North Hwanghae, South Pyongan and Pongyang City]",NaN,NaN
35,646,Rwanda,1,[Kamonyi District],NaN,NaN
37,710,South Africa,2,"[Western Cape, Western Cape Province]",NaN,NaN
4,144,Sri Lanka,1,[Conventional value chain],NaN,NaN
39,764,Thailand,3,"[Chiang Mai, Lamphun, Chanthaburi and Sa Kaeo ...",NaN,NaN
34,626,Timor-Leste,3,"[Baucau, Lautem District, Subdistricts of Bauc...",NaN,NaN
40,788,Tunisia,3,"[Bizerte, Bizerte and Siliana, Siliana]",NaN,NaN
41,800,Uganda,6,"[Apac District, Apac Districy, Apac and Lira d...",NaN,NaN
43,834,United Republic of Tanzania,9,"[Chalinze, Lugoba and Kiwangwa, Dodoma and Man...",NaN,NaN
44,840,United States of America,1,[California],NaN,NaN
36,704,Viet Nam,8,"[An Giang, Sóc Trăng, Bạc Liêu and Kiên Giang...",NaN,NaN
45,894,Zambia,1,[Lusaka ans Southern Province],NaN,NaN
38,716,Zimbabwe,9,"[Gokwe North, Guruve District, Guruwe District...",NaN,NaN

#### **Extra Spaces**

In [193]:
region_text = df_region["region"].astype("string")

extra_spaces = df_region.loc[
    region_text.notna()
    & (
        region_text.ne(region_text.str.strip())
        | region_text.str.contains(r"\s{2,}", regex=True, na=False)
    ),
    ["m49_code", "country", "region"]
].drop_duplicates()

display(extra_spaces)

print("Rows with extra spaces:", len(extra_spaces))

       m49_code   country                                             region
2141        156     China                        Dingxi Prefecture  in Gansu
3682        231  Ethiopia       Southern Nations,  Nationalities and Peoples
3687        231  Ethiopia      Southern Nations,  Nationalities and  Peoples
3690        231  Ethiopia     Southern  Nations,  Nationalities  and Peoples
7657        288     Ghana  coastal and transition ecological zones of Ghana
7809        288     Ghana  Bawku, Wa  Tamale, Yendi , Techiman, and Kintampo
7872        288     Ghana             Bawku, Wa  Tamale, Yendi, and Techiman
7887        288     Ghana              Bawku, Wa  Tamale, Yendi and Techiman
12613       404     Kenya  Upper Athi River Region; Kilala, Ikanganya,  K...
22616       704  Viet Nam  An Giang, Sóc Trăng, Bạc Liêu and Kiên  Giang ...
22617       704  Viet Nam  Mekong Delta- An Giang, Sóc Trăng, Bạc Liêu an...
25311       764  Thailand               Hot district of Chiang Mai  province

Rows with extra spaces: 12

#### **Same Region Used Across Different Countries**

In [194]:
shared_regions = (
    df_region.dropna(
        subset=["_region_normalized", "_country_normalized"]
    )
    .groupby("_region_normalized")
    .agg(
        region_names=(
            "region",
            lambda s: sorted(s.astype(str).unique().tolist())
        ),
        countries=(
            "country",
            lambda s: sorted(s.astype(str).unique().tolist())
        ),
        country_count=("_country_normalized", "nunique"),
        records=("country", "size")
    )
    .reset_index()
)

display(
    shared_regions[
        shared_regions["country_count"] > 1
    ].sort_values("country_count", ascending=False)
)

,_region_normalized,region_names,countries,country_count,records
275,punjab,[Punjab],"[Bangladesh, India, Pakistan]",3,6
21,assam,[Assam],"[India, Peru]",2,5
171,karnataka,[Karnataka],"[Bangladesh, India]",2,13
246,national average,[National average],"[Egypt, Jordan]",2,12
350,uttar pradesh,[Uttar Pradesh],"[Bangladesh, India]",2,3

#### **Mixed Geographic Levels**

In [195]:
region_level_review = (
    df_region.dropna(subset=["region"])
    .groupby(["region"])
    .agg(
        records=("region", "size"),
        country_count=("country", "nunique"),
        countries=(
            "country",
            lambda s: sorted(s.dropna().astype(str).unique().tolist())
        ),
        m49_codes=(
            "m49_code",
            lambda s: sorted(s.dropna().astype(str).unique().tolist())
        )
    )
    .reset_index()
    .sort_values("region")
)

display(region_level_review)

,region,records,country_count,countries,m49_codes
0,4 Upazillas of Chapai Nowabgonj and 2 Upazilla...,2,1,[Bangladesh],[50]
1,? Sites: coastal and transition ecological zon...,1,1,[Ghana],[288]
2,Adami Tulu - Jido Kombolcha and Adama Districts,3,1,[Ethiopia],[231]
3,Addis Ababa and Adama cities,2,1,[Ethiopia],[231]
4,"Ait Baamrane, Rhamna",1,1,[Morocco],[504]
...,...,...,...,...,...
373,coastal and transition ecological zones of Ghana,7,1,[Ghana],[288]
374,forest and coastal ecological zones of Ghana,13,1,[Ghana],[288]
375,"four main potatogrowing counties in Kenya, nam...",4,1,[Kenya],[404]
376,from Jumla,1,1,[Nepal],[524]
377,"grown in Tupi, South Cotabato, in Mindanao, an...",1,1,[Philippines],[608]

#### **Duplicate or Equivalent Names**

In [196]:
equivalent_region_names = (
    df_region.dropna(subset=["region"])
    .groupby("_region_normalized")
    .agg(
        original_names=(
            "region",
            lambda s: sorted(s.astype(str).unique().tolist())
        ),
        number_of_names=("region", "nunique"),
        total_records=("region", "size")
    )
    .reset_index()
)

display(
    equivalent_region_names[
        equivalent_region_names["number_of_names"] > 1
    ]
)

,_region_normalized,original_names,number_of_names,total_records
8,amhara region,"[Amhara Region, Amhara region]",2,4
32,"bawku, wa tamale, yendi, and techiman","[Bawku, Wa Tamale, Yendi, and Techiman, Bawku...",2,15
77,coastal and transition ecological zones of ghana,[coastal and transition ecological zones of Gh...,2,8
324,"southern nations, nationalities and peoples","[Southern Nations, Nationalities and People...",3,8
365,xiasha town,"[Xiasha Town, Xiasha town]",2,7

#### **Validate Missing Regions**

In [197]:
missing_region_records = df_region.loc[
    df_region["region"].isna(),
    [
        "m49_code",
        "country",
        "region",
        "commodity",
        "year",
        "food_supply_stage",
        "activity",
        "cause_of_loss"
    ]
].copy()

display(missing_region_records)

print("Total records with missing region:",
      len(missing_region_records))

print("Countries with missing region:",
      missing_region_records["country"].nunique())

print("\nMissing region records by country:")
display(
    missing_region_records.groupby(
        ["m49_code", "country"],
        dropna=False
    )
    .size()
    .reset_index(name="missing_region_records")
    .sort_values("missing_region_records", ascending=False)
)

,m49_code,country,region,commodity,year,food_supply_stage,activity,cause_of_loss
0,1,World,NaN,Wheat,2022,Processing,Processing,NaN
1,1,World,NaN,Maize (corn),2022,Processing,Processing,NaN
2,1,World,NaN,Maize (corn),2022,Processing,Processing,NaN
3,1,World,NaN,Maize (corn),2022,Processing,Processing,NaN
4,1,World,NaN,Maize (corn),2022,Processing,Processing,NaN
...,...,...,...,...,...,...,...,...
31460,894,Zambia,NaN,Millet,2000,Storage,Storage,NaN
31461,894,Zambia,NaN,Millet,2000,NaN,"Shelling, Threshing",NaN
31462,894,Zambia,NaN,Millet,2000,Farm,Transportation,NaN
31463,894,Zambia,NaN,Millet,2000,Transport,Transportation,NaN
31464,894,Zambia,NaN,Millet,2000,Farm,Winnowing,NaN

Total records with missing region: 29429
Countries with missing region: 157

Missing region records by country:

     m49_code                   country  missing_region_records
152       840  United States of America                    1715
68        356                     India                    1225
49        231                  Ethiopia                    1072
79        404                     Kenya                     969
145       800                    Uganda                     848
..        ...                       ...                     ...
55        266                     Gabon                       1
42        191                   Croatia                       1
37        158              China,Taiwan                       1
122       659     Saint Kitts and Nevis                       1
100       512                      Oman                       1

[157 rows x 3 columns]

#### **Incorrect Country–Region Mapping**

In [198]:
import pandas as pd
import requests
from io import StringIO
from IPython.display import display

# All reference links
reference_links = {
    "un_m49_official_page": (
        "https://unstats.un.org/unsd/methodology/m49/overview/"
    ),
    "un_m49_csv": (
        "https://raw.githubusercontent.com/omnika-datastore/"
        "unsd-m49-standard-area-codes/main/"
        "2022-09-24__CSV_UNSD_M49.csv"
    ),
    "lukes_iso_m49_csv": (
        "https://raw.githubusercontent.com/lukes/"
        "ISO-3166-Countries-with-Regional-Codes/master/all/all.csv"
    ),
    "mledoze_countries_json": (
        "https://raw.githubusercontent.com/mledoze/"
        "countries/master/countries.json"
    ),
    "datahub_country_codes_csv": (
        "https://datahub.io/core/country-codes/r/country-codes.csv"
    ),
    "geojson_countries": (
        "https://raw.githubusercontent.com/datasets/"
        "geo-countries/master/data/countries.geojson"
    ),
}

references = {}
load_results = []

for name, url in reference_links.items():
    try:
        if name == "un_m49_official_page":
            # Official UN page: extract its HTML tables
            tables = pd.read_html(url)

            references[name] = tables

            load_results.append({
                "source": name,
                "status": "Loaded",
                "rows": sum(len(table) for table in tables),
                "columns_or_keys": str([
                    table.columns.tolist() for table in tables
                ]),
                "url": url
            })
            continue

        response = requests.get(url, timeout=30)
        response.raise_for_status()

        if name.endswith("_csv"):
            data = pd.read_csv(
                StringIO(response.text),
                dtype="string"
            )

        elif name.endswith("_json"):
            data = pd.json_normalize(response.json())

        elif name == "geojson_countries":
            geojson = response.json()
            data = pd.json_normalize(geojson["features"])

        else:
            data = response.json()

        references[name] = data

        load_results.append({
            "source": name,
            "status": "Loaded",
            "rows": len(data) if isinstance(data, pd.DataFrame) else None,
            "columns_or_keys": str(
                data.columns.tolist()
                if isinstance(data, pd.DataFrame)
                else list(data.keys())
            ),
            "url": url
        })

    except Exception as e:
        load_results.append({
            "source": name,
            "status": f"Failed: {type(e).__name__}: {e}",
            "rows": None,
            "columns_or_keys": None,
            "url": url
        })

load_report = pd.DataFrame(load_results)

display(load_report)

,source,status,rows,columns_or_keys,url
0,un_m49_official_page,Loaded,1488.0,"[['Global Code', 'Global Name', 'Region Code',...",https://unstats.un.org/unsd/methodology/m49/ov...
1,un_m49_csv,Failed: ParserError: Error tokenizing data. C ...,NaN,NaN,https://raw.githubusercontent.com/omnika-datas...
2,lukes_iso_m49_csv,Loaded,249.0,"['name', 'alpha-2', 'alpha-3', 'country-code',...",https://raw.githubusercontent.com/lukes/ISO-31...
3,mledoze_countries_json,Loaded,250.0,"['tld', 'cca2', 'ccn3', 'cca3', 'cioc', 'indep...",https://raw.githubusercontent.com/mledoze/coun...
4,datahub_country_codes_csv,Loaded,249.0,"['FIFA', 'Dial', 'ISO3166-1-Alpha-3', 'MARC', ...",https://datahub.io/core/country-codes/r/countr...
5,geojson_countries,Loaded,258.0,"['type', 'properties.name', 'properties.ISO316...",https://raw.githubusercontent.com/datasets/geo...

In [199]:
import pandas as pd
import re
import unicodedata

def normalize_name(value):
    if pd.isna(value):
        return ""

    value = unicodedata.normalize("NFKC", str(value))
    value = value.strip().casefold()
    value = re.sub(r"\s+", " ", value)

    return value


# Get the official UN M49 table
un_tables = references["un_m49_official_page"]

un_m49 = next(
    table.copy()
    for table in un_tables
    if {
        "Country or Area",
        "M49 Code",
        "Region Name"
    }.issubset(table.columns)
)

un_m49["country_key"] = un_m49["Country or Area"].map(
    normalize_name
)

un_m49["m49_code"] = (
    un_m49["M49 Code"]
    .astype("string")
    .str.strip()
    .str.zfill(3)
)

un_m49["official_region"] = un_m49["Region Name"].astype("string").str.strip()

display(
    un_m49[
        ["Country or Area", "m49_code", "official_region"]
    ].head()
)

  Country or Area m49_code official_region
0         Algeria      012          Africa
1           Egypt      818          Africa
2           Libya      434          Africa
3         Morocco      504          Africa
4           Sudan      729          Africa

In [200]:
# Validate country + M49 code as a pair, then inspect the region label.
# IMPORTANT: FAO's "region" can be a source-specific/local region (e.g. Upper Egypt),
# so a difference from UN's top-level Region Name is NOT automatically an error.

food = world_food_loss.copy()

def normalize_m49_code(value):
    if pd.isna(value):
        return ""
    text = str(value).strip()
    if text.endswith(".0") and text[:-2].isdigit():
        text = text[:-2]
    if text.isdigit() and len(text) <= 3:
        return text.zfill(3)
    return text

food["country_key"] = food["country"].map(normalize_name)
food["m49_code_key"] = food["m49_code"].map(normalize_m49_code)
food["region_key"] = food["region"].map(normalize_name)

# Country/area reference from official UN M49 table.
country_lookup = (
    un_m49[["country_key", "m49_code", "Country or Area", "official_region"]]
    .drop_duplicates()
    .rename(columns={
        "m49_code": "official_m49_code",
        "Country or Area": "official_country_name",
        "official_region": "un_region"
    })
)

checked = food.merge(
    country_lookup,
    on="country_key",
    how="left",
    validate="many_to_one"
)

checked["country_code_status"] = "PASS"
checked.loc[
    checked["country_key"].eq("") | checked["m49_code_key"].eq(""),
    "country_code_status"
] = "MISSING_COUNTRY_OR_CODE"
checked.loc[
    checked["country_key"].ne("")
    & checked["m49_code_key"].ne("")
    & checked["official_m49_code"].isna(),
    "country_code_status"
] = "COUNTRY_NAME_NOT_FOUND_IN_UN_M49"
checked.loc[
    checked["official_m49_code"].notna()
    & checked["m49_code_key"].ne(
        checked["official_m49_code"].map(normalize_m49_code)
    ),
    "country_code_status"
] = "COUNTRY_CODE_MISMATCH"

# A difference in region labels is only a review candidate.
checked["region_review_status"] = "NOT_COMPARABLE"
comparable_region = (
    checked["region_key"].ne("")
    & checked["un_region"].notna()
    & checked["un_region"].astype("string").str.strip().ne("")
)
checked.loc[comparable_region, "region_review_status"] = "REVIEW_REGION_LEVEL"
checked.loc[
    comparable_region
    & checked["region_key"].eq(checked["un_region"].map(normalize_name)),
    "region_review_status"
] = "MATCHES_UN_TOP_LEVEL_REGION"

country_code_issues = checked.loc[
    checked["country_code_status"].ne("PASS"),
    [
        "country", "m49_code", "region", "official_country_name",
        "official_m49_code", "country_code_status", "commodity",
        "year", "reference", "url"
    ]
].drop_duplicates()

region_level_review = checked.loc[
    checked["region_review_status"].eq("REVIEW_REGION_LEVEL"),
    [
        "country", "m49_code", "region", "un_region",
        "region_review_status", "commodity", "year", "reference"
    ]
].drop_duplicates()

print("Country/code validation status:")
display(checked["country_code_status"].value_counts(dropna=False).rename_axis("status").reset_index(name="records"))
print("Country/code issues:", len(country_code_issues))
display(country_code_issues.head(100))

print("Region labels needing geographic-level review:", len(region_level_review))
display(region_level_review.head(100))

Country/code validation status:

                             status  records
0                              PASS    30735
1  COUNTRY_NAME_NOT_FOUND_IN_UN_M49      730

Country/code issues: 282

,country,m49_code,region,official_country_name,official_m49_code,country_code_status,commodity,year,reference,url
0,World,1,NaN,NaN,<NA>,COUNTRY_NAME_NOT_FOUND_IN_UN_M49,Wheat,2022,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN
1,World,1,NaN,NaN,<NA>,COUNTRY_NAME_NOT_FOUND_IN_UN_M49,Maize (corn),2022,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN
6,World,1,NaN,NaN,<NA>,COUNTRY_NAME_NOT_FOUND_IN_UN_M49,Rice,2022,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN
7,World,1,NaN,NaN,<NA>,COUNTRY_NAME_NOT_FOUND_IN_UN_M49,Sorghum,2022,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN
8,World,1,NaN,NaN,<NA>,COUNTRY_NAME_NOT_FOUND_IN_UN_M49,Barley,2022,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN
...,...,...,...,...,...,...,...,...,...,...
11094,Côte d'Ivoire,384,NaN,NaN,<NA>,COUNTRY_NAME_NOT_FOUND_IN_UN_M49,Rice,2010,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...
11099,Côte d'Ivoire,384,NaN,NaN,<NA>,COUNTRY_NAME_NOT_FOUND_IN_UN_M49,Sorghum,2010,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...
11103,Côte d'Ivoire,384,NaN,NaN,<NA>,COUNTRY_NAME_NOT_FOUND_IN_UN_M49,Millet,2010,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...
11108,Côte d'Ivoire,384,NaN,NaN,<NA>,COUNTRY_NAME_NOT_FOUND_IN_UN_M49,Maize (corn),2009,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...
11113,Côte d'Ivoire,384,NaN,NaN,<NA>,COUNTRY_NAME_NOT_FOUND_IN_UN_M49,Rice,2009,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...

Region labels needing geographic-level review: 666

,country,m49_code,region,un_region,region_review_status,commodity,year,reference
568,Cambodia,116,"Kandal Province, and wholesalers and retailers...",Asia,REVIEW_REGION_LEVEL,Tomatoes,2013,Buntong; B.; Srilaong; V.; Wasusri; T.; Kanlay...
647,Cameroon,120,Boyo,Africa,REVIEW_REGION_LEVEL,Bananas,2020,"Nkwain, K., Odiaka, E., Ikwuba, A.; Nkwi, G. E..."
697,Cameroon,120,Yaoundé,Africa,REVIEW_REGION_LEVEL,Watermelons,2017,Aristide G. Kamda Silapeux;Roger Ponka;Chiara ...
698,Cameroon,120,Yaoundé,Africa,REVIEW_REGION_LEVEL,Avocados,2017,Aristide G. Kamda Silapeux;Roger Ponka;Chiara ...
699,Cameroon,120,Yaoundé,Africa,REVIEW_REGION_LEVEL,Bananas,2017,Aristide G. Kamda Silapeux;Roger Ponka;Chiara ...
...,...,...,...,...,...,...,...,...
3312,Benin,204,Parakou (Borgou),Africa,REVIEW_REGION_LEVEL,"Mangoes, guavas and mangosteens",2005,Jean-François Vayssières; Sam Korie; Ousmane C...
3574,Ecuador,218,"El Carchi, Imbabura, and Pichincha",Americas,REVIEW_REGION_LEVEL,Potatoes,2016,Luciana Delgado; Monica Schuster-; Maximo Tore...
3575,Ecuador,218,Pichincha,Americas,REVIEW_REGION_LEVEL,Potatoes,2016,Luciana Delgado; Monica Schuster-; Maximo Tore...
3576,Ecuador,218,El Carchi,Americas,REVIEW_REGION_LEVEL,Potatoes,2016,Luciana Delgado; Monica Schuster-; Maximo Tore...
3680,Ethiopia,231,"Dugda Woreda, East Shoa Zone, Oromia",Africa,REVIEW_REGION_LEVEL,Papayas,2022,The Effect of Papaya Post-Harvest Losses on Fo...

#### **Unexpected Region Values**

In [201]:
# Collect all official geographic labels by level from the UN M49 table.
region_specs = [
    ("Global Name", "Global Code", "global"),
    ("Region Name", "Region Code", "region"),
    ("Sub-region Name", "Sub-region Code", "sub_region"),
    ("Intermediate Region Name", "Intermediate Region Code", "intermediate_region"),
]

region_reference_frames = []
for name_col, code_col, level in region_specs:
    if name_col in un_m49.columns and code_col in un_m49.columns:
        part = un_m49[[name_col, code_col]].copy()
        part.columns = ["official_region_name", "official_region_code"]
        part["geographic_level"] = level
        part = part.dropna(subset=["official_region_name", "official_region_code"])
        part["official_region_name"] = part["official_region_name"].astype("string").str.strip()
        part["official_region_code"] = part["official_region_code"].map(normalize_m49_code)
        part = part[part["official_region_name"].ne("")]
        region_reference_frames.append(part)

un_geographic_reference = (
    pd.concat(region_reference_frames, ignore_index=True).drop_duplicates()
    if region_reference_frames else
    pd.DataFrame(columns=["official_region_name", "official_region_code", "geographic_level"])
)

un_geographic_reference["region_key"] = un_geographic_reference[
    "official_region_name"
].map(normalize_name)

valid_region_keys = set(un_geographic_reference["region_key"].dropna())

print("UN geographic labels by level:")
display(
    un_geographic_reference.groupby("geographic_level")
    .agg(unique_names=("region_key", "nunique"),
         unique_codes=("official_region_code", "nunique"))
    .reset_index()
)
display(un_geographic_reference.sort_values(["geographic_level", "official_region_name"]).head(100))

UN geographic labels by level:

      geographic_level  unique_names  unique_codes
0               global             1             1
1  intermediate_region             7             7
2               region             5             5
3           sub_region            17            17

,official_region_name,official_region_code,geographic_level,region_key
0,World,001,global,world
795,Caribbean,029,intermediate_region,caribbean
823,Central America,013,intermediate_region,central america
742,Eastern Africa,014,intermediate_region,eastern africa
764,Middle Africa,017,intermediate_region,middle africa
831,South America,005,intermediate_region,south america
773,Southern Africa,018,intermediate_region,southern africa
778,Western Africa,011,intermediate_region,western africa
248,Africa,002,region,africa
308,Americas,019,region,americas
365,Asia,142,region,asia
415,Europe,150,region,europe
466,Oceania,009,region,oceania
713,Australia and New Zealand,053,sub_region,australia and new zealand
612,Central Asia,143,sub_region,central asia
617,Eastern Asia,030,sub_region,eastern asia
662,Eastern Europe,151,sub_region,eastern europe
555,Latin America and the Caribbean,419,sub_region,latin america and the caribbean
719,Melanesia,054,sub_region,melanesia
724,Micronesia,057,sub_region,micronesia
495,Northern Africa,015,sub_region,northern africa
607,Northern America,021,sub_region,northern america
672,Northern Europe,154,sub_region,northern europe
732,Polynesia,061,sub_region,polynesia
624,South-eastern Asia,035,sub_region,south-eastern asia
635,Southern Asia,034,sub_region,southern asia
688,Southern Europe,039,sub_region,southern europe
502,Sub-Saharan Africa,202,sub_region,sub-saharan africa
644,Western Asia,145,sub_region,western asia
704,Western Europe,155,sub_region,western europe

In [202]:
# Identify observed region labels not present in UN M49's global/region/subregion hierarchy.
# These are review candidates, NOT necessarily errors: FAO may contain local or study-specific regions.
observed_regions = (
    world_food_loss["region"]
    .dropna()
    .astype("string")
    .str.strip()
    .drop_duplicates()
)

unexpected_regions = observed_regions[
    ~observed_regions.map(normalize_name).isin(valid_region_keys)
]

unexpected_region_report = (
    world_food_loss[
        world_food_loss["region"].map(normalize_name).isin(
            set(unexpected_regions.map(normalize_name))
        )
    ]
    .groupby("region", dropna=False)
    .agg(
        row_count=("region", "size"),
        country_count=("country", "nunique"),
        sample_countries=(
            "country",
            lambda values: ", ".join(values.dropna().astype(str).unique()[:5])
        ),
        sample_commodities=(
            "commodity",
            lambda values: ", ".join(values.dropna().astype(str).unique()[:5])
        )
    )
    .reset_index()
    .sort_values("row_count", ascending=False)
)

print("Observed region labels not in UN M49 hierarchy:", len(unexpected_regions))
print("Interpret these as source-specific labels to classify, not auto-delete.")
display(unexpected_region_report.head(200))

Observed region labels not in UN M49 hierarchy: 377
Interpret these as source-specific labels to classify, not auto-delete.

,region,row_count,country_count,sample_countries,sample_commodities
359,Western Cape Province,59,1,South Africa,"Pears, Grapes"
78,Comilla,45,1,Bangladesh,"Potatoes, Rice"
349,Uttarakhand,42,1,India,"Cabbages, Cauliflowers and broccoli, Tomatoes,..."
282,Rangpur and Dinazpur district,36,1,Bangladesh,"Wheat, Rice"
31,"Bawku, Wa Tamale, Yendi , Techiman, and Kintampo",36,1,Ghana,"Tomatoes, Yams"
...,...,...,...,...,...
306,Shanxi,3,1,China,"Wheat, Maize (corn), Rice"
253,Nubaria,3,1,Egypt,Grapes
51,Bogra and Dakha,3,1,Bangladesh,Potatoes
280,Rampura,3,1,India,"Wheat, Maize (corn)"
297,Sargodha,3,1,Pakistan,"Tangerines, mandarins, clementines"

### **Check on cpc_code**

#### **Show missing values**

In [203]:

missing_cpc = df_region.loc[
    df_region["cpc_code"].isna(),
    ["country", "region", "commodity", "cpc_code"]
].copy()

display(missing_cpc)

print("Missing cpc_code records:", len(missing_cpc))
print(
    "Percentage missing:",
    round(df_region["cpc_code"].isna().mean() * 100, 2),
    "%"
)

Empty DataFrame
Columns: [country, region, commodity, cpc_code]
Index: []

Missing cpc_code records: 0
Percentage missing: 0.0 %

#### **Show Code with diff syntax**

In [204]:
cpc_text = df_region["cpc_code"].astype("string")
cpc_trimmed = cpc_text.str.strip()

cpc_format_issues = df_region.loc[
    cpc_text.notna()
    & (
        cpc_text.ne(cpc_trimmed)
        | cpc_trimmed.str.contains(r"\s", regex=True, na=False)
    ),
    ["country", "region", "commodity", "cpc_code"]
].copy()

display(cpc_format_issues)

print("Records with whitespace issues:", len(cpc_format_issues))

Empty DataFrame
Columns: [country, region, commodity, cpc_code]
Index: []

Records with whitespace issues: 0

#### **Discovering mixed geographic regions with countries**

***CPC 2.1***

In [205]:
cpc_clean = df_region["cpc_code"].astype("string").str.strip()

# Preliminary syntax check for CPC 2.1 codes.
# This does not validate codes against the official CPC 2.1 list.
expected_cpc_pattern = r"\d+(?:\.\d+)?"

invalid_cpc_format = df_region.loc[
    cpc_clean.notna()
    & cpc_clean.ne("")
    & ~cpc_clean.str.fullmatch(
        expected_cpc_pattern,
        na=False
    ),
    ["country", "region", "commodity", "cpc_code"]
].copy()

display(invalid_cpc_format)

print(
    "Records outside the preliminary format:",
    len(invalid_cpc_format)
)

      country region                                    commodity cpc_code
9893    India    NaN  Meat of goat, fresh or chilled (indigenous)   21116i
19441  Panama    NaN    Raw cane or beet sugar (centrifugal only)    2351f
19463  Panama    NaN    Raw cane or beet sugar (centrifugal only)    2351f
19483  Panama    NaN    Raw cane or beet sugar (centrifugal only)    2351f
19503  Panama    NaN    Raw cane or beet sugar (centrifugal only)    2351f
19523  Panama    NaN    Raw cane or beet sugar (centrifugal only)    2351f
19543  Panama    NaN    Raw cane or beet sugar (centrifugal only)    2351f

Records outside the preliminary format: 7

#### **The compatibility between a CPC Code (Central Product Classification) and a Commodity Code (HS Code)**

In [206]:
# Official CPC 2.1 classification and CPC 2.1 Expanded for Agriculture references
cpc_reference_url = {
    "UNSD_CPC21_Official_Excel":
        "https://unstats.un.org/unsd/classifications/Econ/Download/In%20Text/CPC_Ver_2.1_Exp_Notes_Updated_3Apr2025.xlsx",

    "FAO_Caliper_Classifications_Download":
        "https://www.fao.org/statistics/caliper/tools/download/en",

    "FAO_FCL_to_CPC21_Expanded_Agriculture_Mapping":
        "https://stats.fao.org/caliper/download/FCL/FCL_CPC21AG_mappings.csv",

    "UNSD_CPC21_Code_01199_Details":
        "https://unstats.un.org/unsd/classifications/Econ/Detail/EN/1074/01199"
}

# Load the official CPC 2.1 Excel workbook
cpc_workbook = pd.read_excel(
    cpc_reference_url["UNSD_CPC21_Official_Excel"],
    sheet_name=None,
    dtype=str
)

print("Available sheets:")
for sheet_name, sheet_df in cpc_workbook.items():
    print(f"\nSheet: {sheet_name}")
    print("Columns:", sheet_df.columns.tolist())
    display(sheet_df.head(3))

Available sheets:

Sheet: CPC2.1
Columns: ['CPC Ver. 2.1 Code', 'CPC Ver. 2.1 Title', 'CPC Ver. 2.1 Explanatory Note - Inclusions', 'CPC Ver. 2.1 Explanatory Note - Exclusions']

,CPC Ver. 2.1 Code,CPC Ver. 2.1 Title,CPC Ver. 2.1 Explanatory Note - Inclusions,CPC Ver. 2.1 Explanatory Note - Exclusions
0,0,"Agriculture, forestry and fishery products",NaN,NaN
1,01,"Products of agriculture, horticulture and mark...",NaN,NaN
2,011,Cereals,"This group includes cereals, i.e. annual plant...",NaN

Sheet: 61_62
Columns: ['Four-digit and five-digit codes in Divisions 61 and 62', 'Unnamed: 1', 'Unnamed: 2']

,Four-digit and five-digit codes in Divisions 61 and 62,Unnamed: 1,Unnamed: 2
0,Notes:\n1. The codes in the table below has th...,NaN,NaN
1,CPC Ver. 2.1 Code,CPC Ver. 2.1 Title,CPC Ver. 2.1 Explanatory Note - Inclusions
2,***1,"Trade services, of raw agricultural products a...",NaN

Sheet: Notes
Columns: ['Note on Updates and Corrections to CPC Ver. 2.1:', 'Unnamed: 1']

    Note on Updates and Corrections to CPC Ver. 2.1: Unnamed: 1
0              Last updated by UNSD on 3 April 2025.        NaN
1  This Excel document includes important updates...        NaN
2                                                NaN        NaN

In [207]:

# Load the official CPC 2.1 classification sheet
cpc_reference = cpc_workbook["CPC2.1"].copy()

code_col = "CPC Ver. 2.1 Code"
title_col = "CPC Ver. 2.1 Title"

# Preserve codes as strings and remove surrounding whitespace
cpc_reference["_cpc_code_clean"] = (
    cpc_reference[code_col].astype("string").str.strip()
)

cpc_reference["_cpc_title_clean"] = (
    cpc_reference[title_col].astype("string").str.strip()
)

# Remove rows without a usable code
cpc_reference = cpc_reference.loc[
    cpc_reference["_cpc_code_clean"].notna()
    & cpc_reference["_cpc_code_clean"].ne("")
].copy()

# Prepare the dataset codes
data_cpc = df_region["cpc_code"].astype("string").str.strip()

# Build a lookup set from official CPC 2.1 codes
official_codes = set(cpc_reference["_cpc_code_clean"])

# Find codes that are not present in the official reference
invalid_cpc_codes = df_region.loc[
    data_cpc.notna()
    & data_cpc.ne("")
    & ~data_cpc.isin(official_codes),
    ["country", "region", "commodity", "cpc_code"]
].copy()

display(invalid_cpc_codes)

print("Rows with codes not found in CPC 2.1:", len(invalid_cpc_codes))
print(
    "Distinct codes not found:",
    invalid_cpc_codes["cpc_code"].nunique()
)

,country,region,commodity,cpc_code
16,World,NaN,Cereals n.e.c.,01199.90
17,World,NaN,Cereals n.e.c.,01199.90
18,World,NaN,Cereals n.e.c.,01199.90
19,World,NaN,Pot barley,23140.04
20,World,NaN,Cereal preparations,23140.08
...,...,...,...,...
30691,Venezuela (Bolivarian Republic of),NaN,"Pig, Butcher Fat",21511.02
30693,Venezuela (Bolivarian Republic of),NaN,Cheese from Whole Cow Milk,22251.01
30695,Venezuela (Bolivarian Republic of),NaN,Flour of Maize,23120.03
30696,Venezuela (Bolivarian Republic of),NaN,"Rice, Milled",23161.02
30698,Venezuela (Bolivarian Republic of),NaN,Bran of Maize,39120.04

Rows with codes not found in CPC 2.1: 1629
Distinct codes not found: 71

#### **Displaying each used code and comparing it with the official title**

In [208]:
# Aggregate commodities used with each CPC code
used_codes = (
    df_region.dropna(subset=["cpc_code"])
    .assign(
        _cpc_code_clean=lambda d: (
            d["cpc_code"].astype("string").str.strip()
        )
    )
    .groupby("_cpc_code_clean")
    .agg(
        commodities=(
            "commodity",
            lambda s: sorted(s.dropna().astype(str).unique().tolist())
        ),
        records=("commodity", "size")
    )
    .reset_index()
)

# Match dataset codes to the official CPC 2.1 reference
official_lookup = (
    cpc_reference[
        ["_cpc_code_clean", "_cpc_title_clean"]
    ]
    .drop_duplicates(subset=["_cpc_code_clean"])
)

cpc_code_review = used_codes.merge(
    official_lookup,
    on="_cpc_code_clean",
    how="left",
    indicator=True
)

cpc_code_review = cpc_code_review.rename(
    columns={
        "_cpc_code_clean": "cpc_code",
        "_cpc_title_clean": "official_cpc_title",
        "_merge": "reference_match"
    }
)

display(
    cpc_code_review.sort_values(
        ["reference_match", "cpc_code"]
    )
)

,cpc_code,commodities,records,official_cpc_title,reference_match
13,01199.02,[Mixed grain],57,<NA>,left_only
14,01199.90,"[Cereals n.e.c., Other cereals n.e.]",30,<NA>,left_only
28,01239.01,[Okra],91,<NA>,left_only
29,01241.90,"[Other beans, green]",78,<NA>,left_only
34,01253.01,"[Onions and shallots, green]",141,<NA>,left_only
...,...,...,...,...,...
181,23162,[Husked rice],20,Husked rice,both
188,23520,[Refined sugar],51,Refined sugar,both
189,23710,"[Uncooked pasta, not stuffed or otherwise prep...",9,"Uncooked pasta, not stuffed or otherwise prepared",both
190,23911,"[Coffee, decaffeinated or roasted]",2,"Coffee, decaffeinated or roasted",both
193,24320,"[Malt, whether or not roasted]",2,"Malt, whether or not roasted",both

#### **Checking only the codes that are missing from the reference**

In [209]:
not_found = cpc_code_review.loc[
    cpc_code_review["reference_match"] == "left_only"
].copy()

display(not_found)

print("Distinct unmatched codes:", len(not_found))

,cpc_code,commodities,records,official_cpc_title,reference_match
13,01199.02,[Mixed grain],57,<NA>,left_only
14,01199.90,"[Cereals n.e.c., Other cereals n.e.]",30,<NA>,left_only
28,01239.01,[Okra],91,<NA>,left_only
29,01241.90,"[Other beans, green]",78,<NA>,left_only
34,01253.01,"[Onions and shallots, green]",141,<NA>,left_only
...,...,...,...,...,...
187,2351f,[Raw cane or beet sugar (centrifugal only)],6,<NA>,left_only
191,23993.03,"[Eggs, dried]",6,<NA>,left_only
192,24212.02,[Wine],1,<NA>,left_only
194,39120.04,[Bran of Maize],14,<NA>,left_only
195,39170.01,[Food wastes],2,<NA>,left_only

Distinct unmatched codes: 71

#### **Reviewing suspicious codes**

In [210]:
display(
    cpc_code_review.loc[
        cpc_code_review["reference_match"] == "left_only",
        ["cpc_code", "commodities", "records"]
    ].sort_values("records", ascending=False)
)

print(
    "Distinct codes missing from core CPC reference:",
    cpc_code_review.loc[
        cpc_code_review["reference_match"] == "left_only",
        "cpc_code"
    ].nunique()
)

     cpc_code                                        commodities  records
34   01253.01                       [Onions and shallots, green]      141
73   01359.90         [Other fruits, n.e., Other fruits, n.e.c.]      117
95   01520.01                                   [Cassava, fresh]      115
138  21111.01  [Meat of cattle with the bone, fresh or chille...       99
56   01342.01                                            [Pears]       95
..        ...                                                ...      ...
122  01919.92                        [Other legumes, for forage]        1
163  21439.04                     [Juice of citrus fruit n.e.c.]        1
162  21439.02                                   [Juice of lemon]        1
143    21116i      [Meat of goat, fresh or chilled (indigenous)]        1
192  24212.02                                             [Wine]        1

[71 rows x 3 columns]

Distinct codes missing from core CPC reference: 71

#### **Reviewing codes containing letters**

In [211]:
cpc_text = df_region["cpc_code"].astype("string").str.strip()

codes_containing_letters = df_region.loc[
    cpc_text.str.contains(r"[A-Za-z]", na=False),
    ["country", "region", "commodity", "cpc_code"]
].copy()

display(codes_containing_letters)

print("Records with alphabetic characters:", len(codes_containing_letters))

      country region                                    commodity cpc_code
9893    India    NaN  Meat of goat, fresh or chilled (indigenous)   21116i
19441  Panama    NaN    Raw cane or beet sugar (centrifugal only)    2351f
19463  Panama    NaN    Raw cane or beet sugar (centrifugal only)    2351f
19483  Panama    NaN    Raw cane or beet sugar (centrifugal only)    2351f
19503  Panama    NaN    Raw cane or beet sugar (centrifugal only)    2351f
19523  Panama    NaN    Raw cane or beet sugar (centrifugal only)    2351f
19543  Panama    NaN    Raw cane or beet sugar (centrifugal only)    2351f

Records with alphabetic characters: 7

#### **Checking for potential loss of leading zeros**

In [212]:

cpc = df_region["cpc_code"].astype("string")
cpc_clean = cpc.str.strip()

# Allow digit groups with an optional decimal suffix.
# This checks syntax only, not official CPC validity.
valid_syntax = cpc_clean.str.fullmatch(
    r"\d+(?:\.\d+)?",
    na=False
)

invalid_cpc_format = df_region.loc[
    cpc.notna()
    & cpc_clean.ne("")
    & ~valid_syntax,
    ["country", "region", "commodity", "cpc_code"]
].copy()

display(invalid_cpc_format)

print("Invalid-looking code formats:", len(invalid_cpc_format))

      country region                                    commodity cpc_code
9893    India    NaN  Meat of goat, fresh or chilled (indigenous)   21116i
19441  Panama    NaN    Raw cane or beet sugar (centrifugal only)    2351f
19463  Panama    NaN    Raw cane or beet sugar (centrifugal only)    2351f
19483  Panama    NaN    Raw cane or beet sugar (centrifugal only)    2351f
19503  Panama    NaN    Raw cane or beet sugar (centrifugal only)    2351f
19523  Panama    NaN    Raw cane or beet sugar (centrifugal only)    2351f
19543  Panama    NaN    Raw cane or beet sugar (centrifugal only)    2351f

Invalid-looking code formats: 7

#### **Checking for spaces and null/empty values**

In [213]:
cpc_text = df_region["cpc_code"].astype("string")

cpc_whitespace_issues = df_region.loc[
    cpc_text.notna()
    & (
        cpc_text.ne(cpc_text.str.strip())
        | cpc_text.str.contains(r"\s", regex=True, na=False)
    ),
    ["country", "region", "commodity", "cpc_code"]
].copy()

cpc_blank = df_region.loc[
    cpc_text.notna() & cpc_text.str.strip().eq(""),
    ["country", "region", "commodity", "cpc_code"]
].copy()

cpc_missing = df_region.loc[
    cpc_text.isna(),
    ["country", "region", "commodity", "cpc_code"]
].copy()

display(cpc_whitespace_issues)
display(cpc_blank)
display(cpc_missing)

print("Whitespace issues:", len(cpc_whitespace_issues))
print("Blank codes:", len(cpc_blank))
print("Missing codes:", len(cpc_missing))

Empty DataFrame
Columns: [country, region, commodity, cpc_code]
Index: []

Empty DataFrame
Columns: [country, region, commodity, cpc_code]
Index: []

Empty DataFrame
Columns: [country, region, commodity, cpc_code]
Index: []

Whitespace issues: 0
Blank codes: 0
Missing codes: 0

#### **Checking spelling variations for the same code**

In [214]:
cpc_variants = (
    df_region.dropna(subset=["cpc_code"])
    .assign(
        _cpc_clean=lambda d: (
            d["cpc_code"].astype("string").str.strip()
        )
    )
    .groupby("_cpc_clean")
    .agg(
        original_codes=(
            "cpc_code",
            lambda s: sorted(s.astype(str).unique().tolist())
        ),
        number_of_variants=("cpc_code", "nunique"),
        total_records=("cpc_code", "size"),
        commodities=(
            "commodity",
            lambda s: sorted(s.dropna().astype(str).unique().tolist())
        )
    )
    .reset_index()
)

display(
    cpc_variants[cpc_variants["number_of_variants"] > 1]
    .sort_values("number_of_variants", ascending=False)
)

Empty DataFrame
Columns: [_cpc_clean, original_codes, number_of_variants, total_records, commodities]
Index: []

#### **"Checking for many-to-many relationships" / "Detecting codes mapped to multiple commodities"**

In [215]:
cpc_commodity_mapping = (
    df_region.dropna(subset=["cpc_code", "commodity"])
    .groupby("cpc_code")
    .agg(
        commodities=(
            "commodity",
            lambda s: sorted(s.astype(str).unique().tolist())
        ),
        commodity_count=("commodity", "nunique"),
        records=("commodity", "size")
    )
    .reset_index()
)

display(
    cpc_commodity_mapping[
        cpc_commodity_mapping["commodity_count"] > 1
    ].sort_values("commodity_count", ascending=False)
)

,cpc_code,commodities,commodity_count,records
14,01199.90,"[Cereals n.e.c., Other cereals n.e.]",2,30
23,01231,"[Chillies and peppers, green (<i>Capsicum</i> ...",2,57
39,01290.90,"[Other vegetables, fresh n.e., Other vegetable...",2,52
42,01313,"[Plantains and cooking bananas, Plantains and ...",2,43
45,01316,"[Mangoes, guavas and mangosteens, Mangoes, gua...",2,302
48,01319,"[Other tropical and subtropical fruits, n.e., ...",2,60
53,01329,"[Other citrus fruit, n.e., Other citrus fruit,...",2,37
67,01353.01,"[Raspberries, Raspeberries]",2,36
70,01355.02,"[Cranberries, Cranberries and other fruits of ...",2,35
73,01359.90,"[Other fruits, n.e., Other fruits, n.e.c.]",2,117
85,01443,"[Rape or colza seed, Rapeseed or colza seed]",2,37
101,01599.10,[Edible roots and tubers with high starch or i...,2,16
118,01709.90,"[Other pulses n.e.c., Pulses n.e.]",2,35
138,21111.01,"[Meat of cattle with the bone, fresh or chille...",2,99
139,21113.01,"[Meat of pig with the bone, fresh or chilled, ...",2,62
170,22251.01,"[Cheese from Whole Cow Milk, Cheese from whole...",2,14
179,23161.02,"[Rice, Milled, Rice, milled]",2,37

#### **Checking for leading zeros**

In [216]:
cpc_codes = df_region["cpc_code"].dropna().astype("string").str.strip()

leading_zero_codes = cpc_codes[
    cpc_codes.str.match(r"^0+\d+(?:\.\d+)?$", na=False)
]

print("Codes beginning with zero:", len(leading_zero_codes))
display(leading_zero_codes.drop_duplicates().to_frame("cpc_code"))

Codes beginning with zero: 30719

       cpc_code
0          0111
1          0112
6          0113
7          0114
8          0115
...         ...
27101  01919.08
27512     01708
27871     01216
28846  01990.01
30357     01492

[138 rows x 1 columns]

### **Check on commodity**

### **Show missing values**

In [217]:
# Check missing and empty commodity values
commodity_clean = df_region["commodity"].astype("string").str.strip()

missing_commodity = df_region.loc[
    commodity_clean.isna() | commodity_clean.eq(""),
    ["country", "region", "commodity", "cpc_code"]
].copy()

print("Missing commodity records:", len(missing_commodity))
display(missing_commodity.head(20))

Missing commodity records: 0

Empty DataFrame
Columns: [country, region, commodity, cpc_code]
Index: []

#### **Duplicate names with different formatting**

In [218]:
# Normalize names for comparison only
commodity_normalized = (
    df_region["commodity"]
    .astype("string")
    .str.strip()
    .str.casefold()
    .str.replace(r"\s+", " ", regex=True)
)

commodity_variants = (
    df_region.assign(_commodity_normalized=commodity_normalized)
    .dropna(subset=["_commodity_normalized"])
    .groupby("_commodity_normalized")
    .agg(
        original_names=("commodity", lambda s: sorted(s.astype(str).unique())),
        records=("commodity", "size"),
        cpc_codes=("cpc_code", lambda s: sorted(s.dropna().astype(str).unique()))
    )
    .reset_index()
)

commodity_variants = commodity_variants.loc[
    commodity_variants["original_names"].apply(len) > 1
].copy()

print("Names with formatting/case variants:", len(commodity_variants))
display(commodity_variants)

Names with formatting/case variants: 2

,_commodity_normalized,original_names,records,cpc_codes
35,cheese from whole cow milk,"[Cheese from Whole Cow Milk, Cheese from whole...",14,[22251.01]
171,"rice, milled","[Rice, Milled, Rice, milled]",37,[23161.02]

#### **Diff in Singular vs. plural**

In [219]:
# Install once if needed:
# %pip install inflect

import inflect

engine = inflect.engine()

commodity_names = (
    df_region["commodity"]
    .dropna()
    .astype(str)
    .str.strip()
    .unique()
)

singular_plural_candidates = []

for name in commodity_names:
    singular = engine.singular_noun(name)

    if singular and singular.casefold() != name.casefold():
        if singular.casefold() in {
            value.casefold() for value in commodity_names
        }:
            singular_plural_candidates.append({
                "original_name": name,
                "possible_singular": singular
            })

singular_plural_review = pd.DataFrame(singular_plural_candidates)

display(singular_plural_review)

Empty DataFrame
Columns: []
Index: []

#### **Spelling errors**

In [220]:
commodity_frequency = (
    df_region["commodity"]
    .dropna()
    .astype("string")
    .str.strip()
    .value_counts()
    .rename_axis("commodity")
    .reset_index(name="records")
)

rare_commodity_names = commodity_frequency.loc[
    commodity_frequency["records"] <= 2
].copy()

print("Rare commodity names:", len(rare_commodity_names))
display(rare_commodity_names)

Rare commodity names: 28

                                             commodity  records
185                                         Pot barley        2
186                       Malt, whether or not roasted        2
187                           Other citrus fruit, n.e.        2
188                             Vegetables, dehydrated        2
189                   Coffee, decaffeinated or roasted        2
190                         Cheese from whole cow milk        2
191                                      Natural honey        2
192                 Broad beans and horse beans, green        2
193                                       Plums, dried        2
194                                        Food wastes        2
195            Vegetable products, fresh or dry n.e.c.        2
196                  Meat of turkeys, fresh or chilled        2
197               Bovine meat, salted, dried or smoked        2
198        Other tropical and subtropical fruits, n.e.        1
199        Meat of goat, fresh or chilled (indigenous)        1
200                          Other legumes, for forage        1
201                                               Wine        1
202                                           Chickens        1
203        Meat of pig with the bone, fresh or chilled        1
204                              Peppermint, spearmint        1
205                                         Sisal, raw        1
206                                  Other pome fruits        1
207                                 Swedes, for forage        1
208                                 Bambara beans, dry        1
209  Pig meat, cuts, salted, dried or smoked (bacon...        1
210                                            Raisins        1
211                                     Juice of lemon        1
212                       Juice of citrus fruit n.e.c.        1

#### **General categories mixed with specific products**

In [221]:
# Potential broad or residual commodity categories
general_category_pattern = (
    r"\bother\b|"
    r"\bothers\b|"
    r"\bvarious\b|"
    r"\bmixed\b|"
    r"\bn\.e\.c\.?\b|"
    r"\bnot elsewhere classified\b"
)

commodity_text = df_region["commodity"].astype("string").str.strip()

general_commodity_candidates = df_region.loc[
    commodity_text.str.contains(
        general_category_pattern,
        case=False,
        regex=True,
        na=False
    ),
    ["country", "region", "commodity", "cpc_code"]
].copy()

print("Potential general-category records:", len(general_commodity_candidates))
display(general_commodity_candidates)

Potential general-category records: 669

,country,region,commodity,cpc_code
16,World,NaN,Cereals n.e.c.,01199.90
17,World,NaN,Cereals n.e.c.,01199.90
18,World,NaN,Cereals n.e.c.,01199.90
25,World,NaN,Mixed grain,01199.02
26,World,NaN,Mixed grain,01199.02
...,...,...,...,...
30515,Venezuela (Bolivarian Republic of),NaN,Plantains and others,01313
30553,Venezuela (Bolivarian Republic of),NaN,Plantains and others,01313
30591,Venezuela (Bolivarian Republic of),NaN,Plantains and others,01313
30630,Venezuela (Bolivarian Republic of),NaN,Plantains and others,01313
30668,Venezuela (Bolivarian Republic of),NaN,Plantains and others,01313

### **Check on year**

#### **Show missing values**

In [222]:
# Check missing or empty year values
year_clean = df_region["year"].astype("string").str.strip()

missing_year = df_region.loc[
    year_clean.isna() | year_clean.eq(""),
    ["country", "region", "commodity", "cpc_code", "year"]
].copy()

print("Missing year records:", len(missing_year))
display(missing_year)

Missing year records: 0

Empty DataFrame
Columns: [country, region, commodity, cpc_code, year]
Index: []

#### **Non-numeric years**

In [223]:
# Identify years that cannot be interpreted as numeric values
year_numeric = pd.to_numeric(
    df_region["year"].astype("string").str.strip(),
    errors="coerce"
)

invalid_year_format = df_region.loc[
    df_region["year"].notna()
    & df_region["year"].astype("string").str.strip().ne("")
    & year_numeric.isna(),
    ["country", "region", "commodity", "cpc_code", "year"]
].copy()

print("Non-numeric year records:", len(invalid_year_format))
display(invalid_year_format)

Non-numeric year records: 0

Empty DataFrame
Columns: [country, region, commodity, cpc_code, year]
Index: []

#### **Years outside the expected range**

In [224]:
from datetime import datetime

# FAO FLW database user guide documents records from 1965 onward.
# This is a dataset-level review boundary, not proof that older source studies are invalid.
MIN_EXPECTED_YEAR = 1965
MAX_EXPECTED_YEAR = datetime.now().year

year_numeric = pd.to_numeric(
    df_region["year"].astype("string").str.strip(),
    errors="coerce"
)

valid_numeric_year = year_numeric.notna() & np.isclose(
    year_numeric.fillna(-1),
    np.floor(year_numeric.fillna(-1))
)

outside_documented_range = df_region.loc[
    valid_numeric_year
    & (
        year_numeric.lt(MIN_EXPECTED_YEAR)
        | year_numeric.gt(MAX_EXPECTED_YEAR)
    ),
    ["country", "region", "commodity", "year", "reference", "url"]
].copy()

print(
    f"Review years outside {MIN_EXPECTED_YEAR}–{MAX_EXPECTED_YEAR}: "
    f"{len(outside_documented_range)}"
)
display(outside_documented_range.head(100))

Review years outside 1965–2026: 0

Empty DataFrame
Columns: [country, region, commodity, year, reference, url]
Index: []

#### **Future or unusually old years**

In [225]:
# Future years
future_years = df_region.loc[
    valid_numeric_year & year_numeric.gt(MAX_EXPECTED_YEAR),
    ["country", "region", "commodity", "cpc_code", "year"]
].copy()

# Unusually old years: example threshold
VERY_OLD_YEAR_THRESHOLD = 1900

very_old_years = df_region.loc[
    valid_numeric_year & year_numeric.lt(VERY_OLD_YEAR_THRESHOLD),
    ["country", "region", "commodity", "cpc_code", "year"]
].copy()

print("Future year records:", len(future_years))
display(future_years)

print("Very old year records:", len(very_old_years))
display(very_old_years)

Future year records: 0

Empty DataFrame
Columns: [country, region, commodity, cpc_code, year]
Index: []

Very old year records: 0

Empty DataFrame
Columns: [country, region, commodity, cpc_code, year]
Index: []

### **Check on loss_percentage**

#### **Show missing values**

In [226]:
# Check missing and empty loss_percentage values
loss_text = df_region["loss_percentage"].astype("string").str.strip()

missing_loss_percentage = df_region.loc[
    loss_text.isna() | loss_text.eq(""),
    ["country", "region", "commodity", "year",
     "loss_percentage", "loss_percentage_original"]
].copy()

print("Missing loss_percentage records:", len(missing_loss_percentage))
display(missing_loss_percentage.head(20))

Missing loss_percentage records: 0

Empty DataFrame
Columns: [country, region, commodity, year, loss_percentage, loss_percentage_original]
Index: []

#### **Non-numeric values**

In [227]:
# Convert values for validation only
loss_numeric = pd.to_numeric(loss_text, errors="coerce")

invalid_loss_format = df_region.loc[
    loss_text.notna()
    & loss_text.ne("")
    & loss_numeric.isna(),
    ["country", "region", "commodity", "year",
     "loss_percentage", "loss_percentage_original"]
].copy()

print("Non-numeric loss_percentage records:", len(invalid_loss_format))
display(invalid_loss_format.head(20))

Non-numeric loss_percentage records: 0

Empty DataFrame
Columns: [country, region, commodity, year, loss_percentage, loss_percentage_original]
Index: []

#### **Values outside 0–100**

In [228]:
# Identify values outside the expected percentage range
out_of_range_loss = df_region.loc[
    loss_numeric.notna()
    & (
        loss_numeric.lt(0)
        | loss_numeric.gt(100)
    ),
    ["country", "region", "commodity", "year",
     "loss_percentage", "loss_percentage_original"]
].copy()

print("Out-of-range loss_percentage records:", len(out_of_range_loss))
display(out_of_range_loss.head(20))

Out-of-range loss_percentage records: 0

Empty DataFrame
Columns: [country, region, commodity, year, loss_percentage, loss_percentage_original]
Index: []

#### **Outliers**

In [229]:
# Detect statistical outliers using the IQR method
loss_valid = loss_numeric.dropna()

if not loss_valid.empty:
    q1 = loss_valid.quantile(0.25)
    q3 = loss_valid.quantile(0.75)
    iqr = q3 - q1

    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr

    loss_outlier_mask = (
        loss_numeric.notna()
        & (
            loss_numeric.lt(lower_bound)
            | loss_numeric.gt(upper_bound)
        )
    )

    loss_percentage_outliers = df_region.loc[
        loss_outlier_mask,
        ["country", "region", "commodity", "year",
         "loss_percentage", "loss_percentage_original"]
    ].copy()

    print("Q1:", q1)
    print("Q3:", q3)
    print("IQR:", iqr)
    print("Lower bound:", lower_bound)
    print("Upper bound:", upper_bound)
    print("Potential outliers:", len(loss_percentage_outliers))

    display(loss_percentage_outliers.head(20))
else:
    print("No numeric values available for outlier detection.")

Q1: 1.49833
Q3: 4.55
IQR: 3.0516699999999997
Lower bound: -3.0791749999999993
Upper bound: 9.127505
Potential outliers: 3555

,country,region,commodity,year,loss_percentage,loss_percentage_original
8,World,NaN,Barley,2022,12.00,12%
26,World,NaN,Mixed grain,2018,20.03,20.03%
27,World,NaN,Mixed grain,2018,9.99,9.99%
28,World,NaN,Mixed grain,2018,13.61,13.61%
30,Myanmar,NaN,"Rice, milled",2015,11.77,11.77%
31,Myanmar,NaN,"Rice, milled",2015,17.65,17.65%
111,Burundi,NaN,Wheat,2019,14.50,14.5%
112,Burundi,NaN,Maize (corn),2019,18.00,18%
113,Burundi,NaN,Rice,2019,12.00,12%
564,Cambodia,NaN,Maize (corn),2020,30.00,30%
565,Cambodia,NaN,Rice,2020,20.00,20%
566,Cambodia,NaN,Tomatoes,2015,24.60,24.6%
567,Cambodia,NaN,"Beans, dry",2015,21.80,21.8%
569,Cambodia,"Kandal Province, and wholesalers and retailers...",Tomatoes,2013,12.50,12.5
572,Cambodia,NaN,Cauliflowers and broccoli,2008,16.40,16.4
573,Cambodia,NaN,Cucumbers and gherkins,2008,19.70,19.7
574,Cambodia,NaN,Tomatoes,2008,24.60,24.6
575,Cambodia,NaN,"Other beans, green",2008,21.80,21.8
603,Cambodia,NaN,Tomatoes,2006,13.00,13%
612,Cambodia,NaN,Cauliflowers and broccoli,2005,16.00,16

#### **Unit inconsistency**

In [230]:
# Flag small positive values for unit review
small_positive_loss = df_region.loc[
    loss_numeric.gt(0)
    & loss_numeric.lt(1),
    ["country", "region", "commodity", "year",
     "loss_percentage", "loss_percentage_original"]
].copy()

print("Positive values between 0 and 1:", len(small_positive_loss))
display(small_positive_loss.head(30))

Positive values between 0 and 1: 3191

,country,region,commodity,year,loss_percentage,loss_percentage_original
1,World,NaN,Maize (corn),2022,0.500000,0.5%
4,World,NaN,Maize (corn),2022,0.100000,0.1%
7,World,NaN,Sorghum,2022,0.500000,0.5%
555,Belarus,NaN,Raw milk of cattle,2007,0.010000,0.01%
556,Belarus,NaN,Raw milk of cattle,2006,0.020000,0.02%
557,Belarus,NaN,Raw milk of cattle,2005,0.020000,0.02%
558,Belarus,NaN,Raw milk of cattle,2004,0.020000,0.02%
559,Belarus,NaN,Raw milk of cattle,2003,0.020000,0.02%
560,Belarus,NaN,Raw milk of cattle,2002,0.020000,0.02%
561,Belarus,NaN,Raw milk of cattle,2001,0.040000,0.04%
562,Belarus,NaN,Raw milk of cattle,2000,0.020000,0.02%
623,Cameroon,NaN,Rice,2021,0.403053,0.403053
628,Cameroon,NaN,Millet,2021,0.724270,0.72427
631,Cameroon,NaN,Millet,2021,0.853027,0.853027
638,Cameroon,NaN,Rice,2020,0.403053,0.403053
643,Cameroon,NaN,Millet,2020,0.724270,0.72427
646,Cameroon,NaN,Millet,2020,0.853027,0.853027
658,Cameroon,NaN,Rice,2019,0.403053,0.403053
663,Cameroon,NaN,Millet,2019,0.724270,0.72427
666,Cameroon,NaN,Millet,2019,0.853027,0.853027
673,Cameroon,NaN,Rice,2018,0.422546,0.422546
678,Cameroon,NaN,Millet,2018,0.742476,0.742476
681,Cameroon,NaN,Millet,2018,0.918792,0.918792
688,Cameroon,NaN,Rice,2017,0.397945,0.397945
693,Cameroon,NaN,Millet,2017,0.709428,0.709428
696,Cameroon,NaN,Millet,2017,0.796135,0.796135
715,Cameroon,NaN,Rice,2016,0.397996,0.397996
720,Cameroon,NaN,Millet,2016,0.709428,0.709428
723,Cameroon,NaN,Millet,2016,0.796384,0.796384
730,Cameroon,NaN,Rice,2015,0.397314,0.397314

#### **Compare with loss_percentage_original**

In [231]:
# Convert original values for comparison
original_text = (
    df_region["loss_percentage_original"]
    .astype("string")
    .str.strip()
)

original_numeric = pd.to_numeric(
    original_text,
    errors="coerce"
)

# Compare only rows where both values are numeric
comparable_mask = loss_numeric.notna() & original_numeric.notna()

# Exact numeric comparison
mismatch_mask = (
    comparable_mask
    & ~loss_numeric.eq(original_numeric)
)

loss_percentage_mismatch = df_region.loc[
    mismatch_mask,
    ["country", "region", "commodity", "year",
     "loss_percentage", "loss_percentage_original"]
].copy()

print("Comparable records:", int(comparable_mask.sum()))
print("Mismatched records:", len(loss_percentage_mismatch))
display(loss_percentage_mismatch.head(30))

Comparable records: 22025
Mismatched records: 0

Empty DataFrame
Columns: [country, region, commodity, year, loss_percentage, loss_percentage_original]
Index: []

In [232]:
# Check whether values may differ by a factor of 100
factor_100_mask = (
    comparable_mask
    & (
        np.isclose(
            loss_numeric,
            original_numeric * 100,
            rtol=1e-6,
            atol=1e-8
        )
        | np.isclose(
            loss_numeric * 100,
            original_numeric,
            rtol=1e-6,
            atol=1e-8
        )
    )
    & ~np.isclose(
        loss_numeric,
        original_numeric,
        rtol=1e-6,
        atol=1e-8
    )
)

possible_unit_mismatch = df_region.loc[
    factor_100_mask,
    ["country", "region", "commodity", "year",
     "loss_percentage", "loss_percentage_original"]
].copy()

print("Possible factor-of-100 differences:", len(possible_unit_mismatch))
display(possible_unit_mismatch.head(30))

Possible factor-of-100 differences: 0

Empty DataFrame
Columns: [country, region, commodity, year, loss_percentage, loss_percentage_original]
Index: []

### **Check on loss_percentage**

#### **Show missing values**

In [233]:
# Check missing and empty original loss percentage values
original_text = (
    df_region["loss_percentage_original"]
    .astype("string")
    .str.strip()
)

missing_original_loss = df_region.loc[
    original_text.isna() | original_text.eq(""),
    [
        "country", "region", "commodity", "year",
        "loss_percentage", "loss_percentage_original"
    ]
].copy()

print("Missing original values:", len(missing_original_loss))
display(missing_original_loss.head(20))####

Missing original values: 0

Empty DataFrame
Columns: [country, region, commodity, year, loss_percentage, loss_percentage_original]
Index: []

#### **Non-numeric values**

In [234]:
# Attempt numeric conversion without changing the original column
original_numeric = pd.to_numeric(
    original_text,
    errors="coerce"
)

invalid_original_format = df_region.loc[
    original_text.notna()
    & original_text.ne("")
    & original_numeric.isna(),
    [
        "country", "region", "commodity", "year",
        "loss_percentage", "loss_percentage_original"
    ]
].copy()

print("Non-numeric original values:", len(invalid_original_format))
display(invalid_original_format.head(30))

Non-numeric original values: 9440

,country,region,commodity,year,loss_percentage,loss_percentage_original
0,World,NaN,Wheat,2022,1.00,1%
1,World,NaN,Maize (corn),2022,0.50,0.5%
2,World,NaN,Maize (corn),2022,2.00,2%
3,World,NaN,Maize (corn),2022,2.00,2%
4,World,NaN,Maize (corn),2022,0.10,0.1%
5,World,NaN,Maize (corn),2022,2.00,2%
6,World,NaN,Rice,2022,2.50,2.5%
7,World,NaN,Sorghum,2022,0.50,0.5%
8,World,NaN,Barley,2022,12.00,12%
9,World,NaN,Barley,2022,2.00,2%
10,World,NaN,Barley,2022,2.00,2%
11,World,NaN,Rye,2022,1.00,1%
12,World,NaN,Oats,2022,2.00,2%
13,World,NaN,Oats,2022,2.00,2%
14,World,NaN,Millet,2022,2.00,2%
15,World,NaN,Buckwheat,2022,2.00,2%
16,World,NaN,Cereals n.e.c.,2022,2.00,2%
17,World,NaN,Cereals n.e.c.,2022,2.00,2%
18,World,NaN,Cereals n.e.c.,2022,1.00,1%
19,World,NaN,Pot barley,2022,2.00,2%
20,World,NaN,Cereal preparations,2022,2.00,2%
21,World,NaN,Cereal preparations,2022,2.00,2%
22,World,NaN,Cereal preparations,2022,2.00,2 %
23,World,NaN,Cereal preparations,2022,2.00,2%
24,World,NaN,"Malt, whether or not roasted",2022,2.00,2%
25,World,NaN,Mixed grain,2018,2.85,2.85%
26,World,NaN,Mixed grain,2018,20.03,20.03%
27,World,NaN,Mixed grain,2018,9.99,9.99%
28,World,NaN,Mixed grain,2018,13.61,13.61%
29,Myanmar,NaN,"Rice, milled",2015,5.88,5.88%

#### **Percentage signs**

In [235]:
# Identify values containing a percentage sign
contains_percent_sign = original_text.str.contains(
    "%",
    regex=False,
    na=False
)

percentage_sign_records = df_region.loc[
    contains_percent_sign,
    [
        "country", "region", "commodity", "year",
        "loss_percentage", "loss_percentage_original"
    ]
].copy()

print("Values containing %:", len(percentage_sign_records))
display(percentage_sign_records.head(30))

Values containing %: 9025

,country,region,commodity,year,loss_percentage,loss_percentage_original
0,World,NaN,Wheat,2022,1.00,1%
1,World,NaN,Maize (corn),2022,0.50,0.5%
2,World,NaN,Maize (corn),2022,2.00,2%
3,World,NaN,Maize (corn),2022,2.00,2%
4,World,NaN,Maize (corn),2022,0.10,0.1%
5,World,NaN,Maize (corn),2022,2.00,2%
6,World,NaN,Rice,2022,2.50,2.5%
7,World,NaN,Sorghum,2022,0.50,0.5%
8,World,NaN,Barley,2022,12.00,12%
9,World,NaN,Barley,2022,2.00,2%
10,World,NaN,Barley,2022,2.00,2%
11,World,NaN,Rye,2022,1.00,1%
12,World,NaN,Oats,2022,2.00,2%
13,World,NaN,Oats,2022,2.00,2%
14,World,NaN,Millet,2022,2.00,2%
15,World,NaN,Buckwheat,2022,2.00,2%
16,World,NaN,Cereals n.e.c.,2022,2.00,2%
17,World,NaN,Cereals n.e.c.,2022,2.00,2%
18,World,NaN,Cereals n.e.c.,2022,1.00,1%
19,World,NaN,Pot barley,2022,2.00,2%
20,World,NaN,Cereal preparations,2022,2.00,2%
21,World,NaN,Cereal preparations,2022,2.00,2%
22,World,NaN,Cereal preparations,2022,2.00,2 %
23,World,NaN,Cereal preparations,2022,2.00,2%
24,World,NaN,"Malt, whether or not roasted",2022,2.00,2%
25,World,NaN,Mixed grain,2018,2.85,2.85%
26,World,NaN,Mixed grain,2018,20.03,20.03%
27,World,NaN,Mixed grain,2018,9.99,9.99%
28,World,NaN,Mixed grain,2018,13.61,13.61%
29,Myanmar,NaN,"Rice, milled",2015,5.88,5.88%

#### **Decimal formatting**

In [236]:
# Find original values containing commas
contains_comma = original_text.str.contains(
    ",",
    regex=False,
    na=False
)

comma_format_records = df_region.loc[
    contains_comma,
    [
        "country", "region", "commodity", "year",
        "loss_percentage", "loss_percentage_original"
    ]
].copy()

print("Values containing commas:", len(comma_format_records))
display(comma_format_records.head(30))

Values containing commas: 0

Empty DataFrame
Columns: [country, region, commodity, year, loss_percentage, loss_percentage_original]
Index: []

#### **Compare original and cleaned values**

In [237]:
# Convert both columns for comparison only
loss_numeric = pd.to_numeric(
    df_region["loss_percentage"].astype("string").str.strip(),
    errors="coerce"
)

original_numeric = pd.to_numeric(
    original_text,
    errors="coerce"
)

comparable_mask = (
    loss_numeric.notna()
    & original_numeric.notna()
)

mismatch_mask = (
    comparable_mask
    & ~np.isclose(
        loss_numeric,
        original_numeric,
        rtol=1e-6,
        atol=1e-8
    )
)

original_vs_cleaned_mismatch = df_region.loc[
    mismatch_mask,
    [
        "country", "region", "commodity", "year",
        "loss_percentage", "loss_percentage_original"
    ]
].copy()

print("Comparable numeric records:", int(comparable_mask.sum()))
print("Numeric mismatches:", len(original_vs_cleaned_mismatch))
display(original_vs_cleaned_mismatch.head(30))

Comparable numeric records: 22025
Numeric mismatches: 0

Empty DataFrame
Columns: [country, region, commodity, year, loss_percentage, loss_percentage_original]
Index: []

#### **Are the original values different by a factor of 100?**

In [238]:
# Detect possible factor-of-100 differences
factor_100_mask = (
    comparable_mask
    & (
        np.isclose(
            loss_numeric,
            original_numeric * 100,
            rtol=1e-6,
            atol=1e-8
        )
        | np.isclose(
            loss_numeric * 100,
            original_numeric,
            rtol=1e-6,
            atol=1e-8
        )
    )
    & ~np.isclose(
        loss_numeric,
        original_numeric,
        rtol=1e-6,
        atol=1e-8
    )
)

possible_factor_100_difference = df_region.loc[
    factor_100_mask,
    [
        "country", "region", "commodity", "year",
        "loss_percentage", "loss_percentage_original"
    ]
].copy()

print("Possible factor-of-100 differences:", len(possible_factor_100_difference))
display(possible_factor_100_difference.head(30))

Possible factor-of-100 differences: 0

Empty DataFrame
Columns: [country, region, commodity, year, loss_percentage, loss_percentage_original]
Index: []

#### **Investigating the role of loss_percentage_original**

In [239]:
# Inspect both columns and their data types
print(df_region[
    ["loss_percentage", "loss_percentage_original"]
].dtypes)

display(
    df_region[
        ["loss_percentage", "loss_percentage_original"]
    ].sample(
        min(20, len(df_region)),
        random_state=42
    )
)

loss_percentage             float64
loss_percentage_original        str
dtype: object

       loss_percentage loss_percentage_original
27126          1.50000                     0–3%
17402          4.17000                    4.17%
2320           2.50000                      2.5
25378          3.60000                      3.6
10883          4.00000                        4
18329          2.00000                        2
30801          2.61612                  2.61612
6538           1.25000                     1.25
21787          3.50000                      3.5
16303          2.35000                    2.35%
21775          3.60000                      3.6
31364          1.30000                      1.3
1456           1.40734                  1.40734
10509         10.00000                      10%
26593          0.58750                   0.5875
1298          20.43000                   20.43%
18937          2.57961                  2.57961
3745           3.50000                      3.5
17311          8.20000                     8.2%
10351          1.36000                     1.36

In [240]:
print("Original column dtype:", df_region["loss_percentage_original"].dtype)
print("Total records:", len(df_region))
print("Missing values:", df_region["loss_percentage_original"].isna().sum())
print("Unique non-null values:", df_region["loss_percentage_original"].nunique())

display(
    df_region["loss_percentage_original"]
    .value_counts(dropna=False)
    .head(20)
)

Original column dtype: str
Total records: 31465
Missing values: 0
Unique non-null values: 5995

loss_percentage_original
2.5        2309
3.5        1349
1          1280
2.65       1244
2           760
4           717
3.6         664
1.25        660
2.16667     660
1.32        619
4.40333     609
3.13714     609
6.42        562
4.55        541
1.3         330
4.43333     276
1.65        266
8           254
5           200
1%          178
Name: count, dtype: int64

### **Check on loss_quantity**

#### **Show missing values**

In [241]:
# Check missing and empty loss_quantity values
quantity_text = df_region["loss_quantity"].astype("string").str.strip()

missing_loss_quantity = df_region.loc[
    quantity_text.isna() | quantity_text.eq(""),
    ["country", "region", "commodity", "year", "loss_quantity"]
].copy()

print("Missing loss_quantity records:", len(missing_loss_quantity))
display(missing_loss_quantity.head(20))

Missing loss_quantity records: 26415

   country region       commodity  year loss_quantity
0    World    NaN           Wheat  2022           NaN
1    World    NaN    Maize (corn)  2022           NaN
2    World    NaN    Maize (corn)  2022           NaN
3    World    NaN    Maize (corn)  2022           NaN
4    World    NaN    Maize (corn)  2022           NaN
5    World    NaN    Maize (corn)  2022           NaN
6    World    NaN            Rice  2022           NaN
7    World    NaN         Sorghum  2022           NaN
8    World    NaN          Barley  2022           NaN
9    World    NaN          Barley  2022           NaN
10   World    NaN          Barley  2022           NaN
11   World    NaN             Rye  2022           NaN
12   World    NaN            Oats  2022           NaN
13   World    NaN            Oats  2022           NaN
14   World    NaN          Millet  2022           NaN
15   World    NaN       Buckwheat  2022           NaN
16   World    NaN  Cereals n.e.c.  2022           NaN
17   World    NaN  Cereals n.e.c.  2022           NaN
18   World    NaN  Cereals n.e.c.  2022           NaN
19   World    NaN      Pot barley  2022           NaN

#### **Non-numeric values**

In [242]:
# Convert values for validation only
quantity_numeric = pd.to_numeric(
    quantity_text,
    errors="coerce"
)

invalid_quantity_format = df_region.loc[
    quantity_text.notna()
    & quantity_text.ne("")
    & quantity_numeric.isna(),
    ["country", "region", "commodity", "year", "loss_quantity"]
].copy()

print("Non-numeric loss_quantity records:", len(invalid_quantity_format))
display(invalid_quantity_format.head(30))

Non-numeric loss_quantity records: 691

      country region                  commodity  year           loss_quantity
25      World    NaN                Mixed grain  2018  60 million metric tons
29    Myanmar    NaN               Rice, milled  2015                44.09kgs
30    Myanmar    NaN               Rice, milled  2015                88.18kgs
31    Myanmar    NaN               Rice, milled  2015               132.27kgs
32    Myanmar    NaN               Rice, milled  2015                52.24kgs
33    Myanmar    NaN               Rice, milled  2015                78.36kgs
34    Myanmar    NaN               Rice, milled  2015                26.12kgs
576  Cambodia    NaN  Cauliflowers and broccoli  2006                 52kg/MT
577  Cambodia    NaN  Cauliflowers and broccoli  2006                 37kg/MT
578  Cambodia    NaN  Cauliflowers and broccoli  2006                 31kg/MT
579  Cambodia    NaN  Cauliflowers and broccoli  2006                 52kg/MT
580  Cambodia    NaN  Cauliflowers and broccoli  2006                 31kg/MT
581  Cambodia    NaN  Cauliflowers and broccoli  2006                 31kg/MT
582  Cambodia    NaN  Cauliflowers and broccoli  2006                 52kg/MT
583  Cambodia    NaN  Cauliflowers and broccoli  2006                 44kg/MT
584  Cambodia    NaN  Cauliflowers and broccoli  2006                 44kg/MT
585  Cambodia    NaN  Cauliflowers and broccoli  2006                 37kg/MT
586  Cambodia    NaN  Cauliflowers and broccoli  2006                 44kg/MT
587  Cambodia    NaN  Cauliflowers and broccoli  2006                 37kg/MT
588  Cambodia    NaN     Cucumbers and gherkins  2006                 42kg/MT
589  Cambodia    NaN     Cucumbers and gherkins  2006                 44kg/MT
590  Cambodia    NaN     Cucumbers and gherkins  2006                 48kg/MT
591  Cambodia    NaN     Cucumbers and gherkins  2006                 42kg/MT
592  Cambodia    NaN     Cucumbers and gherkins  2006                 44kg/MT
593  Cambodia    NaN     Cucumbers and gherkins  2006                 48kg/MT
594  Cambodia    NaN     Cucumbers and gherkins  2006                 48kg/MT
595  Cambodia    NaN     Cucumbers and gherkins  2006                 63kg/MT
596  Cambodia    NaN     Cucumbers and gherkins  2006                 42kg/MT
597  Cambodia    NaN     Cucumbers and gherkins  2006                 63kg/MT
598  Cambodia    NaN     Cucumbers and gherkins  2006                 44kg/MT

#### **Negative quantities**

In [243]:
# Identify negative quantities
negative_loss_quantity = df_region.loc[
    quantity_numeric.lt(0),
    ["country", "region", "commodity", "year", "loss_quantity"]
].copy()

print("Negative loss_quantity records:", len(negative_loss_quantity))
display(negative_loss_quantity.head(30))

Negative loss_quantity records: 0

Empty DataFrame
Columns: [country, region, commodity, year, loss_quantity]
Index: []

#### **Zero values**

In [244]:
# Identify zero quantities without treating them as errors
zero_loss_quantity = df_region.loc[
    quantity_numeric.eq(0),
    ["country", "region", "commodity", "year", "loss_quantity"]
].copy()

print("Zero loss_quantity records:", len(zero_loss_quantity))
display(zero_loss_quantity.head(30))

Zero loss_quantity records: 56

       country region                commodity  year loss_quantity
998     Canada    NaN                      Rye  2008             0
999     Canada    NaN                     Oats  2008             0
1006    Canada    NaN                      Rye  2007             0
1007    Canada    NaN                     Oats  2007             0
1041    Canada    NaN                      Rye  2006             0
1042    Canada    NaN                     Oats  2006             0
1076    Canada    NaN                      Rye  2005             0
1077    Canada    NaN                     Oats  2005             0
1112    Canada    NaN                      Rye  2004             0
2712      Cuba    NaN  Pomelos and grapefruits  2005             0
3621   Ecuador    NaN              Sesame seed  2003             0
3647   Ecuador    NaN              Sesame seed  2002             0
7089   Germany    NaN             Rice, Broken  2003             0
8937   Hungary    NaN               Poppy seed  2004             0
8962   Hungary    NaN               Poppy seed  2003             0
9026   Hungary    NaN               Poppy seed  2001             0
9058   Hungary    NaN               Poppy seed  2000             0
10865    Italy    NaN                      Rye  2004             0
10866    Italy    NaN       Other cereals n.e.  2004             0
10867    Italy    NaN                      Rye  2003             0
10868    Italy    NaN       Other cereals n.e.  2003             0
10869    Italy    NaN            Refined sugar  2003             0
10870    Italy    NaN                      Rye  2002             0
10871    Italy    NaN       Other cereals n.e.  2002             0
10872    Italy    NaN            Refined sugar  2002             0
10873    Italy    NaN                      Rye  2001             0
10874    Italy    NaN       Other cereals n.e.  2001             0
10875    Italy    NaN            Refined sugar  2001             0
10876    Italy    NaN                      Rye  2000             0
10877    Italy    NaN       Other cereals n.e.  2000             0

#### **Extreme quantities**

In [245]:
# Detect unusually large quantities using IQR
quantity_valid = quantity_numeric[
    quantity_numeric.notna() & quantity_numeric.ge(0)
]

if not quantity_valid.empty:
    q1 = quantity_valid.quantile(0.25)
    q3 = quantity_valid.quantile(0.75)
    iqr = q3 - q1
    upper_bound = q3 + 1.5 * iqr

    extreme_quantity_mask = (
        quantity_numeric.notna()
        & quantity_numeric.ge(0)
        & quantity_numeric.gt(upper_bound)
    )

    extreme_loss_quantity = df_region.loc[
        extreme_quantity_mask,
        ["country", "region", "commodity", "year", "loss_quantity"]
    ].copy()

    print("Q1:", q1)
    print("Q3:", q3)
    print("IQR:", iqr)
    print("Upper bound:", upper_bound)
    print("Potential extreme records:", len(extreme_loss_quantity))

    display(
        extreme_loss_quantity.sort_values(
            "loss_quantity",
            ascending=False
        ).head(30)
    )
else:
    print("No non-negative numeric quantities available.")

Q1: 1022.0
Q3: 36000.0
IQR: 34978.0
Upper bound: 88467.0
Potential extreme records: 601

,country,region,commodity,year,loss_quantity
19787,Peru,NaN,"Onions and shallots, dry (excluding dehydrated)",2004,99313
6233,France,NaN,Barley,2008,99000
7117,Germany,NaN,Maize (corn),2000,99000
18048,Nicaragua,NaN,Maize (corn),2004,98974
1592,Chad,NaN,Millet,2014,98697
3528,Denmark,NaN,Barley,2006,98300
2684,Cuba,NaN,Maize (corn),2007,98300
7095,Germany,NaN,Rye,2002,98000
7030,Germany,NaN,Rye,2008,98000
13703,Lithuania,NaN,Potatoes,2002,98000
20106,Poland,NaN,Barley,2014,98000
30662,Venezuela (Bolivarian Republic of),NaN,Rice,2000,98000
19862,Peru,NaN,Oranges,2002,97917
6992,Germany,NaN,Rapeseed or colza seed,2013,97000
30663,Venezuela (Bolivarian Republic of),NaN,Sorghum,2000,96910
30483,Venezuela (Bolivarian Republic of),NaN,Sorghum,2006,96555
8221,Argentina,NaN,Raw milk of cattle,2015,96487
18057,Nicaragua,NaN,Maize (corn),2001,96241
6972,Germany,NaN,Rye,2015,96200
17378,Armenia,NaN,Potatoes,2013,96200
26947,Egypt,NaN,Potatoes,2017,953000
6268,France,NaN,Tomatoes,2003,95000
15942,Mexico,NaN,"Beans, dry",2016,94085
2649,Cuba,NaN,Maize (corn),2011,94000
19754,Peru,NaN,"Onions and shallots, dry (excluding dehydrated)",2005,93929
27038,Egypt,NaN,Potatoes,2014,939000
1511,Chad,NaN,Millet,2017,93456
19897,Peru,NaN,Oranges,2001,93226
3523,Denmark,NaN,Barley,2007,93200
6997,Germany,NaN,Rye,2012,93000

#### **Unit inconsistency**

In [246]:
# Inspect numeric quantity distribution
print(
    quantity_numeric.describe(
        percentiles=[0.01, 0.05, 0.25, 0.50, 0.75, 0.95, 0.99]
    )
)

display(
    quantity_numeric.value_counts(dropna=False)
    .sort_index()
    .head(30)
)

count           4359.0
mean      64356.682888
std      218466.371092
min                0.0
1%                 0.0
5%                71.0
25%             1022.0
50%             7000.0
75%            36000.0
95%           250516.8
99%         1270395.62
max          3824000.0
Name: loss_quantity, dtype: Float64

loss_quantity
0.0          56
0.1           2
1.0           2
1.673         1
2.0           1
2.307245      1
3.0           5
4.0           2
6.0           2
8.0           1
10.0          3
11.0          4
12.0          1
12.303829     1
13.0          2
14.0          1
15.0          3
15.69393      1
17.0          2
18.0          7
19.0          2
20.0          4
21.0          1
22.0          3
23.0          3
24.0          7
25.0          1
28.0          1
29.0          4
30.0          2
Name: count, dtype: Int64

In [247]:
# Review the largest numeric quantities
largest_quantities = df_region.loc[
    quantity_numeric.notna(),
    ["country", "region", "commodity", "year", "loss_quantity"]
].copy()

largest_quantities["_quantity_numeric"] = quantity_numeric.loc[
    largest_quantities.index
]

largest_quantities = largest_quantities.sort_values(
    "_quantity_numeric",
    ascending=False
)

display(largest_quantities.head(30))

,country,region,commodity,year,loss_quantity,_quantity_numeric
26815,Ukraine,NaN,Potatoes,2014,3824000,3824000.0
26804,Ukraine,NaN,Potatoes,2015,3799000,3799000.0
20145,Poland,NaN,Potatoes,2000,3390000,3390000.0
26793,Ukraine,NaN,Potatoes,2016,3174000,3174000.0
20143,Poland,NaN,Potatoes,2001,2930000,2930000.0
20757,Russian Federation,NaN,Potatoes,2013,1983900,1983900.0
29511,United States of America,NaN,Potatoes,2000,1981700,1981700.0
20775,Russian Federation,NaN,Potatoes,2007,1825700,1825700.0
20141,Poland,NaN,Potatoes,2002,1817000,1817000.0
20760,Russian Federation,NaN,Potatoes,2012,1751700,1751700.0
29251,United States of America,NaN,Potatoes,2004,1700000,1700000.0
20778,Russian Federation,NaN,Potatoes,2006,1659000,1659000.0
26938,Egypt,NaN,Maize (corn),2017,1621000,1621000.0
20135,Poland,NaN,Potatoes,2003,1605000,1605000.0
15970,Mexico,NaN,Raw milk of cattle,2013,1604496,1604496.0
29316,United States of America,NaN,Potatoes,2003,1601000,1601000.0
6228,France,NaN,Potatoes,2009,1584000,1584000.0
20132,Poland,NaN,Potatoes,2004,1550000,1550000.0
6242,France,NaN,Potatoes,2007,1538000,1538000.0
19296,Pakistan,Northern Areas,Grapes,2001,1510000,1510000.0
20769,Russian Federation,NaN,Potatoes,2009,1494000,1494000.0
20763,Russian Federation,NaN,Potatoes,2011,1469000,1469000.0
20753,Russian Federation,NaN,Potatoes,2017,1461000,1461000.0
20781,Russian Federation,NaN,Potatoes,2005,1436000,1436000.0
20755,Russian Federation,NaN,Potatoes,2015,1431200,1431200.0
29446,United States of America,NaN,Potatoes,2001,1415600,1415600.0
20754,Russian Federation,NaN,Potatoes,2016,1404300,1404300.0
29381,United States of America,NaN,Potatoes,2002,1404100,1404100.0
27005,Egypt,NaN,Maize (corn),2015,1398000,1398000.0
20772,Russian Federation,NaN,Potatoes,2008,1396000,1396000.0

### **Check on Activity**

#### **Check on missing values**

In [248]:
# Check missing or empty activity values
activity_text = df_region["activity"].astype("string").str.strip()

missing_activity = df_region.loc[
    activity_text.isna() | activity_text.eq(""),
    ["country", "region", "commodity", "cpc_code", "activity"]
].copy()

print("Missing activity records:", len(missing_activity))
display(missing_activity.head(20))

Missing activity records:

 7370

      country region                      commodity  cpc_code activity
27      World    NaN                    Mixed grain  01199.02      NaN
35    Myanmar    NaN  Groundnuts, excluding shelled      0142      NaN
36    Myanmar    NaN  Groundnuts, excluding shelled      0142      NaN
37    Myanmar    NaN  Groundnuts, excluding shelled      0142      NaN
38    Myanmar    NaN  Groundnuts, excluding shelled      0142      NaN
39    Myanmar    NaN  Groundnuts, excluding shelled      0142      NaN
40    Myanmar    NaN  Groundnuts, excluding shelled      0142      NaN
41    Myanmar    NaN  Groundnuts, excluding shelled      0142      NaN
111   Burundi    NaN                          Wheat      0111      NaN
112   Burundi    NaN                   Maize (corn)      0112      NaN
113   Burundi    NaN                           Rice      0113      NaN
555   Belarus    NaN             Raw milk of cattle     02211      NaN
556   Belarus    NaN             Raw milk of cattle     02211      NaN
557   Belarus    NaN             Raw milk of cattle     02211      NaN
558   Belarus    NaN             Raw milk of cattle     02211      NaN
559   Belarus    NaN             Raw milk of cattle     02211      NaN
560   Belarus    NaN             Raw milk of cattle     02211      NaN
561   Belarus    NaN             Raw milk of cattle     02211      NaN
562   Belarus    NaN             Raw milk of cattle     02211      NaN
564  Cambodia    NaN                   Maize (corn)      0112      NaN

#### **Formatting inconsistencies**

In [249]:
# Normalize activity labels for comparison only
activity_normalized = (
    df_region["activity"]
    .astype("string")
    .str.strip()
    .str.casefold()
    .str.replace(r"\s+", " ", regex=True)
)

activity_format_review = (
    df_region.assign(_activity_normalized=activity_normalized)
    .dropna(subset=["_activity_normalized"])
    .groupby("_activity_normalized")
    .agg(
        original_labels=(
            "activity",
            lambda s: sorted(s.astype(str).unique().tolist())
        ),
        records=("activity", "size"),
        commodities=(
            "commodity",
            lambda s: sorted(s.dropna().astype(str).unique().tolist())
        )
    )
    .reset_index()
)

activity_format_review = activity_format_review.loc[
    activity_format_review["original_labels"].apply(len) > 1
].copy()

print("Potential formatting inconsistencies:", len(activity_format_review))
display(activity_format_review)

Potential formatting inconsistencies: 0

Empty DataFrame
Columns: [_activity_normalized, original_labels, records, commodities]
Index: []

#### **Potential synonyms**

In [250]:
# List unique activity labels and their frequencies
activity_frequency = (
    df_region["activity"]
    .dropna()
    .astype("string")
    .str.strip()
    .value_counts()
    .rename_axis("activity")
    .reset_index(name="records")
)

print("Unique non-empty activity labels:", len(activity_frequency))
display(activity_frequency)

Unique non-empty activity labels: 180

                                              activity  records
0                                              Storage     6072
1                                       Transportation     5290
2                                   Drying, Harvesting     3500
3                                  Shelling, Threshing     3346
4                                            Winnowing     1356
..                                                 ...      ...
175  Drying, Harvesting, Milling, Sorting, Storage,...        1
176                                   Sorting, Washing        1
177                                   Milling, Storage        1
178            Harvesting, Packaging, Sorting, Storage        1
179                                      Farm, Milling        1

[180 rows x 2 columns]

In [251]:
# Install once if needed:
# %pip install rapidfuzz

from rapidfuzz import fuzz
from itertools import combinations

activity_names = activity_frequency["activity"].dropna().tolist()

similar_activity_candidates = []

for name1, name2 in combinations(activity_names, 2):
    similarity = fuzz.ratio(name1.casefold(), name2.casefold())

    if similarity >= 85:
        similar_activity_candidates.append({
            "activity_1": name1,
            "activity_2": name2,
            "similarity_score": similarity
        })

activity_similarity_review = pd.DataFrame(
    similar_activity_candidates,
    columns=["activity_1", "activity_2", "similarity_score"]
)

if not activity_similarity_review.empty:
    activity_similarity_review = activity_similarity_review.sort_values(
        "similarity_score",
        ascending=False
    )

print("Similar-label pairs:", len(activity_similarity_review))
display(activity_similarity_review.head(50))

Similar-label pairs: 60

,activity_1,activity_2,similarity_score
52,"Collection, Drying, Harvesting, Processing, Re...","Collection, Drying, Harvesting, Packaging, Pro...",95.278970
41,"Collection, Grading, Harvesting, Packaging, Re...","Collection, Harvesting, Packaging, Retailing, ...",94.674556
32,"Assembling, Grading, Harvesting, Loading, Sort...","Assembling, Grading, Harvesting, Sorting, Stor...",94.409938
59,"Drying, Harvesting, Milling, Storage, Threshin...","Drying, Harvesting, Milling, Sorting, Storage,...",94.267516
43,"Collection, Harvesting, Packaging, Sorting, Tr...","Collection, Drying, Harvesting, Packaging, Sor...",93.548387
42,"Collection, Grading, Harvesting, Packaging, Re...","Collection, Grading, Harvesting, Retailing, St...",93.413174
35,"Assembling, Grading, Harvesting, Loading, Sort...","Grading, Harvesting, Loading, Sorting, Storage...",92.405063
18,"Marketing, Storage, Transportation","Farm, Marketing, Storage, Transportation",91.891892
44,"Collection, Harvesting, Packaging, Sorting, Tr...","Collection, Harvesting, Packaging, Transportation",91.588785
27,"Collection, Grading, Harvesting, Packaging, Tr...","Collection, Harvesting, Packaging, Transportation",91.588785
10,"Handling, Storage, Transportation","Handling, Trading, Transportation",90.909091
49,"Collection, Drying, Harvesting, Packaging, Pro...","Collection, Drying, Harvesting, Packaging, Pro...",90.090090
25,"Collection, Grading, Harvesting, Packaging, Tr...","Collection, Grading, Harvesting, Transportation",89.523810
34,"Assembling, Grading, Harvesting, Loading, Sort...","Assembling, Bagging, Grading, Harvesting, Load...",89.473684
6,"Handling, Transportation","Grading, Transportation",89.361702
12,"Handling, Storage, Transportation","Milling, Storage, Transportation",89.230769
20,"Farm, Processing, Storage, Transportation","Farm, Marketing, Storage, Transportation",88.888889
26,"Collection, Grading, Harvesting, Packaging, Tr...","Collection, Drying, Harvesting, Packaging, Sor...",88.709677
39,"Grading, Harvesting, Loading, Sorting, Storage...","Cleaning, Harvesting, Loading, Packaging, Sort...",88.607595
30,"Harvesting, Marketing, Storage, Transportation","Farm, Marketing, Storage, Transportation",88.372093
22,"Loading, Storage, Transportation, Unloading","Storage, Transportation, Unloading",88.311688
37,"Farm, Grading, Harvesting, Loading, Sorting, S...","Grading, Harvesting, Loading, Sorting, Storage...",88.275862
13,"Packaging, Storage, Transportation","Marketing, Storage, Transportation",88.235294
48,"Collection, Harvesting, Processing, Retailing,...","Collection, Harvesting, Packaging, Retailing, ...",88.157895
19,"Marketing, Storage, Transportation","Milling, Storage, Transportation",87.878788
40,"Collection, Grading, Harvesting, Packaging, Re...","Collection, Drying, Harvesting, Packaging, Pro...",87.830688
58,"Farm, Harvesting, Storage, Threshing, Transpor...","Drying, Harvesting, Milling, Storage, Threshin...",87.591241
5,Loading,Unloading,87.500000
38,"Assembling, Bagging, Grading, Harvesting, Load...","Cleaning, Harvesting, Loading, Packaging, Sort...",87.368421
53,"Collection, Harvesting, Packaging, Retailing, ...","Collection, Grading, Harvesting, Retailing, St...",87.341772
29,"Consumption, Handling, Harvesting, Processing,...","Collection, Grading, Harvesting, Packaging, Re...",87.292818
15,"Retailing, Wholesale","Farm, Retailing, Wholesale",86.956522
24,"Distribution, Retailing","Distribution, Marketing",86.956522
46,"Collection, Harvesting, Packaging, Sorting, Tr...","Collection, Grading, Packaging, Storage, Trans...",86.725664
57,"Curing, Storage","Drying, Storage",86.666667
54,"Collection, Harvesting, Packaging, Retailing, ...","Collection, Harvesting, Packaging, Processing,...",86.666667
33,"Assembling, Grading, Harvesting, Loading, Sort...","Farm, Grading, Harvesting, Loading, Sorting, S...",86.624204
9,"Handling, Storage, Transportation","Packaging, Storage, Transportation",86.567164
11,"Handling, Storage, Transportation","Marketing, Storage, Transportation",86.567164
8,"Marketing, Storage","Harvesting, Storage",86.486486
23,"Distribution, Retailing","Distribution, Trading",86.363636
21,"Loading, Storage, Transportation, Unloading","Loading, Marketing, Transportation, Unloading",86.363636
1,"Shelling, Threshing","Farm, Shelling, Threshing",86.363636
45,"Collection, Harvesting, Packaging, Sorting, Tr...","Collection, Harvesting, Packaging, Processing,...",85.937500
36,"Assembling, Grading, Harvesting, Sorting, Stor...","Grading, Harvesting, Loading, Sorting, Storage...",85.906040
28,Lifting,Sifting,85.714286
31,"Drying, Milling, Processing, Storage","Drying, Milling, Processing",85.714286
55,"Grading, Harvesting, Transportation","Grading, Harvesting, Sorting",85.714286
56,"Grading, Harvesting, Sorting","Grading, Processing, Sorting",85.714286
3,Grading,Trading,85.714286

#### **Spelling issues**

In [252]:
# Identify rarely used activity labels
rare_activity_labels = activity_frequency.loc[
    activity_frequency["records"] <= 2
].copy()

print("Rare activity labels:", len(rare_activity_labels))
display(rare_activity_labels)

Rare activity labels: 98

                                              activity  records
82                             Distribution, Retailing        2
83                                    Storage, Trading        2
84                               Collection, Wholesale        2
85                    Distribution, Marketing, Storage        2
86   Collection, Grading, Harvesting, Packaging, Tr...        2
..                                                 ...      ...
175  Drying, Harvesting, Milling, Sorting, Storage,...        1
176                                   Sorting, Washing        1
177                                   Milling, Storage        1
178            Harvesting, Packaging, Sorting, Storage        1
179                                      Farm, Milling        1

[98 rows x 2 columns]

#### **Broad vs. specific activities**

In [253]:
# Identify possible broad activity labels for manual review
broad_activity_pattern = (
    r"\bother\b|"
    r"\bothers\b|"
    r"\bgeneral\b|"
    r"\btotal\b|"
    r"\ball activities\b|"
    r"\bvarious\b|"
    r"\bunspecified\b|"
    r"\bmiscellaneous\b"
)

broad_activity_candidates = df_region.loc[
    activity_text.str.contains(
        broad_activity_pattern,
        case=False,
        regex=True,
        na=False
    ),
    ["country", "region", "commodity", "cpc_code", "activity"]
].copy()

print("Potential broad activity records:", len(broad_activity_candidates))
display(broad_activity_candidates.head(50))

Potential broad activity records: 0

Empty DataFrame
Columns: [country, region, commodity, cpc_code, activity]
Index: []

#### **Checking compatibility between the activity and the commodity**

In [254]:
# Review observed activity-commodity combinations
activity_commodity_combinations = (
    df_region.groupby(
        ["activity", "commodity"],
        dropna=False
    )
    .size()
    .reset_index(name="records")
    .sort_values("records", ascending=False)
)

print("Unique activity-commodity combinations:",
      len(activity_commodity_combinations))

display(activity_commodity_combinations.head(100))

Unique activity-commodity combinations: 1503

            activity             commodity  records
1098         Storage          Maize (corn)     1596
1205  Transportation          Maize (corn)     1299
1124         Storage                  Rice     1071
1129         Storage               Sorghum     1042
1232  Transportation                  Rice      997
...              ...                   ...      ...
998        Retailing              Potatoes       34
1448             NaN  Plantains and others       34
1484             NaN            Sugar cane       32
1444             NaN      Pigeon peas, dry       32
1501             NaN                  Yams       32

[100 rows x 3 columns]

In [255]:
# Replace "stage" with the actual column name in your dataset
activity_stage_combinations = (
    df_region.groupby(
        ["activity", "food_supply_stage"],
        dropna=False
    )
    .size()
    .reset_index(name="records")
    .sort_values("records", ascending=False)
)

display(activity_stage_combinations.head(100))

                               activity   food_supply_stage  records
283                                 NaN  Whole supply chain     5939
75                   Drying, Harvesting             Harvest     3500
255                      Transportation                Farm     3367
227                 Shelling, Threshing                 NaN     3342
237                             Storage                Farm     3295
..                                  ...                 ...      ...
14                             Cleaning                Farm        6
59                               Curing                Farm        5
236                            Stacking                Farm        5
73                               Drying          Processing        5
177  Marketing, Storage, Transportation           Transport        5

[100 rows x 3 columns]

### **Check on food_supply_stage**

#### **Show missing values**

In [256]:
# Check missing or empty food_supply_stage values
stage_text = df_region["food_supply_stage"].astype("string").str.strip()

missing_food_supply_stage = df_region.loc[
    stage_text.isna() | stage_text.eq(""),
    [
        "country", "region", "commodity",
        "activity", "food_supply_stage"
    ]
].copy()

print("Missing food_supply_stage records:", len(missing_food_supply_stage))
display(missing_food_supply_stage.head(20))

Missing food_supply_stage records: 3391

     country region     commodity             activity food_supply_stage
44   Burundi    NaN         Wheat  Shelling, Threshing               NaN
47   Burundi    NaN  Maize (corn)  Shelling, Threshing               NaN
53   Burundi    NaN          Rice  Shelling, Threshing               NaN
58   Burundi    NaN       Sorghum  Shelling, Threshing               NaN
62   Burundi    NaN        Millet  Shelling, Threshing               NaN
67   Burundi    NaN         Wheat  Shelling, Threshing               NaN
70   Burundi    NaN  Maize (corn)  Shelling, Threshing               NaN
76   Burundi    NaN          Rice  Shelling, Threshing               NaN
81   Burundi    NaN       Sorghum  Shelling, Threshing               NaN
85   Burundi    NaN        Millet  Shelling, Threshing               NaN
90   Burundi    NaN         Wheat  Shelling, Threshing               NaN
93   Burundi    NaN  Maize (corn)  Shelling, Threshing               NaN
99   Burundi    NaN          Rice  Shelling, Threshing               NaN
104  Burundi    NaN       Sorghum  Shelling, Threshing               NaN
108  Burundi    NaN        Millet  Shelling, Threshing               NaN
116  Burundi    NaN         Wheat  Shelling, Threshing               NaN
119  Burundi    NaN  Maize (corn)  Shelling, Threshing               NaN
125  Burundi    NaN          Rice  Shelling, Threshing               NaN
130  Burundi    NaN       Sorghum  Shelling, Threshing               NaN
134  Burundi    NaN        Millet  Shelling, Threshing               NaN

#### **Formatting inconsistencies**

In [257]:
# Normalize labels for comparison only
stage_normalized = (
    df_region["food_supply_stage"]
    .astype("string")
    .str.strip()
    .str.casefold()
    .str.replace(r"\s+", " ", regex=True)
)

stage_format_review = (
    df_region.assign(_stage_normalized=stage_normalized)
    .dropna(subset=["_stage_normalized"])
    .groupby("_stage_normalized")
    .agg(
        original_labels=(
            "food_supply_stage",
            lambda s: sorted(s.astype(str).unique().tolist())
        ),
        records=("food_supply_stage", "size"),
        activities=(
            "activity",
            lambda s: sorted(s.dropna().astype(str).unique().tolist())
        )
    )
    .reset_index()
)

stage_format_review = stage_format_review.loc[
    stage_format_review["original_labels"].apply(len) > 1
].copy()

print("Potential formatting inconsistencies:", len(stage_format_review))
display(stage_format_review)

Potential formatting inconsistencies: 0

Empty DataFrame
Columns: [_stage_normalized, original_labels, records, activities]
Index: []

#### **Different phase names potentially referring to the same stage**

In [258]:
# List unique stage labels and frequencies
stage_frequency = (
    df_region["food_supply_stage"]
    .dropna()
    .astype("string")
    .str.strip()
    .value_counts()
    .rename_axis("food_supply_stage")
    .reset_index(name="records")
)

print("Unique stage labels:", len(stage_frequency))
display(stage_frequency)

Unique stage labels: 20

     food_supply_stage  records
0                 Farm    10103
1   Whole supply chain     6147
2              Harvest     4160
3              Storage     3216
4            Transport     2091
5               Retail      754
6           Processing      441
7            Wholesale      325
8           Households      248
9         Post-harvest      168
10              Trader      107
11              Market      101
12              Export       50
13             Packing       48
14        Distribution       39
15         Pre-harvest       24
16       Food Services       23
17           Collector       16
18             Grading       12
19            Stacking        1

In [259]:
# Install once if needed:
# %pip install rapidfuzz

from rapidfuzz import fuzz
from itertools import combinations

stage_names = stage_frequency["food_supply_stage"].tolist()

similar_stage_candidates = []

for stage1, stage2 in combinations(stage_names, 2):
    similarity = fuzz.ratio(stage1.casefold(), stage2.casefold())

    if similarity >= 85:
        similar_stage_candidates.append({
            "stage_1": stage1,
            "stage_2": stage2,
            "similarity_score": similarity
        })

stage_similarity_review = pd.DataFrame(
    similar_stage_candidates,
    columns=["stage_1", "stage_2", "similarity_score"]
)

if not stage_similarity_review.empty:
    stage_similarity_review = stage_similarity_review.sort_values(
        "similarity_score",
        ascending=False
    )

print("Similar stage-label pairs:", len(stage_similarity_review))
display(stage_similarity_review.head(50))

Similar stage-label pairs: 0

Empty DataFrame
Columns: [stage_1, stage_2, similarity_score]
Index: []

#### **Broad vs. specific stages**

In [260]:
# Flag potentially broad or aggregate stage labels
broad_stage_pattern = (
    r"\bother\b|"
    r"\btotal\b|"
    r"\ball stages\b|"
    r"\bwhole supply chain\b|"
    r"\bvarious\b|"
    r"\bunspecified\b|"
    r"\bmultiple stages\b"
)

broad_stage_candidates = df_region.loc[
    stage_text.str.contains(
        broad_stage_pattern,
        case=False,
        regex=True,
        na=False
    ),
    [
        "country", "region", "commodity",
        "activity", "food_supply_stage"
    ]
].copy()

print("Potential broad-stage records:", len(broad_stage_candidates))
display(broad_stage_candidates.head(50))

Potential broad-stage records: 6147

,country,region,commodity,activity,food_supply_stage
35,Myanmar,NaN,"Groundnuts, excluding shelled",NaN,Whole supply chain
36,Myanmar,NaN,"Groundnuts, excluding shelled",NaN,Whole supply chain
37,Myanmar,NaN,"Groundnuts, excluding shelled",NaN,Whole supply chain
38,Myanmar,NaN,"Groundnuts, excluding shelled",NaN,Whole supply chain
39,Myanmar,NaN,"Groundnuts, excluding shelled",NaN,Whole supply chain
40,Myanmar,NaN,"Groundnuts, excluding shelled",NaN,Whole supply chain
41,Myanmar,NaN,"Groundnuts, excluding shelled",NaN,Whole supply chain
111,Burundi,NaN,Wheat,NaN,Whole supply chain
112,Burundi,NaN,Maize (corn),NaN,Whole supply chain
113,Burundi,NaN,Rice,NaN,Whole supply chain
555,Belarus,NaN,Raw milk of cattle,NaN,Whole supply chain
556,Belarus,NaN,Raw milk of cattle,NaN,Whole supply chain
557,Belarus,NaN,Raw milk of cattle,NaN,Whole supply chain
558,Belarus,NaN,Raw milk of cattle,NaN,Whole supply chain
559,Belarus,NaN,Raw milk of cattle,NaN,Whole supply chain
560,Belarus,NaN,Raw milk of cattle,NaN,Whole supply chain
561,Belarus,NaN,Raw milk of cattle,NaN,Whole supply chain
562,Belarus,NaN,Raw milk of cattle,NaN,Whole supply chain
564,Cambodia,NaN,Maize (corn),NaN,Whole supply chain
565,Cambodia,NaN,Rice,NaN,Whole supply chain
572,Cambodia,NaN,Cauliflowers and broccoli,NaN,Whole supply chain
573,Cambodia,NaN,Cucumbers and gherkins,NaN,Whole supply chain
574,Cambodia,NaN,Tomatoes,NaN,Whole supply chain
575,Cambodia,NaN,"Other beans, green",NaN,Whole supply chain
616,Algeria,NaN,Potatoes,NaN,Whole supply chain
647,Cameroon,Boyo,Bananas,"Farm, Marketing, Storage, Transportation",Whole supply chain
769,Cameroon,NaN,Plantains and cooking bananas,NaN,Whole supply chain
966,Canada,NaN,"Hen eggs in shell, fresh",NaN,Whole supply chain
967,Canada,NaN,"Meat of pig, fresh or chilled",NaN,Whole supply chain
968,Canada,NaN,"Hen eggs in shell, fresh",NaN,Whole supply chain
969,Canada,NaN,"Meat of pig, fresh or chilled",NaN,Whole supply chain
970,Canada,NaN,"Hen eggs in shell, fresh",NaN,Whole supply chain
971,Canada,NaN,"Meat of pig, fresh or chilled",NaN,Whole supply chain
972,Canada,NaN,"Hen eggs in shell, fresh",NaN,Whole supply chain
973,Canada,NaN,"Meat of pig, fresh or chilled",NaN,Whole supply chain
975,Canada,NaN,Mixed grain,NaN,Whole supply chain
976,Canada,NaN,"Snails, fresh, chilled, frozen, dried, salted ...",NaN,Whole supply chain
977,Canada,NaN,Wheat,NaN,Whole supply chain
978,Canada,NaN,Grapes,NaN,Whole supply chain
979,Canada,NaN,"Hen eggs in shell, fresh",NaN,Whole supply chain
980,Canada,NaN,"Meat of pig, fresh or chilled",NaN,Whole supply chain
981,Canada,NaN,Wheat,NaN,Whole supply chain
982,Canada,NaN,Grapes,NaN,Whole supply chain
983,Canada,NaN,"Hen eggs in shell, fresh",NaN,Whole supply chain
984,Canada,NaN,"Meat of pig, fresh or chilled",NaN,Whole supply chain
985,Canada,NaN,Wheat,NaN,Whole supply chain
986,Canada,NaN,Grapes,NaN,Whole supply chain
987,Canada,NaN,"Hen eggs in shell, fresh",NaN,Whole supply chain
988,Canada,NaN,"Meat of pig, fresh or chilled",NaN,Whole supply chain
989,Canada,NaN,Wheat,NaN,Whole supply chain

#### **Checking compatibility between the food supply stage and the business activity**

In [261]:
# Review observed stage-activity combinations
stage_activity_combinations = (
    df_region.groupby(
        ["food_supply_stage", "activity"],
        dropna=False
    )
    .size()
    .reset_index(name="records")
    .sort_values("records", ascending=False)
)

print("Unique stage-activity combinations:",
      len(stage_activity_combinations))

display(stage_activity_combinations.head(100))

Unique stage-activity combinations: 286

      food_supply_stage                            activity  records
265  Whole supply chain                                 NaN     5939
101             Harvest                  Drying, Harvesting     3500
89                 Farm                      Transportation     3367
284                 NaN                 Shelling, Threshing     3342
87                 Farm                             Storage     3295
..                  ...                                 ...      ...
77                 Farm                             Milling        6
279           Wholesale                  Sorting, Wholesale        5
215           Transport  Marketing, Storage, Transportation        5
38                 Farm                              Curing        5
54                 Farm                       Farm, Sorting        5

[100 rows x 3 columns]

In [262]:
# Count activities associated with each supply-chain stage
stage_activity_summary = (
    df_region.groupby("food_supply_stage", dropna=False)
    .agg(
        records=("activity", "size"),
        unique_activities=("activity", "nunique"),
        activities=(
            "activity",
            lambda s: sorted(s.dropna().astype(str).unique().tolist())
        )
    )
    .reset_index()
    .sort_values("unique_activities", ascending=False)
)

display(stage_activity_summary)

,food_supply_stage,records,unique_activities,activities
3,Farm,10103,73,"[Assembling, Assembling, Farm, Assembling, Fie..."
18,Whole supply chain,6147,42,"[Assembling, Bagging, Grading, Harvesting, Loa..."
12,Processing,441,29,"[Bagging, Packaging, Cleaning, Sorting, Dewate..."
15,Storage,3216,19,"[Cleaning, Collection, Distribution, Drying, F..."
19,Wholesale,325,16,"[Collection, Marketing, Collection, Wholesale,..."
6,Harvest,4160,14,"[Cleaning, Drying, Field, Harvesting, Ripening..."
17,Transport,2091,13,"[Handling, Handling, Trading, Transportation, ..."
16,Trader,107,10,"[Collection, Collection, Marketing, Distributi..."
10,Post-harvest,168,9,"[Drying, Drying, Milling, Processing, Handling..."
8,Market,101,9,"[Collection, Distribution, Marketing, Wholesal..."
0,Collector,16,8,"[Collection, Drying, Threshing, Grading, Gradi..."
1,Distribution,39,6,"[Bulking, Distribution, Distribution, Distribu..."
13,Retail,754,6,"[Grading, Sorting, Marketing, Marketing, Retai..."
7,Households,248,3,"[Consumption, Consumption, Retailing, Storage]"
2,Export,50,3,"[Cleaning, Collection, Distribution, Drying, F..."
9,Packing,48,3,"[Bagging, Packaging, Packaging, Packaging, Sor..."
20,NaN,3391,2,"[Grading, Sorting, Shelling, Threshing]"
4,Food Services,23,1,[Consumption]
5,Grading,12,1,[Grading]
11,Pre-harvest,24,0,[]
14,Stacking,1,0,[]

### **Check on treatment**

#### **Show missing values**

In [263]:
treatment_text = df_region["treatment"].astype("string").str.strip()

missing_treatment = df_region.loc[
    treatment_text.isna() | treatment_text.eq(""),
    [
        "country",
        "region",
        "commodity",
        "activity",
        "treatment"
    ]
].copy()

print("Number of missing treatment values:", len(missing_treatment))
display(missing_treatment.head(20))

Number of missing treatment values: 29678

   country region       commodity    activity treatment
0    World    NaN           Wheat  Processing       NaN
1    World    NaN    Maize (corn)  Processing       NaN
2    World    NaN    Maize (corn)  Processing       NaN
3    World    NaN    Maize (corn)  Processing       NaN
4    World    NaN    Maize (corn)  Processing       NaN
5    World    NaN    Maize (corn)  Processing       NaN
6    World    NaN            Rice  Processing       NaN
7    World    NaN         Sorghum  Processing       NaN
8    World    NaN          Barley  Processing       NaN
9    World    NaN          Barley  Processing       NaN
10   World    NaN          Barley  Processing       NaN
11   World    NaN             Rye  Processing       NaN
12   World    NaN            Oats  Processing       NaN
13   World    NaN            Oats  Processing       NaN
14   World    NaN          Millet  Processing       NaN
15   World    NaN       Buckwheat  Processing       NaN
16   World    NaN  Cereals n.e.c.  Processing       NaN
17   World    NaN  Cereals n.e.c.  Processing       NaN
18   World    NaN  Cereals n.e.c.  Processing       NaN
19   World    NaN      Pot barley  Processing       NaN

#### **Detecting spelling and formatting variations**

In [264]:
treatment_check = df_region[["treatment"]].copy()

treatment_check["treatment_normalized"] = (
    treatment_check["treatment"]
    .astype("string")
    .str.strip()
    .str.casefold()
    .str.replace(r"\s+", " ", regex=True)
)

treatment_variants = (
    treatment_check
    .groupby("treatment_normalized", dropna=False)
    .agg(
        original_labels=(
            "treatment",
            lambda s: sorted(s.dropna().unique().tolist())
        ),
        records=("treatment", "size")
    )
    .reset_index()
)

treatment_format_review = treatment_variants[
    treatment_variants["original_labels"].apply(len) > 1
].copy()

display(treatment_format_review)

,treatment_normalized,original_labels,records
188,aman rice,"[Aman Rice, Aman rice]",63
200,aus rice,"[Aus Rice, Aus rice]",54
229,boro rice,"[Boro Rice, Boro rice]",63
395,indica rice,"[Indica Rice, Indica rice]",18
454,major season,"[Major Season, Major season]",99
458,manual harvesting,"[Manual Harvesting, Manual harvesting]",8
486,minor season,"[Minor Season, Minor season]",66
517,on-season fresh longan for export,"[On-season fresh longan for Export, On-season ...",4
622,starch factory,"[Starch Factory, Starch factory]",3
733,wheat b (naturally infested grain) during 90 d...,[Wheat B (Naturally infested grain) during 90...,2

#### **Displaying unique values and the frequency of each value**

In [265]:
treatment_frequency = (
    df_region["treatment"]
    .value_counts(dropna=False)
    .rename_axis("treatment")
    .reset_index(name="records")
)

display(treatment_frequency)

                                             treatment  records
0                                                  NaN    29678
1                                            Boro rice       57
2                                            Aman rice       57
3                                         Major Season       54
4                                             Aus rice       48
..                                                 ...      ...
760  Barley during 90 days at 28°C, 70% RH and 12h/...        1
761  Barley during 90 days at 28°C, 70% RH and 12h/...        1
762  Barley during 90 days at 28°C, 70% RH and 12h/...        1
763  Barley during 90 days at 28°C, 70% RH and 12h/...        1
764  Barley during 90 days at 28°C, 70% RH and 12h/...        1

[765 rows x 2 columns]

In [266]:
unique_treatments = (
    df_region["treatment"]
    .dropna()
    .astype("string")
    .str.strip()
    .unique()
)

print("Number of unique treatment values:", len(unique_treatments))
print(sorted(unique_treatments.tolist()))

Number of unique treatment values: 764

#### **Detecting textually similar values**

In [267]:
from itertools import combinations

treatment_labels = sorted(
    df_region["treatment"]
    .dropna()
    .astype("string")
    .str.strip()
    .loc[lambda s: s.ne("")]
    .unique()
    .tolist()
)

treatment_similarity_candidates = []

for value1, value2 in combinations(treatment_labels, 2):
    similarity = fuzz.ratio(
        value1.casefold(),
        value2.casefold()
    )

    if similarity >= 85:
        treatment_similarity_candidates.append({
            "treatment_1": value1,
            "treatment_2": value2,
            "similarity": similarity
        })

treatment_similarity_review = (
    pd.DataFrame(treatment_similarity_candidates)
    .sort_values("similarity", ascending=False)
    .reset_index(drop=True)
)

display(treatment_similarity_review)

,treatment_1,treatment_2,similarity
0,On-season fresh longan for Export,On-season fresh longan for export,100.000000
1,Major Season,Major season,100.000000
2,Minor Season,Minor season,100.000000
3,Boro Rice,Boro rice,100.000000
4,Aus Rice,Aus rice,100.000000
...,...,...,...
1454,6 months storage in Storage in Red clay brick ...,6 months storage in Storage in Red clay brick ...,85.049834
1455,3 months storage in Storage in Red clay brick ...,3 months storage in Storage in Red clay brick ...,85.049834
1456,Wheat B (Naturally infested grain) 90 days at ...,Wheat B (Naturally infested grain) during 90 d...,85.046729
1457,Indica Rice Variety,Japonica Rice Variety,85.000000
1458,High Yielding Variety - Manual Threshing,High Yielding Variety - Manual Winnowing,85.000000

#### **Reviewing generic or ambiguous values**

In [268]:
treatment_broad_candidates = df_region.loc[
    df_region["treatment"]
    .astype("string")
    .str.contains(
        r"\b(other|others|various|unspecified|unknown|miscellaneous)\b",
        case=False,
        na=False,
        regex=True
    ),
    [
        "country",
        "region",
        "commodity",
        "activity",
        "treatment"
    ]
].copy()

display(treatment_broad_candidates)

C:\Users\GM\AppData\Local\Temp\ipykernel_30492\3890336587.py:4: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  .str.contains(

,country,region,commodity,activity,treatment
2064,China,NaN,Maize (corn),Storage,Other storage methods
2076,China,NaN,Rice,Storage,Other storage methods - Indica rice
9871,India,NaN,Rice,Storage,Unspecified storage
25279,Brazil,NaN,Rice,Storage,Unspecified storage

#### **Reviewing the compatibility of treatment with activity and food_supply_stage**

In [269]:
treatment_activity_combinations = (
    df_region
    .groupby(
        ["treatment", "activity"],
        dropna=False
    )
    .size()
    .reset_index(name="records")
    .sort_values("records", ascending=False)
)

display(treatment_activity_combinations)

,treatment,activity,records
1145,NaN,NaN,7200
1136,NaN,Storage,5340
1141,NaN,Transportation,5224
1041,NaN,"Drying, Harvesting",3498
1130,NaN,"Shelling, Threshing",3346
...,...,...,...
30,180 days storage in SuperGrain IV-R™ bag + 12%...,Storage,1
31,180 days storage in SuperGrain IV-R™ bag + 14%...,Storage,1
32,180 days storage in SuperGrain IV-R™ bag + 16%...,Storage,1
33,180 days storage in SuperGrain IV-R™ bag + 18%...,Storage,1
34,2 month storage in a Basket made from woven ba...,Storage,1

In [270]:
treatment_context_summary = (
    df_region
    .groupby(
        ["treatment", "activity", "food_supply_stage"],
        dropna=False
    )
    .size()
    .reset_index(name="records")
    .sort_values("records", ascending=False)
)

display(treatment_context_summary)

,treatment,activity,food_supply_stage,records
1257,NaN,NaN,Whole supply chain,5902
1081,NaN,"Drying, Harvesting",Harvest,3498
1230,NaN,Transportation,Farm,3366
1208,NaN,"Shelling, Threshing",NaN,3342
1217,NaN,Storage,Farm,3273
...,...,...,...,...
9,1 months storage in Storage in Woven basket no...,Storage,Storage,1
8,1 months storage in Storage in Storage in wove...,Storage,Storage,1
7,1 months storage in Storage in Red clay brick ...,Storage,Storage,1
6,1 months storage in Storage in Red clay brick ...,Storage,Storage,1
5,1 months storage in Red clay brick wall intern...,Storage,Storage,1

### **Check on cause_of_loss**

#### **Show missing values**

In [271]:
cause_text = df_region["cause_of_loss"].astype("string").str.strip()

missing_cause_of_loss = df_region.loc[
    cause_text.isna() | cause_text.eq(""),
    [
        "country",
        "region",
        "commodity",
        "activity",
        "cause_of_loss"
    ]
].copy()

print("Number of missing causes:", len(missing_cause_of_loss))
display(missing_cause_of_loss.head(20))

Number of missing causes: 30367

   country region       commodity    activity cause_of_loss
0    World    NaN           Wheat  Processing           NaN
1    World    NaN    Maize (corn)  Processing           NaN
2    World    NaN    Maize (corn)  Processing           NaN
3    World    NaN    Maize (corn)  Processing           NaN
4    World    NaN    Maize (corn)  Processing           NaN
5    World    NaN    Maize (corn)  Processing           NaN
6    World    NaN            Rice  Processing           NaN
7    World    NaN         Sorghum  Processing           NaN
8    World    NaN          Barley  Processing           NaN
9    World    NaN          Barley  Processing           NaN
10   World    NaN          Barley  Processing           NaN
11   World    NaN             Rye  Processing           NaN
12   World    NaN            Oats  Processing           NaN
13   World    NaN            Oats  Processing           NaN
14   World    NaN          Millet  Processing           NaN
15   World    NaN       Buckwheat  Processing           NaN
16   World    NaN  Cereals n.e.c.  Processing           NaN
17   World    NaN  Cereals n.e.c.  Processing           NaN
18   World    NaN  Cereals n.e.c.  Processing           NaN
19   World    NaN      Pot barley  Processing           NaN

#### **Discovering Cause Name Variations**

In [272]:
cause_check = df_region[["cause_of_loss"]].copy()

cause_check["cause_normalized"] = (
    cause_check["cause_of_loss"]
    .astype("string")
    .str.strip()
    .str.casefold()
    .str.replace(r"\s+", " ", regex=True)
)

cause_variants = (
    cause_check
    .groupby("cause_normalized", dropna=False)
    .agg(
        original_labels=(
            "cause_of_loss",
            lambda s: sorted(s.dropna().unique().tolist())
        ),
        records=("cause_of_loss", "size")
    )
    .reset_index()
)

cause_format_review = cause_variants[
    cause_variants["original_labels"].apply(len) > 1
].copy()

display(cause_format_review)

,cause_normalized,original_labels,records
120,insect damage,"[Insect Damage, Insect damage]",19
130,insects and rodents,"[Insects And Rodents, Insects and rodents]",2
195,mechanical damage,"[Mechanical Damage, Mechanical damage]",37
248,physical losses,"[Physical Losses, Physical losses]",94
279,pre-cooling and packaging,"[Pre-Cooling And Packaging, Pre-cooling and p...",2
309,"rodents, insects and moulds","[Rodents, Insects and Moulds, Rodents, Insects...",9
310,"rodents, insects, moulds","[Rodents, Insects, Moulds, Rodents, insects, m...",3
312,rotting,"[Rotting, rotting]",8
317,"rough handling, the effects of high ambient te...","[rough handling, the effects of high ambient t...",4
334,spreading out in sunlight,"[Spreading Out In Sunlight, Spreading out in s...",2

In [273]:
cause_frequency = (
    df_region["cause_of_loss"]
    .value_counts(dropna=False)
    .rename_axis("cause_of_loss")
    .reset_index(name="records")
)

display(cause_frequency)

                                         cause_of_loss  records
0                                                  NaN    30367
1                                      Physical Losses       87
2                                   Insect pest damage       54
3    main causes of this were a mismatch in supply ...       41
4                                    Mechanical Damage       36
..                                                 ...      ...
402                      Carotenoid Loss During Drying        1
403  Price Discount For Every One Bruchid Hole Per ...        1
404                                   Insects and mold        1
405                         Insects, moisture and mold        1
406                            Maize ear rot infection        1

[407 rows x 2 columns]

#### **Detecting Multiple Causes in a Single Cell**

In [274]:
cause_text = df_region["cause_of_loss"].astype("string").str.strip()

multiple_cause_pattern = (
    r",|;|\||\s/\s|\s&\s|\band\b|\bor\b"
)

multiple_cause_mask = cause_text.str.contains(
    multiple_cause_pattern,
    case=False,
    na=False,
    regex=True
)

multiple_cause_candidates = df_region.loc[
    multiple_cause_mask,
    [
        "country",
        "region",
        "commodity",
        "activity",
        "cause_of_loss"
    ]
].copy()

print(
    "Potential records with multiple causes:",
    len(multiple_cause_candidates)
)

display(multiple_cause_candidates.head(30))

Potential records with multiple causes: 453

,country,region,commodity,activity,cause_of_loss
612,Cambodia,NaN,Cauliflowers and broccoli,NaN,Hot Weather During Harvest And Post Packaging
613,Cambodia,NaN,Cucumbers and gherkins,NaN,Hot Weather During Harvest And Post Packaging
614,Cambodia,NaN,Tomatoes,NaN,Hot Weather During Harvest And Post Packaging
615,Cambodia,NaN,"Other beans, green",NaN,Hot Weather During Harvest And Post Packaging
647,Cameroon,Boyo,Bananas,"Farm, Marketing, Storage, Transportation","Over-ripening, poor handling, poor storage"
648,Cameroon,Boyo,Bananas,Farm,"Over-ripening, poor handling, poor storage"
649,Cameroon,Boyo,Bananas,Transportation,"Over-ripening, poor handling"
650,Cameroon,Boyo,Bananas,"Processing, Ripening","Over-ripening, poor handling, poor storage"
651,Cameroon,Boyo,Bananas,Storage,"Over-ripening, poor handling, poor storage"
769,Cameroon,NaN,Plantains and cooking bananas,NaN,"rough handling, unprotected storage conditions..."
2121,China,NaN,Wheat,NaN,decentralized agricultural system in China ce...
2122,China,NaN,Maize (corn),NaN,decentralized agricultural system in China ce...
2123,China,NaN,Rice,NaN,decentralized agricultural system in China ce...
2124,China,NaN,"Meat of cattle with the bone, fresh or chilled",NaN,decentralized agricultural system in China ce...
2125,China,NaN,"Meat of cattle with the bone, fresh or chilled",NaN,decentralized agricultural system in China ce...
2126,China,NaN,"Meat of cattle with the bone, fresh or chilled","Handling, Harvesting",decentralized agricultural system in China ce...
2127,China,NaN,"Meat of cattle with the bone, fresh or chilled",NaN,decentralized agricultural system in China ce...
2153,China,Shandong Province,Cabbages,NaN,"(Md=4.7%, W=0.8%)"
2157,China,"Daxing, Tongxian, and Yanqing counties, which ...",Cabbages,NaN,Pre-Cooling And Packaging
2162,China,Fujian Province,Cabbages,NaN,mechanical and disease damage loss (peeled off)
2165,China,Xiasha Town,Cabbages,"Collection, Marketing",mechanical and disease damage loss (peeled off)
2167,China,"Daxing, Tongxian, and Yanqing counties, which ...",Cabbages,"Grading, Sorting","Triming Of Leaves, Sold Fresh"
2169,China,Fujian Province,Cabbages,NaN,mechanical and disease damage loss (peeled off)
2172,China,Xiasha Town,Cabbages,NaN,mechanical and disease damage loss (peeled off)
2174,China,Cixi county,Cabbages,"Collection, Marketing",mechanical and disease damage loss (peeled off)
2175,China,Xiasha Town,Cabbages,NaN,"(Md=4.7%, W=0.8%)"
2177,China,Shandong Province,Cabbages,NaN,Disease And Rot
2182,China,"Daxing, Tongxian, and Yanqing",Cabbages,NaN,Energy consumption and abscission
2188,China,Cixi county,Cabbages,NaN,mechanical and disease damage loss (peeled off)
2189,China,Fujian Province,Cabbages,"Collection, Marketing",mechanical and disease damage loss (peeled off)

#### **Discovering Differences in Level of Detail / Granularity**

In [275]:
cause_granularity = df_region[["cause_of_loss"]].copy()

cause_granularity["cause_text"] = (
    cause_granularity["cause_of_loss"]
    .astype("string")
    .str.strip()
)

cause_granularity["word_count"] = (
    cause_granularity["cause_text"]
    .str.split()
    .str.len()
)

cause_granularity["character_count"] = (
    cause_granularity["cause_text"]
    .str.len()
)

display(
    cause_granularity[
        [
            "cause_of_loss",
            "word_count",
            "character_count"
        ]
    ].sort_values(
        "word_count",
        ascending=False,
        na_position="last"
    ).head(30)
)

,cause_of_loss,word_count,character_count
12504,The vast majority of mango farmers interviewed...,424,2594
27512,The study revealed that 70% of the surveyed fa...,268,1692
17875,Krishi Bazar Store Oranges In Cemented Floor O...,203,1267
7477,The results of the milling analysis have been ...,203,1282
3458,In the field 1.7 59% 33% During threshing 1.0...,187,1214
27494,Poor Post Harvest Management . Quantitative...,146,1040
27493,"Weather, Field Damage d. Quantitative post-...",145,1034
27495,. Quantitative post-harvest losses of economic...,142,1008
25116,Main harvest side flow reasons: Unacceptable s...,123,798
25114,Main harvest side flow reasons: Unacceptable s...,123,798
25115,Main harvest side flow reasons: Unacceptable s...,123,798
25117,Main harvest side flow reasons: Unacceptable s...,123,798
25118,Main harvest side flow reasons: Unacceptable s...,123,798
3463,Average /Frequency of producers/Frequency of p...,116,688
3461,Average /Frequency of producers/Frequency of p...,116,688
4375,The main causes of storage loss in order of im...,113,600
17874,Field To Krishi Bazar The oranges were foun...,110,666
25120,Damage during harvesting or handling; unacc...,107,716
3464,"Quality issues, pests, plant diseases, harvest...",103,530
7468,The survey finding further showed that most fa...,100,642
26069,Critical loss points • Following review of li...,100,717
26068,Critical loss points • Following review of li...,100,717
7472,The survey finding further showed that most fa...,100,642
7473,The survey finding further showed that most fa...,100,642
7474,The survey finding further showed that most fa...,100,642
26067,Critical loss points • Following review of li...,100,717
26072,Critical loss points • Following review of li...,100,717
26071,Critical loss points • Following review of li...,100,717
26070,Critical loss points • Following review of li...,100,717
7628,Bag Beating/Bambam The results of the surve...,98,620

In [276]:
display(
    cause_granularity[
        ["word_count", "character_count"]
    ].describe()
)

       character_count
count           1098.0
mean         77.123862
std           171.5698
min                4.0
25%               15.0
50%               24.0
75%               63.0
max             2594.0

#### **Distinguishing Between Cause and Effect**

In [277]:
cause_outcome_pattern = (
    r"\b(loss|lost|waste|wasted|spoilage|spoiled|"
    r"damage|damaged|deterioration|deteriorated)\b"
)

cause_outcome_candidates = df_region.loc[
    df_region["cause_of_loss"]
    .astype("string")
    .str.contains(
        cause_outcome_pattern,
        case=False,
        na=False,
        regex=True
    ),
    [
        "country",
        "region",
        "commodity",
        "activity",
        "food_supply_stage",
        "cause_of_loss"
    ]
].copy()

display(cause_outcome_candidates.head(50))

C:\Users\GM\AppData\Local\Temp\ipykernel_30492\1323180583.py:9: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  .str.contains(

,country,region,commodity,activity,food_supply_stage,cause_of_loss
569,Cambodia,"Kandal Province, and wholesalers and retailers...",Tomatoes,NaN,Farm,Immaturity Insect Damage Rotting/Decay
570,Cambodia,"Kandal Province, and wholesalers and retailers...",Tomatoes,NaN,Trader,Physical Damage Rotting/Decay
571,Cambodia,"Kandal Province, and wholesalers and retailers...",Tomatoes,NaN,Wholesale,Physical Damage Rotting/Decay
1960,Chile,North Patagonia Region,Pears,NaN,Farm,Insect Damage
2121,China,NaN,Wheat,NaN,Storage,decentralized agricultural system in China ce...
2122,China,NaN,Maize (corn),NaN,Storage,decentralized agricultural system in China ce...
2123,China,NaN,Rice,NaN,Storage,decentralized agricultural system in China ce...
2124,China,NaN,"Meat of cattle with the bone, fresh or chilled",NaN,Processing,decentralized agricultural system in China ce...
2125,China,NaN,"Meat of cattle with the bone, fresh or chilled",NaN,Storage,decentralized agricultural system in China ce...
2126,China,NaN,"Meat of cattle with the bone, fresh or chilled","Handling, Harvesting",Farm,decentralized agricultural system in China ce...
2127,China,NaN,"Meat of cattle with the bone, fresh or chilled",NaN,Wholesale,decentralized agricultural system in China ce...
2154,China,Shandong Province,Cabbages,"Marketing, Wholesale",Wholesale,disease loss
2161,China,Shandong Province,Cabbages,NaN,Retail,disease loss
2162,China,Fujian Province,Cabbages,NaN,Retail,mechanical and disease damage loss (peeled off)
2165,China,Xiasha Town,Cabbages,"Collection, Marketing",Wholesale,mechanical and disease damage loss (peeled off)
2169,China,Fujian Province,Cabbages,NaN,Wholesale,mechanical and disease damage loss (peeled off)
2172,China,Xiasha Town,Cabbages,NaN,Wholesale,mechanical and disease damage loss (peeled off)
2174,China,Cixi county,Cabbages,"Collection, Marketing",Wholesale,mechanical and disease damage loss (peeled off)
2183,China,Fujian Province,Cabbages,NaN,Wholesale,Mechanical Damage
2184,China,Jiangan district,Cabbages,NaN,Retail,mechanical damage.leaf yellowing. sound leaves...
2185,China,Jiangan district,Cabbages,NaN,Retail,mechanical damage.leaf yellowing. sound leaves...
2188,China,Cixi county,Cabbages,NaN,Retail,mechanical and disease damage loss (peeled off)
2189,China,Fujian Province,Cabbages,"Collection, Marketing",Trader,mechanical and disease damage loss (peeled off)
2190,China,Cixi county,Cabbages,NaN,Wholesale,mechanical and disease damage loss (peeled off)
2191,China,Xiasha town,Cabbages,NaN,Retail,mechanical damage.leaf yellowing. sound leaves...
2196,China,Fujian Province,Cabbages,NaN,Retail,Mechanical Damage
2198,China,Xiasha Town,Cabbages,NaN,Retail,mechanical and disease damage loss (peeled off)
2200,China,"Daxing, Tongxian, and Yanqing counties, which ...",Cauliflowers and broccoli,NaN,Export,Broccoli For Export Was Handled With Care So T...
2203,China,"Daxing, Tongxian, and Yanqing counties, which ...",Cauliflowers and broccoli,NaN,Processing,Broccoli For Export Was Handled With Care So T...
2208,China,"Daxing, Tongxian, and Yanqing counties, which ...","Onions and shallots, green",NaN,Transport,"Dropped, Tossed, And Trodden On On Top Of Load..."
2209,China,"Daxing, Tongxian, and Yanqing counties, which ...","Onions and shallots, green",NaN,Storage,"Dropped, Tossed, And Trodden On On Top Of Load..."
2211,China,"Daxing, Tongxian, and Yanqing counties, which ...","Onions and shallots, green",NaN,Retail,"Dropped, Tossed, And Trodden On On Top Of Load..."
2212,China,"Daxing, Tongxian, and Yanqing counties, which ...","Onions and shallots, green",NaN,Wholesale,"Dropped, Tossed, And Trodden On On Top Of Load..."
3095,Benin,NaN,"Cassava, dry",Storage,Storage,Insect damage
3174,Benin,NaN,Tomatoes,"Grading, Sorting",Farm,Mechanical Damage
3178,Benin,NaN,Tomatoes,"Grading, Sorting",Wholesale,Mechanical Damage
3179,Benin,NaN,Tomatoes,"Grading, Sorting",Retail,Mechanical Damage
3181,Benin,NaN,Tomatoes,"Grading, Sorting",Retail,Mechanical Damage
3187,Benin,NaN,Oranges,"Grading, Sorting",Farm,Mechanical Damage
3188,Benin,NaN,Oranges,"Grading, Sorting",Wholesale,Mechanical Damage
3189,Benin,NaN,Oranges,"Grading, Sorting",Retail,Mechanical Damage
3193,Benin,NaN,"Pepper (<i>Piper</i> spp.), raw","Grading, Sorting",Wholesale,Mechanical Damage
3197,Benin,NaN,"Pepper (<i>Piper</i> spp.), raw","Grading, Sorting",Retail,Mechanical Damage
3198,Benin,NaN,"Pepper (<i>Piper</i> spp.), raw","Grading, Sorting",Farm,Mechanical Damage
3458,Denmark,NaN,Wheat,NaN,Farm,In the field 1.7 59% 33% During threshing 1.0...
3459,Denmark,NaN,"Peas, green",NaN,Farm,"Damage during harvest and handling, no sale..."
3461,Denmark,NaN,"Peas, green",NaN,Processing,Average /Frequency of producers/Frequency of p...
3463,Denmark,NaN,"Peas, green",NaN,Pre-harvest,Average /Frequency of producers/Frequency of p...
3471,Denmark,NaN,"Onions and shallots, green",NaN,Farm,Average/ Frequency of producers/Frequency of p...
3472,Denmark,NaN,"Peas, dry",NaN,Farm,"Damage during harvest and handling, no sale..."

#### **Reviewing Causes by Commodity, Activity, and Stage**

In [278]:
cause_context_summary = (
    df_region
    .groupby(
        [
            "cause_of_loss",
            "commodity",
            "activity",
            "food_supply_stage"
        ],
        dropna=False
    )
    .size()
    .reset_index(name="records")
    .sort_values("records", ascending=False)
)

display(cause_context_summary.head(100))

,cause_of_loss,commodity,activity,food_supply_stage,records
1571,NaN,Maize (corn),Drying,Farm,830
1616,NaN,Maize (corn),Storage,Farm,829
1575,NaN,Maize (corn),"Drying, Harvesting",Harvest,818
1621,NaN,Maize (corn),Transportation,Farm,817
1614,NaN,Maize (corn),"Shelling, Threshing",NaN,814
...,...,...,...,...,...
971,NaN,Bananas,NaN,Whole supply chain,38
1678,NaN,"Mangoes, guavas and mangosteens",NaN,Whole supply chain,37
1491,NaN,"Groundnuts, excluding shelled",NaN,Whole supply chain,36
1754,NaN,Millet,NaN,Whole supply chain,35
2169,NaN,Plantains and others,NaN,Whole supply chain,34

### **Check on sample_size**

#### **Show missing values**

In [279]:
sample_text = df_region["sample_size"].astype("string").str.strip()

missing_sample_size = df_region.loc[
    sample_text.isna() | sample_text.eq(""),
    [
        "country",
        "region",
        "commodity",
        "year",
        "sample_size"
    ]
].copy()

print("Missing sample_size values:", len(missing_sample_size))
display(missing_sample_size.head(20))

Missing sample_size values: 29603

   country region       commodity  year sample_size
0    World    NaN           Wheat  2022         NaN
1    World    NaN    Maize (corn)  2022         NaN
2    World    NaN    Maize (corn)  2022         NaN
3    World    NaN    Maize (corn)  2022         NaN
4    World    NaN    Maize (corn)  2022         NaN
5    World    NaN    Maize (corn)  2022         NaN
6    World    NaN            Rice  2022         NaN
7    World    NaN         Sorghum  2022         NaN
8    World    NaN          Barley  2022         NaN
9    World    NaN          Barley  2022         NaN
10   World    NaN          Barley  2022         NaN
11   World    NaN             Rye  2022         NaN
12   World    NaN            Oats  2022         NaN
13   World    NaN            Oats  2022         NaN
14   World    NaN          Millet  2022         NaN
15   World    NaN       Buckwheat  2022         NaN
16   World    NaN  Cereals n.e.c.  2022         NaN
17   World    NaN  Cereals n.e.c.  2022         NaN
18   World    NaN  Cereals n.e.c.  2022         NaN
19   World    NaN      Pot barley  2022         NaN

#### **Checking for Non-Numeric Values**

In [280]:
sample_numeric = pd.to_numeric(
    sample_text,
    errors="coerce"
)

invalid_sample_size = df_region.loc[
    sample_text.notna()
    & sample_text.ne("")
    & sample_numeric.isna(),
    [
        "country",
        "region",
        "commodity",
        "year",
        "sample_size"
    ]
].copy()

print("Non-numeric sample_size values:", len(invalid_sample_size))
display(invalid_sample_size.head(20))

Non-numeric sample_size values: 1206

,country,region,commodity,year,sample_size
568,Cambodia,"Kandal Province, and wholesalers and retailers...",Tomatoes,2013,onsite interviews were conducted involving 30 ...
569,Cambodia,"Kandal Province, and wholesalers and retailers...",Tomatoes,2013,onsite interviews were conducted involving 30 ...
570,Cambodia,"Kandal Province, and wholesalers and retailers...",Tomatoes,2013,onsite interviews were conducted involving 30 ...
571,Cambodia,"Kandal Province, and wholesalers and retailers...",Tomatoes,2013,onsite interviews were conducted involving 30 ...
647,Cameroon,Boyo,Bananas,2020,380 households
648,Cameroon,Boyo,Bananas,2020,380 households
649,Cameroon,Boyo,Bananas,2020,380 households
650,Cameroon,Boyo,Bananas,2020,380 households
651,Cameroon,Boyo,Bananas,2020,380 households
1298,Sri Lanka,Conventional value chain,Cabbages,2023,"1829 stakeholders (farmers, collectors, wholes..."
1299,Sri Lanka,Conventional value chain,"Chillies and peppers, green (<i>Capsicum</i> s...",2023,"1829 stakeholders (farmers, collectors, wholes..."
1300,Sri Lanka,Conventional value chain,Tomatoes,2023,"1829 stakeholders (farmers, collectors, wholes..."
1301,Sri Lanka,Conventional value chain,Carrots and turnips,2023,"1829 stakeholders (farmers, collectors, wholes..."
1302,Sri Lanka,Conventional value chain,Bananas,2023,"1829 stakeholders (farmers, collectors, wholes..."
1303,Sri Lanka,Conventional value chain,Papayas,2023,"1829 stakeholders (farmers, collectors, wholes..."
1304,Sri Lanka,Conventional value chain,Potatoes,2023,"1829 stakeholders (farmers, collectors, wholes..."
1305,Sri Lanka,Conventional value chain,"Chillies and peppers, dry (<i>Capsicum</i> spp...",2023,"1829 stakeholders (farmers, collectors, wholes..."
1960,Chile,North Patagonia Region,Pears,2013,5500 (individual pears)
2142,China,NaN,Wheat,2008,216 restaurants in 159 counties in Henan province
2143,China,NaN,Rice,2008,216 restaurants in 159 counties in Henan province

#### **Detecting Zero and Negative Values**

In [281]:
negative_sample_size = df_region.loc[
    sample_numeric < 0,
    [
        "country",
        "region",
        "commodity",
        "year",
        "sample_size"
    ]
].copy()

zero_sample_size = df_region.loc[
    sample_numeric == 0,
    [
        "country",
        "region",
        "commodity",
        "year",
        "sample_size"
    ]
].copy()

print("Negative values:", len(negative_sample_size))
display(negative_sample_size.head(20))

print("Zero values:", len(zero_sample_size))
display(zero_sample_size.head(20))

Negative values: 0

Empty DataFrame
Columns: [country, region, commodity, year, sample_size]
Index: []

Zero values: 0

Empty DataFrame
Columns: [country, region, commodity, year, sample_size]
Index: []

#### **Checking for Non-Integer Values / Decimals**

In [282]:
non_integer_mask = (
    sample_numeric.notna()
    & ~np.isclose(
        sample_numeric,
        np.round(sample_numeric),
        rtol=0,
        atol=1e-9
    )
)

non_integer_sample_size = df_region.loc[
    non_integer_mask,
    [
        "country",
        "region",
        "commodity",
        "year",
        "sample_size"
    ]
].copy()

print("Non-integer values:", len(non_integer_sample_size))
display(non_integer_sample_size.head(20))

Non-integer values: 2

      country region           commodity  year sample_size
26116  Uganda    NaN        Maize (corn)  2016       1.193
26117  Uganda    NaN  Flour of triticale  2016       1.193

#### **Detecting Outliers**

In [283]:
valid_sample_sizes = sample_numeric.dropna()

if not valid_sample_sizes.empty:
    q1 = valid_sample_sizes.quantile(0.25)
    q3 = valid_sample_sizes.quantile(0.75)

    iqr = q3 - q1

    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr

    sample_size_outlier_mask = (
        (sample_numeric < lower_bound)
        | (sample_numeric > upper_bound)
    )

    sample_size_outliers = df_region.loc[
        sample_size_outlier_mask,
        [
            "country",
            "region",
            "commodity",
            "year",
            "sample_size"
        ]
    ].copy()

    print("Lower bound:", lower_bound)
    print("Upper bound:", upper_bound)
    print("Potential outliers:", len(sample_size_outliers))

    display(
        sample_size_outliers.sort_values(
            "sample_size",
            ascending=False
        ).head(30)
    )
else:
    print("No numeric sample_size values available for outlier detection.")

Lower bound: -953.625
Upper bound: 1709.375
Potential outliers: 0

Empty DataFrame
Columns: [country, region, commodity, year, sample_size]
Index: []

#### **Reviewing Statistical Distribution**

In [284]:
display(sample_numeric.describe(
    percentiles=[0.25, 0.50, 0.75, 0.90, 0.95, 0.99]
))

count         656.0
mean     308.352723
std      374.717715
min           1.193
25%            45.0
50%           100.0
75%          710.75
90%           933.0
95%           933.0
99%           933.0
max           988.0
Name: sample_size, dtype: Float64

In [285]:
largest_sample_sizes = df_region.loc[
    sample_numeric.notna()
].assign(
    sample_size_numeric=sample_numeric.loc[sample_numeric.notna()]
).sort_values(
    "sample_size_numeric",
    ascending=False
)

display(largest_sample_sizes.head(20))

,m49_code,country,region,cpc_code,commodity,year,loss_percentage,loss_percentage_original,loss_quantity,activity,...,treatment,cause_of_loss,sample_size,method_data_collection,reference,url,notes,_region_normalized,_country_normalized,sample_size_numeric
8772,340,Honduras,"Choluteca, Copan, El Paraiso, Francisco Moraza...",0112,Maize (corn),2016,13.68,9.95-17.41,78.61-284.26 kg,NaN,...,NaN,NaN,988,Survey,Luciana Delgado; Monica Schuster-; Maximo Tore...,https://www.researchgate.net/publication/31868...,NaN,"choluteca, copan, el paraiso, francisco moraza...",honduras,988.0
16539,50,Bangladesh,Mymensingh,0113,Rice,2009,4.30,4.30%,NaN,Storage,...,Aus rice,NaN,933,Survey,B K Bala; M A Haque; Md. Anower Hossain; Shank...,NaN,NaN,mymensingh,bangladesh,933.0
16538,50,Bangladesh,Mymensingh,0113,Rice,2009,2.96,2.96%,NaN,Threshing,...,Aus rice,NaN,933,Survey,B K Bala; M A Haque; Md. Anower Hossain; Shank...,NaN,NaN,mymensingh,bangladesh,933.0
16537,50,Bangladesh,NaN,0113,Rice,2009,1.91,1.91%,NaN,Harvesting,...,Aus rice,NaN,933,Survey,B K Bala; M A Haque; Md. Anower Hossain; Shank...,NaN,NaN,NaN,bangladesh,933.0
16536,50,Bangladesh,Comilla,0113,Rice,2009,0.02,0.02%,NaN,Parboiling,...,Aman rice,NaN,933,Survey,B K Bala; M A Haque; Md. Anower Hossain; Shank...,NaN,NaN,comilla,bangladesh,933.0
16535,50,Bangladesh,NaN,0113,Rice,2009,3.70,3.70%,NaN,Storage,...,Aman rice,NaN,933,Survey,B K Bala; M A Haque; Md. Anower Hossain; Shank...,NaN,NaN,NaN,bangladesh,933.0
16534,50,Bangladesh,Mymensingh,0113,Rice,2009,2.23,2.23%,NaN,Threshing,...,Boro rice,NaN,933,Survey,B K Bala; M A Haque; Md. Anower Hossain; Shank...,NaN,NaN,mymensingh,bangladesh,933.0
16533,50,Bangladesh,Comilla,0113,Rice,2009,2.58,2.58%,NaN,Storage,...,Aus rice,NaN,933,Survey,B K Bala; M A Haque; Md. Anower Hossain; Shank...,NaN,NaN,comilla,bangladesh,933.0
16532,50,Bangladesh,NaN,0113,Rice,2009,0.17,0.17%,NaN,Wholesale,...,Aman rice,NaN,933,Survey,B K Bala; M A Haque; Md. Anower Hossain; Shank...,NaN,NaN,NaN,bangladesh,933.0
16531,50,Bangladesh,Comilla,0113,Rice,2009,6.79,6.79%,NaN,"Cleaning, Collection, Distribution, Drying, Fi...",...,Boro rice,NaN,933,Survey,B K Bala; M A Haque; Md. Anower Hossain; Shank...,NaN,NaN,comilla,bangladesh,933.0
16530,50,Bangladesh,Comilla,0113,Rice,2009,0.63,0.63%,NaN,Transportation,...,Aman rice,NaN,933,Survey,B K Bala; M A Haque; Md. Anower Hossain; Shank...,NaN,NaN,comilla,bangladesh,933.0
16529,50,Bangladesh,Comilla,0113,Rice,2009,0.02,0.02%,NaN,Parboiling,...,Boro rice,NaN,933,Survey,B K Bala; M A Haque; Md. Anower Hossain; Shank...,NaN,NaN,comilla,bangladesh,933.0
16528,50,Bangladesh,Dinajpur,0113,Rice,2009,0.17,0.17%,NaN,Wholesale,...,Aus rice,NaN,933,Survey,B K Bala; M A Haque; Md. Anower Hossain; Shank...,NaN,NaN,dinajpur,bangladesh,933.0
16527,50,Bangladesh,Khulna,0113,Rice,2009,5.00,5.00%,NaN,Storage,...,Aus rice,NaN,933,Survey,B K Bala; M A Haque; Md. Anower Hossain; Shank...,NaN,NaN,khulna,bangladesh,933.0
16526,50,Bangladesh,Khulna,0113,Rice,2009,1.03,1.03%,NaN,Transportation,...,Boro rice,NaN,933,Survey,B K Bala; M A Haque; Md. Anower Hossain; Shank...,NaN,NaN,khulna,bangladesh,933.0
16525,50,Bangladesh,Khulna,0113,Rice,2009,0.25,0.25%,NaN,Transportation,...,Aus rice,NaN,933,Survey,B K Bala; M A Haque; Md. Anower Hossain; Shank...,NaN,NaN,khulna,bangladesh,933.0
16524,50,Bangladesh,Khulna,0113,Rice,2009,0.20,0.2%,NaN,Wholesale,...,Aus rice,NaN,933,Survey,B K Bala; M A Haque; Md. Anower Hossain; Shank...,NaN,NaN,khulna,bangladesh,933.0
16523,50,Bangladesh,Mymensingh,0113,Rice,2009,0.33,0.33%,NaN,Wholesale,...,Aus rice,NaN,933,Survey,B K Bala; M A Haque; Md. Anower Hossain; Shank...,NaN,NaN,mymensingh,bangladesh,933.0
16522,50,Bangladesh,Mymensingh,0113,Rice,2009,15.30,15.30%,NaN,"Cleaning, Collection, Distribution, Drying, Fi...",...,Aus rice,NaN,933,Survey,B K Bala; M A Haque; Md. Anower Hossain; Shank...,NaN,NaN,mymensingh,bangladesh,933.0
16521,50,Bangladesh,Mymensingh,0113,Rice,2009,1.64,1.64%,NaN,Transportation,...,Aus rice,NaN,933,Survey,B K Bala; M A Haque; Md. Anower Hossain; Shank...,NaN,NaN,mymensingh,bangladesh,933.0

### **Check on method_data_collection**

#### **Show missing values**

In [286]:
method_text = (
    df_region["method_data_collection"]
    .astype("string")
    .str.strip()
)

missing_method = df_region.loc[
    method_text.isna() | method_text.eq(""),
    [
        "country",
        "region",
        "commodity",
        "year",
        "method_data_collection"
    ]
].copy()

print("Missing method values:", len(missing_method))
display(missing_method.head(20))

Missing method values: 36

,country,region,commodity,year,method_data_collection
3677,El Salvador,NaN,Rice,2013,NaN
3678,El Salvador,NaN,Sorghum,2013,NaN
14163,Malawi,Zulu,"Groundnuts, excluding shelled",2015,NaN
14169,Malawi,Zulu,"Groundnuts, excluding shelled",2015,NaN
15974,Mexico,NaN,Wheat,2011,NaN
15975,Mexico,NaN,Maize (corn),2011,NaN
15976,Mexico,NaN,Maize (corn),2011,NaN
15977,Mexico,NaN,Rice,2011,NaN
15978,Mexico,NaN,Sorghum,2011,NaN
15979,Mexico,NaN,Barley,2011,NaN
15980,Mexico,NaN,Watermelons,2011,NaN
15981,Mexico,NaN,Avocados,2011,NaN
15982,Mexico,NaN,Bananas,2011,NaN
15983,Mexico,NaN,"Mangoes, guavas and mangosteens",2011,NaN
15984,Mexico,NaN,Papayas,2011,NaN
15985,Mexico,NaN,Pineapples,2011,NaN
15986,Mexico,NaN,Lemons and limes,2011,NaN
15987,Mexico,NaN,Oranges,2011,NaN
15988,Mexico,NaN,Soya beans,2011,NaN
18041,Nicaragua,NaN,Rice,2013,NaN

#### **Displaying Method Names and Their Frequencies**

In [287]:
method_frequency = (
    df_region["method_data_collection"]
    .value_counts(dropna=False)
    .rename_axis("method_data_collection")
    .reset_index(name="records")
)

display(method_frequency)

                               method_data_collection  records
0                                  Modelled Estimates    19497
1   FAO's annual Agriculture Production Questionna...     4209
2                                              Survey     3220
3                                   Literature Review     1694
4                                   National Accounts     1275
5                               Controlled Experiment      629
6                                          Case Study      528
7                        No Data Collection Specified      207
8                                      Expert Opinion      128
9                                        FLW Protocol       41
10                                                NaN       36
11                                             Census        1

In [288]:
unique_methods = (
    df_region["method_data_collection"]
    .dropna()
    .astype("string")
    .str.strip()
    .unique()
)

print("Number of unique methods:", len(unique_methods))
print(sorted(unique_methods.tolist()))

Number of unique methods: 11
['Case Study', 'Census', 'Controlled Experiment', 'Expert Opinion', "FAO's annual Agriculture Production Questionnaires", 'FLW Protocol', 'Literature Review', 'Modelled Estimates', 'National Accounts', 'No Data Collection Specified', 'Survey']

#### **Detecting Formatting Variations in Method Names**

In [289]:
method_check = df_region[["method_data_collection"]].copy()

method_check["method_normalized"] = (
    method_check["method_data_collection"]
    .astype("string")
    .str.strip()
    .str.casefold()
    .str.replace(r"\s+", " ", regex=True)
)

method_variants = (
    method_check
    .groupby("method_normalized", dropna=False)
    .agg(
        original_labels=(
            "method_data_collection",
            lambda s: sorted(s.dropna().unique().tolist())
        ),
        records=("method_data_collection", "size")
    )
    .reset_index()
)

method_format_review = method_variants[
    method_variants["original_labels"].apply(len) > 1
].copy()

display(method_format_review)

Empty DataFrame
Columns: [method_normalized, original_labels, records]
Index: []

#### **Detecting Similar Method Names Requiring Review**

In [290]:

method_labels = sorted(
    df_region["method_data_collection"]
    .dropna()
    .astype("string")
    .str.strip()
    .loc[lambda s: s.ne("")]
    .unique()
    .tolist()
)

method_similarity_candidates = []

for method1, method2 in combinations(method_labels, 2):
    similarity = fuzz.ratio(
        method1.casefold(),
        method2.casefold()
    )

    if similarity >= 85:
        method_similarity_candidates.append({
            "method_1": method1,
            "method_2": method2,
            "similarity": similarity
        })

method_similarity_review = pd.DataFrame(
    method_similarity_candidates,
    columns=["method_1", "method_2", "similarity"]
)

if not method_similarity_review.empty:
    method_similarity_review = (
        method_similarity_review
        .sort_values("similarity", ascending=False)
        .reset_index(drop=True)
    )

display(method_similarity_review)

Empty DataFrame
Columns: [method_1, method_2, similarity]
Index: []

#### **Distinguishing Between Data Collection Methods and Loss Estimation Methods**

In [291]:
method_category_pattern = (
    r"\b(survey|questionnaire|interview|"
    r"measurement|measured|estimation|estimated|"
    r"model|statistics|statistical|administrative data)\b"
)

method_category_candidates = df_region.loc[
    df_region["method_data_collection"]
    .astype("string")
    .str.contains(
        method_category_pattern,
        case=False,
        na=False,
        regex=True
    ),
    [
        "country",
        "region",
        "commodity",
        "year",
        "method_data_collection"
    ]
].copy()

display(method_category_candidates.head(50))

C:\Users\GM\AppData\Local\Temp\ipykernel_30492\1573561479.py:10: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  .str.contains(

,country,region,commodity,year,method_data_collection
0,World,NaN,Wheat,2022,Survey
1,World,NaN,Maize (corn),2022,Survey
2,World,NaN,Maize (corn),2022,Survey
3,World,NaN,Maize (corn),2022,Survey
4,World,NaN,Maize (corn),2022,Survey
5,World,NaN,Maize (corn),2022,Survey
6,World,NaN,Rice,2022,Survey
7,World,NaN,Sorghum,2022,Survey
8,World,NaN,Barley,2022,Survey
9,World,NaN,Barley,2022,Survey
10,World,NaN,Barley,2022,Survey
11,World,NaN,Rye,2022,Survey
12,World,NaN,Oats,2022,Survey
13,World,NaN,Oats,2022,Survey
14,World,NaN,Millet,2022,Survey
15,World,NaN,Buckwheat,2022,Survey
16,World,NaN,Cereals n.e.c.,2022,Survey
17,World,NaN,Cereals n.e.c.,2022,Survey
18,World,NaN,Cereals n.e.c.,2022,Survey
19,World,NaN,Pot barley,2022,Survey
20,World,NaN,Cereal preparations,2022,Survey
21,World,NaN,Cereal preparations,2022,Survey
22,World,NaN,Cereal preparations,2022,Survey
23,World,NaN,Cereal preparations,2022,Survey
24,World,NaN,"Malt, whether or not roasted",2022,Survey
563,Cambodia,NaN,Rice,2022,Survey
568,Cambodia,"Kandal Province, and wholesalers and retailers...",Tomatoes,2013,Survey
569,Cambodia,"Kandal Province, and wholesalers and retailers...",Tomatoes,2013,Survey
570,Cambodia,"Kandal Province, and wholesalers and retailers...",Tomatoes,2013,Survey
571,Cambodia,"Kandal Province, and wholesalers and retailers...",Tomatoes,2013,Survey
572,Cambodia,NaN,Cauliflowers and broccoli,2008,Survey
573,Cambodia,NaN,Cucumbers and gherkins,2008,Survey
574,Cambodia,NaN,Tomatoes,2008,Survey
575,Cambodia,NaN,"Other beans, green",2008,Survey
576,Cambodia,NaN,Cauliflowers and broccoli,2006,Survey
577,Cambodia,NaN,Cauliflowers and broccoli,2006,Survey
578,Cambodia,NaN,Cauliflowers and broccoli,2006,Survey
579,Cambodia,NaN,Cauliflowers and broccoli,2006,Survey
580,Cambodia,NaN,Cauliflowers and broccoli,2006,Survey
581,Cambodia,NaN,Cauliflowers and broccoli,2006,Survey
582,Cambodia,NaN,Cauliflowers and broccoli,2006,Survey
583,Cambodia,NaN,Cauliflowers and broccoli,2006,Survey
584,Cambodia,NaN,Cauliflowers and broccoli,2006,Survey
585,Cambodia,NaN,Cauliflowers and broccoli,2006,Survey
586,Cambodia,NaN,Cauliflowers and broccoli,2006,Survey
587,Cambodia,NaN,Cauliflowers and broccoli,2006,Survey
588,Cambodia,NaN,Cucumbers and gherkins,2006,Survey
589,Cambodia,NaN,Cucumbers and gherkins,2006,Survey
590,Cambodia,NaN,Cucumbers and gherkins,2006,Survey
591,Cambodia,NaN,Cucumbers and gherkins,2006,Survey

#### **Reviewing Methods Based on Study Context**

In [292]:
method_context_columns = [
    col for col in [
        "method_data_collection",
        "country",
        "commodity",
        "activity",
        "food_supply_stage",
        "year"
    ]
    if col in df_region.columns
]

method_context_summary = (
    df_region
    .groupby(
        method_context_columns,
        dropna=False
    )
    .size()
    .reset_index(name="records")
    .sort_values("records", ascending=False)
)

display(method_context_summary.head(100))

,method_data_collection,country,commodity,activity,food_supply_stage,year,records
26984,Survey,Bangladesh,Rice,Storage,Storage,2009,72
514,Controlled Experiment,Zimbabwe,"Cow peas, dry",Storage,Storage,2018,70
28439,Survey,Kenya,Maize (corn),Storage,Storage,2016,49
27123,Survey,China,Rice,Storage,Storage,2015,46
422,Controlled Experiment,Ethiopia,Maize (corn),Storage,Storage,2019,42
...,...,...,...,...,...,...,...
5086,Literature Review,Ethiopia,Mixed grain,NaN,Post-harvest,2014,6
28397,Survey,Indonesia,Rice,Drying,Farm,2012,6
502,Controlled Experiment,South Africa,Pears,Storage,Households,2018,6
26968,Survey,Bangladesh,Potatoes,Wholesale,Wholesale,2009,6
28545,Survey,Nigeria,Rice,NaN,Transport,2014,6

### **Check on refrence , url and notes**

In [293]:
from urllib.parse import urlparse

# ==================================================
# 1. Prepare temporary cleaned text for inspection
# ==================================================

columns_to_check = ["reference", "url", "notes"]

for col in columns_to_check:
    if col not in df_region.columns:
        raise KeyError(f"Column '{col}' does not exist in df_region.")

text_data = {}

for col in columns_to_check:
    text_data[col] = df_region[col].astype("string").str.strip()


# ==================================================
# 2. Missing values and blank strings
# ==================================================

missing_results = {}

for col in columns_to_check:
    missing_mask = (
        text_data[col].isna()
        | text_data[col].eq("").fillna(False)
    )

    missing_results[col] = df_region.loc[missing_mask].copy()

    print(f"\n{col}: {missing_mask.sum()} missing or blank values")
    display(missing_results[col].head(10))


# ==================================================
# 3. Exact duplicates in each column
# ==================================================

duplicate_results = {}

for col in columns_to_check:
    normalized = text_data[col].str.casefold()

    duplicate_mask = (
        normalized.notna()
        & normalized.ne("")
        & normalized.duplicated(keep=False)
    )

    duplicate_results[col] = df_region.loc[
        duplicate_mask
    ].copy()

    print(f"\n{col}: duplicate records")
    display(
        duplicate_results[col]
        .sort_values(col, na_position="last")
        .head(30)
    )


# ==================================================
# 4. Reference formatting variants
# ==================================================

reference_check = pd.DataFrame({
    "original_reference": df_region["reference"],
    "normalized_reference": (
        text_data["reference"]
        .str.casefold()
        .str.replace(r"\s+", " ", regex=True)
    )
})

reference_variants = (
    reference_check
    .dropna(subset=["normalized_reference"])
    .query("normalized_reference != ''")
    .groupby("normalized_reference")
    .agg(
        original_forms=(
            "original_reference",
            lambda s: sorted(s.dropna().unique().tolist())
        ),
        records=("original_reference", "size")
    )
    .reset_index()
)

reference_format_review = reference_variants[
    reference_variants["original_forms"].apply(len) > 1
].copy()

print("\nReference formatting variants:")
display(reference_format_review)


# ==================================================
# 5. URL validation candidates
# ==================================================

def check_url(value):
    if pd.isna(value) or not str(value).strip():
        return "Missing"

    value = str(value)

    # Detect leading/trailing whitespace in original value
    if value != value.strip():
        return "Whitespace around URL"

    # URLs should not contain embedded whitespace
    if re.search(r"\s", value):
        return "Whitespace inside URL"

    try:
        parsed = urlparse(value)

        if parsed.scheme not in ("http", "https"):
            return "Invalid or unsupported scheme"

        if not parsed.hostname:
            return "Missing hostname"

        if "." not in parsed.hostname and parsed.hostname != "localhost":
            return "Suspicious hostname"

        return "Format looks valid"

    except ValueError:
        return "Parsing error"


url_original = df_region["url"].astype("string")

url_validation = pd.DataFrame({
    "original_url": df_region["url"],
    "url_check": url_original.map(check_url)
})

url_review_mask = url_validation["url_check"].ne("Format looks valid")

url_review = df_region.loc[url_review_mask].copy()
url_review["url_check"] = url_validation.loc[
    url_review_mask, "url_check"
]

print("\nURL validation review:")
display(url_review.head(50))


# URLs repeated exactly after trimming whitespace
url_normalized = text_data["url"]

duplicate_url_mask = (
    url_normalized.notna()
    & url_normalized.ne("")
    & url_normalized.duplicated(keep=False)
)

duplicate_urls = df_region.loc[duplicate_url_mask].copy()

print("\nDuplicate URLs:")
display(duplicate_urls.head(50))


# ==================================================
# 6. Possible encoding problems in notes
# ==================================================

notes_text = text_data["notes"]

encoding_pattern = (
    r"Ã.|Â.|â€|â€™|â€œ|â€\x9d|"
    r"ï¿½|�"
)

encoding_mask = notes_text.str.contains(
    encoding_pattern,
    case=False,
    na=False,
    regex=True
)

possible_encoding_issues = df_region.loc[
    encoding_mask,
    ["notes"]
].copy()

print("\nPossible encoding issues in notes:")
display(possible_encoding_issues.head(50))


# ==================================================
# 7. Notes that may contain structured information
# ==================================================

# Search for years, URLs, email addresses, and common labels.
# These are review candidates, not confirmed data-quality errors.

structured_info_pattern = (
    r"\b(?:19|20)\d{2}\b"             # Years
    r"|https?://"                     # URLs
    r"|\b[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}\b"  # Emails
    r"|\bcountry\s*:"
    r"|\bcommodity\s*:"
    r"|\bregion\s*:"
    r"|\bmethod\s*:"
)

structured_notes_mask = notes_text.str.contains(
    structured_info_pattern,
    case=False,
    na=False,
    regex=True
)

structured_notes_candidates = df_region.loc[
    structured_notes_mask,
    ["country", "commodity", "year", "notes"]
].copy()

# Keep only columns that actually exist
structured_notes_candidates = structured_notes_candidates[
    [c for c in structured_notes_candidates.columns
     if c in df_region.columns]
]

print("\nNotes containing possible structured information:")
display(structured_notes_candidates.head(50))


# ==================================================
# 8. Summary of checks
# ==================================================

quality_summary = pd.DataFrame({
    "column": columns_to_check,
    "missing_or_blank": [
        len(missing_results[col]) for col in columns_to_check
    ],
    "duplicate_records": [
        len(duplicate_results[col]) for col in columns_to_check
    ]
})

display(quality_summary)

reference: 73 missing or blank values

,m49_code,country,region,cpc_code,commodity,year,loss_percentage,loss_percentage_original,loss_quantity,activity,food_supply_stage,treatment,cause_of_loss,sample_size,method_data_collection,reference,url,notes,_region_normalized,_country_normalized
2220,170,Colombia,NaN,01317,Papayas,2016,3.00,3,NaN,NaN,Retail,NaN,NaN,NaN,No Data Collection Specified,NaN,NaN,NaN,NaN,colombia
2221,170,Colombia,NaN,01317,Papayas,2016,3.10,3.1,NaN,NaN,Storage,NaN,Conditioning,NaN,No Data Collection Specified,NaN,NaN,NaN,NaN,colombia
2222,170,Colombia,NaN,01317,Papayas,2016,17.67,17.67,NaN,NaN,Harvest,NaN,NaN,NaN,No Data Collection Specified,NaN,NaN,NaN,NaN,colombia
3577,218,Ecuador,NaN,0112,Maize (corn),2013,20.00,10.0-30,NaN,NaN,NaN,NaN,NaN,NaN,Expert Opinion,NaN,http://www.forumdofuturo.com.br/site/wp-conten...,url not found,NaN,ecuador
3578,218,Ecuador,NaN,01194,Quinoa,2013,5.00,5,NaN,NaN,Pre-harvest,NaN,Rain Pre-Harvest Causing Germination On The Stalk,NaN,Expert Opinion,NaN,http://www.forumdofuturo.com.br/site/wp-conten...,url not found,NaN,ecuador
3579,218,Ecuador,NaN,01701,"Beans, dry",2013,10.00,10,NaN,NaN,Farm,NaN,Threshing,NaN,Expert Opinion,NaN,http://www.forumdofuturo.com.br/site/wp-conten...,url not found,NaN,ecuador
3580,218,Ecuador,NaN,01701,"Beans, dry",2013,10.00,10,NaN,NaN,Storage,NaN,Rodents,NaN,Expert Opinion,NaN,http://www.forumdofuturo.com.br/site/wp-conten...,url not found,NaN,ecuador
3676,222,El Salvador,NaN,0112,Maize (corn),2013,8.00,8,NaN,NaN,Farm,NaN,Small-Scale Corn And Bean Farmers Account For ...,NaN,Expert Opinion,NaN,http://www.forumdofuturo.com.br/site/wp-conten...,url not found,NaN,el salvador
3677,222,El Salvador,NaN,0113,Rice,2013,6.00,6,NaN,NaN,Farm,NaN,Small-Scale Corn And Bean Farmers Account For ...,NaN,NaN,NaN,http://www.forumdofuturo.com.br/site/wp-conten...,NaN,NaN,el salvador
3678,222,El Salvador,NaN,0114,Sorghum,2013,6.00,6,NaN,NaN,Farm,NaN,Small-Scale Corn And Bean Farmers Account For ...,NaN,NaN,NaN,http://www.forumdofuturo.com.br/site/wp-conten...,NaN,NaN,el salvador

url: 9342 missing or blank values

,m49_code,country,region,cpc_code,commodity,year,loss_percentage,loss_percentage_original,loss_quantity,activity,food_supply_stage,treatment,cause_of_loss,sample_size,method_data_collection,reference,url,notes,_region_normalized,_country_normalized
0,1,World,NaN,0111,Wheat,2022,1.0,1%,NaN,Processing,Processing,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived product is wheat flour,NaN,world
1,1,World,NaN,0112,Maize (corn),2022,0.5,0.5%,NaN,Processing,Processing,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived product is maize flour.,NaN,world
2,1,World,NaN,0112,Maize (corn),2022,2.0,2%,NaN,Processing,Processing,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived product is Maize (corn) grits.,NaN,world
3,1,World,NaN,0112,Maize (corn),2022,2.0,2%,NaN,Processing,Processing,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived product is Maize (corn) grits flaked.,NaN,world
4,1,World,NaN,0112,Maize (corn),2022,0.1,0.1%,NaN,Processing,Processing,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived product is corn starch.,NaN,world
5,1,World,NaN,0112,Maize (corn),2022,2.0,2%,NaN,Processing,Processing,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived product is undenaturated ethyl alcohol.,NaN,world
6,1,World,NaN,0113,Rice,2022,2.5,2.5%,NaN,Processing,Processing,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived product is milled rice.,NaN,world
7,1,World,NaN,0114,Sorghum,2022,0.5,0.5%,NaN,Processing,Processing,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived product is flour of sorghum.,NaN,world
8,1,World,NaN,0115,Barley,2022,12.0,12%,NaN,Processing,Processing,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived product is barley malt,NaN,world
9,1,World,NaN,0115,Barley,2022,2.0,2%,NaN,Processing,Processing,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived product is pot barley,NaN,world

notes: 29931 missing or blank values

,m49_code,country,region,cpc_code,commodity,year,loss_percentage,loss_percentage_original,loss_quantity,activity,food_supply_stage,treatment,cause_of_loss,sample_size,method_data_collection,reference,url,notes,_region_normalized,_country_normalized
29,104,Myanmar,NaN,23161.02,"Rice, milled",2015,5.88,5.88%,44.09kgs,Storage,Storage,"30 days storage, no trapping",Rodents,NaN,Controlled Experiment,Steven R. Belmain; Nyo Me Htwe; Nazira Q. Kama...,NaN,NaN,NaN,myanmar
30,104,Myanmar,NaN,23161.02,"Rice, milled",2015,11.77,11.77%,88.18kgs,Storage,Storage,"60 days storage, no trapping",Rodents,NaN,Controlled Experiment,Steven R. Belmain; Nyo Me Htwe; Nazira Q. Kama...,NaN,NaN,NaN,myanmar
31,104,Myanmar,NaN,23161.02,"Rice, milled",2015,17.65,17.65%,132.27kgs,Storage,Storage,"90 days storage, no trapping",Rodents,NaN,Controlled Experiment,Steven R. Belmain; Nyo Me Htwe; Nazira Q. Kama...,NaN,NaN,NaN,myanmar
32,104,Myanmar,NaN,23161.02,"Rice, milled",2015,3.57,3.57%,52.24kgs,Storage,Storage,"60 days storage, with trapping",Rodents,NaN,Controlled Experiment,Steven R. Belmain; Nyo Me Htwe; Nazira Q. Kama...,NaN,NaN,NaN,myanmar
33,104,Myanmar,NaN,23161.02,"Rice, milled",2015,5.35,5.35%,78.36kgs,Storage,Storage,"90 days storage, with trapping",Rodents,NaN,Controlled Experiment,Steven R. Belmain; Nyo Me Htwe; Nazira Q. Kama...,NaN,NaN,NaN,myanmar
34,104,Myanmar,NaN,23161.02,"Rice, milled",2015,1.78,1.78%,26.12kgs,Storage,Storage,"30 days storage, with trapping",Rodents,NaN,Controlled Experiment,Steven R. Belmain; Nyo Me Htwe; Nazira Q. Kama...,NaN,NaN,NaN,myanmar
35,104,Myanmar,NaN,0142,"Groundnuts, excluding shelled",2009,5.22,5.22%,68100,NaN,Whole supply chain,NaN,NaN,NaN,FAO's annual Agriculture Production Questionna...,FAO Sources,NaN,NaN,NaN,myanmar
36,104,Myanmar,NaN,0142,"Groundnuts, excluding shelled",2008,5.43,5.43%,65240,NaN,Whole supply chain,NaN,NaN,NaN,FAO's annual Agriculture Production Questionna...,FAO Sources,NaN,NaN,NaN,myanmar
37,104,Myanmar,NaN,0142,"Groundnuts, excluding shelled",2007,5.61,5.61%,61080,NaN,Whole supply chain,NaN,NaN,NaN,FAO's annual Agriculture Production Questionna...,FAO Sources,NaN,NaN,NaN,myanmar
38,104,Myanmar,NaN,0142,"Groundnuts, excluding shelled",2006,5.40,5.4%,55270,NaN,Whole supply chain,NaN,NaN,NaN,FAO's annual Agriculture Production Questionna...,FAO Sources,NaN,NaN,NaN,myanmar

reference: duplicate records

,m49_code,country,region,cpc_code,commodity,year,loss_percentage,loss_percentage_original,loss_quantity,activity,food_supply_stage,treatment,cause_of_loss,sample_size,method_data_collection,reference,url,notes,_region_normalized,_country_normalized
4200,231,Ethiopia,Amhara region,0112,Maize (corn),2014,9.10,2.3-15.9%,NaN,Storage,Storage,NaN,NaN,NaN,Literature Review,"(), (2014), Analysis Of Post-Harvest Loss Esti...",NaN,"Source : SSEAD consultancy, 1997",amhara region,ethiopia
4196,231,Ethiopia,Western Ethiopia,0112,Maize (corn),2014,7.95,2.1-13.8%,NaN,Storage,Storage,NaN,NaN,NaN,Literature Review,"(), (2014), Analysis Of Post-Harvest Loss Esti...",NaN,"Source : Abraham, 1993",western ethiopia,ethiopia
4197,231,Ethiopia,Western Ethiopia,0112,Maize (corn),2014,9.05,0.2-17.9%,NaN,Storage,Storage,NaN,NaN,NaN,Literature Review,"(), (2014), Analysis Of Post-Harvest Loss Esti...",NaN,"Source : Abraham, et. al, 1993",western ethiopia,ethiopia
4198,231,Ethiopia,Southern Ethiopia,0112,Maize (corn),2014,15.00,12-18%,NaN,Storage,Storage,NaN,NaN,NaN,Literature Review,"(), (2014), Analysis Of Post-Harvest Loss Esti...",NaN,"Source : Emana Getu, 1993",southern ethiopia,ethiopia
4199,231,Ethiopia,Western Ethiopia,0112,Maize (corn),2014,17.50,5-30%,NaN,Storage,Storage,NaN,NaN,NaN,Literature Review,"(), (2014), Analysis Of Post-Harvest Loss Esti...",NaN,"Source : Abraham, 1997",western ethiopia,ethiopia
4206,231,Ethiopia,Hararghe,0114,Sorghum,2014,28.50,2-55%,NaN,Storage,Storage,Pit Storage,NaN,NaN,Literature Review,"(), (2014), Analysis Of Post-Harvest Loss Esti...",NaN,"Source : Boxall R.A., 1974",hararghe,ethiopia
4201,231,Ethiopia,NaN,0112,Maize (corn),2014,5.64,5.64%,NaN,Storage,Storage,NaN,NaN,NaN,Literature Review,"(), (2014), Analysis Of Post-Harvest Loss Esti...",NaN,"Source : Abraham Tadesse, 2003 Area Coverage ...",NaN,ethiopia
4202,231,Ethiopia,NaN,0112,Maize (corn),2014,15.00,15%,NaN,Storage,Storage,NaN,NaN,NaN,Literature Review,"(), (2014), Analysis Of Post-Harvest Loss Esti...",NaN,"Source : McFarlane, 1969 Area Coverage : Nati...",NaN,ethiopia
4203,231,Ethiopia,Western Ethiopia,0112,Maize (corn),2014,6.90,6.3 - 7.5%,NaN,Storage,Storage,NaN,NaN,NaN,Literature Review,"(), (2014), Analysis Of Post-Harvest Loss Esti...",NaN,"Source : Abraham, 1991",western ethiopia,ethiopia
4204,231,Ethiopia,NaN,0113,Rice,2014,50.00,50%,NaN,Storage,Storage,NaN,NaN,NaN,Literature Review,"(), (2014), Analysis Of Post-Harvest Loss Esti...",NaN,"Source : MoARDb, 2010 Area Coverage : National",NaN,ethiopia
4207,231,Ethiopia,NaN,0115,Barley,2014,2.00,2%,NaN,Storage,Storage,NaN,NaN,NaN,Literature Review,"(), (2014), Analysis Of Post-Harvest Loss Esti...",NaN,"Source : McFarlane, 1969 Area Coverage : Nati...",NaN,ethiopia
4195,231,Ethiopia,NaN,0111,Wheat,2014,5.00,5%,NaN,Storage,Storage,NaN,NaN,NaN,Literature Review,"(), (2014), Analysis Of Post-Harvest Loss Esti...",NaN,"Source : McFarlane, 1969 Area Coverage : Nati...",NaN,ethiopia
4205,231,Ethiopia,NaN,0114,Sorghum,2014,5.00,5%,NaN,Storage,Storage,NaN,NaN,NaN,Literature Review,"(), (2014), Analysis Of Post-Harvest Loss Esti...",NaN,"Source : McFarlane, 1969 Area Coverage : Nati...",NaN,ethiopia
4226,231,Ethiopia,Yerer and Kereyu,01241.90,"Other beans, green",2014,14.40,14.4%,NaN,Storage,Storage,NaN,NaN,NaN,Literature Review,"(), (2014), Analysis Of Post-Harvest Loss Esti...",NaN,"Source : Tadesse G/Medhin, 1987 Faba bean",yerer and kereyu,ethiopia
4227,231,Ethiopia,Amhara Region,01241.90,"Other beans, green",2014,1.95,1.95%,NaN,Storage,Storage,For grains stored from 6 to 9 months,NaN,NaN,Literature Review,"(), (2014), Analysis Of Post-Harvest Loss Esti...",NaN,"Source : Worku Teka, 2000 Faba bean",amhara region,ethiopia
4228,231,Ethiopia,Amhara Region,01242,"Peas, green",2014,12.10,12.10%,NaN,Storage,Storage,For grains stored from 6 to 9 months,NaN,NaN,Literature Review,"(), (2014), Analysis Of Post-Harvest Loss Esti...",NaN,"Source : Worku Teka, 2000",amhara region,ethiopia
4229,231,Ethiopia,Yerer and Kereyu,01703,"Chick peas, dry",2014,8.20,8.2%,NaN,Storage,Storage,NaN,NaN,NaN,Literature Review,"(), (2014), Analysis Of Post-Harvest Loss Esti...",NaN,"Source : Teshome Lemma, 1990",yerer and kereyu,ethiopia
4230,231,Ethiopia,Amhara Region,01703,"Chick peas, dry",2014,6.37,6.37%,NaN,Storage,Storage,For grains stored from 6 to 9 months,NaN,NaN,Literature Review,"(), (2014), Analysis Of Post-Harvest Loss Esti...",NaN,"Source : Worku Teka, 2000",amhara region,ethiopia
4208,231,Ethiopia,Arsi,01199.02,Mixed grain,2014,10.00,10%,NaN,Threshing,Farm,NaN,Improper threshing (animal trampling),NaN,Literature Review,"(), (2017), Analysis Of Post-Harvest Loss Esti...",NaN,"Source: CADU, 1969",arsi,ethiopia
4211,231,Ethiopia,NaN,01199.02,Mixed grain,2014,15.00,10-20%,NaN,NaN,Post-harvest,NaN,NaN,NaN,Literature Review,"(), (2017), Analysis Of Post-Harvest Loss Esti...",NaN,"Source: FAO, 1977 Area coverage - National",NaN,ethiopia
4212,231,Ethiopia,NaN,01199.02,Mixed grain,2014,13.20,13.2%,NaN,Storage,Storage,NaN,NaN,NaN,Literature Review,"(), (2017), Analysis Of Post-Harvest Loss Esti...",NaN,"Source: Kashi, 1985 Area coverage - National",NaN,ethiopia
4213,231,Ethiopia,NaN,01199.02,Mixed grain,2014,20.00,20%,NaN,NaN,Post-harvest,NaN,NaN,NaN,Literature Review,"(), (2017), Analysis Of Post-Harvest Loss Esti...",NaN,"Source: Dereje Ashagari, 2000 Area coverage -...",NaN,ethiopia
4214,231,Ethiopia,NaN,01199.02,Mixed grain,2014,8.50,7-10%,NaN,NaN,Harvest,NaN,Improper harvesting,NaN,Literature Review,"(), (2017), Analysis Of Post-Harvest Loss Esti...",NaN,"Source: Dereje Ashagari, 2000 Area coverage -...",NaN,ethiopia
4215,231,Ethiopia,NaN,01199.02,Mixed grain,2014,4.00,3-5%,NaN,"Harvesting, Stacking, Threshing",Farm,NaN,Improper harvesting,NaN,Literature Review,"(), (2017), Analysis Of Post-Harvest Loss Esti...",NaN,"Source: Kasahun Bedada, 2000 Area coverage - ...",NaN,ethiopia
4210,231,Ethiopia,NaN,01199.02,Mixed grain,2014,5.50,5.5%,NaN,Storage,Storage,NaN,NaN,NaN,Literature Review,"(), (2017), Analysis Of Post-Harvest Loss Esti...",NaN,"Source: McFarlane, 1969 Area coverage - National",NaN,ethiopia
4209,231,Ethiopia,NaN,01199.02,Mixed grain,2014,3.50,3-4%,NaN,NaN,Farm,NaN,NaN,NaN,Literature Review,"(), (2017), Analysis Of Post-Harvest Loss Esti...",NaN,"Source: McFarlane, 1969 Area coverage - National",NaN,ethiopia
4222,231,Ethiopia,NaN,01199.02,Mixed grain,2014,15.50,10-21%,NaN,Storage,Storage,NaN,NaN,NaN,Literature Review,"(), (2017), Analysis Of Post-Harvest Loss Esti...",NaN,"Source: Abraham Tadesse, 2005 Area coverage: ...",NaN,ethiopia
4216,231,Ethiopia,"Southern Nations, Nationalities, and Peoples R...",01199.02,Mixed grain,2014,10.00,10%,NaN,Harvesting,Harvest,NaN,NaN,NaN,Literature Review,"(), (2017), Analysis Of Post-Harvest Loss Esti...",NaN,"Source: Duressa Chibsa, 2000","southern nations, nationalities, and peoples r...",ethiopia
4219,231,Ethiopia,"Southern Nations, Nationalities, and Peoples R...",01199.02,Mixed grain,2014,12.50,10-15%,NaN,Threshing,Farm,NaN,NaN,NaN,Literature Review,"(), (2017), Analysis Of Post-Harvest Loss Esti...",NaN,"Source: Duressa Chibsa, 2000","southern nations, nationalities, and peoples r...",ethiopia
4220,231,Ethiopia,"Southern Nations, Nationalities, and Peoples R...",01199.02,Mixed grain,2014,7.50,5-10%,NaN,Transportation,Transport,NaN,NaN,NaN,Literature Review,"(), (2017), Analysis Of Post-Harvest Loss Esti...",NaN,"Source: Duressa Chibsa, 2000","southern nations, nationalities, and peoples r...",ethiopia

url: duplicate records

,m49_code,country,region,cpc_code,commodity,year,loss_percentage,loss_percentage_original,loss_quantity,activity,food_supply_stage,treatment,cause_of_loss,sample_size,method_data_collection,reference,url,notes,_region_normalized,_country_normalized
7628,288,Ghana,NaN,0113,Rice,2009,2.300,0.53-4.07,NaN,Threshing,Farm,NaN,Bag Beating/Bambam The results of the surve...,5,Case Study,"Appiah F; Guisse R; Dartey P. K. A, (2011), Po...",http://academicjournals.org/article/article137...,NaN,NaN,ghana
7627,288,Ghana,Nerica 1 & Nerica 2,0113,Rice,2009,2.190,1.13-3.25,NaN,NaN,Harvest,NaN,Pancle/ Sickle Harvesting two varieties of rice,58 Table 1. Harvesting losses in of Nerica 1 ...,Controlled Experiment,"Appiah F; Guisse R; Dartey P. K. A, (2011), Po...",http://academicjournals.org/article/article137...,NaN,nerica 1 & nerica 2,ghana
7626,288,Ghana,NaN,0113,Rice,2009,3.940,0.92-6.96,NaN,Threshing,Farm,NaN,Bag Beating/Bambam,58 Table 2. Threshing losses of Nerica 1 an...,Controlled Experiment,"Appiah F; Guisse R; Dartey P. K. A, (2011), Po...",http://academicjournals.org/article/article137...,NaN,NaN,ghana
7625,288,Ghana,NaN,0113,Rice,2009,6.275,3.29-9.26,NaN,NaN,Harvest,Different harvest techniques,The reduction in the weight could also be due ...,58 Table 4. Weight losses during storage lo...,Controlled Experiment,"Appiah F; Guisse R; Dartey P. K. A, (2011), Po...",http://academicjournals.org/article/article137...,NaN,NaN,ghana
7624,288,Ghana,NaN,0113,Rice,2009,7.540,3.03-12.05%,NaN,NaN,Harvest,NaN,Pancle/ Sickle Harvesting two varieties of ric...,5 Table 3. Harvesting and threshing losses at...,Case Study,"Appiah F; Guisse R; Dartey P. K. A, (2011), Po...",http://academicjournals.org/article/article137...,NaN,NaN,ghana
7623,288,Ghana,Ejisu Juabeng,0113,Rice,2009,4.295,2.45 - 6.14%,NaN,Threshing,Farm,NaN,Pancle/ Sickle Harvesting two varieties of ric...,5 Table 3. Harvesting and threshing losses at...,Case Study,"Appiah F; Guisse R; Dartey P. K. A, (2011), Po...",http://academicjournals.org/article/article137...,NaN,ejisu juabeng,ghana
2207,156,China,"Daxing, Tongxian, and Yanqing counties, which ...",01253.01,"Onions and shallots, green",2001,5.000,5,NaN,NaN,Transport,NaN,NaN,NaN,No Data Collection Specified,Tim O’Hare; John Bagshaw; Wu Li; ; Greg Johnso...,http://aciar.gov.au/files/node/2249/p105chapte...,NaN,"daxing, tongxian, and yanqing counties, which ...",china
2189,156,China,Fujian Province,01212,Cabbages,2001,9.300,9.3,NaN,"Collection, Marketing",Trader,NaN,mechanical and disease damage loss (peeled off),NaN,Expert Opinion,Tim O’Hare; John Bagshaw; Wu Li; ; Greg Johnso...,http://aciar.gov.au/files/node/2249/p105chapte...,NaN,fujian province,china
2188,156,China,Cixi county,01212,Cabbages,2001,2.750,.8-4.7,NaN,NaN,Retail,NaN,mechanical and disease damage loss (peeled off),NaN,Expert Opinion,Tim O’Hare; John Bagshaw; Wu Li; ; Greg Johnso...,http://aciar.gov.au/files/node/2249/p105chapte...,NaN,cixi county,china
2187,156,China,Jiangan district,01212,Cabbages,2001,5.700,5.7,NaN,"Harvesting, Sorting",Harvest,NaN,NaN,NaN,Expert Opinion,Tim O’Hare; John Bagshaw; Wu Li; ; Greg Johnso...,http://aciar.gov.au/files/node/2249/p105chapte...,NaN,jiangan district,china
2186,156,China,Jiangan district,01212,Cabbages,2001,7.700,7.7,NaN,NaN,Harvest,NaN,NaN,NaN,Expert Opinion,Tim O’Hare; John Bagshaw; Wu Li; ; Greg Johnso...,http://aciar.gov.au/files/node/2249/p105chapte...,NaN,jiangan district,china
2185,156,China,Jiangan district,01212,Cabbages,2001,5.750,3.2-8.3,NaN,NaN,Retail,NaN,mechanical damage.leaf yellowing. sound leaves...,NaN,Expert Opinion,Tim O’Hare; John Bagshaw; Wu Li; ; Greg Johnso...,http://aciar.gov.au/files/node/2249/p105chapte...,NaN,jiangan district,china
2184,156,China,Jiangan district,01212,Cabbages,2001,4.900,2.4-7.4,NaN,NaN,Retail,NaN,mechanical damage.leaf yellowing. sound leaves...,NaN,Expert Opinion,Tim O’Hare; John Bagshaw; Wu Li; ; Greg Johnso...,http://aciar.gov.au/files/node/2249/p105chapte...,NaN,jiangan district,china
2183,156,China,Fujian Province,01212,Cabbages,2001,22.200,22.2,NaN,NaN,Wholesale,NaN,Mechanical Damage,NaN,No Data Collection Specified,Tim O’Hare; John Bagshaw; Wu Li; ; Greg Johnso...,http://aciar.gov.au/files/node/2249/p105chapte...,NaN,fujian province,china
2182,156,China,"Daxing, Tongxian, and Yanqing",01212,Cabbages,2001,25.000,20-30,NaN,NaN,Storage,NaN,Energy consumption and abscission,NaN,Expert Opinion,Tim O’Hare; John Bagshaw; Wu Li; ; Greg Johnso...,http://aciar.gov.au/files/node/2249/p105chapte...,NaN,"daxing, tongxian, and yanqing",china
2181,156,China,Fujian Province,01212,Cabbages,2001,6.000,6,NaN,"Harvesting, Sorting",Harvest,NaN,NaN,NaN,Expert Opinion,Tim O’Hare; John Bagshaw; Wu Li; ; Greg Johnso...,http://aciar.gov.au/files/node/2249/p105chapte...,NaN,fujian province,china
2177,156,China,Shandong Province,01212,Cabbages,2001,32.700,32.7,NaN,NaN,Storage,NaN,Disease And Rot,NaN,No Data Collection Specified,Tim O’Hare; John Bagshaw; Wu Li; ; Greg Johnso...,http://aciar.gov.au/files/node/2249/p105chapte...,NaN,shandong province,china
2179,156,China,"Daxing, Tongxian, and Yanqing counties, which ...",01212,Cabbages,2001,2.500,2.0-3,NaN,NaN,Retail,NaN,Market,NaN,No Data Collection Specified,Tim O’Hare; John Bagshaw; Wu Li; ; Greg Johnso...,http://aciar.gov.au/files/node/2249/p105chapte...,NaN,"daxing, tongxian, and yanqing counties, which ...",china
2178,156,China,"Daxing, Tongxian, and Yanqing",01212,Cabbages,2001,47.500,45-50,NaN,Collection,Trader,Trimming,Trimming &collection,NaN,Expert Opinion,Tim O’Hare; John Bagshaw; Wu Li; ; Greg Johnso...,http://aciar.gov.au/files/node/2249/p105chapte...,NaN,"daxing, tongxian, and yanqing",china
2190,156,China,Cixi county,01212,Cabbages,2001,15.300,15.3,NaN,NaN,Wholesale,NaN,mechanical and disease damage loss (peeled off),NaN,Expert Opinion,Tim O’Hare; John Bagshaw; Wu Li; ; Greg Johnso...,http://aciar.gov.au/files/node/2249/p105chapte...,NaN,cixi county,china
2176,156,China,Shandong Province,01212,Cabbages,2001,12.300,12.3,NaN,NaN,Wholesale,NaN,NaN,NaN,No Data Collection Specified,Tim O’Hare; John Bagshaw; Wu Li; ; Greg Johnso...,http://aciar.gov.au/files/node/2249/p105chapte...,NaN,shandong province,china
2175,156,China,Xiasha Town,01212,Cabbages,2001,5.530,5.53,NaN,NaN,Retail,NaN,"(Md=4.7%, W=0.8%)",NaN,No Data Collection Specified,Tim O’Hare; John Bagshaw; Wu Li; ; Greg Johnso...,http://aciar.gov.au/files/node/2249/p105chapte...,NaN,xiasha town,china
2174,156,China,Cixi county,01212,Cabbages,2001,12.500,12.5,NaN,"Collection, Marketing",Wholesale,NaN,mechanical and disease damage loss (peeled off),NaN,Expert Opinion,Tim O’Hare; John Bagshaw; Wu Li; ; Greg Johnso...,http://aciar.gov.au/files/node/2249/p105chapte...,NaN,cixi county,china
2173,156,China,"Daxing, Tongxian, and Yanqing",01212,Cabbages,2001,2.500,2.0-3,NaN,NaN,Farm,NaN,Spreading out in sunlight,NaN,Expert Opinion,Tim O’Hare; John Bagshaw; Wu Li; ; Greg Johnso...,http://aciar.gov.au/files/node/2249/p105chapte...,NaN,"daxing, tongxian, and yanqing",china
2171,156,China,"Daxing, Tongxian, and Yanqing",01212,Cabbages,2001,2.500,2.0-3,NaN,NaN,Wholesale,NaN,NaN,NaN,Expert Opinion,Tim O’Hare; John Bagshaw; Wu Li; ; Greg Johnso...,http://aciar.gov.au/files/node/2249/p105chapte...,NaN,"daxing, tongxian, and yanqing",china
2170,156,China,"Daxing, Tongxian, and Yanqing",01212,Cabbages,2001,5.000,5,NaN,"Marketing, Wholesale",Wholesale,NaN,NaN,NaN,Expert Opinion,Tim O’Hare; John Bagshaw; Wu Li; ; Greg Johnso...,http://aciar.gov.au/files/node/2249/p105chapte...,NaN,"daxing, tongxian, and yanqing",china
2180,156,China,Cixi county,01212,Cabbages,2001,5.700,5.7,NaN,"Harvesting, Sorting",Harvest,NaN,NaN,NaN,Expert Opinion,Tim O’Hare; John Bagshaw; Wu Li; ; Greg Johnso...,http://aciar.gov.au/files/node/2249/p105chapte...,NaN,cixi county,china
2191,156,China,Xiasha town,01212,Cabbages,2001,4.900,2.4-7.4,NaN,NaN,Retail,NaN,mechanical damage.leaf yellowing. sound leaves...,NaN,Expert Opinion,Tim O’Hare; John Bagshaw; Wu Li; ; Greg Johnso...,http://aciar.gov.au/files/node/2249/p105chapte...,NaN,xiasha town,china
2194,156,China,"Daxing, Tongxian, and Yanqing",01212,Cabbages,2001,3.500,3.0-4,NaN,NaN,Transport,NaN,NaN,NaN,Expert Opinion,Tim O’Hare; John Bagshaw; Wu Li; ; Greg Johnso...,http://aciar.gov.au/files/node/2249/p105chapte...,NaN,"daxing, tongxian, and yanqing",china
2193,156,China,"Daxing, Tongxian, and Yanqing counties, which ...",01212,Cabbages,2001,1.500,1.0-2,NaN,Farm,Farm,Trimming,Trimming,NaN,Expert Opinion,Tim O’Hare; John Bagshaw; Wu Li; ; Greg Johnso...,http://aciar.gov.au/files/node/2249/p105chapte...,NaN,"daxing, tongxian, and yanqing counties, which ...",china

notes: duplicate records

,m49_code,country,region,cpc_code,commodity,year,loss_percentage,loss_percentage_original,loss_quantity,activity,food_supply_stage,treatment,cause_of_loss,sample_size,method_data_collection,reference,url,notes,_region_normalized,_country_normalized
27490,834,United Republic of Tanzania,Dodoma and Manyara,0112,Maize (corn),2013,22.00,22%,NaN,NaN,Farm,NaN,NaN,NaN,Literature Review,Adebayo B. Abassa; Gabriel Ndunguru; Peter Mam...,http://biblio.iita.org/documents/U14ArtAbassPo...,. Hodges (2012) estimated post-harvest loss of...,dodoma and manyara,united republic of tanzania
3038,204,Benin,NaN,0112,Maize (corn),2013,27.00,27%,NaN,NaN,Farm,NaN,NaN,NaN,Literature Review,Adebayo B. Abassa; Gabriel Ndunguru; Peter Mam...,http://biblio.iita.org/documents/U14ArtAbassPo...,. Hodges (2012) estimated post-harvest loss of...,NaN,benin
2124,156,China,NaN,21111.01,"Meat of cattle with the bone, fresh or chilled",2013,1.10,1.1%,0 tons,NaN,Processing,NaN,decentralized agricultural system in China ce...,NaN,Literature Review,"Gang Liu, (2013), Food Losses And Food Waste I...",NaN,"5.7-8.6 % for grain , 2.5- 3.7 % for meats , a...",NaN,china
2125,156,China,NaN,21111.01,"Meat of cattle with the bone, fresh or chilled",2013,3.10,2.5- 3.7%,0 tons,NaN,Storage,NaN,decentralized agricultural system in China ce...,NaN,Literature Review,"Gang Liu, (2013), Food Losses And Food Waste I...",NaN,"5.7-8.6 % for grain , 2.5- 3.7 % for meats , a...",NaN,china
2126,156,China,NaN,21111.01,"Meat of cattle with the bone, fresh or chilled",2013,1.75,1.4-2.1%,0 tons,"Handling, Harvesting",Farm,NaN,decentralized agricultural system in China ce...,NaN,Literature Review,"Gang Liu, (2013), Food Losses And Food Waste I...",NaN,"5.7-8.6 % for grain , 2.5- 3.7 % for meats , a...",NaN,china
2127,156,China,NaN,21111.01,"Meat of cattle with the bone, fresh or chilled",2013,3.00,3%,0 tons,NaN,Wholesale,NaN,decentralized agricultural system in China ce...,NaN,Literature Review,"Gang Liu, (2013), Food Losses And Food Waste I...",NaN,"5.7-8.6 % for grain , 2.5- 3.7 % for meats , a...",NaN,china
2121,156,China,NaN,0111,Wheat,2013,4.70,4.7%,0 tons,NaN,Storage,NaN,decentralized agricultural system in China ce...,NaN,Literature Review,"Gang Liu, (2013), Food Losses And Food Waste I...",NaN,"5.7-8.6 % for grain , 2.5- 3.7 % for meats , a...",NaN,china
2122,156,China,NaN,0112,Maize (corn),2013,11.00,11%,0 tons,NaN,Storage,NaN,decentralized agricultural system in China ce...,NaN,Literature Review,"Gang Liu, (2013), Food Losses And Food Waste I...",NaN,"5.7-8.6 % for grain , 2.5- 3.7 % for meats , a...",NaN,china
2123,156,China,NaN,0113,Rice,2013,6.50,6.5%,0 tons,NaN,Storage,NaN,decentralized agricultural system in China ce...,NaN,Literature Review,"Gang Liu, (2013), Food Losses And Food Waste I...",NaN,"5.7-8.6 % for grain , 2.5- 3.7 % for meats , a...",NaN,china
19187,586,Pakistan,NaN,0111,Wheat,2013,12.71,12.71%,31.4 kg ha-1,NaN,Harvest,different models of combine during harvest stage,Mirasi et al. (2013) measured grain losses of ...,NaN,Literature Review,Muhammad Sattar; Mueen-u-Din; Mushtaq Ali; Lia...,NaN,"According to a most conservative estimate, abo...",NaN,pakistan
19208,586,Pakistan,NaN,0111,Wheat,2012,40.85,40.85%,2.35 kg/quintal,NaN,Harvest,"combine, reapers, manual estimates",Begum et al. (2012) found 0.51 kg/quintal grai...,NaN,Literature Review,Muhammad Sattar; Mueen-u-Din; Mushtaq Ali; Lia...,NaN,"According to a most conservative estimate, abo...",NaN,pakistan
16044,50,Bangladesh,NaN,0113,Rice,2016,11.71,11.71%,NaN,NaN,Whole supply chain,Boro Rice,NaN,NaN,Literature Review,"Deepak Kumar; Prasanta Kalita, (2017), Reducin...",NaN,Adapted from Bala et al,NaN,bangladesh
16045,50,Bangladesh,NaN,0113,Rice,2016,11.59,11.59%,NaN,NaN,Whole supply chain,Aus Rice,NaN,NaN,Literature Review,"Deepak Kumar; Prasanta Kalita, (2017), Reducin...",NaN,Adapted from Bala et al,NaN,bangladesh
10469,356,India,Karnataka,0112,Maize (corn),2004,0.46,0.46%,NaN,"Farm, Threshing",Farm,NaN,NaN,NaN,Literature Review,"(2022), Assessment Of Losses In Harvesting And...",NaN,Adapted from Basappa et al. (2007),karnataka,india
10470,356,India,Karnataka,0112,Maize (corn),2004,0.18,0.18%,NaN,Harvesting,Harvest,NaN,NaN,NaN,Literature Review,"(2022), Assessment Of Losses In Harvesting And...",NaN,Adapted from Basappa et al. (2007),karnataka,india
17833,524,Nepal,NaN,01251,Carrots and turnips,2019,18.00,18%,NaN,Retailing,Retail,NaN,NaN,NaN,Literature Review,"Alessandro Suardi; Nadia Palmieri, (2022), Agr...",NaN,"Adapted from Bhattarai, D.R.et al 2017",NaN,nepal
17832,524,Nepal,NaN,01251,Carrots and turnips,2019,5.00,5%,NaN,Wholesale,Wholesale,NaN,NaN,NaN,Literature Review,"Alessandro Suardi; Nadia Palmieri, (2022), Agr...",NaN,"Adapted from Bhattarai, D.R.et al 2017",NaN,nepal
17831,524,Nepal,NaN,01251,Carrots and turnips,2019,2.00,2%,NaN,Collection,Collector,NaN,NaN,NaN,Literature Review,"Alessandro Suardi; Nadia Palmieri, (2022), Agr...",NaN,"Adapted from Bhattarai, D.R.et al 2017",NaN,nepal
17830,524,Nepal,NaN,01251,Carrots and turnips,2019,10.00,10%,NaN,Farm,Farm,NaN,NaN,NaN,Literature Review,"Alessandro Suardi; Nadia Palmieri, (2022), Agr...",NaN,"Adapted from Bhattarai, D.R.et al 2017",NaN,nepal
17829,524,Nepal,NaN,01251,Carrots and turnips,2019,35.00,35%,NaN,"Collection, Farm, Marketing, Retailing, Wholesale",Whole supply chain,NaN,NaN,NaN,Literature Review,"Alessandro Suardi; Nadia Palmieri, (2022), Agr...",NaN,"Adapted from Bhattarai, D.R.et al 2017",NaN,nepal
19158,586,Pakistan,NaN,0111,Wheat,2021,4.53,4.53%,NaN,"Cleaning, Farm",Farm,NaN,NaN,NaN,Literature Review,"YA Yigezu, (2021), Food Losses And Wastage Alo...",NaN,"Adapted from Bukhari, S.J et al.1983.",NaN,pakistan
19153,586,Pakistan,NaN,0111,Wheat,2021,3.67,3.67%,NaN,Harvesting,Harvest,Conventional harvesting,NaN,NaN,Literature Review,"YA Yigezu, (2021), Food Losses And Wastage Alo...",NaN,"Adapted from Bukhari, S.J et al.1983.",NaN,pakistan
19154,586,Pakistan,NaN,0111,Wheat,2021,3.98,3.98%,NaN,"Collection, Farm",Farm,Bundling,NaN,NaN,Literature Review,"YA Yigezu, (2021), Food Losses And Wastage Alo...",NaN,"Adapted from Bukhari, S.J et al.1983.",NaN,pakistan
19155,586,Pakistan,NaN,0111,Wheat,2021,0.24,0.24%,NaN,Transportation,Transport,NaN,NaN,NaN,Literature Review,"YA Yigezu, (2021), Food Losses And Wastage Alo...",NaN,"Adapted from Bukhari, S.J et al.1983.",NaN,pakistan
19156,586,Pakistan,NaN,0111,Wheat,2021,1.18,1.18%,NaN,"Farm, Threshing",Farm,NaN,NaN,NaN,Literature Review,"YA Yigezu, (2021), Food Losses And Wastage Alo...",NaN,"Adapted from Bukhari, S.J et al.1983.",NaN,pakistan
19157,586,Pakistan,NaN,0111,Wheat,2021,2.46,2.46%,NaN,"Farm, Winnowing",Farm,NaN,NaN,NaN,Literature Review,"YA Yigezu, (2021), Food Losses And Wastage Alo...",NaN,"Adapted from Bukhari, S.J et al.1983.",NaN,pakistan
2218,170,Colombia,NaN,01234,Tomatoes,2019,7.50,7.5%,NaN,Farm,Farm,NaN,NaN,NaN,Literature Review,"JM Boiteau, (2021), The State Of Food Loss Alo...",NaN,Adapted from Chaboud (2017),NaN,colombia
2219,170,Colombia,NaN,01234,Tomatoes,2019,13.60,13.6%,NaN,Wholesale,Whole supply chain,NaN,NaN,NaN,Literature Review,"JM Boiteau, (2021), The State Of Food Loss Alo...",NaN,Adapted from Chaboud (2017),NaN,colombia
10472,356,India,NaN,0112,Maize (corn),2004,1.60,1.6%,NaN,"Farm, Threshing",Farm,NaN,NaN,NaN,Literature Review,"(2022), Assessment Of Losses In Harvesting And...",NaN,Adapted from Nanda et al. (2012),NaN,india
10468,356,India,NaN,0111,Wheat,2004,1.60,1.6%,NaN,"Farm, Threshing",Farm,NaN,NaN,NaN,Literature Review,"(2022), Assessment Of Losses In Harvesting And...",NaN,Adapted from Nanda et al. (2012),NaN,india

Reference formatting variants:

,normalized_reference,original_forms,records
81,"d. n. manandhar, j. k. ransom and n. p. rajbha...","[D. N. Manandhar, J. K. Ransom and N. P. Rajbh...",25
278,"saudi grains organization, (2019), saudi flw b...","[Saudi Grains Organization, (2019), Saudi FLW ...",58

URL validation review:

,m49_code,country,region,cpc_code,commodity,year,loss_percentage,loss_percentage_original,loss_quantity,activity,...,treatment,cause_of_loss,sample_size,method_data_collection,reference,url,notes,_region_normalized,_country_normalized,url_check
0,1,World,NaN,0111,Wheat,2022,1.00,1%,NaN,Processing,...,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived product is wheat flour,NaN,world,Missing
1,1,World,NaN,0112,Maize (corn),2022,0.50,0.5%,NaN,Processing,...,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived product is maize flour.,NaN,world,Missing
2,1,World,NaN,0112,Maize (corn),2022,2.00,2%,NaN,Processing,...,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived product is Maize (corn) grits.,NaN,world,Missing
3,1,World,NaN,0112,Maize (corn),2022,2.00,2%,NaN,Processing,...,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived product is Maize (corn) grits flaked.,NaN,world,Missing
4,1,World,NaN,0112,Maize (corn),2022,0.10,0.1%,NaN,Processing,...,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived product is corn starch.,NaN,world,Missing
5,1,World,NaN,0112,Maize (corn),2022,2.00,2%,NaN,Processing,...,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived product is undenaturated ethyl alcohol.,NaN,world,Missing
6,1,World,NaN,0113,Rice,2022,2.50,2.5%,NaN,Processing,...,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived product is milled rice.,NaN,world,Missing
7,1,World,NaN,0114,Sorghum,2022,0.50,0.5%,NaN,Processing,...,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived product is flour of sorghum.,NaN,world,Missing
8,1,World,NaN,0115,Barley,2022,12.00,12%,NaN,Processing,...,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived product is barley malt,NaN,world,Missing
9,1,World,NaN,0115,Barley,2022,2.00,2%,NaN,Processing,...,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived product is pot barley,NaN,world,Missing
10,1,World,NaN,0115,Barley,2022,2.00,2%,NaN,Processing,...,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived product is pearled barley,NaN,world,Missing
11,1,World,NaN,0116,Rye,2022,1.00,1%,NaN,Processing,...,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived Product is rye flour,NaN,world,Missing
12,1,World,NaN,0117,Oats,2022,2.00,2%,NaN,Processing,...,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived Product is oat flakes,NaN,world,Missing
13,1,World,NaN,0117,Oats,2022,2.00,2%,NaN,Processing,...,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived Product is oat rolled,NaN,world,Missing
14,1,World,NaN,0118,Millet,2022,2.00,2%,NaN,Processing,...,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived Product is millet dehulled,NaN,world,Missing
15,1,World,NaN,01192,Buckwheat,2022,2.00,2%,NaN,Processing,...,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived Product is buckwheat dehulled,NaN,world,Missing
16,1,World,NaN,01199.90,Cereals n.e.c.,2022,2.00,2%,NaN,Processing,...,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Spelt wheat (Dinkel) to pearled spelt wheat .,NaN,world,Missing
17,1,World,NaN,01199.90,Cereals n.e.c.,2022,2.00,2%,NaN,Processing,...,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Spelt wheat (Dinkel) to spelt wheat dehulled,NaN,world,Missing
18,1,World,NaN,01199.90,Cereals n.e.c.,2022,1.00,1%,NaN,Processing,...,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Amaranth to flour of amaranth.,NaN,world,Missing
19,1,World,NaN,23140.04,Pot barley,2022,2.00,2%,NaN,Processing,...,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived product is flour of barley,NaN,world,Missing
20,1,World,NaN,23140.08,Cereal preparations,2022,2.00,2%,NaN,Processing,...,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Millet dehulled to millet flour,NaN,world,Missing
21,1,World,NaN,23140.08,Cereal preparations,2022,2.00,2%,NaN,Processing,...,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Millet dehulled to millet flakes,NaN,world,Missing
22,1,World,NaN,23140.08,Cereal preparations,2022,2.00,2 %,NaN,Processing,...,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Buckwheat dehulled to buckwheat flakes,NaN,world,Missing
23,1,World,NaN,23140.08,Cereal preparations,2022,2.00,2%,NaN,Processing,...,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Buckwheat dehulled to buckwheat flour,NaN,world,Missing
24,1,World,NaN,24320,"Malt, whether or not roasted",2022,2.00,2%,NaN,Processing,...,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived product is barley beer,NaN,world,Missing
25,1,World,NaN,01199.02,Mixed grain,2018,2.85,2.85%,60 million metric tons,Harvesting,...,NaN,NaN,NaN,Modelled Estimates,"Mesterházy, Ákos; Oláh, Judit; Popp, József, (...",NaN,Grains,NaN,world,Missing
26,1,World,NaN,01199.02,Mixed grain,2018,20.03,20.03%,NaN,Storage,...,NaN,NaN,NaN,Modelled Estimates,"Mesterházy, Ákos; Oláh, Judit; Popp, József, (...",NaN,"Grains - wheat, corn, rice and soybean",NaN,world,Missing
27,1,World,NaN,01199.02,Mixed grain,2018,9.99,9.99%,NaN,NaN,...,NaN,Field mycotoxin contamination,NaN,Modelled Estimates,"Mesterházy, Ákos; Oláh, Judit; Popp, József, (...",NaN,"Grains - wheat, corn, rice and soybean",NaN,world,Missing
28,1,World,NaN,01199.02,Mixed grain,2018,13.61,13.61%,NaN,Consumption,...,NaN,NaN,NaN,Modelled Estimates,"Mesterházy, Ákos; Oláh, Judit; Popp, József, (...",NaN,"Grains - wheat, corn, rice and soybean Food w...",NaN,world,Missing
29,104,Myanmar,NaN,23161.02,"Rice, milled",2015,5.88,5.88%,44.09kgs,Storage,...,"30 days storage, no trapping",Rodents,NaN,Controlled Experiment,Steven R. Belmain; Nyo Me Htwe; Nazira Q. Kama...,NaN,NaN,NaN,myanmar,Missing
30,104,Myanmar,NaN,23161.02,"Rice, milled",2015,11.77,11.77%,88.18kgs,Storage,...,"60 days storage, no trapping",Rodents,NaN,Controlled Experiment,Steven R. Belmain; Nyo Me Htwe; Nazira Q. Kama...,NaN,NaN,NaN,myanmar,Missing
31,104,Myanmar,NaN,23161.02,"Rice, milled",2015,17.65,17.65%,132.27kgs,Storage,...,"90 days storage, no trapping",Rodents,NaN,Controlled Experiment,Steven R. Belmain; Nyo Me Htwe; Nazira Q. Kama...,NaN,NaN,NaN,myanmar,Missing
32,104,Myanmar,NaN,23161.02,"Rice, milled",2015,3.57,3.57%,52.24kgs,Storage,...,"60 days storage, with trapping",Rodents,NaN,Controlled Experiment,Steven R. Belmain; Nyo Me Htwe; Nazira Q. Kama...,NaN,NaN,NaN,myanmar,Missing
33,104,Myanmar,NaN,23161.02,"Rice, milled",2015,5.35,5.35%,78.36kgs,Storage,...,"90 days storage, with trapping",Rodents,NaN,Controlled Experiment,Steven R. Belmain; Nyo Me Htwe; Nazira Q. Kama...,NaN,NaN,NaN,myanmar,Missing
34,104,Myanmar,NaN,23161.02,"Rice, milled",2015,1.78,1.78%,26.12kgs,Storage,...,"30 days storage, with trapping",Rodents,NaN,Controlled Experiment,Steven R. Belmain; Nyo Me Htwe; Nazira Q. Kama...,NaN,NaN,NaN,myanmar,Missing
35,104,Myanmar,NaN,0142,"Groundnuts, excluding shelled",2009,5.22,5.22%,68100,NaN,...,NaN,NaN,NaN,FAO's annual Agriculture Production Questionna...,FAO Sources,NaN,NaN,NaN,myanmar,Missing
36,104,Myanmar,NaN,0142,"Groundnuts, excluding shelled",2008,5.43,5.43%,65240,NaN,...,NaN,NaN,NaN,FAO's annual Agriculture Production Questionna...,FAO Sources,NaN,NaN,NaN,myanmar,Missing
37,104,Myanmar,NaN,0142,"Groundnuts, excluding shelled",2007,5.61,5.61%,61080,NaN,...,NaN,NaN,NaN,FAO's annual Agriculture Production Questionna...,FAO Sources,NaN,NaN,NaN,myanmar,Missing
38,104,Myanmar,NaN,0142,"Groundnuts, excluding shelled",2006,5.40,5.4%,55270,NaN,...,NaN,NaN,NaN,FAO's annual Agriculture Production Questionna...,FAO Sources,NaN,NaN,NaN,myanmar,Missing
39,104,Myanmar,NaN,0142,"Groundnuts, excluding shelled",2005,5.00,5%,51970,NaN,...,NaN,NaN,NaN,FAO's annual Agriculture Production Questionna...,FAO Sources,NaN,NaN,NaN,myanmar,Missing
40,104,Myanmar,NaN,0142,"Groundnuts, excluding shelled",2004,5.00,5%,47310,NaN,...,NaN,NaN,NaN,FAO's annual Agriculture Production Questionna...,FAO Sources,NaN,NaN,NaN,myanmar,Missing
41,104,Myanmar,NaN,0142,"Groundnuts, excluding shelled",2003,5.00,5%,43880,NaN,...,NaN,NaN,NaN,FAO's annual Agriculture Production Questionna...,FAO Sources,NaN,NaN,NaN,myanmar,Missing
111,108,Burundi,NaN,0111,Wheat,2019,14.50,14.5%,NaN,NaN,...,NaN,NaN,NaN,Literature Review,"Cini, Leonardo, (2019), The Food Loss Reductio...",NaN,Source : APHILIS,NaN,burundi,Missing
112,108,Burundi,NaN,0112,Maize (corn),2019,18.00,18%,NaN,NaN,...,NaN,NaN,NaN,Literature Review,"Cini, Leonardo, (2019), The Food Loss Reductio...",NaN,Source : APHILIS,NaN,burundi,Missing
113,108,Burundi,NaN,0113,Rice,2019,12.00,12%,NaN,NaN,...,NaN,NaN,NaN,Literature Review,"Cini, Leonardo, (2019), The Food Loss Reductio...",NaN,Source : APHILIS,NaN,burundi,Missing
551,11,Western Africa,NaN,0113,Rice,2010,1.50,1 -2%,NaN,Drying,...,NaN,NaN,NaN,Literature Review,Julian Parfitt; Mark Barthel; Sarah Macnaughto...,NaN,Sourced from FAO 2007,NaN,western africa,Missing
552,11,Western Africa,NaN,0113,Rice,2010,6.00,2 -10%,NaN,Storage,...,NaN,NaN,NaN,Literature Review,Julian Parfitt; Mark Barthel; Sarah Macnaughto...,NaN,Sourced from FAO 2007,NaN,western africa,Missing
553,11,Western Africa,NaN,0113,Rice,2010,1.50,1 -2%,NaN,Parboiling,...,NaN,NaN,NaN,Literature Review,Julian Parfitt; Mark Barthel; Sarah Macnaughto...,NaN,Sourced from FAO 2007,NaN,western africa,Missing
554,11,Western Africa,NaN,0113,Rice,2010,6.00,2 -10%,NaN,Milling,...,NaN,NaN,NaN,Literature Review,Julian Parfitt; Mark Barthel; Sarah Macnaughto...,NaN,Sourced from FAO 2007,NaN,western africa,Missing
555,112,Belarus,NaN,02211,Raw milk of cattle,2007,0.01,0.01%,400,NaN,...,NaN,NaN,NaN,FAO's annual Agriculture Production Questionna...,FAO Sources,NaN,NaN,NaN,belarus,Missing

Duplicate URLs:

,m49_code,country,region,cpc_code,commodity,year,loss_percentage,loss_percentage_original,loss_quantity,activity,food_supply_stage,treatment,cause_of_loss,sample_size,method_data_collection,reference,url,notes,_region_normalized,_country_normalized
42,108,Burundi,NaN,0111,Wheat,2021,4.43333,4.43333,NaN,"Drying, Harvesting",Harvest,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
43,108,Burundi,NaN,0111,Wheat,2021,4.86667,4.86667,NaN,Storage,Farm,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
44,108,Burundi,NaN,0111,Wheat,2021,3.50000,3.5,NaN,"Shelling, Threshing",NaN,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
45,108,Burundi,NaN,0111,Wheat,2021,2.50000,2.5,NaN,Transportation,Farm,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
46,108,Burundi,NaN,0112,Maize (corn),2021,5.26375,5.26375,NaN,Storage,Farm,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
47,108,Burundi,NaN,0112,Maize (corn),2021,1.32000,1.32,NaN,"Shelling, Threshing",NaN,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
48,108,Burundi,NaN,0112,Maize (corn),2021,2.35714,2.35714,NaN,Transportation,Farm,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
49,108,Burundi,NaN,0112,Maize (corn),2021,4.00000,4,NaN,Drying,Farm,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
50,108,Burundi,NaN,0112,Maize (corn),2021,6.42000,6.42,NaN,"Drying, Harvesting",Harvest,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
51,108,Burundi,NaN,0113,Rice,2021,4.40333,4.40333,NaN,"Drying, Harvesting",Harvest,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
52,108,Burundi,NaN,0113,Rice,2021,1.20000,1.2,NaN,Storage,Farm,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
53,108,Burundi,NaN,0113,Rice,2021,3.13714,3.13714,NaN,"Shelling, Threshing",NaN,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
54,108,Burundi,NaN,0113,Rice,2021,1.25000,1.25,NaN,Transportation,Farm,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
55,108,Burundi,NaN,0113,Rice,2021,2.50000,2.5,NaN,Winnowing,Farm,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
56,108,Burundi,NaN,0114,Sorghum,2021,4.55000,4.55,NaN,"Drying, Harvesting",Harvest,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
57,108,Burundi,NaN,0114,Sorghum,2021,2.69444,2.69444,NaN,Storage,Farm,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
58,108,Burundi,NaN,0114,Sorghum,2021,3.60000,3.6,NaN,"Shelling, Threshing",NaN,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
59,108,Burundi,NaN,0114,Sorghum,2021,2.16667,2.16667,NaN,Transportation,Farm,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
60,108,Burundi,NaN,0118,Millet,2021,3.50000,3.5,NaN,"Drying, Harvesting",Harvest,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
61,108,Burundi,NaN,0118,Millet,2021,1.17500,1.175,NaN,Storage,Farm,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
62,108,Burundi,NaN,0118,Millet,2021,2.00000,2,NaN,"Shelling, Threshing",NaN,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
63,108,Burundi,NaN,0118,Millet,2021,2.50000,2.5,NaN,Transportation,Farm,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
64,108,Burundi,NaN,0118,Millet,2021,2.50000,2.5,NaN,Winnowing,Farm,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
65,108,Burundi,NaN,0111,Wheat,2020,4.43333,4.43333,NaN,"Drying, Harvesting",Harvest,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
66,108,Burundi,NaN,0111,Wheat,2020,4.86667,4.86667,NaN,Storage,Farm,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
67,108,Burundi,NaN,0111,Wheat,2020,3.50000,3.5,NaN,"Shelling, Threshing",NaN,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
68,108,Burundi,NaN,0111,Wheat,2020,2.50000,2.5,NaN,Transportation,Farm,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
69,108,Burundi,NaN,0112,Maize (corn),2020,5.26375,5.26375,NaN,Storage,Farm,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
70,108,Burundi,NaN,0112,Maize (corn),2020,1.32000,1.32,NaN,"Shelling, Threshing",NaN,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
71,108,Burundi,NaN,0112,Maize (corn),2020,2.35714,2.35714,NaN,Transportation,Farm,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
72,108,Burundi,NaN,0112,Maize (corn),2020,4.00000,4,NaN,Drying,Farm,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
73,108,Burundi,NaN,0112,Maize (corn),2020,6.42000,6.42,NaN,"Drying, Harvesting",Harvest,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
74,108,Burundi,NaN,0113,Rice,2020,4.40333,4.40333,NaN,"Drying, Harvesting",Harvest,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
75,108,Burundi,NaN,0113,Rice,2020,1.20000,1.2,NaN,Storage,Farm,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
76,108,Burundi,NaN,0113,Rice,2020,3.13714,3.13714,NaN,"Shelling, Threshing",NaN,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
77,108,Burundi,NaN,0113,Rice,2020,1.25000,1.25,NaN,Transportation,Farm,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
78,108,Burundi,NaN,0113,Rice,2020,2.50000,2.5,NaN,Winnowing,Farm,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
79,108,Burundi,NaN,0114,Sorghum,2020,4.55000,4.55,NaN,"Drying, Harvesting",Harvest,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
80,108,Burundi,NaN,0114,Sorghum,2020,2.69444,2.69444,NaN,Storage,Farm,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
81,108,Burundi,NaN,0114,Sorghum,2020,3.60000,3.6,NaN,"Shelling, Threshing",NaN,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
82,108,Burundi,NaN,0114,Sorghum,2020,2.16667,2.16667,NaN,Transportation,Farm,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
83,108,Burundi,NaN,0118,Millet,2020,3.50000,3.5,NaN,"Drying, Harvesting",Harvest,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
84,108,Burundi,NaN,0118,Millet,2020,1.17500,1.175,NaN,Storage,Farm,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
85,108,Burundi,NaN,0118,Millet,2020,2.00000,2,NaN,"Shelling, Threshing",NaN,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
86,108,Burundi,NaN,0118,Millet,2020,2.50000,2.5,NaN,Transportation,Farm,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
87,108,Burundi,NaN,0118,Millet,2020,2.50000,2.5,NaN,Winnowing,Farm,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
88,108,Burundi,NaN,0111,Wheat,2019,4.43333,4.43333,NaN,"Drying, Harvesting",Harvest,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
89,108,Burundi,NaN,0111,Wheat,2019,4.86667,4.86667,NaN,Storage,Farm,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
90,108,Burundi,NaN,0111,Wheat,2019,3.50000,3.5,NaN,"Shelling, Threshing",NaN,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi
91,108,Burundi,NaN,0111,Wheat,2019,2.50000,2.5,NaN,Transportation,Farm,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN,NaN,burundi

Possible encoding issues in notes:

Empty DataFrame
Columns: [notes]
Index: []

Notes containing possible structured information:

,country,commodity,year,notes
551,Western Africa,Rice,2010,Sourced from FAO 2007
552,Western Africa,Rice,2010,Sourced from FAO 2007
553,Western Africa,Rice,2010,Sourced from FAO 2007
554,Western Africa,Rice,2010,Sourced from FAO 2007
566,Cambodia,Tomatoes,2015,Sourced from Weinberger et al 2008
567,Cambodia,"Beans, dry",2015,Sourced from Weinberger et al 2008
572,Cambodia,Cauliflowers and broccoli,2008,Sourced from Weinberger et al 2008
573,Cambodia,Cucumbers and gherkins,2008,Sourced from Weinberger et al 2008
616,Algeria,Potatoes,2005,Sourced from Yahia 2005
975,Canada,Mixed grain,2014,"Sourced from Gunders, (2012)"
976,Canada,"Snails, fresh, chilled, frozen, dried, salted ...",2014,"Sourced from Gunders, (2012)"
1292,Asia,Rice,2019,"Source: Singleton, G. Impacts of Rodents on R..."
1317,Sri Lanka,Bananas,2015,Sourced from Wasala et al 2014
1962,China,Wheat,2021,Referenced to Gao et al (2016)
1963,China,Wheat,2021,Referenced to Gao et al (2016)
1964,China,Wheat,2021,Referenced to Gao et al (2016)
1965,China,Wheat,2021,Referenced to Gao et al (2016)
1966,China,Wheat,2021,Referenced to Gao et al (2018)
1967,China,Wheat,2021,Referenced to Luo et al (2020)
1968,China,Maize (corn),2021,Referenced to Gao et al (2016)
1969,China,Maize (corn),2021,Referenced to Gao et al (2016)
1970,China,Maize (corn),2021,Referenced to Gao et al (2016)
1971,China,Maize (corn),2021,Referenced to Guo et al (2019)
1972,China,Maize (corn),2021,Referenced to Gao et al (2016)
1973,China,Maize (corn),2021,Referenced to Luo et al (2020)
1974,China,Rice,2021,Referenced to Gao et al (2016)
1975,China,Rice,2021,Referenced to Gao et al (2016)
1976,China,Rice,2021,Referenced to Gao et al (2016)
1977,China,Rice,2021,Referenced to Gao et al (2016)
1978,China,Rice,2021,Referenced to Lu et al (2019)
1979,China,Rice,2021,Referenced to Lu et al (2019)
1980,China,Rice,2021,Referenced to Lu et al (2019)
1981,China,Rice,2021,Referenced to Lu et al (2019)
1982,China,Rice,2021,Referenced to Lu et al (2019)
1983,China,Rice,2021,Referenced to Huang et al (2018)
1984,China,Rice,2021,Referenced to Qu et al (2019)
1985,China,Wheat,2021,Adopted from Gao et al. (2020)
1986,China,Wheat,2021,Adopted from Gao et al. (2020)
1987,China,Wheat,2021,Adopted from Gao et al. (2020)
1988,China,Wheat,2021,Adopted from Cao et al. (2018)
1989,China,Wheat,2021,Adopted from Gao et al. (2016)
1990,China,Maize (corn),2021,Adopted from Luo et al. (2020)
1991,China,Maize (corn),2021,Adopted from Gao et al. (2016)
1992,China,Maize (corn),2021,Adopted from Gao et al. (2016)
1993,China,Maize (corn),2021,Adopted from Gao et al. (2016)
1994,China,Maize (corn),2021,Adopted from Gao et al. (2016)
1995,China,Maize (corn),2021,Adopted from Guo et al. (2019)
1996,China,Maize (corn),2021,Adopted from Luo et al. (2020)
1997,China,Rice,2021,Adopted from Gao et al. (2016)
1998,China,Rice,2021,Adopted from Gao et al. (2016)

      column  missing_or_blank  duplicate_records
0  reference                73              31348
1        url              9342              22097
2      notes             29931               1225

---
# Final validation summary and reproducible outputs

This section consolidates key checks into machine-readable outputs. It does not change `world_food_loss`; all normalized fields are for comparison only.

## Authoritative references

- FAO Food Loss and Waste Database: https://www.fao.org/platform-food-loss-waste/flw-data/en/
- FAO FLW Database User Guide: https://www.fao.org/platform-food-loss-waste/flw-data/user-guide/en
- UN M49 Overview: https://unstats.un.org/unsd/methodology/m49/overview/
- UN M49 Methodology: https://unstats.un.org/unsd/methodology/m49/
- UN CPC 2.1 classification: https://unstats.un.org/unsd/classifications/Econ/Download/In%20Text/CPC_Ver_2.1_Exp_Notes_Updated_3Apr2025.xlsx
- FAO Caliper classification downloads and mappings: https://www.fao.org/statistics/caliper/tools/download/en

**Reference policy:** UN M49 is authoritative for M49 codes and its geographic hierarchy; CPC is authoritative for CPC classification; FAO documentation defines the meaning and scope of the source dataset. GitHub datasets can be useful cross-checks, but should not override the official reference without documented justification.

## How to interpret flags

- `FAIL` / `MISMATCH`: a rule is violated and needs correction or a documented exception.
- `REVIEW`: the value is unusual or context-dependent; do not automatically modify it.
- `NOT_COMPARABLE`: insufficient information for that specific check.
- A valid code does not guarantee that the code is paired with the right country, region, commodity, or unit.

In [295]:
# Build final audit summary and export review tables.
# This cell is defensive: it only uses outputs that exist and never overwrites source data.

from pathlib import Path
from datetime import datetime, timezone
import json

REPORT_DIR = Path("../report") / "step_1_validation"
REPORT_DIR.mkdir(parents=True, exist_ok=True)

def safe_write_csv(frame, filename):
    if isinstance(frame, pd.DataFrame):
        path = REPORT_DIR / filename
        frame.to_csv(path, index=False, encoding="utf-8-sig")
        print(f"Saved {path.resolve()} ({len(frame):,} rows)")
        return path
    print(f"Skipped {filename}: expected DataFrame, got {type(frame).__name__}")
    return None

# Overall profile: one row per source column.
profile_rows = []
for column in world_food_loss.columns:
    series = world_food_loss[column]
    text_values = series.astype("string") if (
        pd.api.types.is_object_dtype(series.dtype)
        or pd.api.types.is_string_dtype(series.dtype)
    ) else None
    blank_count = int(text_values.str.strip().eq("").fillna(False).sum()) if text_values is not None else 0
    profile_rows.append({
        "column": column,
        "dtype": str(series.dtype),
        "row_count": int(len(series)),
        "missing_count": int(series.isna().sum()),
        "missing_pct": round(float(series.isna().mean() * 100), 4) if len(series) else 0,
        "blank_string_count": blank_count,
        "distinct_non_null": int(series.nunique(dropna=True)),
    })
final_column_profile = pd.DataFrame(profile_rows)

# Whole-row duplicates and likely duplicate source records are different concepts.
exact_duplicate_rows = world_food_loss.loc[
    world_food_loss.duplicated(keep=False)
].copy()

key_columns = [
    col for col in ["country", "region", "cpc_code", "commodity", "year",
                    "activity", "food_supply_stage", "reference"]
    if col in world_food_loss.columns
]
if key_columns:
    duplicate_candidate_rows = world_food_loss.loc[
        world_food_loss.duplicated(subset=key_columns, keep=False)
    ].copy()
else:
    duplicate_candidate_rows = pd.DataFrame()

# Compact validation status summary if the earlier validation cell ran.
status_summary = pd.DataFrame()
if "checked" in globals() and isinstance(checked, pd.DataFrame):
    for status_col in ["country_code_status", "region_review_status"]:
        if status_col in checked.columns:
            part = checked[status_col].value_counts(dropna=False).rename_axis("status").reset_index(name="records")
            part.insert(0, "validation", status_col)
            status_summary = pd.concat([status_summary, part], ignore_index=True)

# Export core audit outputs.
safe_write_csv(final_column_profile, "column_profile.csv")
safe_write_csv(exact_duplicate_rows, "exact_duplicate_rows.csv")
safe_write_csv(duplicate_candidate_rows, "duplicate_record_candidates.csv")
safe_write_csv(status_summary, "geographic_validation_status_summary.csv")

# Export any available review tables from the notebook.
review_tables = {
    "country_code_issues.csv": "country_code_issues",
    "region_level_review.csv": "region_level_review",
    "unexpected_region_report.csv": "unexpected_region_report",
    "cpc_code_review.csv": "cpc_code_review",
    "reference_format_review.csv": "reference_format_review",
    "out_of_range_loss_percentage.csv": "out_of_range_loss",
    "negative_loss_quantity.csv": "negative_loss_quantity",
    "invalid_sample_size.csv": "invalid_sample_size",
}
for filename, variable_name in review_tables.items():
    value = globals().get(variable_name)
    if isinstance(value, pd.DataFrame):
        safe_write_csv(value, filename)

run_manifest = {
    "run_timestamp_utc": datetime.now(timezone.utc).isoformat(),
    "source_file": str(globals().get("DATA_PATH", "path not recorded")),
    "source_rows": int(len(world_food_loss)),
    "source_columns": int(len(world_food_loss.columns)),
    "exact_duplicate_rows_including_all_copies": int(world_food_loss.duplicated(keep=False).sum()),
    "key_columns_used_for_duplicate_candidates": key_columns,
    "source_modified": False,
    "reference_links": {
        "FAO_FLW": "https://www.fao.org/platform-food-loss-waste/flw-data/en/",
        "FAO_FLW_User_Guide": "https://www.fao.org/platform-food-loss-waste/flw-data/user-guide/en",
        "UN_M49": "https://unstats.un.org/unsd/methodology/m49/overview/",
        "UN_CPC_2_1": "https://unstats.un.org/unsd/classifications/Econ/Download/In%20Text/CPC_Ver_2.1_Exp_Notes_Updated_3Apr2025.xlsx",
    },
}
manifest_path = REPORT_DIR / "run_manifest.json"
manifest_path.write_text(json.dumps(run_manifest, indent=2, ensure_ascii=False), encoding="utf-8")
print(f"Saved {manifest_path.resolve()}")

print("\nFINAL AUDIT OVERVIEW")
display(pd.DataFrame([
    {"metric": "Rows", "value": len(world_food_loss)},
    {"metric": "Columns", "value": len(world_food_loss.columns)},
    {"metric": "Exact duplicate rows (including all copies)", "value": int(world_food_loss.duplicated(keep=False).sum())},
    {"metric": "Rows with at least one missing value", "value": int(world_food_loss.isna().any(axis=1).sum())},
    {"metric": "Rows with no missing values", "value": int((~world_food_loss.isna().any(axis=1)).sum())},
]))
print("\nReview files are saved under:", REPORT_DIR.resolve())

Saved D:\My_projects\data-engineer\waste-food-project\report\step_1_validation\column_profile.csv (18 rows)
Saved D:\My_projects\data-engineer\waste-food-project\report\step_1_validation\exact_duplicate_rows.csv (339 rows)
Saved D:\My_projects\data-engineer\waste-food-project\report\step_1_validation\duplicate_record_candidates.csv (2,862 rows)
Saved D:\My_projects\data-engineer\waste-food-project\report\step_1_validation\geographic_validation_status_summary.csv (4 rows)
Saved D:\My_projects\data-engineer\waste-food-project\report\step_1_validation\country_code_issues.csv (282 rows)
Saved D:\My_projects\data-engineer\waste-food-project\report\step_1_validation\region_level_review.csv (666 rows)
Saved D:\My_projects\data-engineer\waste-food-project\report\step_1_validation\unexpected_region_report.csv (378 rows)
Saved D:\My_projects\data-engineer\waste-food-project\report\step_1_validation\cpc_code_review.csv (196 rows)
Saved D:\My_projects\data-engineer\waste-food-project\report\step_1_validation\reference_format_review.csv (2 rows)
Saved D:\My_projects\data-engineer\waste-food-project\report\step_1_validation\out_of_range_loss_percentage.csv (0 rows)
Saved D:\My_projects\data-engineer\waste-food-project\report\step_1_validation\negative_loss_quantity.csv (0 rows)
Saved D:\My_projects\data-engineer\waste-food-project\report\step_1_validation\invalid_sample_size.csv (1,206 rows)
Saved D:\My_projects\data-engineer\waste-food-project\report\step_1_validation\run_manifest.json

FINAL AUDIT OVERVIEW

                                        metric  value
0                                         Rows  31465
1                                      Columns     18
2  Exact duplicate rows (including all copies)    339
3         Rows with at least one missing value  31465
4                  Rows with no missing values      0

Review files are saved under: D:\My_projects\data-engineer\waste-food-project\report\step_1_validation