# ***Global Food Waste Graduation project (without Egypt)***

In [1]:
import pandas as pd
import numpy as np

## **Read Data**

In [3]:
food_global = pd.read_csv('../data-set/global_food_wastage_dataset.csv');
food_global

,Country,Year,Food Category,Total Waste (Tons),Economic Loss (Million $),Avg Waste per Capita (Kg),Population (Million),Household Waste (%)
0,Australia,2019,Fruits & Vegetables,19268.63,18686.68,72.69,87.59,53.64
1,Indonesia,2019,Prepared Food,3916.97,4394.48,192.52,1153.99,30.61
2,Germany,2022,Dairy Products,9700.16,8909.16,166.94,1006.11,48.08
3,France,2023,Fruits & Vegetables,46299.69,40551.22,120.19,953.05,31.91
4,France,2023,Beverages,33096.57,36980.82,104.74,1105.47,36.06
...,...,...,...,...,...,...,...,...
4995,France,2021,Beverages,47524.74,48058.40,77.41,1087.46,39.73
4996,Australia,2021,Beverages,32337.72,32705.08,194.35,1336.32,64.83
4997,China,2018,Meat & Seafood,20640.96,22485.33,21.04,16.13,31.23
4998,Australia,2021,Beverages,26566.64,29357.57,197.14,1086.17,69.95
4999,France,2024,Bakery Items,8860.27,7360.38,51.50,879.67,54.27

## **DATASET OVERVIEW**

In [34]:
print("=" * 60)
print("DATASET OVERVIEW")
print("=" * 60)

print("Shape:", food_global.shape)
print("Number of rows:", food_global.shape[0])
print("Number of columns:", food_global.shape[1])
print("Memory usage (MB):", round(food_global.memory_usage(deep=True).sum() / (1024 ** 2), 2))

display(food_global.head())
display(food_global.tail())
display(food_global.sample(min(5, len(food_global)), random_state=42))

============================================================
DATASET OVERVIEW
============================================================
Shape: (5000, 8)
Number of rows: 5000
Number of columns: 8
Memory usage (MB): 0.79

,Country,Year,Food Category,Total Waste (Tons),Economic Loss (Million $),Avg Waste per Capita (Kg),Population (Million),Household Waste (%)
0,Australia,2019,Fruits & Vegetables,19268.63,18686.68,72.69,87.59,53.64
1,Indonesia,2019,Prepared Food,3916.97,4394.48,192.52,1153.99,30.61
2,Germany,2022,Dairy Products,9700.16,8909.16,166.94,1006.11,48.08
3,France,2023,Fruits & Vegetables,46299.69,40551.22,120.19,953.05,31.91
4,France,2023,Beverages,33096.57,36980.82,104.74,1105.47,36.06

,Country,Year,Food Category,Total Waste (Tons),Economic Loss (Million $),Avg Waste per Capita (Kg),Population (Million),Household Waste (%)
4995,France,2021,Beverages,47524.74,48058.40,77.41,1087.46,39.73
4996,Australia,2021,Beverages,32337.72,32705.08,194.35,1336.32,64.83
4997,China,2018,Meat & Seafood,20640.96,22485.33,21.04,16.13,31.23
4998,Australia,2021,Beverages,26566.64,29357.57,197.14,1086.17,69.95
4999,France,2024,Bakery Items,8860.27,7360.38,51.50,879.67,54.27

,Country,Year,Food Category,Total Waste (Tons),Economic Loss (Million $),Avg Waste per Capita (Kg),Population (Million),Household Waste (%)
1501,Germany,2018,Beverages,49821.95,47175.67,44.62,903.11,36.71
2586,Indonesia,2022,Grains & Cereals,48773.09,49979.19,110.86,885.95,35.71
2653,Mexico,2022,Fruits & Vegetables,13381.14,15056.57,131.13,603.48,32.25
1055,Indonesia,2023,Fruits & Vegetables,21279.19,22604.89,160.58,362.46,34.14
705,Russia,2022,Dairy Products,41031.17,41606.00,198.76,1379.01,39.85

## **Analysis Columns**

In [35]:
print("COLUMN NAMES")
print(food_global.columns.tolist())

print("\nDATA TYPES")
print(food_global.dtypes)

print("\nDATASET INFO")
food_global.info()

print("\nNUMERIC SUMMARY")
display(food_global.describe().T)

print("\nALL COLUMNS SUMMARY")
display(food_global.describe(include="all").T)

COLUMN NAMES
['Country', 'Year', 'Food Category', 'Total Waste (Tons)', 'Economic Loss (Million $)', 'Avg Waste per Capita (Kg)', 'Population (Million)', 'Household Waste (%)']

DATA TYPES
Country                          str
Year                           int64
Food Category                    str
Total Waste (Tons)           float64
Economic Loss (Million $)    float64
Avg Waste per Capita (Kg)    float64
Population (Million)         float64
Household Waste (%)          float64
dtype: object

DATASET INFO
<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Country                    5000 non-null   str
 1   Year                       5000 non-null   int64
 2   Food Category              5000 non-null   str
 3   Total Waste (Tons)         5000 non-null   float64
 4   Economic Loss (Million $)  5000 non-null   float64
 5   Avg Waste per Capita (Kg)  5000 non-null   float64
 6   Population (Million)       5000 non-null   float64
 7   Household Waste (%)        5000 non-null   float64
dtypes: float64(5), int64(1), str(2)
memory usage: 312.6 KB

NUMERIC SUMMARY

,count,mean,std,min,25%,50%,75%,max
Year,5000.0,2021.015600,1.999239,2018.00,2019.0000,2021.000,2023.0000,2024.00
Total Waste (Tons),5000.0,25061.780072,14245.119588,502.61,12783.7375,24865.220,37471.0350,49990.76
Economic Loss (Million $),5000.0,25039.703870,14620.236429,406.69,12612.4775,24428.155,37146.0375,59228.93
Avg Waste per Capita (Kg),5000.0,109.463970,51.933730,20.09,64.0500,110.080,154.5250,199.97
Population (Million),5000.0,706.606416,402.546464,11.29,350.6025,713.530,1057.2550,1399.97
Household Waste (%),5000.0,50.060890,11.596203,30.02,40.0125,50.295,60.1250,70.00

ALL COLUMNS SUMMARY

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Country,5000,20,Germany,287,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Year,5000.0,NaN,NaN,NaN,2021.0156,1.999239,2018.0,2019.0,2021.0,2023.0,2024.0
Food Category,5000,8,Prepared Food,711,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Total Waste (Tons),5000.0,NaN,NaN,NaN,25061.780072,14245.119588,502.61,12783.7375,24865.22,37471.035,49990.76
Economic Loss (Million $),5000.0,NaN,NaN,NaN,25039.70387,14620.236429,406.69,12612.4775,24428.155,37146.0375,59228.93
Avg Waste per Capita (Kg),5000.0,NaN,NaN,NaN,109.46397,51.93373,20.09,64.05,110.08,154.525,199.97
Population (Million),5000.0,NaN,NaN,NaN,706.606416,402.546464,11.29,350.6025,713.53,1057.255,1399.97
Household Waste (%),5000.0,NaN,NaN,NaN,50.06089,11.596203,30.02,40.0125,50.295,60.125,70.0

## **Analysis Missing values in Data-set**

In [36]:
missing_report = pd.DataFrame({
    "missing_count": food_global.isna().sum(),
    "missing_percentage": food_global.isna().mean().mul(100),
    "non_missing_count": food_global.notna().sum(),
    "unique_non_null": food_global.nunique(dropna=True)
})

missing_report = missing_report.sort_values(
    by="missing_percentage",
    ascending=False
)

display(missing_report)

,missing_count,missing_percentage,non_missing_count,unique_non_null
Country,0,0.0,5000,20
Year,0,0.0,5000,7
Food Category,0,0.0,5000,8
Total Waste (Tons),0,0.0,5000,4998
Economic Loss (Million $),0,0.0,5000,4998
Avg Waste per Capita (Kg),0,0.0,5000,4338
Population (Million),0,0.0,5000,4901
Household Waste (%),0,0.0,5000,2858

### **Show "NA", "N/A", "NULL", "NONE", "UNKNOWN", "MISSING", "-" in string data-types**

In [37]:
print("Empty strings:")
display(
    (food_global.astype("string").apply(
        lambda col: col.str.strip().eq("").sum()
    )).to_frame("empty_string_count")
)

missing_tokens = [
    "NA", "N/A", "NULL", "NONE", "UNKNOWN", "MISSING", "-"
]

for col in food_global.select_dtypes(include=["object", "string"]).columns:
    values = food_global[col].astype("string").str.strip().str.upper()
    count = values.isin(missing_tokens).sum()

    if count > 0:
        print(f"{col}: {count} possible missing tokens")

Empty strings:

                           empty_string_count
Country                                     0
Year                                        0
Food Category                               0
Total Waste (Tons)                          0
Economic Loss (Million $)                   0
Avg Waste per Capita (Kg)                   0
Population (Million)                        0
Household Waste (%)                         0

## **Show duplicated and unique data**

In [38]:
unique_report = pd.DataFrame({
    "unique_count": food_global.nunique(dropna=True),
    "unique_with_nan": food_global.nunique(dropna=False),
    "dtype": food_global.dtypes.astype(str),
    "is_constant": food_global.nunique(dropna=True).le(1)
})

display(unique_report.sort_values("unique_count"))

                           unique_count  unique_with_nan    dtype  is_constant
Year                                  7                7    int64        False
Food Category                         8                8      str        False
Country                              20               20      str        False
Household Waste (%)                2858             2858  float64        False
Avg Waste per Capita (Kg)          4338             4338  float64        False
Population (Million)               4901             4901  float64        False
Total Waste (Tons)                 4998             4998  float64        False
Economic Loss (Million $)          4998             4998  float64        False

In [39]:
categorical_cols = food_global.select_dtypes(
    include=["object", "string", "category"]
).columns

for col in categorical_cols:
    print(f"\n{'=' * 60}")
    print(f"Column: {col}")
    print("Unique values:", food_global[col].nunique(dropna=True))
    print("Most frequent values:")
    display(food_global[col].value_counts(dropna=False))

============================================================
Column: Country
Unique values: 20
Most frequent values:

Country
Germany         287
Spain           274
China           262
Brazil          258
India           257
USA             257
Turkey          256
Canada          254
Italy           253
Mexico          251
South Africa    245
Indonesia       244
UK              242
South Korea     241
Japan           240
France          239
Saudi Arabia    239
Argentina       238
Russia          237
Australia       226
Name: count, dtype: int64

============================================================
Column: Food Category
Unique values: 8
Most frequent values:

Food Category
Prepared Food          711
Beverages              639
Bakery Items           630
Fruits & Vegetables    620
Dairy Products         616
Meat & Seafood         605
Frozen Food            596
Grains & Cereals       583
Name: count, dtype: int64

In [40]:
print("Fully duplicated rows:", food_global.duplicated().sum())

print(
    "Duplicated rows including all copies:",
    food_global.duplicated(keep=False).sum()
)

duplicates = food_global[
    food_global.duplicated(keep=False)
].sort_values(by=food_global.columns.tolist())

display(duplicates.head(20))

Fully duplicated rows: 0
Duplicated rows including all copies: 0

Empty DataFrame
Columns: [Country, Year, Food Category, Total Waste (Tons), Economic Loss (Million $), Avg Waste per Capita (Kg), Population (Million), Household Waste (%)]
Index: []

## **Describe numeric data**

In [41]:
numeric_cols = food_global.select_dtypes(
    include=np.number
).columns

numeric_report = pd.DataFrame(index=numeric_cols)

numeric_report["missing"] = food_global[numeric_cols].isna().sum()
numeric_report["unique"] = food_global[numeric_cols].nunique()
numeric_report["min"] = food_global[numeric_cols].min()
numeric_report["max"] = food_global[numeric_cols].max()
numeric_report["mean"] = food_global[numeric_cols].mean()
numeric_report["median"] = food_global[numeric_cols].median()
numeric_report["std"] = food_global[numeric_cols].std()
numeric_report["negative_count"] = food_global[numeric_cols].lt(0).sum()

display(numeric_report)

,missing,unique,min,max,mean,median,std,negative_count
Year,0,7,2018.00,2024.00,2021.015600,2021.000,1.999239,0
Total Waste (Tons),0,4998,502.61,49990.76,25061.780072,24865.220,14245.119588,0
Economic Loss (Million $),0,4998,406.69,59228.93,25039.703870,24428.155,14620.236429,0
Avg Waste per Capita (Kg),0,4338,20.09,199.97,109.463970,110.080,51.933730,0
Population (Million),0,4901,11.29,1399.97,706.606416,713.530,402.546464,0
Household Waste (%),0,2858,30.02,70.00,50.060890,50.295,11.596203,0

## **Show ouliers**

In [42]:
outlier_rows = []

for col in numeric_cols:
    series = food_global[col].dropna()

    if series.empty:
        continue

    q1 = series.quantile(0.25)
    q3 = series.quantile(0.75)
    iqr = q3 - q1

    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr

    mask = (food_global[col] < lower_bound) | (
        food_global[col] > upper_bound
    )

    outlier_rows.append({
        "column": col,
        "lower_bound": lower_bound,
        "upper_bound": upper_bound,
        "outlier_count": int(mask.sum()),
        "outlier_percentage": round(mask.mean() * 100, 2)
    })

outlier_report = pd.DataFrame(outlier_rows)
display(outlier_report)

,column,lower_bound,upper_bound,outlier_count,outlier_percentage
0,Year,2013.00000,2029.00000,0,0.0
1,Total Waste (Tons),-24247.20875,74501.98125,0,0.0
2,Economic Loss (Million $),-24187.86250,73946.37750,0,0.0
3,Avg Waste per Capita (Kg),-71.66250,290.23750,0,0.0
4,Population (Million),-709.37625,2117.23375,0,0.0
5,Household Waste (%),9.84375,90.29375,0,0.0

## **Show final columns**

In [43]:
print(food_global.columns.tolist())

['Country', 'Year', 'Food Category', 'Total Waste (Tons)', 'Economic Loss (Million $)', 'Avg Waste per Capita (Kg)', 'Population (Million)', 'Household Waste (%)']

## **Data quality check on the Year**

In [44]:
if "Year" in food_global.columns:
    print("Invalid or suspicious years:")
    display(
        food_global.loc[
            ~food_global["Year"].between(1900, 2100),
            ["Year"]
        ].head(20)
    )

Invalid or suspicious years:

Empty DataFrame
Columns: [Year]
Index: []

## **Finally analysis of data**

In [45]:
quality_report = pd.DataFrame(index=food_global.columns)

quality_report["dtype"] = food_global.dtypes.astype(str)
quality_report["total_rows"] = len(food_global)
quality_report["missing_count"] = food_global.isna().sum()
quality_report["missing_pct"] = (
    food_global.isna().mean() * 100
).round(2)

quality_report["unique_count"] = food_global.nunique(dropna=True)
quality_report["unique_pct"] = (
    food_global.nunique(dropna=True) / max(len(food_global), 1) * 100
).round(2)

quality_report["duplicate_row_count"] = food_global.duplicated().sum()
quality_report["memory_bytes"] = food_global.memory_usage(deep=True).iloc[1:].values

display(quality_report)

,dtype,total_rows,missing_count,missing_pct,unique_count,unique_pct,duplicate_row_count,memory_bytes
Country,str,5000,0,0.0,20,0.40,0,278495
Year,int64,5000,0,0.0,7,0.14,0,40000
Food Category,str,5000,0,0.0,8,0.16,0,312312
Total Waste (Tons),float64,5000,0,0.0,4998,99.96,0,40000
Economic Loss (Million $),float64,5000,0,0.0,4998,99.96,0,40000
Avg Waste per Capita (Kg),float64,5000,0,0.0,4338,86.76,0,40000
Population (Million),float64,5000,0,0.0,4901,98.02,0,40000
Household Waste (%),float64,5000,0,0.0,2858,57.16,0,40000