# ***World Food Waste Graduation project***

In [4]:

import pandas as pd
import numpy as np
from pathlib import Path

## **Read Data**

In [5]:
world_food_loss = pd.read_csv('../data-set/World-food-waste.csv', dtype={"cpc_code": "string"})
display(world_food_loss.head())

,m49_code,country,region,cpc_code,commodity,year,loss_percentage,loss_percentage_original,loss_quantity,activity,food_supply_stage,treatment,cause_of_loss,sample_size,method_data_collection,reference,url,notes
0,1,World,NaN,0111,Wheat,2022,1.0,1%,NaN,Processing,Processing,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived product is wheat flour
1,1,World,NaN,0112,Maize (corn),2022,0.5,0.5%,NaN,Processing,Processing,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived product is maize flour.
2,1,World,NaN,0112,Maize (corn),2022,2.0,2%,NaN,Processing,Processing,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived product is Maize (corn) grits.
3,1,World,NaN,0112,Maize (corn),2022,2.0,2%,NaN,Processing,Processing,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived product is Maize (corn) grits flaked.
4,1,World,NaN,0112,Maize (corn),2022,0.1,0.1%,NaN,Processing,Processing,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived product is corn starch.

| اسم العمود | معناه في سياق بيانات FAO |
| :--- | :--- |
| **m49_code** | كود الدولة أو المنطقة حسب معيار الأمم المتحدة M49. مصر كودها 818. |
| **country** | اسم الدولة المرتبطة بالسجل، زي Egypt. |
| **region** | المنطقة الجغرافية، لو السجل بيمثل منطقة بدل دولة منفردة أو بيحتوي على تصنيف إقليمي. لازم نراجع تعريف الملف لمعرفة الاستخدام الدقيق للحقل ده. |
| **cpc_code** | كود تصنيف السلعة حسب نظام CPC. |
| **commodity** | اسم المنتج أو السلعة الغذائية، زي Tomatoes. |
| **year** | السنة المسجلة للدراسة في قاعدة البيانات، وفق تعريف FAO. |
| **loss_percentage** | نسبة الفقد المسجلة في الدراسة، وده المتغير الأساسي اللي بنحلله. |
| **loss_percentage_original** | يبدو إنه بيحتفظ بتمثيل النسبة الأصلي، لكن لازم نراجع ملف التصدير أو وصف الحقول علشان نأكد الفرق الدقيق بينه وبين العمود السابق. |
| **loss_quantity** | كمية الفقد، لو متاحة ومسجلة في المصدر. لازم نراجع الوحدة وتعريف الكمية قبل استخدامها. |
| **activity** | النشاط المرتبط بفقد الطعام، حسب وصف الدراسة الأصلية. |
| **food_supply_stage** | مرحلة سلسلة الإمداد الغذائي اللي الدراسة ربطت بيها الفقد. |
| **treatment** | حقل متعلق بالمعالجة أو التعامل مع المنتج وفق تعريف المصدر؛ محتاجين تعريف الحقل الأصلي لتحديد معناه بدقة. |
| **cause_of_loss** | سبب الفقد، لو الدراسة سجلته. |
| **sample_size** | حجم العينة المسجلة للدراسة، وفق وحدة العينة المستخدمة فيها. |
| **method_data_collection** | طريقة جمع أو تقدير بيانات الفقد، زي Survey. |
| **reference** | المرجع أو الدراسة اللي اتاخدت منها البيانات. |
| **url** | رابط المصدر الأصلي، لو متاح. |
| **notes** | ملاحظات إضافية مرتبطة بالسجل، لو موجودة. |

## **DATASET OVERVIEW**

In [6]:
print("=" * 60)
print("DATASET OVERVIEW")
print("=" * 60)

print("Shape:", world_food_loss.shape)
print("Number of rows:", world_food_loss.shape[0])
print("Number of columns:", world_food_loss.shape[1])
print("Memory usage (MB):", round(world_food_loss.memory_usage(deep=True).sum() / (1024 ** 2), 2))

display(world_food_loss.head())
display(world_food_loss.tail())
display(world_food_loss.sample(min(5, len(world_food_loss)), random_state=42))

============================================================
DATASET OVERVIEW
============================================================
Shape: (31465, 18)
Number of rows: 31465
Number of columns: 18
Memory usage (MB): 25.66

,m49_code,country,region,cpc_code,commodity,year,loss_percentage,loss_percentage_original,loss_quantity,activity,food_supply_stage,treatment,cause_of_loss,sample_size,method_data_collection,reference,url,notes
0,1,World,NaN,0111,Wheat,2022,1.0,1%,NaN,Processing,Processing,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived product is wheat flour
1,1,World,NaN,0112,Maize (corn),2022,0.5,0.5%,NaN,Processing,Processing,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived product is maize flour.
2,1,World,NaN,0112,Maize (corn),2022,2.0,2%,NaN,Processing,Processing,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived product is Maize (corn) grits.
3,1,World,NaN,0112,Maize (corn),2022,2.0,2%,NaN,Processing,Processing,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived product is Maize (corn) grits flaked.
4,1,World,NaN,0112,Maize (corn),2022,0.1,0.1%,NaN,Processing,Processing,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived product is corn starch.

,m49_code,country,region,cpc_code,commodity,year,loss_percentage,loss_percentage_original,loss_quantity,activity,food_supply_stage,treatment,cause_of_loss,sample_size,method_data_collection,reference,url,notes
31460,894,Zambia,NaN,0118,Millet,2000,2.38075,2.38075,NaN,Storage,Storage,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN
31461,894,Zambia,NaN,0118,Millet,2000,2.00000,2,NaN,"Shelling, Threshing",NaN,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN
31462,894,Zambia,NaN,0118,Millet,2000,2.50000,2.5,NaN,Transportation,Farm,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN
31463,894,Zambia,NaN,0118,Millet,2000,1.00000,1,NaN,Transportation,Transport,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN
31464,894,Zambia,NaN,0118,Millet,2000,2.50000,2.5,NaN,Winnowing,Farm,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN

,m49_code,country,region,cpc_code,commodity,year,loss_percentage,loss_percentage_original,loss_quantity,activity,food_supply_stage,treatment,cause_of_loss,sample_size,method_data_collection,reference,url,notes
27126,826,United Kingdom of Great Britain and Northern I...,NaN,01312,Bananas,2014,1.50,0–3%,NaN,Packaging,Packing,NaN,NaN,NaN,Survey,"Carlos Mena, Leon A. Terry, Adrian Williams; L...",NaN,NaN
17402,51,Armenia,NaN,01199.90,Other cereals n.e.,2012,4.17,4.17%,600,NaN,Whole supply chain,NaN,NaN,NaN,FAO's annual Agriculture Production Questionna...,FAO Sources,NaN,NaN
2320,180,Democratic Republic of the Congo,NaN,0118,Millet,2017,2.50,2.5,NaN,Winnowing,Farm,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN
25378,768,Togo,NaN,0114,Sorghum,2020,3.60,3.6,NaN,"Shelling, Threshing",NaN,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN
10883,384,Côte d'Ivoire,NaN,0112,Maize (corn),2021,4.00,4,NaN,Drying,Farm,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN

## **Analysis Columns**

In [7]:
print("COLUMN NAMES")
print(world_food_loss.columns.tolist())

print("\nDATA TYPES")
print(world_food_loss.dtypes)

print("\nDATASET INFO")
world_food_loss.info()

print("\nNUMERIC SUMMARY")
display(world_food_loss.describe().T)

print("\nALL COLUMNS SUMMARY")
display(world_food_loss.describe(include="all").T)

COLUMN NAMES
['m49_code', 'country', 'region', 'cpc_code', 'commodity', 'year', 'loss_percentage', 'loss_percentage_original', 'loss_quantity', 'activity', 'food_supply_stage', 'treatment', 'cause_of_loss', 'sample_size', 'method_data_collection', 'reference', 'url', 'notes']

DATA TYPES
m49_code                      int64
country                         str
region                          str
cpc_code                     string
commodity                       str
year                          int64
loss_percentage             float64
loss_percentage_original        str
loss_quantity                   str
activity                        str
food_supply_stage               str
treatment                       str
cause_of_loss                   str
sample_size                     str
method_data_collection          str
reference                       str
url                             str
notes                           str
dtype: object

DATASET INFO
<class 'pandas.DataFrame'>
RangeIndex: 31465 entries, 0 to 31464
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   m49_code                  31465 non-null  int64
 1   country                   31465 non-null  str
 2   region                    2036 non-null   str
 3   cpc_code                  31465 non-null  string
 4   commodity                 31465 non-null  str
 5   year                      31465 non-null  int64
 6   loss_percentage           31465 non-null  float64
 7   loss_percentage_original  31465 non-null  str
 8   loss_quantity             5050 non-null   str
 9   activity                  24095 non-null  str
 10  food_supply_stage         28074 non-null  str
 11  treatment                 1787 non-null   str
 12  cause_of_loss             1098 non-null   str
 13  sample_size               1862 non-null   str
 14  method_data_collection    31429 non-null  str
 15  reference                 31392 non-null  str
 16  url                       22123 non-null  str
 17  notes                     1534 non-null   str
dtypes: float64(1), int64(2), str(14), string(1)
memory usage: 4.3 MB

NUMERIC SUMMARY

,count,mean,std,min,25%,50%,75%,max
m49_code,31465.0,471.301637,260.948893,1.0,233.00000,454.00,710.00,894.0
year,31465.0,2010.610774,6.220568,2000.0,2005.00000,2011.00,2016.00,2026.0
loss_percentage,31465.0,4.683186,6.359491,0.0,1.49833,2.65,4.55,65.0

ALL COLUMNS SUMMARY

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
m49_code,31465.0,NaN,NaN,NaN,471.301637,260.948893,1.0,233.0,454.0,710.0,894.0
country,31465,159,United States of America,1716,NaN,NaN,NaN,NaN,NaN,NaN,NaN
region,2036,378,Western Cape Province,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cpc_code,31465,196,0112,6090,NaN,NaN,NaN,NaN,NaN,NaN,NaN
commodity,31465,213,Maize (corn),6090,NaN,NaN,NaN,NaN,NaN,NaN,NaN
year,31465.0,NaN,NaN,NaN,2010.610774,6.220568,2000.0,2005.0,2011.0,2016.0,2026.0
loss_percentage,31465.0,NaN,NaN,NaN,4.683186,6.359491,0.0,1.49833,2.65,4.55,65.0
loss_percentage_original,31465,5995,2.5,2309,NaN,NaN,NaN,NaN,NaN,NaN,NaN
loss_quantity,5050,3429,1000,74,NaN,NaN,NaN,NaN,NaN,NaN,NaN
activity,24095,180,Storage,6072,NaN,NaN,NaN,NaN,NaN,NaN,NaN
food_supply_stage,28074,20,Farm,10103,NaN,NaN,NaN,NaN,NaN,NaN,NaN
treatment,1787,764,Boro rice,57,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cause_of_loss,1098,406,Physical Losses,87,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sample_size,1862,266,933,159,NaN,NaN,NaN,NaN,NaN,NaN,NaN
method_data_collection,31429,11,Modelled Estimates,19497,NaN,NaN,NaN,NaN,NaN,NaN,NaN
reference,31392,328,"APHLIS, (2021), APHLIS",18922,NaN,NaN,NaN,NaN,NaN,NaN,NaN
url,22123,948,https://www.ers.usda.gov/data-products/food-av...,1196,NaN,NaN,NaN,NaN,NaN,NaN,NaN
notes,1534,586,Loss percentages obtained by dividing indicate...,72,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## **Analysis Missing values in Data-set**

In [8]:
missing_report = pd.DataFrame({
    "missing_count": world_food_loss.isna().sum(),
    "missing_percentage": world_food_loss.isna().mean().mul(100),
    "non_missing_count": world_food_loss.notna().sum(),
    "unique_non_null": world_food_loss.nunique(dropna=True)
})

missing_report = missing_report.sort_values(
    by="missing_percentage",
    ascending=False
)

display(missing_report)

,missing_count,missing_percentage,non_missing_count,unique_non_null
cause_of_loss,30367,96.510408,1098,406
notes,29931,95.124742,1534,586
treatment,29678,94.320674,1787,764
sample_size,29603,94.082314,1862,266
region,29429,93.529318,2036,378
loss_quantity,26415,83.950421,5050,3429
url,9342,29.690132,22123,948
activity,7370,23.422851,24095,180
food_supply_stage,3391,10.777054,28074,20
reference,73,0.232004,31392,328
method_data_collection,36,0.114413,31429,11
m49_code,0,0.000000,31465,157
country,0,0.000000,31465,159
loss_percentage,0,0.000000,31465,4629
cpc_code,0,0.000000,31465,196
loss_percentage_original,0,0.000000,31465,5995
commodity,0,0.000000,31465,213
year,0,0.000000,31465,27

### **Show "NA", "N/A", "NULL", "NONE", "UNKNOWN", "MISSING", "-" in string data-types**

In [9]:
import pandas as pd

missing_tokens = {
    "NA", "N/A", "NULL", "NONE",
    "UNKNOWN", "MISSING", "-", "NAN"
}

text_df = world_food_loss.select_dtypes(
    include=["object", "string"]
)

results = []

for col in text_df.columns:
    values = text_df[col].astype("string").str.strip()

    empty_count = values.eq("").sum()

    token_count = values.str.upper().isin(
        missing_tokens
    ).sum()

    actual_missing_count = values.isna().sum()

    results.append({
        "column": col,
        "empty_string_count": int(empty_count),
        "missing_token_count": int(token_count),
        "actual_missing_count": int(actual_missing_count)
    })

missing_report = (
    pd.DataFrame(results)
    .set_index("column")
    .sort_values(
        "actual_missing_count",
        ascending=False
    )
)

display(missing_report)

,empty_string_count,missing_token_count,actual_missing_count
column,,,
cause_of_loss,0,0,30367
notes,0,0,29931
treatment,0,0,29678
sample_size,0,6,29603
region,0,0,29429
loss_quantity,0,0,26415
url,0,0,9342
activity,0,0,7370
food_supply_stage,0,0,3391
reference,0,0,73
method_data_collection,0,0,36
commodity,0,0,0
loss_percentage_original,0,0,0
country,0,0,0
cpc_code,0,0,0

## **Show duplicated and unique data**

In [10]:
unique_report = pd.DataFrame({
    "unique_count": world_food_loss.nunique(dropna=True),
    "unique_with_nan": world_food_loss.nunique(dropna=False),
    "dtype": world_food_loss.dtypes.astype(str),
    "is_constant": world_food_loss.nunique(dropna=True).le(1)
})

display(unique_report.sort_values("unique_count"))

                          unique_count  unique_with_nan    dtype  is_constant
method_data_collection              11               12      str        False
food_supply_stage                   20               21      str        False
year                                27               27    int64        False
m49_code                           157              157    int64        False
country                            159              159      str        False
activity                           180              181      str        False
cpc_code                           196              196   string        False
commodity                          213              213      str        False
sample_size                        266              267      str        False
reference                          328              329      str        False
region                             378              379      str        False
cause_of_loss                      406              407      str        False
notes                              586              587      str        False
treatment                          764              765      str        False
url                                948              949      str        False
loss_quantity                     3429             3430      str        False
loss_percentage                   4629             4629  float64        False
loss_percentage_original          5995             5995      str        False

In [11]:
categorical_cols = world_food_loss.select_dtypes(
    include=["object", "string", "category"]
).columns

for col in categorical_cols:
    print(f"\n{'=' * 60}")
    print(f"Column: {col}")
    print("Unique values:", world_food_loss[col].nunique(dropna=True))
    print("Most frequent values:")
    display(world_food_loss[col].value_counts(dropna=False))

============================================================
Column: country
Unique values: 159
Most frequent values:

country
United States of America    1716
India                       1439
Ethiopia                    1151
Kenya                       1050
Ghana                        918
                            ...
Gabon                          1
Greece                         1
Bahrain                        1
Oman                           1
Saint Kitts and Nevis          1
Name: count, Length: 159, dtype: int64

============================================================
Column: region
Unique values: 378
Most frequent values:

region
NaN                                                  29429
Western Cape Province                                   59
Comilla                                                 45
Uttarakhand                                             42
Bawku, Wa  Tamale, Yendi , Techiman, and Kintampo       36
                                                     ...
Siliana                                                  1
Bizerte and Siliana                                      1
Apac Districy                                            1
California                                               1
Lusaka ans Southern Province                             1
Name: count, Length: 379, dtype: int64

============================================================
Column: cpc_code
Unique values: 196
Most frequent values:

cpc_code
0112        6090
0113        4880
0118        3686
0114        3531
0111        2379
            ...
01708          1
21181          1
21411          1
21439.02       1
21439.04       1
Name: count, Length: 196, dtype: Int64

============================================================
Column: commodity
Unique values: 213
Most frequent values:

commodity
Maize (corn)                                               6090
Rice                                                       4880
Millet                                                     3686
Sorghum                                                    3531
Wheat                                                      2379
                                                           ...
Bambara beans, dry                                            1
Pig meat, cuts, salted, dried or smoked (bacon and ham)       1
Raisins                                                       1
Juice of lemon                                                1
Juice of citrus fruit n.e.c.                                  1
Name: count, Length: 213, dtype: int64

============================================================
Column: loss_percentage_original
Unique values: 5995
Most frequent values:

loss_percentage_original
2.5        2309
3.5        1349
1          1280
2.65       1244
2           760
           ...
3.73079       1
2.30739       1
3.44008       1
1.27433       1
2.38075       1
Name: count, Length: 5995, dtype: int64

============================================================
Column: loss_quantity
Unique values: 3429
Most frequent values:

loss_quantity
NaN        26415
1000          74
0             56
3000          47
2000          46
           ...
2204           1
1276           1
2005           1
2482           1
2843.05        1
Name: count, Length: 3430, dtype: int64

============================================================
Column: activity
Unique values: 180
Most frequent values:

activity
NaN                                                                                    7370
Storage                                                                                6072
Transportation                                                                         5290
Drying, Harvesting                                                                     3500
Shelling, Threshing                                                                    3346
                                                                                       ...
Drying, Harvesting, Milling, Sorting, Storage, Threshing, Transportation, Winnowing       1
Sorting, Washing                                                                          1
Milling, Storage                                                                          1
Harvesting, Packaging, Sorting, Storage                                                   1
Farm, Milling                                                                             1
Name: count, Length: 181, dtype: int64

============================================================
Column: food_supply_stage
Unique values: 20
Most frequent values:

food_supply_stage
Farm                  10103
Whole supply chain     6147
Harvest                4160
NaN                    3391
Storage                3216
Transport              2091
Retail                  754
Processing              441
Wholesale               325
Households              248
Post-harvest            168
Trader                  107
Market                  101
Export                   50
Packing                  48
Distribution             39
Pre-harvest              24
Food Services            23
Collector                16
Grading                  12
Stacking                  1
Name: count, dtype: int64

============================================================
Column: treatment
Unique values: 764
Most frequent values:

treatment
NaN                                                                                                            29678
Boro rice                                                                                                         57
Aman rice                                                                                                         57
Major Season                                                                                                      54
Aus rice                                                                                                          48
                                                                                                               ...
Barley during 90 days at 28°C, 70% RH and 12h/12h light regime - Modified standard volume/dry-weight ratio         1
Barley during 90 days at 28°C, 70% RH and 12h/12h light regime - Grain count and weight                            1
Barley during 90 days at 28°C, 70% RH and 12h/12h light regime -  % damaged grains converted to weight loss        1
Barley during 90 days at 28°C, 70% RH and 12h/12h light regime -  1000 grain mass (TGM)                            1
Barley during 90 days at 28°C, 70% RH and 12h/12h light regime - TGM + dust                                        1
Name: count, Length: 765, dtype: int64

============================================================
Column: cause_of_loss
Unique values: 406
Most frequent values:

cause_of_loss
NaN                                                                                         30367
Physical Losses                                                                                87
Insect pest damage                                                                             54
main causes of this were a mismatch in supply and demand or cosmetic and quality related       41
Mechanical Damage                                                                              36
                                                                                            ...
Carotenoid Loss During Drying                                                                   1
Price Discount For Every One Bruchid Hole Per 100 Grains                                        1
Insects and mold                                                                                1
Insects, moisture and mold                                                                      1
Maize ear rot infection                                                                         1
Name: count, Length: 407, dtype: int64

============================================================
Column: sample_size
Unique values: 266
Most frequent values:

sample_size
NaN                                                                                                                                                        29603
933                                                                                                                                                          159
823 farmers                                                                                                                                                  112
10, planning project                                                                                                                                          93
600 stores from six large national and regional food retail chains                                                                                            91
                                                                                                                                                           ...
1520 Households                                                                                                                                                1
1301 Households                                                                                                                                                1
Table 1: On-farm post-harvest loss of maize limited on average and concentrated among few  National PHL among losers only  ( 11 months adjusted)  1,301        1
5 national and regional chains with  2,900 stores                                                                                                              1
114 farmsteads                                                                                                                                                 1
Name: count, Length: 267, dtype: int64

============================================================
Column: method_data_collection
Unique values: 11
Most frequent values:

method_data_collection
Modelled Estimates                                    19497
FAO's annual Agriculture Production Questionnaires     4209
Survey                                                 3220
Literature Review                                      1694
National Accounts                                      1275
Controlled Experiment                                   629
Case Study                                              528
No Data Collection Specified                            207
Expert Opinion                                          128
FLW Protocol                                             41
NaN                                                      36
Census                                                    1
Name: count, dtype: int64

============================================================
Column: reference
Unique values: 328
Most frequent values:

reference
APHLIS, (2021), APHLIS                                                                                                                                                          18922
FAO Sources                                                                                                                                                                      4209
USDA, (2021), USDA Food Loss                                                                                                                                                     1196
Jha SN; Vishwakarma RK; Ahmad T; Rai A; Dixit AK, (2015), Assessment Of Quantitative Harvest And Post-Harvest Losses Of Major Crops And Commodities In India                      428
S.K. Nanda; Rajesh Kumar Vishwakarma; H.V.L. Bathla; Poonam Chandra, (2012), Harvest And Post Harvest Losses Of Major Crops And Livestock Produce In India                        391
                                                                                                                                                                                ...
Tomlins et al.                                                                                                                                                                      1
Rees et al.                                                                                                                                                                         1
National Agricultural Statistics Service (NASS), (2011), Cattle And Calf Death Losses                                                                                               1
National Agricultural Statistics Service (NASS), (2006), Cattle And Calf Death Losses                                                                                               1
Mweshi Mukanga;John Derera;Pangirayi Tongoona;Mark D. Laing, (2010), A Survey Of Pre-Harvest Ear Rot Diseases Of Maize And Associated Mycotoxins In South And Central Zambia        1
Name: count, Length: 329, dtype: int64

============================================================
Column: url
Unique values: 948
Most frequent values:

url
NaN                                                                                                                                                                                      9342
https://www.ers.usda.gov/data-products/food-availability-per-capita-data-system/                                                                                                         1196
http://www.ciphet.in/upload/sphl/MOFPI%20REPORT1.pdf                                                                                                                                      428
https://www.researchgate.net/publication/280780214_Harvest_and_post_harvest_losses_of_major_crops_and_livestock_produce_in_India                                                          391
http://ucanr.edu/datastoreFiles/234-1847.pdf                                                                                                                                              226
                                                                                                                                                                                         ...
http://www.fao.org/fileadmin/user_upload/hlpe/hlpe_documents/Critical_Emerging_Issues/HLPE_Inquiry_Full_Proceedings__27-April-2014.pdf ; http://ucanr.edu/datastoreFiles/234-1847.pdf       1
https://www.researchgate.net/publication/267816160_Post-harvest_loss_in_sub-Saharan_Africa-what_do_farmers_say                                                                              1
https://ac.els-cdn.com/S0022474X1300101X/1-s2.0-S0022474X1300101X-main.pdf?_tid=7838d032-321c-4307-aedb-c3ae09ac7766&acdnat=1525860786_a8e0ced97dbaf2e10e043080c7f96a83                     1
http://usda.mannlib.cornell.edu/usda/current/CattDeath/CattDeath-05-12-2011.pdf                                                                                                             1
http://usda.mannlib.cornell.edu/usda/nass/CattDeath//2000s/2006/CattDeath-05-05-2006.pdf                                                                                                    1
Name: count, Length: 949, dtype: int64

============================================================
Column: notes
Unique values: 586
Most frequent values:

notes
NaN                                                                                                                     29931
Loss percentages obtained by dividing indicated losses by total resources and multiplying by 100%                          72
url not found                                                                                                              24
Review of databases and institutional libraries, relevant documentation of   studies conducted between 1980 and 2012       23
Food loss and waste                                                                                                        22
                                                                                                                        ...
The relative loss percentage is 9.9 ± 3.2 %                                                                                 1
The relative loss percentage is 10.1 ± 3.1 %                                                                                1
The relative loss percentage is 12.4 ± 3.5 %                                                                                1
Mean                                                                                                                        1
Sourced from Adams and Harman 1977                                                                                          1
Name: count, Length: 587, dtype: int64

In [12]:
print("Fully duplicated rows:", world_food_loss.duplicated().sum())

print(
    "Duplicated rows including all copies:",
    world_food_loss.duplicated(keep=False).sum()
)

duplicates = world_food_loss[
    world_food_loss.duplicated(keep=False)
].sort_values(by=world_food_loss.columns.tolist())

display(duplicates.head(20))

Fully duplicated rows: 180
Duplicated rows including all copies: 339

,m49_code,country,region,cpc_code,commodity,year,loss_percentage,loss_percentage_original,loss_quantity,activity,food_supply_stage,treatment,cause_of_loss,sample_size,method_data_collection,reference,url,notes
16249,50,Bangladesh,NaN,0113,Rice,2010,1.30,1.3,NaN,NaN,Processing,NaN,NaN,NaN,Modelled Estimates,Mst. Esmat Ara Begum; Mohammad Ismail Hossain;...,http://www.setscholars.org/index.php/ijarbae,NaN
16252,50,Bangladesh,NaN,0113,Rice,2010,1.30,1.3,NaN,NaN,Processing,NaN,NaN,NaN,Modelled Estimates,Mst. Esmat Ara Begum; Mohammad Ismail Hossain;...,http://www.setscholars.org/index.php/ijarbae,NaN
16123,50,Bangladesh,NaN,01312,Bananas,2010,3.20,3.2,NaN,NaN,Retail,NaN,NaN,100,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16125,50,Bangladesh,NaN,01312,Bananas,2010,3.20,3.2,NaN,NaN,Retail,NaN,NaN,100,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16121,50,Bangladesh,NaN,01312,Bananas,2010,5.10,5.1,NaN,NaN,Trader,NaN,NaN,100,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16122,50,Bangladesh,NaN,01312,Bananas,2010,5.10,5.1,NaN,NaN,Trader,NaN,NaN,100,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16120,50,Bangladesh,NaN,01312,Bananas,2010,7.70,7.7,NaN,NaN,Farm,NaN,NaN,100,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16126,50,Bangladesh,NaN,01312,Bananas,2010,7.70,7.7,NaN,NaN,Farm,NaN,NaN,100,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16124,50,Bangladesh,NaN,01312,Bananas,2010,8.60,8.6,NaN,NaN,Wholesale,NaN,NaN,100,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16130,50,Bangladesh,NaN,01312,Bananas,2010,8.60,8.6,NaN,NaN,Wholesale,NaN,NaN,100,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16166,50,Bangladesh,NaN,01319,"Other tropical and subtropical fruits, n.e.c.",2010,5.11,5.11,NaN,NaN,Trader,NaN,NaN,100,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16168,50,Bangladesh,NaN,01319,"Other tropical and subtropical fruits, n.e.c.",2010,5.11,5.11,NaN,NaN,Trader,NaN,NaN,100,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16165,50,Bangladesh,NaN,01319,"Other tropical and subtropical fruits, n.e.c.",2010,5.14,5.14,NaN,NaN,Retail,NaN,NaN,100,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16167,50,Bangladesh,NaN,01319,"Other tropical and subtropical fruits, n.e.c.",2010,5.14,5.14,NaN,NaN,Retail,NaN,NaN,100,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16164,50,Bangladesh,NaN,01319,"Other tropical and subtropical fruits, n.e.c.",2010,6.10,6.1,NaN,NaN,Wholesale,NaN,NaN,75,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16171,50,Bangladesh,NaN,01319,"Other tropical and subtropical fruits, n.e.c.",2010,6.10,6.1,NaN,NaN,Wholesale,NaN,NaN,75,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16169,50,Bangladesh,NaN,01319,"Other tropical and subtropical fruits, n.e.c.",2010,8.51,8.51,NaN,NaN,Farm,NaN,NaN,120,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16176,50,Bangladesh,NaN,01319,"Other tropical and subtropical fruits, n.e.c.",2010,8.51,8.51,NaN,NaN,Farm,NaN,NaN,120,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16180,50,Bangladesh,NaN,01323,Oranges,2010,4.00,4,NaN,NaN,Wholesale,NaN,NaN,50,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16184,50,Bangladesh,NaN,01323,Oranges,2010,4.00,4,NaN,NaN,Wholesale,NaN,NaN,50,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN

## **Describe numeric data**

In [13]:
numeric_cols = world_food_loss.select_dtypes(
    include=np.number
).columns

numeric_report = pd.DataFrame(index=numeric_cols)

numeric_report["missing"] = world_food_loss[numeric_cols].isna().sum()
numeric_report["unique"] = world_food_loss[numeric_cols].nunique()
numeric_report["min"] = world_food_loss[numeric_cols].min()
numeric_report["max"] = world_food_loss[numeric_cols].max()
numeric_report["mean"] = world_food_loss[numeric_cols].mean()
numeric_report["median"] = world_food_loss[numeric_cols].median()
numeric_report["std"] = world_food_loss[numeric_cols].std()
numeric_report["negative_count"] = world_food_loss[numeric_cols].lt(0).sum()

display(numeric_report)

,missing,unique,min,max,mean,median,std,negative_count
m49_code,0,157,1.0,894.0,471.301637,454.00,260.948893,0
year,0,27,2000.0,2026.0,2010.610774,2011.00,6.220568,0
loss_percentage,0,4629,0.0,65.0,4.683186,2.65,6.359491,0

## **Show ouliers**

In [14]:
outlier_rows = []

for col in numeric_cols:
    series = world_food_loss[col].dropna()

    if series.empty:
        continue

    q1 = series.quantile(0.25)
    q3 = series.quantile(0.75)
    iqr = q3 - q1

    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr

    mask = (world_food_loss[col] < lower_bound) | (
        world_food_loss[col] > upper_bound
    )

    outlier_rows.append({
        "column": col,
        "lower_bound": lower_bound,
        "upper_bound": upper_bound,
        "outlier_count": int(mask.sum()),
        "outlier_percentage": round(mask.mean() * 100, 2)
    })

outlier_report = pd.DataFrame(outlier_rows)
display(outlier_report)

,column,lower_bound,upper_bound,outlier_count,outlier_percentage
0,m49_code,-482.500000,1425.500000,0,0.0
1,year,1988.500000,2032.500000,0,0.0
2,loss_percentage,-3.079175,9.127505,3555,11.3

## **Show final columns**

In [15]:
print(world_food_loss.columns.tolist())

['m49_code', 'country', 'region', 'cpc_code', 'commodity', 'year', 'loss_percentage', 'loss_percentage_original', 'loss_quantity', 'activity', 'food_supply_stage', 'treatment', 'cause_of_loss', 'sample_size', 'method_data_collection', 'reference', 'url', 'notes']

## **Data quality check on the Year**

In [16]:
if "year" in world_food_loss.columns:
    print("Invalid or suspicious years:")
    display(
        world_food_loss.loc[
            ~world_food_loss["year"].between(1900, 2100),
            ["year"]
        ].head(20)
    )

Invalid or suspicious years:

Empty DataFrame
Columns: [year]
Index: []

## **Finally analysis of data**

In [17]:
quality_report = pd.DataFrame(index=world_food_loss.columns)

quality_report["dtype"] = world_food_loss.dtypes.astype(str)
quality_report["total_rows"] = len(world_food_loss)
quality_report["missing_count"] = world_food_loss.isna().sum()
quality_report["missing_pct"] = (
    world_food_loss.isna().mean() * 100
).round(2)

quality_report["unique_count"] = world_food_loss.nunique(dropna=True)
quality_report["unique_pct"] = (
    world_food_loss.nunique(dropna=True) / max(len(world_food_loss), 1) * 100
).round(2)

quality_report["duplicate_row_count"] = world_food_loss.duplicated().sum()
quality_report["memory_bytes"] = world_food_loss.memory_usage(deep=True).iloc[1:].values

display(quality_report)

,dtype,total_rows,missing_count,missing_pct,unique_count,unique_pct,duplicate_row_count,memory_bytes
m49_code,int64,31465,0,0.00,157,0.50,180,251720
country,str,31465,0,0.00,159,0.51,180,1852077
region,str,31465,29429,93.53,378,1.20,180,1085553
cpc_code,string,31465,0,0.00,196,0.62,180,1681711
commodity,str,31465,0,0.00,213,0.68,180,1848523
year,int64,31465,0,0.00,27,0.09,180,251720
loss_percentage,float64,31465,0,0.00,4629,14.71,180,251720
loss_percentage_original,str,31465,0,0.00,5995,19.05,180,1680265
loss_quantity,str,31465,26415,83.95,3429,10.90,180,1118501
activity,str,31465,7370,23.42,180,0.57,180,1735342
food_supply_stage,str,31465,3391,10.78,20,0.06,180,1725153
treatment,str,31465,29678,94.32,764,2.43,180,1112143
cause_of_loss,str,31465,30367,96.51,406,1.29,180,1130002
sample_size,str,31465,29603,94.08,266,0.85,180,1136945
method_data_collection,str,31465,36,0.11,11,0.03,180,2198937
reference,str,31465,73,0.23,328,1.04,180,3265963
url,str,31465,9342,29.69,948,3.01,180,3367226
notes,str,31465,29931,95.12,586,1.86,180,1235020

## **Result of analysis**

## **Solution of these problems**

### **1. Convert "cpc_code" column to <"string type">**

In [18]:
# Keep CPC codes as strings throughout the cleaning process.
world_food_loss["cpc_code"] = world_food_loss["cpc_code"].astype("string").str.strip()

In [19]:
print(world_food_loss["cpc_code"].dtype)

string

### **2. Drop columns "sample_size" and "cause_of_loss" columns**

In [20]:
world_food_loss = world_food_loss.drop(
    columns=['sample_size', 'cause_of_loss']
)

In [21]:
world_food_loss.columns.tolist()

['m49_code',
 'country',
 'region',
 'cpc_code',
 'commodity',
 'year',
 'loss_percentage',
 'loss_percentage_original',
 'loss_quantity',
 'activity',
 'food_supply_stage',
 'treatment',
 'method_data_collection',
 'reference',
 'url',
 'notes']

### **3. Drop column "m49_code"**

In [22]:
world_food_loss = world_food_loss.drop(
    columns=['m49_code']
)

In [23]:
world_food_loss.columns.tolist()

['country',
 'region',
 'cpc_code',
 'commodity',
 'year',
 'loss_percentage',
 'loss_percentage_original',
 'loss_quantity',
 'activity',
 'food_supply_stage',
 'treatment',
 'method_data_collection',
 'reference',
 'url',
 'notes']

### **4. Drop column "url"**

In [24]:
world_food_loss = world_food_loss.drop(
    columns=['url']
)

world_food_loss.columns.tolist()

['country',
 'region',
 'cpc_code',
 'commodity',
 'year',
 'loss_percentage',
 'loss_percentage_original',
 'loss_quantity',
 'activity',
 'food_supply_stage',
 'treatment',
 'method_data_collection',
 'reference',
 'notes']

### **5. Drop duplicated data**

In [25]:
world_food_loss= world_food_loss.drop_duplicates()

### **6. Separate loss_quality to 2 columns since the Unit**

In [26]:
q = world_food_loss["loss_quantity"].astype("string").str.strip()

is_per_ha  = q.str.contains("/ha", na=False)        # "0.61ton/ha"
is_million = q.str.contains(r"\bM\b", na=False)     # "4.4 M tonnes"
num = pd.to_numeric(q.str.extract(r"([\d.]+)")[0], errors="coerce")

world_food_loss["loss_tonnes"] = np.where(
    is_per_ha, np.nan,
    np.where(is_million, num * 1_000_000, num)
)
world_food_loss["loss_tonnes_per_ha"] = np.where(is_per_ha, num, np.nan)

world_food_loss = world_food_loss.drop(columns="loss_quantity")

### **7. Classify Geographic Levels and Extract Governorate Names**

In [27]:
world_food_loss["region"] = world_food_loss["region"].replace({"Bani Suef": "Beni Suef"})   

regions3 = ["Lower Egypt", "Middle Egypt", "Upper Egypt"]

world_food_loss["geo_level"] = np.select(
    [world_food_loss["region"].isna() | world_food_loss["region"].eq("National average"),
     world_food_loss["region"].isin(regions3)],
    ["National", "Region"],
    default="Governorate/Area"
)

world_food_loss["governorate"] = (
    world_food_loss["region"].str.replace(r"\s*\(.*\)", "", regex=True)
    .where(world_food_loss["geo_level"].eq("Governorate/Area"))
)

In [28]:
world_food_loss.head(10)

,country,region,cpc_code,commodity,year,loss_percentage,loss_percentage_original,activity,food_supply_stage,treatment,method_data_collection,reference,notes,loss_tonnes,loss_tonnes_per_ha,geo_level,governorate
0,World,NaN,0111,Wheat,2022,1.0,1%,Processing,Processing,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",Derived product is wheat flour,NaN,NaN,National,NaN
1,World,NaN,0112,Maize (corn),2022,0.5,0.5%,Processing,Processing,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",Derived product is maize flour.,NaN,NaN,National,NaN
2,World,NaN,0112,Maize (corn),2022,2.0,2%,Processing,Processing,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",Derived product is Maize (corn) grits.,NaN,NaN,National,NaN
3,World,NaN,0112,Maize (corn),2022,2.0,2%,Processing,Processing,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",Derived product is Maize (corn) grits flaked.,NaN,NaN,National,NaN
4,World,NaN,0112,Maize (corn),2022,0.1,0.1%,Processing,Processing,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",Derived product is corn starch.,NaN,NaN,National,NaN
5,World,NaN,0112,Maize (corn),2022,2.0,2%,Processing,Processing,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",Derived product is undenaturated ethyl alcohol.,NaN,NaN,National,NaN
6,World,NaN,0113,Rice,2022,2.5,2.5%,Processing,Processing,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",Derived product is milled rice.,NaN,NaN,National,NaN
7,World,NaN,0114,Sorghum,2022,0.5,0.5%,Processing,Processing,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",Derived product is flour of sorghum.,NaN,NaN,National,NaN
8,World,NaN,0115,Barley,2022,12.0,12%,Processing,Processing,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",Derived product is barley malt,NaN,NaN,National,NaN
9,World,NaN,0115,Barley,2022,2.0,2%,Processing,Processing,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",Derived product is pot barley,NaN,NaN,National,NaN

In [29]:
world_food_loss = world_food_loss.drop(columns=["region"])

### **8. Handle names of treatment**

In [30]:
treatment_map = {
    "Use of manual harvesting":       "Manual harvesting",
    "Manual harvest":                 "Manual harvesting",
    "Use of reapers for harvesting":  "Reaper (unspecified)",
    "Use of combine harvesters":      "Combine harvester",
    "Sorage on farm":                 "Storage on farm",
}
world_food_loss["treatment"] = world_food_loss["treatment"].replace(treatment_map)

In [31]:
world_food_loss.governorate.value_counts()

governorate
Western Cape Province                                59
Comilla                                              45
Uttarakhand                                          42
Bawku, Wa  Tamale, Yendi , Techiman, and Kintampo    36
Rangpur and Dinazpur district                        36
                                                     ..
Siliana                                               1
Bizerte and Siliana                                   1
Apac Districy                                         1
California                                            1
Lusaka ans Southern Province                          1
Name: count, Length: 372, dtype: int64

In [32]:
world_food_loss.treatment.value_counts()

treatment
Boro rice                                                                                                      57
Aman rice                                                                                                      57
Major Season                                                                                                   54
Aus rice                                                                                                       48
Major season                                                                                                   45
                                                                                                               ..
Barley during 90 days at 28°C, 70% RH and 12h/12h light regime - Modified standard volume/dry-weight ratio      1
Barley during 90 days at 28°C, 70% RH and 12h/12h light regime - Grain count and weight                         1
Barley during 90 days at 28°C, 70% RH and 12h/12h light regime -  % damaged grains converted to weight loss     1
Barley during 90 days at 28°C, 70% RH and 12h/12h light regime -  1000 grain mass (TGM)                         1
Barley during 90 days at 28°C, 70% RH and 12h/12h light regime - TGM + dust                                     1
Name: count, Length: 761, dtype: int64

### **11/12. handle flag outliers**

In [33]:
world_food_loss["is_suspect_year"] = world_food_loss.year > 2025

In [34]:
world_food_loss["is_lit_outlier"] = (world_food_loss.method_data_collection == "Literature Review") & (world_food_loss.loss_percentage > 22.56)

In [35]:
world_food_loss.head()

,country,cpc_code,commodity,year,loss_percentage,loss_percentage_original,activity,food_supply_stage,treatment,method_data_collection,reference,notes,loss_tonnes,loss_tonnes_per_ha,geo_level,governorate,is_suspect_year,is_lit_outlier
0,World,0111,Wheat,2022,1.0,1%,Processing,Processing,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",Derived product is wheat flour,NaN,NaN,National,NaN,False,False
1,World,0112,Maize (corn),2022,0.5,0.5%,Processing,Processing,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",Derived product is maize flour.,NaN,NaN,National,NaN,False,False
2,World,0112,Maize (corn),2022,2.0,2%,Processing,Processing,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",Derived product is Maize (corn) grits.,NaN,NaN,National,NaN,False,False
3,World,0112,Maize (corn),2022,2.0,2%,Processing,Processing,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",Derived product is Maize (corn) grits flaked.,NaN,NaN,National,NaN,False,False
4,World,0112,Maize (corn),2022,0.1,0.1%,Processing,Processing,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",Derived product is corn starch.,NaN,NaN,National,NaN,False,False

### **13. Standardize Food Supply Stages and Remove Redundant Activity Column**

In [36]:
world_food_loss.loc[:, ["food_supply_stage", "activity"]].value_counts()

food_supply_stage   activity
Harvest             Drying, Harvesting                           3500
Farm                Transportation                               3367
                    Storage                                      3295
Storage             Storage                                      2685
Transport           Transportation                               1918
                                                                 ...
Retail              Marketing                                       1
Market              Marketing, Transportation                       1
                    Marketing, Wholesale                            1
Farm                Farm, Milling                                   1
Whole supply chain  Farm, Processing, Storage, Transportation       1
Name: count, Length: 265, dtype: int64

In [37]:
stage_map = {
    "Farm": "Farm/Harvest", "Harvest": "Farm/Harvest",
    "Trader": "Wholesale/Market", "Wholesale": "Wholesale/Market", "Market": "Wholesale/Market",
}
world_food_loss["food_supply_stage"] = world_food_loss["food_supply_stage"].replace(stage_map)

world_food_loss = world_food_loss.drop(columns="activity")

In [38]:
world_food_loss.head()

,country,cpc_code,commodity,year,loss_percentage,loss_percentage_original,food_supply_stage,treatment,method_data_collection,reference,notes,loss_tonnes,loss_tonnes_per_ha,geo_level,governorate,is_suspect_year,is_lit_outlier
0,World,0111,Wheat,2022,1.0,1%,Processing,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",Derived product is wheat flour,NaN,NaN,National,NaN,False,False
1,World,0112,Maize (corn),2022,0.5,0.5%,Processing,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",Derived product is maize flour.,NaN,NaN,National,NaN,False,False
2,World,0112,Maize (corn),2022,2.0,2%,Processing,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",Derived product is Maize (corn) grits.,NaN,NaN,National,NaN,False,False
3,World,0112,Maize (corn),2022,2.0,2%,Processing,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",Derived product is Maize (corn) grits flaked.,NaN,NaN,National,NaN,False,False
4,World,0112,Maize (corn),2022,0.1,0.1%,Processing,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",Derived product is corn starch.,NaN,NaN,National,NaN,False,False

### **14. Classify Measurement Scope and Analyze Food Supply Stages**

In [39]:
world_food_loss.food_supply_stage.value_counts()

food_supply_stage
Farm/Harvest          14251
Whole supply chain     6005
Storage                3210
Transport              2090
Retail                  747
Wholesale/Market        523
Processing              437
Households              247
Post-harvest            168
Export                   50
Packing                  48
Distribution             39
Pre-harvest              24
Food Services            23
Collector                16
Grading                  12
Stacking                  1
Name: count, dtype: int64

In [40]:
# Separate whole-chain, stage-level, and unknown-scope records.
# Missing food-supply-stage values are retained and explicitly classified as Unknown;
# they must not silently be treated as single-stage observations.
world_food_loss["measurement_scope"] = np.select(
    [world_food_loss["food_supply_stage"].eq("Whole supply chain"),
     world_food_loss["food_supply_stage"].eq("Post-harvest"),
     world_food_loss["food_supply_stage"].isna()],
    ["Whole chain", "Post-harvest (aggregate)", "Unknown"],
    default="Single stage"
)
whole_chain_world_food_loss = world_food_loss[world_food_loss["measurement_scope"].eq("Whole chain")]
stage_world_food_loss = world_food_loss[world_food_loss["measurement_scope"].eq("Single stage")]
unknown_scope_world_food_loss = world_food_loss[world_food_loss["measurement_scope"].eq("Unknown")]

In [41]:
world_food_loss.head()

,country,cpc_code,commodity,year,loss_percentage,loss_percentage_original,food_supply_stage,treatment,method_data_collection,reference,notes,loss_tonnes,loss_tonnes_per_ha,geo_level,governorate,is_suspect_year,is_lit_outlier,measurement_scope
0,World,0111,Wheat,2022,1.0,1%,Processing,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",Derived product is wheat flour,NaN,NaN,National,NaN,False,False,Single stage
1,World,0112,Maize (corn),2022,0.5,0.5%,Processing,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",Derived product is maize flour.,NaN,NaN,National,NaN,False,False,Single stage
2,World,0112,Maize (corn),2022,2.0,2%,Processing,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",Derived product is Maize (corn) grits.,NaN,NaN,National,NaN,False,False,Single stage
3,World,0112,Maize (corn),2022,2.0,2%,Processing,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",Derived product is Maize (corn) grits flaked.,NaN,NaN,National,NaN,False,False,Single stage
4,World,0112,Maize (corn),2022,0.1,0.1%,Processing,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",Derived product is corn starch.,NaN,NaN,National,NaN,False,False,Single stage

### **Show result yet**

In [42]:
world_food_loss.shape

(31282, 18)

In [43]:
world_food_loss.columns.tolist()

['country',
 'cpc_code',
 'commodity',
 'year',
 'loss_percentage',
 'loss_percentage_original',
 'food_supply_stage',
 'treatment',
 'method_data_collection',
 'reference',
 'notes',
 'loss_tonnes',
 'loss_tonnes_per_ha',
 'geo_level',
 'governorate',
 'is_suspect_year',
 'is_lit_outlier',
 'measurement_scope']

In [44]:
quality_report = pd.DataFrame(index=world_food_loss.columns)

quality_report["dtype"] = world_food_loss.dtypes.astype(str)
quality_report["total_rows"] = len(world_food_loss)
quality_report["missing_count"] = world_food_loss.isna().sum()
quality_report["missing_pct"] = (
    world_food_loss.isna().mean() * 100
).round(2)

quality_report["unique_count"] = world_food_loss.nunique(dropna=True)
quality_report["unique_pct"] = (
    world_food_loss.nunique(dropna=True) / max(len(world_food_loss), 1) * 100
).round(2)

quality_report["duplicate_row_count"] = world_food_loss.duplicated().sum()
quality_report["memory_bytes"] = world_food_loss.memory_usage(deep=True).iloc[1:].values

display(quality_report)

,dtype,total_rows,missing_count,missing_pct,unique_count,unique_pct,duplicate_row_count,memory_bytes
country,str,31282,0,0.00,159,0.51,452,1839403
cpc_code,string,31282,0,0.00,196,0.63,452,1671830
commodity,str,31282,0,0.00,213,0.68,452,1836204
year,int64,31282,0,0.00,27,0.09,452,250256
loss_percentage,float64,31282,0,0.00,4629,14.80,452,250256
loss_percentage_original,str,31282,0,0.00,5995,19.16,452,1670929
food_supply_stage,str,31282,3391,10.84,17,0.05,452,1819162
treatment,str,31282,29499,94.30,761,2.43,452,1105987
method_data_collection,str,31282,36,0.12,11,0.04,452,2187063
reference,str,31282,73,0.23,328,1.05,452,3245087
notes,str,31282,29749,95.10,586,1.87,452,1229119
loss_tonnes,float64,31282,26251,83.92,3223,10.30,452,250256
loss_tonnes_per_ha,float64,31282,31263,99.94,18,0.06,452,250256
geo_level,str,31282,0,0.00,3,0.01,452,1799168
governorate,str,31282,29268,93.56,372,1.19,452,1078292
is_suspect_year,bool,31282,0,0.00,2,0.01,452,31282
is_lit_outlier,bool,31282,0,0.00,2,0.01,452,31282
measurement_scope,str,31282,0,0.00,4,0.01,452,1887258

# **Step 2: Finalize the dataset (flags + missing values + validation + save)**

### **1. Fix `cpc_code` (restore leading zeros) and drop constant `country`**

In [45]:
# Normalize CPC codes while preserving leading zeros.
# Some CSV exports store codes such as 0111 as 111.0; other valid codes have
# five digits and/or a two-digit decimal subcode.
s = world_food_loss["cpc_code"].astype("string").str.strip()
s = s.str.replace(r"\.0$", "", regex=True)
world_food_loss["cpc_code"] = s.where(
    s.isna() | s.str.startswith("0"),
    "0" + s
)

# country is constant in this Egypt extract and adds no analytical information.
world_food_loss = world_food_loss.drop(columns=["country"], errors="ignore")
print(world_food_loss["cpc_code"].dropna().unique())

<StringArray>
[     '0111',      '0112',      '0113',      '0114',      '0115',      '0116',
      '0117',      '0118',     '01192',  '01199.90',
 ...
    '021124',    '021182',     '01492', '023120.03', '039120.04', '021113.02',
    '021151',    '021153', '021511.02',    '021512']
Length: 196, dtype: string

## 2) Flags 13, 14, 15 (suspicious rows: flag them, do not delete)

In [46]:
df = world_food_loss

# --- 13) New Valley row identical to a National row (same crop/year/stage/value) -> probably copied
key = ["commodity", "year", "food_supply_stage", "loss_percentage"]
national_keys = set(map(tuple, df.loc[df["geo_level"].eq("National"), key].values))
df["is_new_valley_copy"] = (
    df["governorate"].eq("New Valley")
    & df[key].apply(tuple, axis=1).isin(national_keys)
)

# --- 14) Value 5x higher or 5x lower than the crop's median (whole-chain rows only)
whole = df["food_supply_stage"].eq("Whole supply chain")
med   = df.loc[whole].groupby("commodity")["loss_percentage"].transform("median")
ratio = (df["loss_percentage"] / med).reindex(df.index)
df["is_suspect_value"] = whole & med.reindex(df.index).gt(0) & ((ratio < 0.2) | (ratio > 5))

# --- 15) Zero loss (Lupins): real zero or "not reported"?  Keep original, add a clean column
df["is_zero_loss"] = df["loss_percentage"].eq(0)
df["loss_percentage_clean"] = df["loss_percentage"].mask(df["is_zero_loss"])

world_food_loss = df
print(df[["is_suspect_year", "is_lit_outlier", "is_new_valley_copy",
          "is_suspect_value", "is_zero_loss"]].sum())
display(df.loc[df["is_suspect_value"] | df["is_new_valley_copy"],
               ["commodity", "year", "food_supply_stage", "governorate", "loss_percentage"]])

is_suspect_year         5
is_lit_outlier        230
is_new_valley_copy      2
is_suspect_value      765
is_zero_loss           60
dtype: int64

,commodity,year,food_supply_stage,governorate,loss_percentage
111,Wheat,2019,Whole supply chain,NaN,14.50
112,Maize (corn),2019,Whole supply chain,NaN,18.00
555,Raw milk of cattle,2007,Whole supply chain,NaN,0.01
556,Raw milk of cattle,2006,Whole supply chain,NaN,0.02
557,Raw milk of cattle,2005,Whole supply chain,NaN,0.02
...,...,...,...,...,...
30638,Sesame seed,2001,Whole supply chain,NaN,0.30
30658,Refined sugar,2001,Whole supply chain,NaN,0.01
30676,Sesame seed,2000,Whole supply chain,NaN,0.36
30697,Refined sugar,2000,Whole supply chain,NaN,0.02
30916,Sorghum,2015,Whole supply chain,NaN,35.00

## 3) Handle missing values
| Column | Why missing | Action |
|---|---|---|
| `treatment` | only recorded for wheat harvest/storage | fill with label **"Not specified"** |
| `governorate` | row is national or regional | fill with label **"Not applicable"** |
| `notes` | no note in source | fill with label **"No note"** |
| `loss_tonnes` | source did not report quantity | **keep NaN** + indicator column |
| `loss_tonnes_per_ha` | only wheat harvest rows | **keep NaN** + indicator column |
| `loss_percentage_clean` | zero values turned into NaN | **keep NaN** |

Numeric columns are NOT imputed (mean/median would invent loss quantities that no source reported).

In [47]:
df = world_food_loss

# indicator columns (so you always know which values were really reported)
df["has_loss_tonnes"]        = df["loss_tonnes"].notna()
df["has_loss_tonnes_per_ha"] = df["loss_tonnes_per_ha"].notna()

# categorical columns -> explicit labels (NaN means "not applicable", not "lost data")
df["treatment"]   = df["treatment"].fillna("Not specified")
df["governorate"] = df["governorate"].fillna("Not applicable")
df["notes"]       = df["notes"].fillna("No note")

# one simple column to filter reliable rows for the main analysis
# (literature outliers are NOT excluded: they are valid but lower-quality data, so keep them flagged)
df["is_reliable"] = ~(df["is_suspect_year"] | df["is_new_valley_copy"]
                      | df["is_suspect_value"] | df["is_zero_loss"])

world_food_loss = df
print("Reliable rows:", int(df["is_reliable"].sum()), "of", len(df))
display(df.isna().sum()[lambda s: s > 0])

Reliable rows: 30509 of 31282

food_supply_stage          3391
method_data_collection       36
reference                    73
loss_tonnes               26251
loss_tonnes_per_ha        31263
loss_percentage_clean        60
dtype: int64

## 4) Types, column order, validation

In [48]:
df = world_food_loss

duplicate_count = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

Number of duplicate rows: 13501

In [49]:
duplicates = df[df.duplicated(keep=False)].sort_values(
    by=["cpc_code", "commodity", "year"]
)

display(duplicates.head(20))

,cpc_code,commodity,year,loss_percentage,loss_percentage_original,food_supply_stage,treatment,method_data_collection,reference,notes,...,is_suspect_year,is_lit_outlier,measurement_scope,is_new_valley_copy,is_suspect_value,is_zero_loss,loss_percentage_clean,has_loss_tonnes,has_loss_tonnes_per_ha,is_reliable
528,0111,Wheat,2000,4.43333,4.43333,Farm/Harvest,Not specified,Modelled Estimates,"APHLIS, (2021), APHLIS",No note,...,False,False,Single stage,False,False,False,4.43333,False,False,True
529,0111,Wheat,2000,4.86667,4.86667,Farm/Harvest,Not specified,Modelled Estimates,"APHLIS, (2021), APHLIS",No note,...,False,False,Single stage,False,False,False,4.86667,False,False,True
530,0111,Wheat,2000,3.50000,3.5,NaN,Not specified,Modelled Estimates,"APHLIS, (2021), APHLIS",No note,...,False,False,Unknown,False,False,False,3.50000,False,False,True
531,0111,Wheat,2000,2.50000,2.5,Farm/Harvest,Not specified,Modelled Estimates,"APHLIS, (2021), APHLIS",No note,...,False,False,Single stage,False,False,False,2.50000,False,False,True
1916,0111,Wheat,2000,4.43333,4.43333,Farm/Harvest,Not specified,Modelled Estimates,"APHLIS, (2021), APHLIS",No note,...,False,False,Single stage,False,False,False,4.43333,False,False,True
1917,0111,Wheat,2000,3.10000,3.1,Farm/Harvest,Not specified,Modelled Estimates,"APHLIS, (2021), APHLIS",No note,...,False,False,Single stage,False,False,False,3.10000,False,False,True
1918,0111,Wheat,2000,3.50000,3.5,NaN,Not specified,Modelled Estimates,"APHLIS, (2021), APHLIS",No note,...,False,False,Unknown,False,False,False,3.50000,False,False,True
1919,0111,Wheat,2000,2.50000,2.5,Farm/Harvest,Not specified,Modelled Estimates,"APHLIS, (2021), APHLIS",No note,...,False,False,Single stage,False,False,False,2.50000,False,False,True
4790,0111,Wheat,2000,4.43333,4.43333,Farm/Harvest,Not specified,Modelled Estimates,"APHLIS, (2021), APHLIS",No note,...,False,False,Single stage,False,False,False,4.43333,False,False,True
4792,0111,Wheat,2000,2.65000,2.65,Storage,Not specified,Modelled Estimates,"APHLIS, (2021), APHLIS",No note,...,False,False,Single stage,False,False,False,2.65000,False,False,True
4793,0111,Wheat,2000,3.50000,3.5,NaN,Not specified,Modelled Estimates,"APHLIS, (2021), APHLIS",No note,...,False,False,Unknown,False,False,False,3.50000,False,False,True
4794,0111,Wheat,2000,2.50000,2.5,Farm/Harvest,Not specified,Modelled Estimates,"APHLIS, (2021), APHLIS",No note,...,False,False,Single stage,False,False,False,2.50000,False,False,True
4795,0111,Wheat,2000,1.00000,1,Transport,Not specified,Modelled Estimates,"APHLIS, (2021), APHLIS",No note,...,False,False,Single stage,False,False,False,1.00000,False,False,True
5275,0111,Wheat,2000,4.43333,4.43333,Farm/Harvest,Not specified,Modelled Estimates,"APHLIS, (2021), APHLIS",No note,...,False,False,Single stage,False,False,False,4.43333,False,False,True
5276,0111,Wheat,2000,3.10000,3.1,Farm/Harvest,Not specified,Modelled Estimates,"APHLIS, (2021), APHLIS",No note,...,False,False,Single stage,False,False,False,3.10000,False,False,True
5277,0111,Wheat,2000,3.50000,3.5,NaN,Not specified,Modelled Estimates,"APHLIS, (2021), APHLIS",No note,...,False,False,Unknown,False,False,False,3.50000,False,False,True
5278,0111,Wheat,2000,2.50000,2.5,Farm/Harvest,Not specified,Modelled Estimates,"APHLIS, (2021), APHLIS",No note,...,False,False,Single stage,False,False,False,2.50000,False,False,True
6034,0111,Wheat,2000,5.75000,5.75,Farm/Harvest,Not specified,Modelled Estimates,"APHLIS, (2021), APHLIS",No note,...,False,False,Single stage,False,False,False,5.75000,False,False,True
6035,0111,Wheat,2000,1.30000,1.3,Storage,Not specified,Modelled Estimates,"APHLIS, (2021), APHLIS",No note,...,False,False,Single stage,False,False,False,1.30000,False,False,True
6036,0111,Wheat,2000,3.50000,3.5,NaN,Not specified,Modelled Estimates,"APHLIS, (2021), APHLIS",No note,...,False,False,Unknown,False,False,False,3.50000,False,False,True

In [50]:
duplicates = df[df.duplicated(keep=False)].sort_values(
    by=["cpc_code", "commodity", "year"]
)

display(duplicates)

,cpc_code,commodity,year,loss_percentage,loss_percentage_original,food_supply_stage,treatment,method_data_collection,reference,notes,...,is_suspect_year,is_lit_outlier,measurement_scope,is_new_valley_copy,is_suspect_value,is_zero_loss,loss_percentage_clean,has_loss_tonnes,has_loss_tonnes_per_ha,is_reliable
528,0111,Wheat,2000,4.43333,4.43333,Farm/Harvest,Not specified,Modelled Estimates,"APHLIS, (2021), APHLIS",No note,...,False,False,Single stage,False,False,False,4.43333,False,False,True
529,0111,Wheat,2000,4.86667,4.86667,Farm/Harvest,Not specified,Modelled Estimates,"APHLIS, (2021), APHLIS",No note,...,False,False,Single stage,False,False,False,4.86667,False,False,True
530,0111,Wheat,2000,3.50000,3.5,NaN,Not specified,Modelled Estimates,"APHLIS, (2021), APHLIS",No note,...,False,False,Unknown,False,False,False,3.50000,False,False,True
531,0111,Wheat,2000,2.50000,2.5,Farm/Harvest,Not specified,Modelled Estimates,"APHLIS, (2021), APHLIS",No note,...,False,False,Single stage,False,False,False,2.50000,False,False,True
1916,0111,Wheat,2000,4.43333,4.43333,Farm/Harvest,Not specified,Modelled Estimates,"APHLIS, (2021), APHLIS",No note,...,False,False,Single stage,False,False,False,4.43333,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7874,02111,Cattle,2007,12.36000,12.36%,Transport,Major Season,Survey,"Dr (Mrs.) Irene S. Egyir, Dr. D. B. Sarpong, a...",No note,...,False,False,Single stage,False,False,False,12.36000,True,False,True
7875,02111,Cattle,2007,12.36000,12.36%,Transport,Major Season,Survey,"Dr (Mrs.) Irene S. Egyir, Dr. D. B. Sarpong, a...",No note,...,False,False,Single stage,False,False,False,12.36000,True,False,True
976,02920,"Snails, fresh, chilled, frozen, dried, salted ...",2014,50.00000,50%,Whole supply chain,Not specified,Literature Review,Radojko Lukic; Dragana Vojteski Kljenak; Dragi...,"Sourced from Gunders, (2012)",...,False,True,Whole chain,False,False,False,50.00000,False,False,True
18015,02920,"Snails, fresh, chilled, frozen, dried, salted ...",2014,50.00000,50%,Whole supply chain,Not specified,Literature Review,Radojko Lukic; Dragana Vojteski Kljenak; Dragi...,"Sourced from Gunders, (2012)",...,False,True,Whole chain,False,False,False,50.00000,False,False,True
28267,02920,"Snails, fresh, chilled, frozen, dried, salted ...",2014,50.00000,50%,Whole supply chain,Not specified,Literature Review,Radojko Lukic; Dragana Vojteski Kljenak; Dragi...,"Sourced from Gunders, (2012)",...,False,True,Whole chain,False,False,False,50.00000,False,False,True

In [51]:
df = world_food_loss.copy()
cat_cols = ["commodity", "food_supply_stage", "treatment", "geo_level", "governorate",
            "measurement_scope", "method_data_collection", "reference"]
for c in cat_cols:
    df[c] = df[c].astype("category")
final_cols = [
    # what / when / where
    "cpc_code", "commodity", "year", "geo_level", "governorate",
    "food_supply_stage", "measurement_scope", "treatment",
    # values
    "loss_percentage", "loss_percentage_clean", "loss_percentage_original",
    "loss_tonnes", "has_loss_tonnes", "loss_tonnes_per_ha", "has_loss_tonnes_per_ha",
    # quality flags
    "is_reliable", "is_suspect_year", "is_lit_outlier", "is_new_valley_copy",
    "is_suspect_value", "is_zero_loss",
    # source
    "method_data_collection", "reference", "notes",
]
df = df[final_cols].drop_duplicates().reset_index(drop=True)

# Validation: fail early with useful messages if the cleaned dataset is not valid.
assert not df.duplicated().any(), "duplicate rows found"
assert df["loss_percentage"].between(0, 100).all(), "loss_percentage out of 0-100"
assert df["cpc_code"].dropna().str.fullmatch(r"0\d{3,5}[A-Za-z]?(?:\.\d{1,2})?").all(), \
       "bad cpc_code format"
assert df["year"].between(1900, 2100).all(), "year out of range"
required_cols = ["cpc_code", "commodity", "year", "loss_percentage",
                 "measurement_scope", "geo_level"]
assert df[required_cols].notna().all().all(), "missing values in required columns"
print("All checks passed.", df.shape)
egypt_food_waste_final = df
display(df.head())

All checks passed. (17781, 24)

,cpc_code,commodity,year,geo_level,governorate,food_supply_stage,measurement_scope,treatment,loss_percentage,loss_percentage_clean,...,has_loss_tonnes_per_ha,is_reliable,is_suspect_year,is_lit_outlier,is_new_valley_copy,is_suspect_value,is_zero_loss,method_data_collection,reference,notes
0,0111,Wheat,2022,National,Not applicable,Processing,Single stage,Not specified,1.0,1.0,...,False,True,False,False,False,False,False,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",Derived product is wheat flour
1,0112,Maize (corn),2022,National,Not applicable,Processing,Single stage,Not specified,0.5,0.5,...,False,True,False,False,False,False,False,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",Derived product is maize flour.
2,0112,Maize (corn),2022,National,Not applicable,Processing,Single stage,Not specified,2.0,2.0,...,False,True,False,False,False,False,False,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",Derived product is Maize (corn) grits.
3,0112,Maize (corn),2022,National,Not applicable,Processing,Single stage,Not specified,2.0,2.0,...,False,True,False,False,False,False,False,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",Derived product is Maize (corn) grits flaked.
4,0112,Maize (corn),2022,National,Not applicable,Processing,Single stage,Not specified,0.1,0.1,...,False,True,False,False,False,False,False,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",Derived product is corn starch.

## 5) Save the final data

In [ ]:

egypt_food_waste_final.to_csv('../final-data-set/world' / "World-food-waste_final.csv", index=False)
egypt_food_waste_final.query("measurement_scope == 'Whole chain'").to_csv(
    '../final-data-set/world' / "World-whole-chain.csv", index=False
)
egypt_food_waste_final.query("measurement_scope == 'Single stage'").to_csv(
    '../final-data-set/world' / "World-stage-level.csv", index=False
)
egypt_food_waste_final.query("measurement_scope == 'Unknown'").to_csv(
    '../final-data-set/world' / "World-unknown-scope.csv", index=False
)

Saved cleaned data and subsets to D:\My_projects\data-engineer\waste-food-project\notebooks\final-data-set