# ***Egypt Food Waste Graduation project***

In [2]:
import pandas as pd
import numpy as np

## **Read Data**

In [3]:
egypt_food_waste = pd.read_csv('../data-set/Egypt-food-waste.csv');
egypt_food_waste

,m49_code,country,region,cpc_code,commodity,year,loss_percentage,loss_percentage_original,loss_quantity,activity,food_supply_stage,treatment,cause_of_loss,sample_size,method_data_collection,reference,url,notes
0,818,Egypt,NaN,1234.00,Tomatoes,2026,7.95,7.95%,NaN,Farm,Farm,NaN,NaN,NaN,Survey,Abdelrahman Ali; Chunping Xia; N'Banan Ouattar...,NaN,NaN
1,818,Egypt,NaN,1234.00,Tomatoes,2026,7.75,7.75%,NaN,Processing,Processing,NaN,NaN,NaN,Survey,Abdelrahman Ali; Chunping Xia; N'Banan Ouattar...,NaN,NaN
2,818,Egypt,NaN,1234.00,Tomatoes,2026,2.50,2.5%,NaN,Trading,Trader,NaN,NaN,NaN,Survey,Abdelrahman Ali; Chunping Xia; N'Banan Ouattar...,NaN,NaN
3,818,Egypt,NaN,1234.00,Tomatoes,2026,2.60,2.6%,NaN,Wholesale,Wholesale,NaN,NaN,NaN,Survey,Abdelrahman Ali; Chunping Xia; N'Banan Ouattar...,NaN,NaN
4,818,Egypt,NaN,1234.00,Tomatoes,2026,1.74,1.74%,NaN,Retailing,Retail,NaN,NaN,NaN,Survey,Abdelrahman Ali; Chunping Xia; N'Banan Ouattar...,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,818,Egypt,NaN,1709.02,Lupins,2014,0.00,0%,0,NaN,Whole supply chain,NaN,NaN,NaN,FAO's annual Agriculture Production Questionna...,FAO Sources,NaN,NaN
136,818,Egypt,NaN,1921.01,"Seed cotton, unginned",2014,1.52,1.52%,8000,NaN,Whole supply chain,NaN,NaN,NaN,FAO's annual Agriculture Production Questionna...,FAO Sources,NaN,NaN
137,818,Egypt,NaN,1234.00,Tomatoes,2013,43.00,43%,NaN,NaN,Post-harvest,NaN,NaN,NaN,Literature Review,Julian Parfitt; Mark Barthel; Sarah Macnaughto...,NaN,Sourced from Blond 1984
138,818,Egypt,NaN,1330.00,Grapes,2013,28.00,28%,NaN,NaN,Post-harvest,NaN,NaN,NaN,Literature Review,Julian Parfitt; Mark Barthel; Sarah Macnaughto...,NaN,Sourced from Blond 1984
139,818,Egypt,NaN,111.00,Wheat,2011,14.00,13.0-15,NaN,NaN,Farm,NaN,NaN,NaN,Literature Review,"COMCEC, (2016), Reducing Postharvest Losses In...",http://www.mod.gov.tr/Lists/RecentPublications...,NaN

# **Step 1: Clean and explore dataset**

| اسم العمود | معناه في سياق بيانات FAO |
| :--- | :--- |
| **m49_code** | كود الدولة أو المنطقة حسب معيار الأمم المتحدة M49. مصر كودها 818. |
| **country** | اسم الدولة المرتبطة بالسجل، زي Egypt. |
| **region** | المنطقة الجغرافية، لو السجل بيمثل منطقة بدل دولة منفردة أو بيحتوي على تصنيف إقليمي. لازم نراجع تعريف الملف لمعرفة الاستخدام الدقيق للحقل ده. |
| **cpc_code** | كود تصنيف السلعة حسب نظام CPC. |
| **commodity** | اسم المنتج أو السلعة الغذائية، زي Tomatoes. |
| **year** | السنة المسجلة للدراسة في قاعدة البيانات، وفق تعريف FAO. |
| **loss_percentage** | نسبة الفقد المسجلة في الدراسة، وده المتغير الأساسي اللي بنحلله. |
| **loss_percentage_original** | يبدو إنه بيحتفظ بتمثيل النسبة الأصلي، لكن لازم نراجع ملف التصدير أو وصف الحقول علشان نأكد الفرق الدقيق بينه وبين العمود السابق. |
| **loss_quantity** | كمية الفقد، لو متاحة ومسجلة في المصدر. لازم نراجع الوحدة وتعريف الكمية قبل استخدامها. |
| **activity** | النشاط المرتبط بفقد الطعام، حسب وصف الدراسة الأصلية. |
| **food_supply_stage** | مرحلة سلسلة الإمداد الغذائي اللي الدراسة ربطت بيها الفقد. |
| **treatment** | حقل متعلق بالمعالجة أو التعامل مع المنتج وفق تعريف المصدر؛ محتاجين تعريف الحقل الأصلي لتحديد معناه بدقة. |
| **cause_of_loss** | سبب الفقد، لو الدراسة سجلته. |
| **sample_size** | حجم العينة المسجلة للدراسة، وفق وحدة العينة المستخدمة فيها. |
| **method_data_collection** | طريقة جمع أو تقدير بيانات الفقد، زي Survey. |
| **reference** | المرجع أو الدراسة اللي اتاخدت منها البيانات. |
| **url** | رابط المصدر الأصلي، لو متاح. |
| **notes** | ملاحظات إضافية مرتبطة بالسجل، لو موجودة. |

## **DATASET OVERVIEW**

In [4]:
print("=" * 60)
print("DATASET OVERVIEW")
print("=" * 60)

print("Shape:", egypt_food_waste.shape)
print("Number of rows:", egypt_food_waste.shape[0])
print("Number of columns:", egypt_food_waste.shape[1])
print("Memory usage (MB):", round(egypt_food_waste.memory_usage(deep=True).sum() / (1024 ** 2), 2))

display(egypt_food_waste.head())
display(egypt_food_waste.tail())
display(egypt_food_waste.sample(min(5, len(egypt_food_waste)), random_state=42))

============================================================
DATASET OVERVIEW
============================================================
Shape: (140, 18)
Number of rows: 140
Number of columns: 18
Memory usage (MB): 0.1

,m49_code,country,region,cpc_code,commodity,year,loss_percentage,loss_percentage_original,loss_quantity,activity,food_supply_stage,treatment,cause_of_loss,sample_size,method_data_collection,reference,url,notes
0,818,Egypt,NaN,1234.0,Tomatoes,2026,7.95,7.95%,NaN,Farm,Farm,NaN,NaN,NaN,Survey,Abdelrahman Ali; Chunping Xia; N'Banan Ouattar...,NaN,NaN
1,818,Egypt,NaN,1234.0,Tomatoes,2026,7.75,7.75%,NaN,Processing,Processing,NaN,NaN,NaN,Survey,Abdelrahman Ali; Chunping Xia; N'Banan Ouattar...,NaN,NaN
2,818,Egypt,NaN,1234.0,Tomatoes,2026,2.50,2.5%,NaN,Trading,Trader,NaN,NaN,NaN,Survey,Abdelrahman Ali; Chunping Xia; N'Banan Ouattar...,NaN,NaN
3,818,Egypt,NaN,1234.0,Tomatoes,2026,2.60,2.6%,NaN,Wholesale,Wholesale,NaN,NaN,NaN,Survey,Abdelrahman Ali; Chunping Xia; N'Banan Ouattar...,NaN,NaN
4,818,Egypt,NaN,1234.0,Tomatoes,2026,1.74,1.74%,NaN,Retailing,Retail,NaN,NaN,NaN,Survey,Abdelrahman Ali; Chunping Xia; N'Banan Ouattar...,NaN,NaN

,m49_code,country,region,cpc_code,commodity,year,loss_percentage,loss_percentage_original,loss_quantity,activity,food_supply_stage,treatment,cause_of_loss,sample_size,method_data_collection,reference,url,notes
135,818,Egypt,NaN,1709.02,Lupins,2014,0.00,0%,0,NaN,Whole supply chain,NaN,NaN,NaN,FAO's annual Agriculture Production Questionna...,FAO Sources,NaN,NaN
136,818,Egypt,NaN,1921.01,"Seed cotton, unginned",2014,1.52,1.52%,8000,NaN,Whole supply chain,NaN,NaN,NaN,FAO's annual Agriculture Production Questionna...,FAO Sources,NaN,NaN
137,818,Egypt,NaN,1234.00,Tomatoes,2013,43.00,43%,NaN,NaN,Post-harvest,NaN,NaN,NaN,Literature Review,Julian Parfitt; Mark Barthel; Sarah Macnaughto...,NaN,Sourced from Blond 1984
138,818,Egypt,NaN,1330.00,Grapes,2013,28.00,28%,NaN,NaN,Post-harvest,NaN,NaN,NaN,Literature Review,Julian Parfitt; Mark Barthel; Sarah Macnaughto...,NaN,Sourced from Blond 1984
139,818,Egypt,NaN,111.00,Wheat,2011,14.00,13.0-15,NaN,NaN,Farm,NaN,NaN,NaN,Literature Review,"COMCEC, (2016), Reducing Postharvest Losses In...",http://www.mod.gov.tr/Lists/RecentPublications...,NaN

,m49_code,country,region,cpc_code,commodity,year,loss_percentage,loss_percentage_original,loss_quantity,activity,food_supply_stage,treatment,cause_of_loss,sample_size,method_data_collection,reference,url,notes
108,818,Egypt,NaN,1550.0,Taro,2015,16.58,16.58%,17000,NaN,Whole supply chain,NaN,NaN,NaN,FAO's annual Agriculture Production Questionna...,FAO Sources,NaN,NaN
67,818,Egypt,National average,111.0,Wheat,2017,4.58,4.58%,NaN,Storage,Storage,NaN,NaN,NaN,Survey,"YA Yigezu, (2021), Food Losses And Wastage Alo...",NaN,NaN
31,818,Egypt,NaN,113.0,Rice,2017,3.59,3.59%,178000,NaN,Whole supply chain,NaN,NaN,NaN,FAO's annual Agriculture Production Questionna...,FAO Sources,NaN,NaN
119,818,Egypt,NaN,113.0,Rice,2014,2.09,2.09%,114000,NaN,Whole supply chain,NaN,NaN,NaN,FAO's annual Agriculture Production Questionna...,FAO Sources,NaN,NaN
42,818,Egypt,NaN,1701.0,"Beans, dry",2017,0.69,0.69%,1000,NaN,Whole supply chain,NaN,NaN,NaN,FAO's annual Agriculture Production Questionna...,FAO Sources,NaN,NaN

## **Analysis Columns**

In [5]:
print("COLUMN NAMES")
print(egypt_food_waste.columns.tolist())

print("\nDATA TYPES")
print(egypt_food_waste.dtypes)

print("\nDATASET INFO")
egypt_food_waste.info()

print("\nNUMERIC SUMMARY")
display(egypt_food_waste.describe().T)

print("\nALL COLUMNS SUMMARY")
display(egypt_food_waste.describe(include="all").T)

COLUMN NAMES
['m49_code', 'country', 'region', 'cpc_code', 'commodity', 'year', 'loss_percentage', 'loss_percentage_original', 'loss_quantity', 'activity', 'food_supply_stage', 'treatment', 'cause_of_loss', 'sample_size', 'method_data_collection', 'reference', 'url', 'notes']

DATA TYPES
m49_code                      int64
country                         str
region                          str
cpc_code                    float64
commodity                       str
year                          int64
loss_percentage             float64
loss_percentage_original        str
loss_quantity                   str
activity                        str
food_supply_stage               str
treatment                       str
cause_of_loss               float64
sample_size                 float64
method_data_collection          str
reference                       str
url                             str
notes                           str
dtype: object

DATASET INFO
<class 'pandas.DataFrame'>
RangeIndex: 140 entries, 0 to 139
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   m49_code                  140 non-null    int64
 1   country                   140 non-null    str
 2   region                    49 non-null     str
 3   cpc_code                  140 non-null    float64
 4   commodity                 140 non-null    str
 5   year                      140 non-null    int64
 6   loss_percentage           140 non-null    float64
 7   loss_percentage_original  140 non-null    str
 8   loss_quantity             92 non-null     str
 9   activity                  57 non-null     str
 10  food_supply_stage         140 non-null    str
 11  treatment                 24 non-null     str
 12  cause_of_loss             0 non-null      float64
 13  sample_size               0 non-null      float64
 14  method_data_collection    140 non-null    str
 15  reference                 140 non-null    str
 16  url                       1 non-null      str
 17  notes                     17 non-null     str
dtypes: float64(4), int64(2), str(12)
memory usage: 19.8 KB

NUMERIC SUMMARY

,count,mean,std,min,25%,50%,75%,max
m49_code,140.0,818.000000,0.000000,818.0,818.000,818.00,818.000,818.00
cpc_code,140.0,805.372143,725.983275,111.0,111.000,142.00,1510.000,1921.01
year,140.0,2016.600000,2.398441,2011.0,2015.000,2017.00,2017.000,2026.00
loss_percentage,140.0,8.246143,7.547446,0.0,2.935,6.53,10.785,43.00
cause_of_loss,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sample_size,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

ALL COLUMNS SUMMARY

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
m49_code,140.0,NaN,NaN,NaN,818.0,0.0,818.0,818.0,818.0,818.0,818.0
country,140,1,Egypt,140,NaN,NaN,NaN,NaN,NaN,NaN,NaN
region,49,11,National average,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cpc_code,140.0,NaN,NaN,NaN,805.372143,725.983275,111.0,111.0,142.0,1510.0,1921.01
commodity,140,24,Wheat,48,NaN,NaN,NaN,NaN,NaN,NaN,NaN
year,140.0,NaN,NaN,NaN,2016.6,2.398441,2011.0,2015.0,2017.0,2017.0,2026.0
loss_percentage,140.0,NaN,NaN,NaN,8.246143,7.547446,0.0,2.935,6.53,10.785,43.0
loss_percentage_original,140,128,0.75%,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
loss_quantity,92,63,1000,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
activity,57,11,Harvesting,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN
food_supply_stage,140,13,Whole supply chain,78,NaN,NaN,NaN,NaN,NaN,NaN,NaN
treatment,24,12,Reaper without bundling,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cause_of_loss,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sample_size,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
method_data_collection,140,4,FAO's annual Agriculture Production Questionna...,77,NaN,NaN,NaN,NaN,NaN,NaN,NaN
reference,140,7,FAO Sources,77,NaN,NaN,NaN,NaN,NaN,NaN,NaN
url,1,1,http://www.mod.gov.tr/Lists/RecentPublications...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
notes,17,4,Area weighted average for harvesting and thres...,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## **Analysis Missing values in Data-set**

In [6]:
missing_report = pd.DataFrame({
    "missing_count": egypt_food_waste.isna().sum(),
    "missing_percentage": egypt_food_waste.isna().mean().mul(100),
    "non_missing_count": egypt_food_waste.notna().sum(),
    "unique_non_null": egypt_food_waste.nunique(dropna=True)
})

missing_report = missing_report.sort_values(
    by="missing_percentage",
    ascending=False
)

display(missing_report)

,missing_count,missing_percentage,non_missing_count,unique_non_null
sample_size,140,100.000000,0,0
cause_of_loss,140,100.000000,0,0
url,139,99.285714,1,1
notes,123,87.857143,17,4
treatment,116,82.857143,24,12
region,91,65.000000,49,11
activity,83,59.285714,57,11
loss_quantity,48,34.285714,92,63
country,0,0.000000,140,1
m49_code,0,0.000000,140,1
loss_percentage,0,0.000000,140,126
loss_percentage_original,0,0.000000,140,128
commodity,0,0.000000,140,24
year,0,0.000000,140,9
cpc_code,0,0.000000,140,24
food_supply_stage,0,0.000000,140,13
reference,0,0.000000,140,7
method_data_collection,0,0.000000,140,4

### **Show "NA", "N/A", "NULL", "NONE", "UNKNOWN", "MISSING", "-" in string data-types**

In [7]:
import pandas as pd

missing_tokens = {
    "NA", "N/A", "NULL", "NONE",
    "UNKNOWN", "MISSING", "-", "NAN"
}

text_df = egypt_food_waste.select_dtypes(
    include=["object", "string"]
)

results = []

for col in text_df.columns:
    values = text_df[col].astype("string").str.strip()

    empty_count = values.eq("").sum()

    token_count = values.str.upper().isin(
        missing_tokens
    ).sum()

    actual_missing_count = values.isna().sum()

    results.append({
        "column": col,
        "empty_string_count": int(empty_count),
        "missing_token_count": int(token_count),
        "actual_missing_count": int(actual_missing_count)
    })

missing_report = (
    pd.DataFrame(results)
    .set_index("column")
    .sort_values(
        "actual_missing_count",
        ascending=False
    )
)

display(missing_report)

,empty_string_count,missing_token_count,actual_missing_count
column,,,
url,0,0,139
notes,0,0,123
treatment,0,0,116
region,0,0,91
activity,0,0,83
loss_quantity,0,0,48
country,0,0,0
commodity,0,0,0
loss_percentage_original,0,0,0
food_supply_stage,0,0,0
reference,0,0,0
method_data_collection,0,0,0

## **Show duplicated and unique data**

In [8]:
unique_report = pd.DataFrame({
    "unique_count": egypt_food_waste.nunique(dropna=True),
    "unique_with_nan": egypt_food_waste.nunique(dropna=False),
    "dtype": egypt_food_waste.dtypes.astype(str),
    "is_constant": egypt_food_waste.nunique(dropna=True).le(1)
})

display(unique_report.sort_values("unique_count"))

                          unique_count  unique_with_nan    dtype  is_constant
cause_of_loss                        0                1  float64         True
sample_size                          0                1  float64         True
m49_code                             1                1    int64         True
country                              1                1      str         True
url                                  1                2      str         True
method_data_collection               4                4      str        False
notes                                4                5      str        False
reference                            7                7      str        False
year                                 9                9    int64        False
region                              11               12      str        False
activity                            11               12      str        False
treatment                           12               13      str        False
food_supply_stage                   13               13      str        False
cpc_code                            24               24  float64        False
commodity                           24               24      str        False
loss_quantity                       63               64      str        False
loss_percentage                    126              126  float64        False
loss_percentage_original           128              128      str        False

In [9]:
categorical_cols = egypt_food_waste.select_dtypes(
    include=["object", "string", "category"]
).columns

for col in categorical_cols:
    print(f"\n{'=' * 60}")
    print(f"Column: {col}")
    print("Unique values:", egypt_food_waste[col].nunique(dropna=True))
    print("Most frequent values:")
    display(egypt_food_waste[col].value_counts(dropna=False))

============================================================
Column: country
Unique values: 1
Most frequent values:

country
Egypt    140
Name: count, dtype: int64

============================================================
Column: region
Unique values: 11
Most frequent values:

region
NaN                         91
National average            11
Dakahlia (Lower Egypt)       8
Qena (Upper Egypt)           6
Beni Suef (Middle Egypt)     4
Lower Egypt                  3
Middle Egypt                 3
Upper Egypt                  3
Bani Suef                    3
Sharkia and Nubaria          3
Nubaria                      3
New Valley                   2
Name: count, dtype: int64

============================================================
Column: commodity
Unique values: 24
Most frequent values:

commodity
Wheat                               48
Tomatoes                            10
Maize (corn)                         4
Rice                                 4
Sorghum                              4
Barley                               4
Soya beans                           4
Groundnuts, excluding shelled        4
Sesame seed                          4
Sunflower seed                       4
Olives                               4
Potatoes                             4
Sweet potatoes                       4
Taro                                 4
Beans, dry                           4
Broad beans and horse beans, dry     4
Chick peas, dry                      4
Lentils, dry                         4
Seed cotton, unginned                4
Grapes                               4
Sugar beet                           3
Linseed                              3
Lupins                               3
Oranges                              1
Name: count, dtype: int64

============================================================
Column: loss_percentage_original
Unique values: 128
Most frequent values:

loss_percentage_original
0.75%      3
0%         3
7.95%      2
3.86%      2
9.26%      2
          ..
2.97%      1
1.52%      1
43%        1
28%        1
13.0-15    1
Name: count, Length: 128, dtype: int64

============================================================
Column: loss_quantity
Unique values: 63
Most frequent values:

loss_quantity
NaN       48
1000      10
4000       6
5000       5
8000       3
          ..
31000      1
8400       1
939000     1
21000      1
20000      1
Name: count, Length: 64, dtype: int64

============================================================
Column: activity
Unique values: 11
Most frequent values:

activity
NaN                      83
Harvesting               17
Harvesting, Threshing    10
Storage                   8
Transportation            4
Farm                      3
Processing                3
Wholesale                 3
Retailing                 3
Consumption               3
Marketing                 2
Trading                   1
Name: count, dtype: int64

============================================================
Column: food_supply_stage
Unique values: 13
Most frequent values:

food_supply_stage
Whole supply chain    78
Harvest               27
Storage                8
Farm                   4
Transport              4
Post-harvest           4
Processing             3
Wholesale              3
Retail                 3
Market                 2
Households             2
Trader                 1
Food Services          1
Name: count, dtype: int64

============================================================
Column: treatment
Unique values: 12
Most frequent values:

treatment
NaN                                    116
Reaper without bundling                  6
Manual harvesting                        3
Storage in shona (traditional crib)      3
Reaper with bundling                     2
Rice harvester                           2
Storage on farm                          2
Use of manual harvesting                 1
Use of reapers for harvesting            1
Use of combine harvesters                1
Manual harvest                           1
Sorage on farm                           1
Storage in silo                          1
Name: count, dtype: int64

============================================================
Column: method_data_collection
Unique values: 4
Most frequent values:

method_data_collection
FAO's annual Agriculture Production Questionnaires    77
Survey                                                47
Literature Review                                     14
Expert Opinion                                         2
Name: count, dtype: int64

============================================================
Column: reference
Unique values: 7
Most frequent values:

reference
FAO Sources                                                                                                                                                                                                   77
YA Yigezu, (2021), Food Losses And Wastage Along The Wheat Value Chain In Egypt And Their Implications On Food And Energy Security, Natural Resources, And The Environment                                    47
Gustavo Anríquez; William Foster; Jozimo Santos Rocha; Jorge Ortega; Jennifer Smolak; Sarah Jansen, (2023), Reducing Food Loss And Waste In The Near East And North Africa                                     6
Abdelrahman Ali; Chunping Xia; N'Banan Ouattara; Irfan Mahmood; Muhammad Faisal, (2021), Economic And Environmental Consequences' Of Postharvest Loss Across Food Supply Chain In The Developing Countries     5
Lisa Kitinoja; Adel A. Kader, (2015), Measuring Postharvest Losses Of Fresh Fruits And Vegetables In Developing Countries                                                                                      2
Julian Parfitt; Mark Barthel; Sarah Macnaughton, (2010), Food Waste Within Food Supply Chains: Quantification And Potential For Change To 2050                                                                 2
COMCEC, (2016), Reducing Postharvest Losses In The Oic Member Countries                                                                                                                                        1
Name: count, dtype: int64

============================================================
Column: url
Unique values: 1
Most frequent values:

url
NaN                                                                                                                                         139
http://www.mod.gov.tr/Lists/RecentPublications/Attachments/120/Reducing%20Postharvest%20Losses%20in%20the%20OIC%20Member%20Countries.pdf      1
Name: count, dtype: int64

============================================================
Column: notes
Unique values: 4
Most frequent values:

notes
NaN                                                   123
Area weighted average for harvesting and threshing     10
Adapted from Sattar M. et al, 2015.                     3
Sourced from El Shazly et al 2009                       2
Sourced from Blond 1984                                 2
Name: count, dtype: int64

In [10]:
print("Fully duplicated rows:", egypt_food_waste.duplicated().sum())

print(
    "Duplicated rows including all copies:",
    egypt_food_waste.duplicated(keep=False).sum()
)

duplicates = egypt_food_waste[
    egypt_food_waste.duplicated(keep=False)
].sort_values(by=egypt_food_waste.columns.tolist())

display(duplicates.head(20))

Fully duplicated rows: 1
Duplicated rows including all copies: 2

,m49_code,country,region,cpc_code,commodity,year,loss_percentage,loss_percentage_original,loss_quantity,activity,food_supply_stage,treatment,cause_of_loss,sample_size,method_data_collection,reference,url,notes
28,818,Egypt,National average,111.0,Wheat,2018,1.91,1.91%,NaN,Consumption,Households,NaN,NaN,NaN,Expert Opinion,"YA Yigezu, (2021), Food Losses And Wastage Alo...",NaN,NaN
29,818,Egypt,National average,111.0,Wheat,2018,1.91,1.91%,NaN,Consumption,Households,NaN,NaN,NaN,Expert Opinion,"YA Yigezu, (2021), Food Losses And Wastage Alo...",NaN,NaN

## **Describe numeric data**

In [11]:
numeric_cols = egypt_food_waste.select_dtypes(
    include=np.number
).columns

numeric_report = pd.DataFrame(index=numeric_cols)

numeric_report["missing"] = egypt_food_waste[numeric_cols].isna().sum()
numeric_report["unique"] = egypt_food_waste[numeric_cols].nunique()
numeric_report["min"] = egypt_food_waste[numeric_cols].min()
numeric_report["max"] = egypt_food_waste[numeric_cols].max()
numeric_report["mean"] = egypt_food_waste[numeric_cols].mean()
numeric_report["median"] = egypt_food_waste[numeric_cols].median()
numeric_report["std"] = egypt_food_waste[numeric_cols].std()
numeric_report["negative_count"] = egypt_food_waste[numeric_cols].lt(0).sum()

display(numeric_report)

,missing,unique,min,max,mean,median,std,negative_count
m49_code,0,1,818.0,818.00,818.000000,818.00,0.000000,0
cpc_code,0,24,111.0,1921.01,805.372143,142.00,725.983275,0
year,0,9,2011.0,2026.00,2016.600000,2017.00,2.398441,0
loss_percentage,0,126,0.0,43.00,8.246143,6.53,7.547446,0
cause_of_loss,140,0,NaN,NaN,NaN,NaN,NaN,0
sample_size,140,0,NaN,NaN,NaN,NaN,NaN,0

## **Show ouliers**

In [12]:
outlier_rows = []

for col in numeric_cols:
    series = egypt_food_waste[col].dropna()

    if series.empty:
        continue

    q1 = series.quantile(0.25)
    q3 = series.quantile(0.75)
    iqr = q3 - q1

    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr

    mask = (egypt_food_waste[col] < lower_bound) | (
        egypt_food_waste[col] > upper_bound
    )

    outlier_rows.append({
        "column": col,
        "lower_bound": lower_bound,
        "upper_bound": upper_bound,
        "outlier_count": int(mask.sum()),
        "outlier_percentage": round(mask.mean() * 100, 2)
    })

outlier_report = pd.DataFrame(outlier_rows)
display(outlier_report)

,column,lower_bound,upper_bound,outlier_count,outlier_percentage
0,m49_code,818.00,818.00,0,0.00
1,cpc_code,-1987.50,3608.50,0,0.00
2,year,2012.00,2020.00,9,6.43
3,loss_percentage,-8.84,22.56,5,3.57

## **Show final columns**

In [13]:
print(egypt_food_waste.columns.tolist())

['m49_code', 'country', 'region', 'cpc_code', 'commodity', 'year', 'loss_percentage', 'loss_percentage_original', 'loss_quantity', 'activity', 'food_supply_stage', 'treatment', 'cause_of_loss', 'sample_size', 'method_data_collection', 'reference', 'url', 'notes']

## **Data quality check on the Year**

In [14]:
if "year" in egypt_food_waste.columns:
    print("Invalid or suspicious years:")
    display(
        egypt_food_waste.loc[
            ~egypt_food_waste["year"].between(1900, 2100),
            ["year"]
        ].head(20)
    )

Invalid or suspicious years:

Empty DataFrame
Columns: [year]
Index: []

## **Finally analysis of data**

In [15]:
quality_report = pd.DataFrame(index=egypt_food_waste.columns)

quality_report["dtype"] = egypt_food_waste.dtypes.astype(str)
quality_report["total_rows"] = len(egypt_food_waste)
quality_report["missing_count"] = egypt_food_waste.isna().sum()
quality_report["missing_pct"] = (
    egypt_food_waste.isna().mean() * 100
).round(2)

quality_report["unique_count"] = egypt_food_waste.nunique(dropna=True)
quality_report["unique_pct"] = (
    egypt_food_waste.nunique(dropna=True) / max(len(egypt_food_waste), 1) * 100
).round(2)

quality_report["duplicate_row_count"] = egypt_food_waste.duplicated().sum()
quality_report["memory_bytes"] = egypt_food_waste.memory_usage(deep=True).iloc[1:].values

display(quality_report)

,dtype,total_rows,missing_count,missing_pct,unique_count,unique_pct,duplicate_row_count,memory_bytes
m49_code,int64,140,0,0.00,1,0.71,1,1120
country,str,140,0,0.00,1,0.71,1,7560
region,str,140,91,65.00,11,7.86,1,6096
cpc_code,float64,140,0,0.00,24,17.14,1,1120
commodity,str,140,0,0.00,24,17.14,1,8140
year,int64,140,0,0.00,9,6.43,1,1120
loss_percentage,float64,140,0,0.00,126,90.00,1,1120
loss_percentage_original,str,140,0,0.00,128,91.43,1,7551
loss_quantity,str,140,48,34.29,63,45.00,1,6557
activity,str,140,83,59.29,11,7.86,1,6095
food_supply_stage,str,140,0,0.00,13,9.29,1,8735
treatment,str,140,116,82.86,12,8.57,1,5401
cause_of_loss,float64,140,140,100.00,0,0.00,1,1120
sample_size,float64,140,140,100.00,0,0.00,1,1120
method_data_collection,str,140,0,0.00,4,2.86,1,11258
reference,str,140,0,0.00,7,5.00,1,19452
url,str,140,139,99.29,1,0.71,1,4633
notes,str,140,123,87.86,4,2.86,1,5486

## **Result of analysis**

## **Solution of these problems**

### **1. Convert "cpc_code" column to <"string type">**

In [16]:
egypt_food_waste["cpc_code"] = (
    egypt_food_waste["cpc_code"].astype("string")
)

In [17]:
print(egypt_food_waste["cpc_code"].dtype)

string

### **2. Drop columns "sample_size" and "cause_of_loss" columns**

In [18]:
egypt_food_waste = egypt_food_waste.drop(
    columns=['sample_size', 'cause_of_loss']
)

In [19]:
egypt_food_waste.columns.tolist()

['m49_code',
 'country',
 'region',
 'cpc_code',
 'commodity',
 'year',
 'loss_percentage',
 'loss_percentage_original',
 'loss_quantity',
 'activity',
 'food_supply_stage',
 'treatment',
 'method_data_collection',
 'reference',
 'url',
 'notes']

### **3. Drop column "m49_code"**

In [20]:
egypt_food_waste = egypt_food_waste.drop(
    columns=['m49_code']
)

In [21]:
egypt_food_waste.columns.tolist()

['country',
 'region',
 'cpc_code',
 'commodity',
 'year',
 'loss_percentage',
 'loss_percentage_original',
 'loss_quantity',
 'activity',
 'food_supply_stage',
 'treatment',
 'method_data_collection',
 'reference',
 'url',
 'notes']

### **4. Drop column "url"**

In [22]:
egypt_food_waste = egypt_food_waste.drop(
    columns=['url']
)

egypt_food_waste.columns.tolist()

['country',
 'region',
 'cpc_code',
 'commodity',
 'year',
 'loss_percentage',
 'loss_percentage_original',
 'loss_quantity',
 'activity',
 'food_supply_stage',
 'treatment',
 'method_data_collection',
 'reference',
 'notes']

### **5. Drop duplicated data**

In [23]:
egypt_food_waste= egypt_food_waste.drop_duplicates()

### **6. Separate loss_quality to 2 columns since the Unit**

In [24]:
q = egypt_food_waste["loss_quantity"].astype("string").str.strip()

is_per_ha  = q.str.contains("/ha", na=False)        # "0.61ton/ha"
is_million = q.str.contains(r"\bM\b", na=False)     # "4.4 M tonnes"
num = pd.to_numeric(q.str.extract(r"([\d.]+)")[0], errors="coerce")

egypt_food_waste["loss_tonnes"] = np.where(
    is_per_ha, np.nan,
    np.where(is_million, num * 1_000_000, num)
)
egypt_food_waste["loss_tonnes_per_ha"] = np.where(is_per_ha, num, np.nan)

egypt_food_waste = egypt_food_waste.drop(columns="loss_quantity")

### **7. Classify Geographic Levels and Extract Governorate Names**

In [25]:
egypt_food_waste["region"] = egypt_food_waste["region"].replace({"Bani Suef": "Beni Suef"})   

regions3 = ["Lower Egypt", "Middle Egypt", "Upper Egypt"]

egypt_food_waste["geo_level"] = np.select(
    [egypt_food_waste["region"].isna() | egypt_food_waste["region"].eq("National average"),
     egypt_food_waste["region"].isin(regions3)],
    ["National", "Region"],
    default="Governorate/Area"
)

egypt_food_waste["governorate"] = (
    egypt_food_waste["region"].str.replace(r"\s*\(.*\)", "", regex=True)
    .where(egypt_food_waste["geo_level"].eq("Governorate/Area"))
)

In [26]:
egypt_food_waste.head(10)

,country,region,cpc_code,commodity,year,loss_percentage,loss_percentage_original,activity,food_supply_stage,treatment,method_data_collection,reference,notes,loss_tonnes,loss_tonnes_per_ha,geo_level,governorate
0,Egypt,NaN,1234.0,Tomatoes,2026,7.95,7.95%,Farm,Farm,NaN,Survey,Abdelrahman Ali; Chunping Xia; N'Banan Ouattar...,NaN,NaN,NaN,National,NaN
1,Egypt,NaN,1234.0,Tomatoes,2026,7.75,7.75%,Processing,Processing,NaN,Survey,Abdelrahman Ali; Chunping Xia; N'Banan Ouattar...,NaN,NaN,NaN,National,NaN
2,Egypt,NaN,1234.0,Tomatoes,2026,2.50,2.5%,Trading,Trader,NaN,Survey,Abdelrahman Ali; Chunping Xia; N'Banan Ouattar...,NaN,NaN,NaN,National,NaN
3,Egypt,NaN,1234.0,Tomatoes,2026,2.60,2.6%,Wholesale,Wholesale,NaN,Survey,Abdelrahman Ali; Chunping Xia; N'Banan Ouattar...,NaN,NaN,NaN,National,NaN
4,Egypt,NaN,1234.0,Tomatoes,2026,1.74,1.74%,Retailing,Retail,NaN,Survey,Abdelrahman Ali; Chunping Xia; N'Banan Ouattar...,NaN,NaN,NaN,National,NaN
5,Egypt,NaN,111.0,Wheat,2021,3.16,3.16%,Harvesting,Harvest,Use of manual harvesting,Literature Review,"YA Yigezu, (2021), Food Losses And Wastage Alo...","Adapted from Sattar M. et al, 2015.",NaN,NaN,National,NaN
6,Egypt,NaN,111.0,Wheat,2021,2.70,2.7%,Harvesting,Harvest,Use of reapers for harvesting,Literature Review,"YA Yigezu, (2021), Food Losses And Wastage Alo...","Adapted from Sattar M. et al, 2015.",NaN,NaN,National,NaN
7,Egypt,NaN,111.0,Wheat,2021,2.92,2.92%,Harvesting,Harvest,Use of combine harvesters,Literature Review,"YA Yigezu, (2021), Food Losses And Wastage Alo...","Adapted from Sattar M. et al, 2015.",NaN,NaN,National,NaN
8,Egypt,NaN,111.0,Wheat,2018,20.62,20.62%,NaN,Whole supply chain,NaN,Survey,"YA Yigezu, (2021), Food Losses And Wastage Alo...",NaN,4400000.0,NaN,National,NaN
9,Egypt,Qena (Upper Egypt),111.0,Wheat,2018,7.92,7.92%,Harvesting,Harvest,Manual harvesting,Survey,"YA Yigezu, (2021), Food Losses And Wastage Alo...",NaN,NaN,0.61,Governorate/Area,Qena

In [27]:
egypt_food_waste = egypt_food_waste.drop(columns=["region"])

### **8. Handle names of treatment**

In [28]:
treatment_map = {
    "Use of manual harvesting":       "Manual harvesting",
    "Manual harvest":                 "Manual harvesting",
    "Use of reapers for harvesting":  "Reaper (unspecified)",
    "Use of combine harvesters":      "Combine harvester",
    "Sorage on farm":                 "Storage on farm",
}
egypt_food_waste["treatment"] = egypt_food_waste["treatment"].replace(treatment_map)

In [29]:
egypt_food_waste.governorate.value_counts()

governorate
Dakahlia               8
Beni Suef              7
Qena                   6
Sharkia and Nubaria    3
Nubaria                3
New Valley             2
Name: count, dtype: int64

In [30]:
egypt_food_waste.treatment.value_counts()

treatment
Reaper without bundling                6
Manual harvesting                      5
Storage on farm                        3
Storage in shona (traditional crib)    3
Reaper with bundling                   2
Rice harvester                         2
Reaper (unspecified)                   1
Combine harvester                      1
Storage in silo                        1
Name: count, dtype: int64

### **9/10. handle flag outliers**

In [31]:
egypt_food_waste["is_suspect_year"] = egypt_food_waste.year > 2025

In [32]:
egypt_food_waste["is_lit_outlier"] = (egypt_food_waste.method_data_collection == "Literature Review") & (egypt_food_waste.loss_percentage > 22.56)

In [33]:
egypt_food_waste.head()

,country,cpc_code,commodity,year,loss_percentage,loss_percentage_original,activity,food_supply_stage,treatment,method_data_collection,reference,notes,loss_tonnes,loss_tonnes_per_ha,geo_level,governorate,is_suspect_year,is_lit_outlier
0,Egypt,1234.0,Tomatoes,2026,7.95,7.95%,Farm,Farm,NaN,Survey,Abdelrahman Ali; Chunping Xia; N'Banan Ouattar...,NaN,NaN,NaN,National,NaN,True,False
1,Egypt,1234.0,Tomatoes,2026,7.75,7.75%,Processing,Processing,NaN,Survey,Abdelrahman Ali; Chunping Xia; N'Banan Ouattar...,NaN,NaN,NaN,National,NaN,True,False
2,Egypt,1234.0,Tomatoes,2026,2.50,2.5%,Trading,Trader,NaN,Survey,Abdelrahman Ali; Chunping Xia; N'Banan Ouattar...,NaN,NaN,NaN,National,NaN,True,False
3,Egypt,1234.0,Tomatoes,2026,2.60,2.6%,Wholesale,Wholesale,NaN,Survey,Abdelrahman Ali; Chunping Xia; N'Banan Ouattar...,NaN,NaN,NaN,National,NaN,True,False
4,Egypt,1234.0,Tomatoes,2026,1.74,1.74%,Retailing,Retail,NaN,Survey,Abdelrahman Ali; Chunping Xia; N'Banan Ouattar...,NaN,NaN,NaN,National,NaN,True,False

### **11. Standardize Food Supply Stages and Remove Redundant Activity Column**

In [34]:
egypt_food_waste.loc[:, ["food_supply_stage", "activity"]].value_counts()

food_supply_stage  activity
Harvest            Harvesting               17
                   Harvesting, Threshing    10
Storage            Storage                   8
Transport          Transportation            4
Farm               Farm                      3
Processing         Processing                3
Wholesale          Wholesale                 3
Retail             Retailing                 3
Market             Marketing                 2
Trader             Trading                   1
Food Services      Consumption               1
Households         Consumption               1
Name: count, dtype: int64

In [35]:
stage_map = {
    "Farm": "Farm/Harvest", "Harvest": "Farm/Harvest",
    "Trader": "Wholesale/Market", "Wholesale": "Wholesale/Market", "Market": "Wholesale/Market",
}
egypt_food_waste["food_supply_stage"] = egypt_food_waste["food_supply_stage"].replace(stage_map)

egypt_food_waste = egypt_food_waste.drop(columns="activity")

In [36]:
egypt_food_waste.head()

,country,cpc_code,commodity,year,loss_percentage,loss_percentage_original,food_supply_stage,treatment,method_data_collection,reference,notes,loss_tonnes,loss_tonnes_per_ha,geo_level,governorate,is_suspect_year,is_lit_outlier
0,Egypt,1234.0,Tomatoes,2026,7.95,7.95%,Farm/Harvest,NaN,Survey,Abdelrahman Ali; Chunping Xia; N'Banan Ouattar...,NaN,NaN,NaN,National,NaN,True,False
1,Egypt,1234.0,Tomatoes,2026,7.75,7.75%,Processing,NaN,Survey,Abdelrahman Ali; Chunping Xia; N'Banan Ouattar...,NaN,NaN,NaN,National,NaN,True,False
2,Egypt,1234.0,Tomatoes,2026,2.50,2.5%,Wholesale/Market,NaN,Survey,Abdelrahman Ali; Chunping Xia; N'Banan Ouattar...,NaN,NaN,NaN,National,NaN,True,False
3,Egypt,1234.0,Tomatoes,2026,2.60,2.6%,Wholesale/Market,NaN,Survey,Abdelrahman Ali; Chunping Xia; N'Banan Ouattar...,NaN,NaN,NaN,National,NaN,True,False
4,Egypt,1234.0,Tomatoes,2026,1.74,1.74%,Retail,NaN,Survey,Abdelrahman Ali; Chunping Xia; N'Banan Ouattar...,NaN,NaN,NaN,National,NaN,True,False

### **12. Classify Measurement Scope and Analyze Food Supply Stages**

In [37]:
egypt_food_waste.food_supply_stage.value_counts()

food_supply_stage
Whole supply chain    78
Farm/Harvest          31
Storage                8
Wholesale/Market       6
Transport              4
Post-harvest           4
Processing             3
Retail                 3
Food Services          1
Households             1
Name: count, dtype: int64

In [38]:
egypt_food_waste["measurement_scope"] = np.select(
    [egypt_food_waste["food_supply_stage"].eq("Whole supply chain"),
     egypt_food_waste["food_supply_stage"].eq("Post-harvest")],
    ["Whole chain", "Post-harvest (aggregate)"],
    default="Single stage"
)

whole_chain_egypt_food_waste = egypt_food_waste[egypt_food_waste["measurement_scope"].eq("Whole chain")]
stage_egypt_food_waste       = egypt_food_waste[egypt_food_waste["measurement_scope"].eq("Single stage")]

In [39]:
egypt_food_waste.head()

,country,cpc_code,commodity,year,loss_percentage,loss_percentage_original,food_supply_stage,treatment,method_data_collection,reference,notes,loss_tonnes,loss_tonnes_per_ha,geo_level,governorate,is_suspect_year,is_lit_outlier,measurement_scope
0,Egypt,1234.0,Tomatoes,2026,7.95,7.95%,Farm/Harvest,NaN,Survey,Abdelrahman Ali; Chunping Xia; N'Banan Ouattar...,NaN,NaN,NaN,National,NaN,True,False,Single stage
1,Egypt,1234.0,Tomatoes,2026,7.75,7.75%,Processing,NaN,Survey,Abdelrahman Ali; Chunping Xia; N'Banan Ouattar...,NaN,NaN,NaN,National,NaN,True,False,Single stage
2,Egypt,1234.0,Tomatoes,2026,2.50,2.5%,Wholesale/Market,NaN,Survey,Abdelrahman Ali; Chunping Xia; N'Banan Ouattar...,NaN,NaN,NaN,National,NaN,True,False,Single stage
3,Egypt,1234.0,Tomatoes,2026,2.60,2.6%,Wholesale/Market,NaN,Survey,Abdelrahman Ali; Chunping Xia; N'Banan Ouattar...,NaN,NaN,NaN,National,NaN,True,False,Single stage
4,Egypt,1234.0,Tomatoes,2026,1.74,1.74%,Retail,NaN,Survey,Abdelrahman Ali; Chunping Xia; N'Banan Ouattar...,NaN,NaN,NaN,National,NaN,True,False,Single stage

### **Show result yet**

In [40]:
egypt_food_waste.shape

(139, 18)

In [41]:
egypt_food_waste.columns.tolist()

['country',
 'cpc_code',
 'commodity',
 'year',
 'loss_percentage',
 'loss_percentage_original',
 'food_supply_stage',
 'treatment',
 'method_data_collection',
 'reference',
 'notes',
 'loss_tonnes',
 'loss_tonnes_per_ha',
 'geo_level',
 'governorate',
 'is_suspect_year',
 'is_lit_outlier',
 'measurement_scope']

In [42]:
quality_report = pd.DataFrame(index=egypt_food_waste.columns)

quality_report["dtype"] = egypt_food_waste.dtypes.astype(str)
quality_report["total_rows"] = len(egypt_food_waste)
quality_report["missing_count"] = egypt_food_waste.isna().sum()
quality_report["missing_pct"] = (
    egypt_food_waste.isna().mean() * 100
).round(2)

quality_report["unique_count"] = egypt_food_waste.nunique(dropna=True)
quality_report["unique_pct"] = (
    egypt_food_waste.nunique(dropna=True) / max(len(egypt_food_waste), 1) * 100
).round(2)

quality_report["duplicate_row_count"] = egypt_food_waste.duplicated().sum()
quality_report["memory_bytes"] = egypt_food_waste.memory_usage(deep=True).iloc[1:].values

display(quality_report)

,dtype,total_rows,missing_count,missing_pct,unique_count,unique_pct,duplicate_row_count,memory_bytes
country,str,139,0,0.00,1,0.72,0,7506
cpc_code,string,139,0,0.00,24,17.27,0,7581
commodity,str,139,0,0.00,24,17.27,0,8086
year,int64,139,0,0.00,9,6.47,0,1112
loss_percentage,float64,139,0,0.00,126,90.65,0,1112
loss_percentage_original,str,139,0,0.00,128,92.09,0,7497
food_supply_stage,str,139,0,0.00,10,7.19,0,8894
treatment,str,139,115,82.73,9,6.47,0,5349
method_data_collection,str,139,0,0.00,4,2.88,0,11195
reference,str,139,0,0.00,7,5.04,0,19233
notes,str,139,122,87.77,4,2.88,0,5454
loss_tonnes,float64,139,61,43.88,50,35.97,0,1112
loss_tonnes_per_ha,float64,139,125,89.93,13,9.35,0,1112
geo_level,str,139,0,0.00,3,2.16,0,8137
governorate,str,139,110,79.14,6,4.32,0,5190
is_suspect_year,bool,139,0,0.00,2,1.44,0,139
is_lit_outlier,bool,139,0,0.00,2,1.44,0,139
measurement_scope,str,139,0,0.00,3,2.16,0,8449

# **Step 2: Finalize the dataset (flags + missing values + validation + save)**

### **1. Fix `cpc_code` (restore leading zeros)**

In [43]:
# cpc_code was read as float, so "0111" became "111.0". All CPC codes here start with "0".
# This cell is safe to run twice (idempotent).
s = egypt_food_waste["cpc_code"].astype("string").str.strip().str.replace(r"\.0$", "", regex=True)
egypt_food_waste["cpc_code"] = s.where(s.str.startswith("0"), "0" + s)

print(egypt_food_waste["cpc_code"].unique())

<StringArray>
[   '01234',     '0111',     '0112',     '0113',     '0114',     '0115',
     '0141',     '0142',    '01444',    '01445',    '01450',    '01510',
    '01530',    '01550',    '01701',    '01702',    '01703',    '01704',
    '01801', '01921.01',    '01330',    '01441', '01709.02',    '01323']
Length: 24, dtype: string

### **2\. Detect Potential Duplicates, Flag Suspected Outliers, and Handle Zero Loss Values Without Deleting Suspicious Records**

In [44]:
df = egypt_food_waste


key = ["commodity", "year", "food_supply_stage", "loss_percentage"]
national_keys = set(map(tuple, df.loc[df["geo_level"].eq("National"), key].values))
df["is_new_valley_copy"] = (
    df["governorate"].eq("New Valley")
    & df[key].apply(tuple, axis=1).isin(national_keys)
)

whole = df["food_supply_stage"].eq("Whole supply chain")
med   = df.loc[whole].groupby("commodity")["loss_percentage"].transform("median")
ratio = (df["loss_percentage"] / med).reindex(df.index)
df["is_suspect_value"] = whole & med.reindex(df.index).gt(0) & ((ratio < 0.2) | (ratio > 5))


df["is_zero_loss"] = df["loss_percentage"].eq(0)
df["loss_percentage_clean"] = df["loss_percentage"].mask(df["is_zero_loss"])

egypt_food_waste = df
print(df[["is_suspect_year", "is_lit_outlier", "is_new_valley_copy",
          "is_suspect_value", "is_zero_loss"]].sum())
display(df.loc[df["is_suspect_value"] | df["is_new_valley_copy"],
               ["commodity", "year", "food_supply_stage", "governorate", "loss_percentage"]])

is_suspect_year       5
is_lit_outlier        5
is_new_valley_copy    2
is_suspect_value      1
is_zero_loss          3
dtype: int64

    commodity  year   food_supply_stage governorate  loss_percentage
19      Wheat  2018        Farm/Harvest  New Valley             9.26
58      Wheat  2017        Farm/Harvest  New Valley            10.16
127    Olives  2014  Whole supply chain         NaN             1.48

### **3. Handle missing values**
| Column | Why missing | Action |
|---|---|---|
| `treatment` | only recorded for wheat harvest/storage | fill with label **"Not specified"** |
| `governorate` | row is national or regional | fill with label **"Not applicable"** |
| `notes` | no note in source | fill with label **"No note"** |
| `loss_tonnes` | source did not report quantity | **keep NaN** + indicator column |
| `loss_tonnes_per_ha` | only wheat harvest rows | **keep NaN** + indicator column |
| `loss_percentage_clean` | zero values turned into NaN | **keep NaN** |

Numeric columns are NOT imputed (mean/median would invent loss quantities that no source reported).

In [45]:
df = egypt_food_waste

df["has_loss_tonnes"]        = df["loss_tonnes"].notna()
df["has_loss_tonnes_per_ha"] = df["loss_tonnes_per_ha"].notna()

df["treatment"]   = df["treatment"].fillna("Not specified")
df["governorate"] = df["governorate"].fillna("Not applicable")
df["notes"]       = df["notes"].fillna("No note")

df["is_reliable"] = ~(df["is_suspect_year"] | df["is_new_valley_copy"]
                      | df["is_suspect_value"] | df["is_zero_loss"])

egypt_food_waste = df
print("Reliable rows:", int(df["is_reliable"].sum()), "of", len(df))
display(df.isna().sum()[lambda s: s > 0])

Reliable rows: 128 of 139

loss_tonnes               61
loss_tonnes_per_ha       125
loss_percentage_clean      3
dtype: int64

### **4. Types, column order, validation**

In [46]:
df = egypt_food_waste

cat_cols = ["commodity", "food_supply_stage", "treatment", "geo_level", "governorate",
            "measurement_scope", "method_data_collection", "reference"]
for c in cat_cols:
    df[c] = df[c].astype("category")

final_cols = [
    # what / when / where
    "cpc_code", "commodity", "year", "geo_level", "governorate",
    "food_supply_stage", "measurement_scope", "treatment",
    # values
    "loss_percentage", "loss_percentage_clean", "loss_percentage_original",
    "loss_tonnes", "has_loss_tonnes", "loss_tonnes_per_ha", "has_loss_tonnes_per_ha",
    # quality flags
    "is_reliable", "is_suspect_year", "is_lit_outlier", "is_new_valley_copy",
    "is_suspect_value", "is_zero_loss",
    # source
    "method_data_collection", "reference", "notes",
]
df = df[final_cols].drop_duplicates().reset_index(drop=True)

# ---- validation (will raise an error if something is wrong) ----
assert df.duplicated().sum() == 0,                       "duplicate rows found"
assert df["loss_percentage"].between(0, 100).all(),      "loss_percentage out of 0-100"
assert df["cpc_code"].str.match(r"^0\d{3,4}(\.\d{2})?$").all(), "bad cpc_code format"
assert df["year"].between(2000, 2026).all(),             "year out of range"
key_cols = ["cpc_code", "commodity", "year", "loss_percentage", "food_supply_stage",
            "measurement_scope", "geo_level", "method_data_collection", "reference"]
assert df[key_cols].notna().all().all(),                 "missing values in key columns"
print("All checks passed.", df.shape)

egypt_food_waste_final = df
display(df.head())

All checks passed. (139, 24)

,cpc_code,commodity,year,geo_level,governorate,food_supply_stage,measurement_scope,treatment,loss_percentage,loss_percentage_clean,...,has_loss_tonnes_per_ha,is_reliable,is_suspect_year,is_lit_outlier,is_new_valley_copy,is_suspect_value,is_zero_loss,method_data_collection,reference,notes
0,01234,Tomatoes,2026,National,Not applicable,Farm/Harvest,Single stage,Not specified,7.95,7.95,...,False,False,True,False,False,False,False,Survey,Abdelrahman Ali; Chunping Xia; N'Banan Ouattar...,No note
1,01234,Tomatoes,2026,National,Not applicable,Processing,Single stage,Not specified,7.75,7.75,...,False,False,True,False,False,False,False,Survey,Abdelrahman Ali; Chunping Xia; N'Banan Ouattar...,No note
2,01234,Tomatoes,2026,National,Not applicable,Wholesale/Market,Single stage,Not specified,2.50,2.50,...,False,False,True,False,False,False,False,Survey,Abdelrahman Ali; Chunping Xia; N'Banan Ouattar...,No note
3,01234,Tomatoes,2026,National,Not applicable,Wholesale/Market,Single stage,Not specified,2.60,2.60,...,False,False,True,False,False,False,False,Survey,Abdelrahman Ali; Chunping Xia; N'Banan Ouattar...,No note
4,01234,Tomatoes,2026,National,Not applicable,Retail,Single stage,Not specified,1.74,1.74,...,False,False,True,False,False,False,False,Survey,Abdelrahman Ali; Chunping Xia; N'Banan Ouattar...,No note

### **5. Save the final data**

| الملف | السؤال التحليلي الأساسي |
| :--- | :--- |
| **Egypt-food-waste_final.csv** | إيه كل البيانات المتاحة بعد التنظيف؟ |
| **Egypt-whole-chain.csv** | إزاي نقارن نسب الفقد بين المحاصيل على مستوى السلسلة بالكامل؟ |
| **Egypt-stage-level.csv** | إيه مراحل الفقد المسجلة لكل محصول، زي القمح والطماطم؟ |

In [ ]:
egypt_food_waste_final.to_csv("../final-data-set/egypt/Egypt-food-waste_final.csv", index=False)

# ready-made subsets for Step 3 (analysis)
egypt_food_waste_final.query("measurement_scope == 'Whole chain'") \
    .to_csv("../final-data-set/egypt/Egypt-whole-chain.csv", index=False)
egypt_food_waste_final.query("measurement_scope == 'Single stage'") \
    .to_csv("../final-data-set/egypt/Egypt-stage-level.csv", index=False)
print("Saved.")

Saved.

# ***Final Analysis***

In [49]:
quality_report = pd.DataFrame(index=egypt_food_waste.columns)

quality_report["dtype"] = egypt_food_waste.dtypes.astype(str)
quality_report["total_rows"] = len(egypt_food_waste)
quality_report["missing_count"] = egypt_food_waste.isna().sum()
quality_report["missing_pct"] = (
    egypt_food_waste.isna().mean() * 100
).round(2)

quality_report["unique_count"] = egypt_food_waste.nunique(dropna=True)
quality_report["unique_pct"] = (
    egypt_food_waste.nunique(dropna=True) / max(len(egypt_food_waste), 1) * 100
).round(2)

quality_report["duplicate_row_count"] = egypt_food_waste.duplicated().sum()
quality_report["memory_bytes"] = egypt_food_waste.memory_usage(deep=True).iloc[1:].values

display(quality_report)

,dtype,total_rows,missing_count,missing_pct,unique_count,unique_pct,duplicate_row_count,memory_bytes
country,str,139,0,0.00,1,0.72,0,7506
cpc_code,string,139,0,0.00,24,17.27,0,7456
commodity,category,139,0,0.00,24,17.27,0,1579
year,int64,139,0,0.00,9,6.47,0,1112
loss_percentage,float64,139,0,0.00,126,90.65,0,1112
loss_percentage_original,str,139,0,0.00,128,92.09,0,7497
food_supply_stage,category,139,0,0.00,10,7.19,0,742
treatment,category,139,0,0.00,10,7.19,0,818
method_data_collection,category,139,0,0.00,4,2.88,0,422
reference,category,139,0,0.00,7,5.04,0,1557
notes,str,139,0,0.00,5,3.60,0,8382
loss_tonnes,float64,139,61,43.88,50,35.97,0,1112
loss_tonnes_per_ha,float64,139,125,89.93,13,9.35,0,1112
geo_level,category,139,0,0.00,3,2.16,0,316
governorate,category,139,0,0.00,7,5.04,0,553
is_suspect_year,bool,139,0,0.00,2,1.44,0,139
is_lit_outlier,bool,139,0,0.00,2,1.44,0,139
measurement_scope,category,139,0,0.00,3,2.16,0,441
is_new_valley_copy,bool,139,0,0.00,2,1.44,0,139
is_suspect_value,bool,139,0,0.00,2,1.44,0,139
is_zero_loss,bool,139,0,0.00,2,1.44,0,139
loss_percentage_clean,float64,139,3,2.16,125,89.93,0,1112
has_loss_tonnes,bool,139,0,0.00,2,1.44,0,139
has_loss_tonnes_per_ha,bool,139,0,0.00,2,1.44,0,139
is_reliable,bool,139,0,0.00,2,1.44,0,139


| #  | العمود                     | النوع      | معناه                                                             | قراءة الأرقام بتاعتك                                              |
| -- | -------------------------- | ---------- | ----------------------------------------------------------------- | ----------------------------------------------------------------- |
| 1  | `country`                  | `str`      | الدولة (Egypt)                                                    | قيمة واحدة، فمالوش لازمة للتحليل الحالي                           |
| 2  | `cpc_code`                 | `string`   | كود المنتج في تصنيف FAO                                           | 24 كود = 24 محصول، يعني كل محصول له كود واحد                      |
| 3  | `commodity`                | `category` | اسم المحصول                                                       | 24 محصول، والقمح 48 صف                                            |
| 4  | `year`                     | `int64`    | سنة البيانات                                                      | 9 سنين من 2011 لـ 2026                                            |
| 5  | `loss_percentage`          | `float64`  | نسبة الفاقد %                                                     | 126 قيمة رقمية، من غير ناقص                                       |
| 6  | `loss_percentage_original` | `str`      | النسبة زي ما اتكتبت في المصدر، زي `"7.95%"` و`"13.0-15"`          | 128 قيمة                                                          |
| 7  | `food_supply_stage`        | `category` | مرحلة سلسلة الإمداد، زي Farm/Harvest وStorage وRetail             | 10 مراحل بعد الدمج                                                |
| 8  | `treatment`                | `category` | الطريقة المستخدمة، زي الحصاد اليدوي أو الـ silo                   | 10 قيم، فيها `"Not specified"`                                    |
| 9  | `method_data_collection`   | `category` | طريقة جمع البيانات، زي FAO وSurvey وLiterature وExpert            | 4 قيم                                                             |
| 10 | `reference`                | `category` | المرجع العلمي الكامل                                              | 7 مراجع                                                           |
| 11 | `notes`                    | `str`      | ملاحظات المصدر                                                    | 5 قيم، منها `"No note"`                                           |
| 12 | `loss_tonnes`              | `float64`  | كمية الفاقد بالطن                                                 | ناقص 61 صف (43.9%)                                                |
| 13 | `loss_tonnes_per_ha`       | `float64`  | الفاقد بالطن لكل هكتار                                            | ناقص 125 صف (89.9%)، وموجود في 14 صف حصاد قمح                     |
| 14 | `geo_level`                | `category` | المستوى الجغرافي: National أو Region أو Governorate/Area          | 3 قيم                                                             |
| 15 | `governorate`              | `category` | اسم المحافظة أو المنطقة                                           | 7 قيم، منها 6 أسماء و`"Not applicable"`                           |
| 16 | `measurement_scope`        | `category` | نطاق القياس: Whole chain أو Single stage أو Post-harvest          | 3 قيم                                                             |
| 17 | `is_suspect_year`          | `bool`     | هل السنة مشكوك فيها؟                                              | بيحدد صفوف 2026، وعددها 5 صفوف طماطم حسب الفحص السابق             |
| 18 | `is_lit_outlier`           | `bool`     | هل القيمة متطرفة مقارنة بالقيم اللي اتراجعت من الأدبيات؟          | الطماطم والعنب، بقيم من 28% لـ43% حسب الفحص السابق                |
| 19 | `is_new_valley_copy`       | `bool`     | هل سجل New Valley مطابق لتركيبة موجودة في السجلات القومية؟        | متوقع صفّين                                                       |
| 20 | `is_suspect_value`         | `bool`     | هل نسبة الفقد بعيدة 5 أضعاف عن وسيط المحصول في سجلات Whole chain؟ | متوقع صف واحد، للزيتون 2014                                       |
| 21 | `is_zero_loss`             | `bool`     | هل نسبة الفقد تساوي صفر؟                                          | متوقع 3 صفوف للـ Lupins                                           |
| 22 | `loss_percentage_clean`    | `float64`  | نسخة من نسبة الفقد، مع تحويل الأصفار إلى `NaN`                    | ناقص 3 صفوف (2.16%)                                               |
| 23 | `has_loss_tonnes`          | `bool`     | هل كمية الفاقد بالطن متاحة؟                                       | 78 `True` و61 `False`                                             |
| 24 | `has_loss_tonnes_per_ha`   | `bool`     | هل كمية الفاقد لكل هكتار متاحة؟                                   | 14 `True` و125 `False`                                            |
| 25 | `is_reliable`              | `bool`     | هل الصف مستوفي شروط التحليل الأساسي المحددة في الكود؟             | المفروض يستبعد الصفوف اللي عليها العلامات المحددة في منطق التصنيف |