# ***World Food Waste Graduation project***

In [85]:

import pandas as pd
import numpy as np
from pathlib import Path

## **Read Data**

In [86]:
world_food_loss = pd.read_csv('../data-set/World-food-waste.csv', dtype={"cpc_code": "string"})
display(world_food_loss.head())

,m49_code,country,region,cpc_code,commodity,year,loss_percentage,loss_percentage_original,loss_quantity,activity,food_supply_stage,treatment,cause_of_loss,sample_size,method_data_collection,reference,url,notes
0,1,World,NaN,0111,Wheat,2022,1.0,1%,NaN,Processing,Processing,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived product is wheat flour
1,1,World,NaN,0112,Maize (corn),2022,0.5,0.5%,NaN,Processing,Processing,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived product is maize flour.
2,1,World,NaN,0112,Maize (corn),2022,2.0,2%,NaN,Processing,Processing,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived product is Maize (corn) grits.
3,1,World,NaN,0112,Maize (corn),2022,2.0,2%,NaN,Processing,Processing,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived product is Maize (corn) grits flaked.
4,1,World,NaN,0112,Maize (corn),2022,0.1,0.1%,NaN,Processing,Processing,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived product is corn starch.

| اسم العمود | معناه في سياق بيانات FAO |
| :--- | :--- |
| **m49_code** | كود الدولة أو المنطقة حسب معيار الأمم المتحدة M49. مصر كودها 818. |
| **country** | اسم الدولة المرتبطة بالسجل، زي Egypt. |
| **region** | المنطقة الجغرافية، لو السجل بيمثل منطقة بدل دولة منفردة أو بيحتوي على تصنيف إقليمي. لازم نراجع تعريف الملف لمعرفة الاستخدام الدقيق للحقل ده. |
| **cpc_code** | كود تصنيف السلعة حسب نظام CPC. |
| **commodity** | اسم المنتج أو السلعة الغذائية، زي Tomatoes. |
| **year** | السنة المسجلة للدراسة في قاعدة البيانات، وفق تعريف FAO. |
| **loss_percentage** | نسبة الفقد المسجلة في الدراسة، وده المتغير الأساسي اللي بنحلله. |
| **loss_percentage_original** | يبدو إنه بيحتفظ بتمثيل النسبة الأصلي، لكن لازم نراجع ملف التصدير أو وصف الحقول علشان نأكد الفرق الدقيق بينه وبين العمود السابق. |
| **loss_quantity** | كمية الفقد، لو متاحة ومسجلة في المصدر. لازم نراجع الوحدة وتعريف الكمية قبل استخدامها. |
| **activity** | النشاط المرتبط بفقد الطعام، حسب وصف الدراسة الأصلية. |
| **food_supply_stage** | مرحلة سلسلة الإمداد الغذائي اللي الدراسة ربطت بيها الفقد. |
| **treatment** | حقل متعلق بالمعالجة أو التعامل مع المنتج وفق تعريف المصدر؛ محتاجين تعريف الحقل الأصلي لتحديد معناه بدقة. |
| **cause_of_loss** | سبب الفقد، لو الدراسة سجلته. |
| **sample_size** | حجم العينة المسجلة للدراسة، وفق وحدة العينة المستخدمة فيها. |
| **method_data_collection** | طريقة جمع أو تقدير بيانات الفقد، زي Survey. |
| **reference** | المرجع أو الدراسة اللي اتاخدت منها البيانات. |
| **url** | رابط المصدر الأصلي، لو متاح. |
| **notes** | ملاحظات إضافية مرتبطة بالسجل، لو موجودة. |

## **DATASET OVERVIEW**

In [87]:
print("=" * 60)
print("DATASET OVERVIEW")
print("=" * 60)

print("Shape:", world_food_loss.shape)
print("Number of rows:", world_food_loss.shape[0])
print("Number of columns:", world_food_loss.shape[1])
print("Memory usage (MB):", round(world_food_loss.memory_usage(deep=True).sum() / (1024 ** 2), 2))

display(world_food_loss.head())
display(world_food_loss.tail())
display(world_food_loss.sample(min(5, len(world_food_loss)), random_state=42))

============================================================
DATASET OVERVIEW
============================================================
Shape: (31465, 18)
Number of rows: 31465
Number of columns: 18
Memory usage (MB): 25.66

,m49_code,country,region,cpc_code,commodity,year,loss_percentage,loss_percentage_original,loss_quantity,activity,food_supply_stage,treatment,cause_of_loss,sample_size,method_data_collection,reference,url,notes
0,1,World,NaN,0111,Wheat,2022,1.0,1%,NaN,Processing,Processing,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived product is wheat flour
1,1,World,NaN,0112,Maize (corn),2022,0.5,0.5%,NaN,Processing,Processing,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived product is maize flour.
2,1,World,NaN,0112,Maize (corn),2022,2.0,2%,NaN,Processing,Processing,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived product is Maize (corn) grits.
3,1,World,NaN,0112,Maize (corn),2022,2.0,2%,NaN,Processing,Processing,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived product is Maize (corn) grits flaked.
4,1,World,NaN,0112,Maize (corn),2022,0.1,0.1%,NaN,Processing,Processing,NaN,NaN,NaN,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",NaN,Derived product is corn starch.

,m49_code,country,region,cpc_code,commodity,year,loss_percentage,loss_percentage_original,loss_quantity,activity,food_supply_stage,treatment,cause_of_loss,sample_size,method_data_collection,reference,url,notes
31460,894,Zambia,NaN,0118,Millet,2000,2.38075,2.38075,NaN,Storage,Storage,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN
31461,894,Zambia,NaN,0118,Millet,2000,2.00000,2,NaN,"Shelling, Threshing",NaN,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN
31462,894,Zambia,NaN,0118,Millet,2000,2.50000,2.5,NaN,Transportation,Farm,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN
31463,894,Zambia,NaN,0118,Millet,2000,1.00000,1,NaN,Transportation,Transport,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN
31464,894,Zambia,NaN,0118,Millet,2000,2.50000,2.5,NaN,Winnowing,Farm,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN

,m49_code,country,region,cpc_code,commodity,year,loss_percentage,loss_percentage_original,loss_quantity,activity,food_supply_stage,treatment,cause_of_loss,sample_size,method_data_collection,reference,url,notes
27126,826,United Kingdom of Great Britain and Northern I...,NaN,01312,Bananas,2014,1.50,0–3%,NaN,Packaging,Packing,NaN,NaN,NaN,Survey,"Carlos Mena, Leon A. Terry, Adrian Williams; L...",NaN,NaN
17402,51,Armenia,NaN,01199.90,Other cereals n.e.,2012,4.17,4.17%,600,NaN,Whole supply chain,NaN,NaN,NaN,FAO's annual Agriculture Production Questionna...,FAO Sources,NaN,NaN
2320,180,Democratic Republic of the Congo,NaN,0118,Millet,2017,2.50,2.5,NaN,Winnowing,Farm,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN
25378,768,Togo,NaN,0114,Sorghum,2020,3.60,3.6,NaN,"Shelling, Threshing",NaN,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN
10883,384,Côte d'Ivoire,NaN,0112,Maize (corn),2021,4.00,4,NaN,Drying,Farm,NaN,NaN,NaN,Modelled Estimates,"APHLIS, (2021), APHLIS",https://www.aphlis.net/en/data/tables/value-ch...,NaN

## **Analysis Columns**

In [88]:
print("COLUMN NAMES")
print(world_food_loss.columns.tolist())

print("\nDATA TYPES")
print(world_food_loss.dtypes)

print("\nDATASET INFO")
world_food_loss.info()

print("\nNUMERIC SUMMARY")
display(world_food_loss.describe().T)

print("\nALL COLUMNS SUMMARY")
display(world_food_loss.describe(include="all").T)

COLUMN NAMES
['m49_code', 'country', 'region', 'cpc_code', 'commodity', 'year', 'loss_percentage', 'loss_percentage_original', 'loss_quantity', 'activity', 'food_supply_stage', 'treatment', 'cause_of_loss', 'sample_size', 'method_data_collection', 'reference', 'url', 'notes']

DATA TYPES
m49_code                      int64
country                         str
region                          str
cpc_code                     string
commodity                       str
year                          int64
loss_percentage             float64
loss_percentage_original        str
loss_quantity                   str
activity                        str
food_supply_stage               str
treatment                       str
cause_of_loss                   str
sample_size                     str
method_data_collection          str
reference                       str
url                             str
notes                           str
dtype: object

DATASET INFO
<class 'pandas.DataFrame'>
RangeIndex: 31465 entries, 0 to 31464
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   m49_code                  31465 non-null  int64
 1   country                   31465 non-null  str
 2   region                    2036 non-null   str
 3   cpc_code                  31465 non-null  string
 4   commodity                 31465 non-null  str
 5   year                      31465 non-null  int64
 6   loss_percentage           31465 non-null  float64
 7   loss_percentage_original  31465 non-null  str
 8   loss_quantity             5050 non-null   str
 9   activity                  24095 non-null  str
 10  food_supply_stage         28074 non-null  str
 11  treatment                 1787 non-null   str
 12  cause_of_loss             1098 non-null   str
 13  sample_size               1862 non-null   str
 14  method_data_collection    31429 non-null  str
 15  reference                 31392 non-null  str
 16  url                       22123 non-null  str
 17  notes                     1534 non-null   str
dtypes: float64(1), int64(2), str(14), string(1)
memory usage: 4.3 MB

NUMERIC SUMMARY

,count,mean,std,min,25%,50%,75%,max
m49_code,31465.0,471.301637,260.948893,1.0,233.00000,454.00,710.00,894.0
year,31465.0,2010.610774,6.220568,2000.0,2005.00000,2011.00,2016.00,2026.0
loss_percentage,31465.0,4.683186,6.359491,0.0,1.49833,2.65,4.55,65.0

ALL COLUMNS SUMMARY

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
m49_code,31465.0,NaN,NaN,NaN,471.301637,260.948893,1.0,233.0,454.0,710.0,894.0
country,31465,159,United States of America,1716,NaN,NaN,NaN,NaN,NaN,NaN,NaN
region,2036,378,Western Cape Province,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cpc_code,31465,196,0112,6090,NaN,NaN,NaN,NaN,NaN,NaN,NaN
commodity,31465,213,Maize (corn),6090,NaN,NaN,NaN,NaN,NaN,NaN,NaN
year,31465.0,NaN,NaN,NaN,2010.610774,6.220568,2000.0,2005.0,2011.0,2016.0,2026.0
loss_percentage,31465.0,NaN,NaN,NaN,4.683186,6.359491,0.0,1.49833,2.65,4.55,65.0
loss_percentage_original,31465,5995,2.5,2309,NaN,NaN,NaN,NaN,NaN,NaN,NaN
loss_quantity,5050,3429,1000,74,NaN,NaN,NaN,NaN,NaN,NaN,NaN
activity,24095,180,Storage,6072,NaN,NaN,NaN,NaN,NaN,NaN,NaN
food_supply_stage,28074,20,Farm,10103,NaN,NaN,NaN,NaN,NaN,NaN,NaN
treatment,1787,764,Boro rice,57,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cause_of_loss,1098,406,Physical Losses,87,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sample_size,1862,266,933,159,NaN,NaN,NaN,NaN,NaN,NaN,NaN
method_data_collection,31429,11,Modelled Estimates,19497,NaN,NaN,NaN,NaN,NaN,NaN,NaN
reference,31392,328,"APHLIS, (2021), APHLIS",18922,NaN,NaN,NaN,NaN,NaN,NaN,NaN
url,22123,948,https://www.ers.usda.gov/data-products/food-av...,1196,NaN,NaN,NaN,NaN,NaN,NaN,NaN
notes,1534,586,Loss percentages obtained by dividing indicate...,72,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## **Analysis Missing values in Data-set**

In [89]:
missing_report = pd.DataFrame({
    "missing_count": world_food_loss.isna().sum(),
    "missing_percentage": world_food_loss.isna().mean().mul(100),
    "non_missing_count": world_food_loss.notna().sum(),
    "unique_non_null": world_food_loss.nunique(dropna=True)
})

missing_report = missing_report.sort_values(
    by="missing_percentage",
    ascending=False
)

display(missing_report)

,missing_count,missing_percentage,non_missing_count,unique_non_null
cause_of_loss,30367,96.510408,1098,406
notes,29931,95.124742,1534,586
treatment,29678,94.320674,1787,764
sample_size,29603,94.082314,1862,266
region,29429,93.529318,2036,378
loss_quantity,26415,83.950421,5050,3429
url,9342,29.690132,22123,948
activity,7370,23.422851,24095,180
food_supply_stage,3391,10.777054,28074,20
reference,73,0.232004,31392,328
method_data_collection,36,0.114413,31429,11
m49_code,0,0.000000,31465,157
country,0,0.000000,31465,159
loss_percentage,0,0.000000,31465,4629
cpc_code,0,0.000000,31465,196
loss_percentage_original,0,0.000000,31465,5995
commodity,0,0.000000,31465,213
year,0,0.000000,31465,27

### **Show "NA", "N/A", "NULL", "NONE", "UNKNOWN", "MISSING", "-" in string data-types**

In [90]:
import pandas as pd

missing_tokens = {
    "NA", "N/A", "NULL", "NONE",
    "UNKNOWN", "MISSING", "-", "NAN"
}

text_df = world_food_loss.select_dtypes(
    include=["object", "string"]
)

results = []

for col in text_df.columns:
    values = text_df[col].astype("string").str.strip()

    empty_count = values.eq("").sum()

    token_count = values.str.upper().isin(
        missing_tokens
    ).sum()

    actual_missing_count = values.isna().sum()

    results.append({
        "column": col,
        "empty_string_count": int(empty_count),
        "missing_token_count": int(token_count),
        "actual_missing_count": int(actual_missing_count)
    })

missing_report = (
    pd.DataFrame(results)
    .set_index("column")
    .sort_values(
        "actual_missing_count",
        ascending=False
    )
)

display(missing_report)

,empty_string_count,missing_token_count,actual_missing_count
column,,,
cause_of_loss,0,0,30367
notes,0,0,29931
treatment,0,0,29678
sample_size,0,6,29603
region,0,0,29429
loss_quantity,0,0,26415
url,0,0,9342
activity,0,0,7370
food_supply_stage,0,0,3391
reference,0,0,73
method_data_collection,0,0,36
commodity,0,0,0
loss_percentage_original,0,0,0
country,0,0,0
cpc_code,0,0,0

## **Show duplicated and unique data**

In [91]:
unique_report = pd.DataFrame({
    "unique_count": world_food_loss.nunique(dropna=True),
    "unique_with_nan": world_food_loss.nunique(dropna=False),
    "dtype": world_food_loss.dtypes.astype(str),
    "is_constant": world_food_loss.nunique(dropna=True).le(1)
})

display(unique_report.sort_values("unique_count"))

                          unique_count  unique_with_nan    dtype  is_constant
method_data_collection              11               12      str        False
food_supply_stage                   20               21      str        False
year                                27               27    int64        False
m49_code                           157              157    int64        False
country                            159              159      str        False
activity                           180              181      str        False
cpc_code                           196              196   string        False
commodity                          213              213      str        False
sample_size                        266              267      str        False
reference                          328              329      str        False
region                             378              379      str        False
cause_of_loss                      406              407      str        False
notes                              586              587      str        False
treatment                          764              765      str        False
url                                948              949      str        False
loss_quantity                     3429             3430      str        False
loss_percentage                   4629             4629  float64        False
loss_percentage_original          5995             5995      str        False

In [92]:
categorical_cols = world_food_loss.select_dtypes(
    include=["object", "string", "category"]
).columns

for col in categorical_cols:
    print(f"\n{'=' * 60}")
    print(f"Column: {col}")
    print("Unique values:", world_food_loss[col].nunique(dropna=True))
    print("Most frequent values:")
    display(world_food_loss[col].value_counts(dropna=False))

============================================================
Column: country
Unique values: 159
Most frequent values:

country
United States of America    1716
India                       1439
Ethiopia                    1151
Kenya                       1050
Ghana                        918
                            ...
Gabon                          1
Greece                         1
Bahrain                        1
Oman                           1
Saint Kitts and Nevis          1
Name: count, Length: 159, dtype: int64

============================================================
Column: region
Unique values: 378
Most frequent values:

region
NaN                                                  29429
Western Cape Province                                   59
Comilla                                                 45
Uttarakhand                                             42
Bawku, Wa  Tamale, Yendi , Techiman, and Kintampo       36
                                                     ...
Siliana                                                  1
Bizerte and Siliana                                      1
Apac Districy                                            1
California                                               1
Lusaka ans Southern Province                             1
Name: count, Length: 379, dtype: int64

============================================================
Column: cpc_code
Unique values: 196
Most frequent values:

cpc_code
0112        6090
0113        4880
0118        3686
0114        3531
0111        2379
            ...
01708          1
21181          1
21411          1
21439.02       1
21439.04       1
Name: count, Length: 196, dtype: Int64

============================================================
Column: commodity
Unique values: 213
Most frequent values:

commodity
Maize (corn)                                               6090
Rice                                                       4880
Millet                                                     3686
Sorghum                                                    3531
Wheat                                                      2379
                                                           ...
Bambara beans, dry                                            1
Pig meat, cuts, salted, dried or smoked (bacon and ham)       1
Raisins                                                       1
Juice of lemon                                                1
Juice of citrus fruit n.e.c.                                  1
Name: count, Length: 213, dtype: int64

============================================================
Column: loss_percentage_original
Unique values: 5995
Most frequent values:

loss_percentage_original
2.5        2309
3.5        1349
1          1280
2.65       1244
2           760
           ...
3.73079       1
2.30739       1
3.44008       1
1.27433       1
2.38075       1
Name: count, Length: 5995, dtype: int64

============================================================
Column: loss_quantity
Unique values: 3429
Most frequent values:

loss_quantity
NaN        26415
1000          74
0             56
3000          47
2000          46
           ...
2204           1
1276           1
2005           1
2482           1
2843.05        1
Name: count, Length: 3430, dtype: int64

============================================================
Column: activity
Unique values: 180
Most frequent values:

activity
NaN                                                                                    7370
Storage                                                                                6072
Transportation                                                                         5290
Drying, Harvesting                                                                     3500
Shelling, Threshing                                                                    3346
                                                                                       ...
Drying, Harvesting, Milling, Sorting, Storage, Threshing, Transportation, Winnowing       1
Sorting, Washing                                                                          1
Milling, Storage                                                                          1
Harvesting, Packaging, Sorting, Storage                                                   1
Farm, Milling                                                                             1
Name: count, Length: 181, dtype: int64

============================================================
Column: food_supply_stage
Unique values: 20
Most frequent values:

food_supply_stage
Farm                  10103
Whole supply chain     6147
Harvest                4160
NaN                    3391
Storage                3216
Transport              2091
Retail                  754
Processing              441
Wholesale               325
Households              248
Post-harvest            168
Trader                  107
Market                  101
Export                   50
Packing                  48
Distribution             39
Pre-harvest              24
Food Services            23
Collector                16
Grading                  12
Stacking                  1
Name: count, dtype: int64

============================================================
Column: treatment
Unique values: 764
Most frequent values:

treatment
NaN                                                                                                            29678
Boro rice                                                                                                         57
Aman rice                                                                                                         57
Major Season                                                                                                      54
Aus rice                                                                                                          48
                                                                                                               ...
Barley during 90 days at 28°C, 70% RH and 12h/12h light regime - Modified standard volume/dry-weight ratio         1
Barley during 90 days at 28°C, 70% RH and 12h/12h light regime - Grain count and weight                            1
Barley during 90 days at 28°C, 70% RH and 12h/12h light regime -  % damaged grains converted to weight loss        1
Barley during 90 days at 28°C, 70% RH and 12h/12h light regime -  1000 grain mass (TGM)                            1
Barley during 90 days at 28°C, 70% RH and 12h/12h light regime - TGM + dust                                        1
Name: count, Length: 765, dtype: int64

============================================================
Column: cause_of_loss
Unique values: 406
Most frequent values:

cause_of_loss
NaN                                                                                         30367
Physical Losses                                                                                87
Insect pest damage                                                                             54
main causes of this were a mismatch in supply and demand or cosmetic and quality related       41
Mechanical Damage                                                                              36
                                                                                            ...
Carotenoid Loss During Drying                                                                   1
Price Discount For Every One Bruchid Hole Per 100 Grains                                        1
Insects and mold                                                                                1
Insects, moisture and mold                                                                      1
Maize ear rot infection                                                                         1
Name: count, Length: 407, dtype: int64

============================================================
Column: sample_size
Unique values: 266
Most frequent values:

sample_size
NaN                                                                                                                                                        29603
933                                                                                                                                                          159
823 farmers                                                                                                                                                  112
10, planning project                                                                                                                                          93
600 stores from six large national and regional food retail chains                                                                                            91
                                                                                                                                                           ...
1520 Households                                                                                                                                                1
1301 Households                                                                                                                                                1
Table 1: On-farm post-harvest loss of maize limited on average and concentrated among few  National PHL among losers only  ( 11 months adjusted)  1,301        1
5 national and regional chains with  2,900 stores                                                                                                              1
114 farmsteads                                                                                                                                                 1
Name: count, Length: 267, dtype: int64

============================================================
Column: method_data_collection
Unique values: 11
Most frequent values:

method_data_collection
Modelled Estimates                                    19497
FAO's annual Agriculture Production Questionnaires     4209
Survey                                                 3220
Literature Review                                      1694
National Accounts                                      1275
Controlled Experiment                                   629
Case Study                                              528
No Data Collection Specified                            207
Expert Opinion                                          128
FLW Protocol                                             41
NaN                                                      36
Census                                                    1
Name: count, dtype: int64

============================================================
Column: reference
Unique values: 328
Most frequent values:

reference
APHLIS, (2021), APHLIS                                                                                                                                                          18922
FAO Sources                                                                                                                                                                      4209
USDA, (2021), USDA Food Loss                                                                                                                                                     1196
Jha SN; Vishwakarma RK; Ahmad T; Rai A; Dixit AK, (2015), Assessment Of Quantitative Harvest And Post-Harvest Losses Of Major Crops And Commodities In India                      428
S.K. Nanda; Rajesh Kumar Vishwakarma; H.V.L. Bathla; Poonam Chandra, (2012), Harvest And Post Harvest Losses Of Major Crops And Livestock Produce In India                        391
                                                                                                                                                                                ...
Tomlins et al.                                                                                                                                                                      1
Rees et al.                                                                                                                                                                         1
National Agricultural Statistics Service (NASS), (2011), Cattle And Calf Death Losses                                                                                               1
National Agricultural Statistics Service (NASS), (2006), Cattle And Calf Death Losses                                                                                               1
Mweshi Mukanga;John Derera;Pangirayi Tongoona;Mark D. Laing, (2010), A Survey Of Pre-Harvest Ear Rot Diseases Of Maize And Associated Mycotoxins In South And Central Zambia        1
Name: count, Length: 329, dtype: int64

============================================================
Column: url
Unique values: 948
Most frequent values:

url
NaN                                                                                                                                                                                      9342
https://www.ers.usda.gov/data-products/food-availability-per-capita-data-system/                                                                                                         1196
http://www.ciphet.in/upload/sphl/MOFPI%20REPORT1.pdf                                                                                                                                      428
https://www.researchgate.net/publication/280780214_Harvest_and_post_harvest_losses_of_major_crops_and_livestock_produce_in_India                                                          391
http://ucanr.edu/datastoreFiles/234-1847.pdf                                                                                                                                              226
                                                                                                                                                                                         ...
http://www.fao.org/fileadmin/user_upload/hlpe/hlpe_documents/Critical_Emerging_Issues/HLPE_Inquiry_Full_Proceedings__27-April-2014.pdf ; http://ucanr.edu/datastoreFiles/234-1847.pdf       1
https://www.researchgate.net/publication/267816160_Post-harvest_loss_in_sub-Saharan_Africa-what_do_farmers_say                                                                              1
https://ac.els-cdn.com/S0022474X1300101X/1-s2.0-S0022474X1300101X-main.pdf?_tid=7838d032-321c-4307-aedb-c3ae09ac7766&acdnat=1525860786_a8e0ced97dbaf2e10e043080c7f96a83                     1
http://usda.mannlib.cornell.edu/usda/current/CattDeath/CattDeath-05-12-2011.pdf                                                                                                             1
http://usda.mannlib.cornell.edu/usda/nass/CattDeath//2000s/2006/CattDeath-05-05-2006.pdf                                                                                                    1
Name: count, Length: 949, dtype: int64

============================================================
Column: notes
Unique values: 586
Most frequent values:

notes
NaN                                                                                                                     29931
Loss percentages obtained by dividing indicated losses by total resources and multiplying by 100%                          72
url not found                                                                                                              24
Review of databases and institutional libraries, relevant documentation of   studies conducted between 1980 and 2012       23
Food loss and waste                                                                                                        22
                                                                                                                        ...
The relative loss percentage is 9.9 ± 3.2 %                                                                                 1
The relative loss percentage is 10.1 ± 3.1 %                                                                                1
The relative loss percentage is 12.4 ± 3.5 %                                                                                1
Mean                                                                                                                        1
Sourced from Adams and Harman 1977                                                                                          1
Name: count, Length: 587, dtype: int64

In [93]:
print("Fully duplicated rows:", world_food_loss.duplicated().sum())

print(
    "Duplicated rows including all copies:",
    world_food_loss.duplicated(keep=False).sum()
)

duplicates = world_food_loss[
    world_food_loss.duplicated(keep=False)
].sort_values(by=world_food_loss.columns.tolist())

display(duplicates.head(20))

Fully duplicated rows: 180
Duplicated rows including all copies: 339

,m49_code,country,region,cpc_code,commodity,year,loss_percentage,loss_percentage_original,loss_quantity,activity,food_supply_stage,treatment,cause_of_loss,sample_size,method_data_collection,reference,url,notes
16249,50,Bangladesh,NaN,0113,Rice,2010,1.30,1.3,NaN,NaN,Processing,NaN,NaN,NaN,Modelled Estimates,Mst. Esmat Ara Begum; Mohammad Ismail Hossain;...,http://www.setscholars.org/index.php/ijarbae,NaN
16252,50,Bangladesh,NaN,0113,Rice,2010,1.30,1.3,NaN,NaN,Processing,NaN,NaN,NaN,Modelled Estimates,Mst. Esmat Ara Begum; Mohammad Ismail Hossain;...,http://www.setscholars.org/index.php/ijarbae,NaN
16123,50,Bangladesh,NaN,01312,Bananas,2010,3.20,3.2,NaN,NaN,Retail,NaN,NaN,100,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16125,50,Bangladesh,NaN,01312,Bananas,2010,3.20,3.2,NaN,NaN,Retail,NaN,NaN,100,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16121,50,Bangladesh,NaN,01312,Bananas,2010,5.10,5.1,NaN,NaN,Trader,NaN,NaN,100,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16122,50,Bangladesh,NaN,01312,Bananas,2010,5.10,5.1,NaN,NaN,Trader,NaN,NaN,100,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16120,50,Bangladesh,NaN,01312,Bananas,2010,7.70,7.7,NaN,NaN,Farm,NaN,NaN,100,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16126,50,Bangladesh,NaN,01312,Bananas,2010,7.70,7.7,NaN,NaN,Farm,NaN,NaN,100,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16124,50,Bangladesh,NaN,01312,Bananas,2010,8.60,8.6,NaN,NaN,Wholesale,NaN,NaN,100,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16130,50,Bangladesh,NaN,01312,Bananas,2010,8.60,8.6,NaN,NaN,Wholesale,NaN,NaN,100,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16166,50,Bangladesh,NaN,01319,"Other tropical and subtropical fruits, n.e.c.",2010,5.11,5.11,NaN,NaN,Trader,NaN,NaN,100,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16168,50,Bangladesh,NaN,01319,"Other tropical and subtropical fruits, n.e.c.",2010,5.11,5.11,NaN,NaN,Trader,NaN,NaN,100,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16165,50,Bangladesh,NaN,01319,"Other tropical and subtropical fruits, n.e.c.",2010,5.14,5.14,NaN,NaN,Retail,NaN,NaN,100,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16167,50,Bangladesh,NaN,01319,"Other tropical and subtropical fruits, n.e.c.",2010,5.14,5.14,NaN,NaN,Retail,NaN,NaN,100,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16164,50,Bangladesh,NaN,01319,"Other tropical and subtropical fruits, n.e.c.",2010,6.10,6.1,NaN,NaN,Wholesale,NaN,NaN,75,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16171,50,Bangladesh,NaN,01319,"Other tropical and subtropical fruits, n.e.c.",2010,6.10,6.1,NaN,NaN,Wholesale,NaN,NaN,75,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16169,50,Bangladesh,NaN,01319,"Other tropical and subtropical fruits, n.e.c.",2010,8.51,8.51,NaN,NaN,Farm,NaN,NaN,120,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16176,50,Bangladesh,NaN,01319,"Other tropical and subtropical fruits, n.e.c.",2010,8.51,8.51,NaN,NaN,Farm,NaN,NaN,120,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16180,50,Bangladesh,NaN,01323,Oranges,2010,4.00,4,NaN,NaN,Wholesale,NaN,NaN,50,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN
16184,50,Bangladesh,NaN,01323,Oranges,2010,4.00,4,NaN,NaN,Wholesale,NaN,NaN,50,Survey,Md Kamrul Hassan; Bishan Lal Das Chowdhury; Na...,http://www.measurepostharvestlosses.com/sites/...,NaN

## **Describe numeric data**

In [94]:
numeric_cols = world_food_loss.select_dtypes(
    include=np.number
).columns

numeric_report = pd.DataFrame(index=numeric_cols)

numeric_report["missing"] = world_food_loss[numeric_cols].isna().sum()
numeric_report["unique"] = world_food_loss[numeric_cols].nunique()
numeric_report["min"] = world_food_loss[numeric_cols].min()
numeric_report["max"] = world_food_loss[numeric_cols].max()
numeric_report["mean"] = world_food_loss[numeric_cols].mean()
numeric_report["median"] = world_food_loss[numeric_cols].median()
numeric_report["std"] = world_food_loss[numeric_cols].std()
numeric_report["negative_count"] = world_food_loss[numeric_cols].lt(0).sum()

display(numeric_report)

,missing,unique,min,max,mean,median,std,negative_count
m49_code,0,157,1.0,894.0,471.301637,454.00,260.948893,0
year,0,27,2000.0,2026.0,2010.610774,2011.00,6.220568,0
loss_percentage,0,4629,0.0,65.0,4.683186,2.65,6.359491,0

## **Show ouliers**

In [95]:
outlier_rows = []

for col in numeric_cols:
    series = world_food_loss[col].dropna()

    if series.empty:
        continue

    q1 = series.quantile(0.25)
    q3 = series.quantile(0.75)
    iqr = q3 - q1

    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr

    mask = (world_food_loss[col] < lower_bound) | (
        world_food_loss[col] > upper_bound
    )

    outlier_rows.append({
        "column": col,
        "lower_bound": lower_bound,
        "upper_bound": upper_bound,
        "outlier_count": int(mask.sum()),
        "outlier_percentage": round(mask.mean() * 100, 2)
    })

outlier_report = pd.DataFrame(outlier_rows)
display(outlier_report)

,column,lower_bound,upper_bound,outlier_count,outlier_percentage
0,m49_code,-482.500000,1425.500000,0,0.0
1,year,1988.500000,2032.500000,0,0.0
2,loss_percentage,-3.079175,9.127505,3555,11.3

## **Show final columns**

In [96]:
print(world_food_loss.columns.tolist())

['m49_code', 'country', 'region', 'cpc_code', 'commodity', 'year', 'loss_percentage', 'loss_percentage_original', 'loss_quantity', 'activity', 'food_supply_stage', 'treatment', 'cause_of_loss', 'sample_size', 'method_data_collection', 'reference', 'url', 'notes']

## **Data quality check on the Year**

In [97]:
if "year" in world_food_loss.columns:
    print("Invalid or suspicious years:")
    display(
        world_food_loss.loc[
            ~world_food_loss["year"].between(1900, 2100),
            ["year"]
        ].head(20)
    )

Invalid or suspicious years:

Empty DataFrame
Columns: [year]
Index: []

## **Finally analysis of data**

In [98]:
quality_report = pd.DataFrame(index=world_food_loss.columns)

quality_report["dtype"] = world_food_loss.dtypes.astype(str)
quality_report["total_rows"] = len(world_food_loss)
quality_report["missing_count"] = world_food_loss.isna().sum()
quality_report["missing_pct"] = (
    world_food_loss.isna().mean() * 100
).round(2)

quality_report["unique_count"] = world_food_loss.nunique(dropna=True)
quality_report["unique_pct"] = (
    world_food_loss.nunique(dropna=True) / max(len(world_food_loss), 1) * 100
).round(2)

quality_report["duplicate_row_count"] = world_food_loss.duplicated().sum()
quality_report["memory_bytes"] = world_food_loss.memory_usage(deep=True).iloc[1:].values

display(quality_report)

,dtype,total_rows,missing_count,missing_pct,unique_count,unique_pct,duplicate_row_count,memory_bytes
m49_code,int64,31465,0,0.00,157,0.50,180,251720
country,str,31465,0,0.00,159,0.51,180,1852077
region,str,31465,29429,93.53,378,1.20,180,1085553
cpc_code,string,31465,0,0.00,196,0.62,180,1681711
commodity,str,31465,0,0.00,213,0.68,180,1848523
year,int64,31465,0,0.00,27,0.09,180,251720
loss_percentage,float64,31465,0,0.00,4629,14.71,180,251720
loss_percentage_original,str,31465,0,0.00,5995,19.05,180,1680265
loss_quantity,str,31465,26415,83.95,3429,10.90,180,1118501
activity,str,31465,7370,23.42,180,0.57,180,1735342
food_supply_stage,str,31465,3391,10.78,20,0.06,180,1725153
treatment,str,31465,29678,94.32,764,2.43,180,1112143
cause_of_loss,str,31465,30367,96.51,406,1.29,180,1130002
sample_size,str,31465,29603,94.08,266,0.85,180,1136945
method_data_collection,str,31465,36,0.11,11,0.03,180,2198937
reference,str,31465,73,0.23,328,1.04,180,3265963
url,str,31465,9342,29.69,948,3.01,180,3367226
notes,str,31465,29931,95.12,586,1.86,180,1235020

## **Result of analysis**

## **Result of analysis**
| الملاحظة (من الاستكشاف فوق) | الرقم |
|---|---|
| الشكل الأصلي | 31,465 صف × 18 عمود |
| عدد الدول | 159 اسم (فيهم World وأقاليم) |
| صفوف مكررة بالكامل | 180 |
| `cause_of_loss` و`notes` و`treatment` و`sample_size` و`region` | ناقصين 93% لـ 96%، لكن **مش فاضيين** (فيهم معلومة حقيقية) |
| `loss_quantity` | ناقص 84%، ونوعه نص بوحدات مختلطة (kg, quintals, thousand tons, kg/MT...) |
| `food_supply_stage` | ناقص 3,391 صف (10.8%) وأغلبهم عندهم `activity` |
| `method_data_collection` | 11 طريقة، أكترها Modelled Estimates |
| `loss_percentage` | من 0 لـ 65، والـ IQR بيعتبر 11.3% outliers (مش بالضرورة غلط) |
| `year` | من 2000 لـ 2026 |
| `cpc_code` | **مش كله بيبدأ بصفر**: 730 كود بيبدأ بـ 2 (لحوم وألبان) و16 بـ 3 |
| الداتا مش متوازنة | أمريكا والهند وإثيوبيا وكينيا ليهم آلاف الصفوف، و17 دولة عندها أقل من 5 صفوف |

## **Solution of these problems**
الخطوات هنا نفس خطوات مصر، لكن اتعدّلت عشان الداتا بقت **159 دولة**:

| خطوة مصر | في العالم |
|---|---|
| حذف `sample_size` و`cause_of_loss` | **منحذفهمش**: فيهم معلومة حقيقية (1,862 و1,098 صف). `sample_size` بتتحول لرقم، و`cause_of_loss` بتفضل نص |
| حذف `m49_code` و`country` (ثابتين) | **منحذفهمش**: الدولة هي البُعد الأساسي دلوقتي |
| حذف `url` | بنسيبه (70% من الصفوف فيها رابط المصدر) |
| تصحيح `cpc_code` بإضافة صفر في الأول | **ممنوع هنا**: 746 كود بيبدأ بـ 2 أو 3 (زي `21111.01` لحم بقري)، والصفر هيبوّظهم. بنقراه نص وخلاص |
| `governorate` من `region` | `region` بقت `subnational_region` (مكان جوه الدولة: مقاطعة، district...) |
| `is_new_valley_copy` | بقت `is_subnational_copy`: صف محلي مطابق لصف قومي لنفس الدولة |
| `is_suspect_value` (وسيط المحصول) | بقت جوه **كل دولة × محصول** (3 صفوف على الأقل) |
| حذف `activity` | منحذفهاش، بنستخدمها نملى المرحلة الناقصة

### **1. Convert "cpc_code" column to <"string type">**

In [99]:
world_food_loss["cpc_code"] = world_food_loss["cpc_code"].astype("string").str.strip()
print(world_food_loss["cpc_code"].dtype)
print("codes not starting with 0:", int((~world_food_loss["cpc_code"].str.startswith("0")).sum()))
print(world_food_loss.loc[~world_food_loss["cpc_code"].str.startswith("0"), "cpc_code"].unique()[:10])

string
codes not starting with 0: 746
<StringArray>
['23140.04', '23140.08',    '24320', '23161.02', '21113.01', '21111.01',
    '21115',    '21121', '21393.90',    '23911']
Length: 10, dtype: string

### **2. Clean text, unify spelling, drop duplicated data**
> الداتا الخام فيها 180 صف مكرر فقط. بنشيل التكرار على **كل الأعمدة الأصلية** قبل ما نحذف أو نغيّر أي عمود، وإلا صفوف من دول مختلفة هتبان مكررة وتتمسح بالغلط.

In [100]:
df = world_food_loss

MISSING = {"", "na", "n/a", "null", "none", "unknown", "missing", "-", "nan"}
for c in df.select_dtypes(include=["object", "string"]).columns:
    s = df[c].astype("string").str.strip().str.replace(r"\s+", " ", regex=True)
    df[c] = s.mask(s.str.lower().isin(MISSING))

# HTML tags inside some commodity names, e.g. "Chillies (<i>Capsicum</i> spp.)"
df["commodity"] = (df["commodity"].str.replace(r"<[^>]+>", "", regex=True)
                                  .str.replace(r"\s+", " ", regex=True).str.strip())

def unify_case(s):
    """'Major Season' / 'Major season' -> the most frequent spelling."""
    s = s.astype("string")
    key = s.str.casefold()
    canon = (pd.DataFrame({"k": key, "v": s}).dropna()
               .groupby("k")["v"].agg(lambda x: x.value_counts().index[0]).to_dict())
    return key.map(canon).astype("string")

for c in ["country", "commodity", "region", "treatment", "cause_of_loss", "activity",
          "food_supply_stage", "method_data_collection", "reference"]:
    df[c] = unify_case(df[c])

before = len(df)
df = df.drop_duplicates().reset_index(drop=True)
print(f"exact duplicates removed: {before - len(df)}  ->  {len(df)} rows")

# one name per country code and one name per CPC code (UK / Taiwan variants, 'n.e.' vs 'n.e.c.')
most_common = lambda x: x.value_counts().index[0]
n1, n2 = df["country"].nunique(), df["commodity"].nunique()
df["country"]   = df.groupby("m49_code")["country"].transform(most_common)
df["commodity"] = df.groupby("cpc_code")["commodity"].transform(most_common)
print("country names:", n1, "->", df["country"].nunique())
print("commodity names:", n2, "->", df["commodity"].nunique())

world_food_loss = df

exact duplicates removed: 180  ->  31285 rows
country names: 159 -> 157
commodity names: 210 -> 196

### **3. Keep `m49_code`, `country`, `url`, `cause_of_loss`; convert `sample_size` to a number**

In [101]:
df = world_food_loss

ss = df["sample_size"].astype("string")
df["sample_size_n"]    = pd.to_numeric(ss.str.replace(",", "", regex=False)
                                         .str.extract(r"(\d+(?:\.\d+)?)")[0], errors="coerce")
df["sample_size_text"] = ss
df = df.drop(columns="sample_size")

world_food_loss = df
print(world_food_loss[["m49_code", "country", "url", "cause_of_loss", "sample_size_n"]].notna().mean().round(3))

m49_code         1.000
country          1.000
url              0.702
cause_of_loss    0.035
sample_size_n    0.058
dtype: float64

### **4. Separate loss_quantity to 2 columns since the Unit (tonnes / tonnes per ha) and mark rates**

In [102]:
df = world_food_loss

df["loss_quantity_text"] = df["loss_quantity"]
q = df["loss_quantity"].astype("string").str.lower().str.strip()
q = q.str.replace(r"(?<=\d),(?=\d)", "", regex=True)                  # 5,799.33 -> 5799.33
q = q.str.replace(r"(?<=\d)\s(?=\d{3}(?!\d))", "", regex=True)        # "36 275" -> 36275

num_all = pd.to_numeric(q, errors="coerce")                             # plain numbers (1e+05 included)
num_txt = pd.to_numeric(q.str.extract(r"(\d+(?:\.\d+)?)")[0], errors="coerce")
num = num_all.fillna(num_txt)

per_ha   = q.str.contains(r"/\s*ha\b|per\s*ha\b|ha-1|t/ha", na=False)
is_rate  = (q.str.contains(r"/\s*(?:mt|quintal|q\b|capita|household|acre|farm)|per\s*(?:quintal|acre|capita|household|farm)"
                           r"|\bhead\b|kfarm|kga", na=False)) & ~per_ha
million  = q.str.contains(r"million|milion|\bm\s+(?:ton|tonne|kg)", na=False)
thousand = q.str.contains(r"thousand", na=False)
kilo     = q.str.contains(r"\bkgs?\b|kilogram", na=False)
quintal  = q.str.contains(r"quintal", na=False)
unit_known = per_ha | is_rate | million | thousand | kilo | quintal | q.str.contains(r"ton|tonne|\bt\b|\bmt\b|metric", na=False)

scale  = np.where(million, 1_000_000, np.where(thousand, 1_000, 1))
factor = np.where(kilo, 0.001, np.where(quintal, 0.1, 1.0))             # kg -> t, quintal (100 kg) -> t
value_t = num * scale * factor

df["loss_tonnes"]        = value_t.where(~per_ha & ~is_rate)
df["loss_tonnes_per_ha"] = (num * factor).where(per_ha & ~is_rate)
df["quantity_is_rate"]   = is_rate.fillna(False)                       # kg/quintal, kg/MT, per capita, heads
df["quantity_unit_assumed"] = q.notna() & ~unit_known                  # plain number -> assumed tonnes
df = df.drop(columns="loss_quantity")

world_food_loss = df
print("rates/counts (loss_tonnes left empty):", int(df["quantity_is_rate"].sum()))
print("plain numbers, tonnes assumed:", int(df["quantity_unit_assumed"].sum()))
display(df.loc[df["loss_quantity_text"].notna(), ["loss_quantity_text", "loss_tonnes", "loss_tonnes_per_ha", "quantity_is_rate"]].sample(10, random_state=1))

rates/counts (loss_tonnes left empty): 87
plain numbers, tonnes assumed: 4537

      loss_quantity_text  loss_tonnes  loss_tonnes_per_ha  quantity_is_rate
20039              80000      80000.0                <NA>             False
25194               1000       1000.0                <NA>             False
9052                  98         98.0                <NA>             False
14927             262000     262000.0                <NA>             False
8931                  18         18.0                <NA>             False
8784                 157        157.0                <NA>             False
27109               3000       3000.0                <NA>             False
6203                8900       8900.0                <NA>             False
19727             537675     537675.0                <NA>             False
19306               1539       1539.0                <NA>             False

### **5. Read `loss_percentage_original`: ranges and mismatches**

In [103]:
df = world_food_loss

orig = df["loss_percentage_original"]
orig_num = pd.to_numeric(orig.str.extract(r"(\d*\.?\d+)")[0], errors="coerce")
df["is_range_value"]  = orig.str.contains(r"\d\s*%?\s*(?:-|–|—|to)\s*\.?\d", na=False)   # "5.43% - 9.68%", ".49-.55"
df["is_pct_mismatch"] = (~df["is_range_value"] & orig_num.notna()
                         & ((orig_num - df["loss_percentage"]).abs() > 0.5))

world_food_loss = df
print("ranges:", int(df["is_range_value"].sum()), "| mismatches:", int(df["is_pct_mismatch"].sum()))

ranges: 890 | mismatches: 0

### **6. Country level: flag aggregates (World / regions) and add continent**

In [104]:
df = world_food_loss

M49_AGGREGATES = {1, 2, 5, 9, 11, 13, 14, 15, 17, 18, 19, 21, 29, 30, 34, 35, 39,
                  53, 54, 57, 61, 142, 143, 145, 150, 151, 154, 155, 202, 419,
                  199, 432, 485, 514, 722, 747}
df["is_aggregate"] = (df["m49_code"].isin(M49_AGGREGATES)
                      | df["country"].str.contains(r"^world$|^total", case=False, na=False))

CONTINENTS = {
 "Africa": {12,24,204,72,854,108,120,148,384,180,818,232,748,231,266,270,288,324,624,404,426,430,
            450,454,466,478,480,504,508,516,562,566,646,686,694,706,710,728,729,768,788,800,834,894,716},
 "Asia": {4,51,31,48,50,116,156,158,268,356,360,364,376,392,400,398,408,410,417,418,422,458,496,104,
          524,512,586,275,608,682,144,760,762,764,626,792,860,704},
 "Europe": {8,40,112,56,191,208,233,246,250,276,300,348,372,380,428,440,442,528,578,616,620,642,643,
            688,703,724,752,756,807,804,826},
 "North America": {124,484,840,188,192,222,320,332,340,388,558,591,659,662,780},
 "South America": {32,68,76,152,170,218,328,600,604,862},
 "Oceania": {36,242,540,554},
}
m49_to_continent = {code: cont for cont, codes in CONTINENTS.items() for code in codes}
df["continent"] = df["m49_code"].map(m49_to_continent).fillna("Unknown")
df.loc[df["is_aggregate"], "continent"] = "Aggregate"

world_food_loss = df
print("aggregate rows:", int(df["is_aggregate"].sum()))
display(df.loc[df["is_aggregate"], "country"].value_counts())
display(df["continent"].value_counts())
print("countries without continent:", df.loc[df["continent"].eq("Unknown"), "country"].unique())

aggregate rows: 107

country
World                              29
Sub-Saharan Africa                 17
Europe                             14
South-Eastern Asia                  6
Central Asia                        5
Western Asia                        5
Northern Africa                     5
Northern America                    5
Southern Asia                       5
Latin America and the Caribbean     5
Western Africa                      4
Africa                              4
Australia and New Zealand           2
Asia                                1
Name: count, dtype: int64

continent
Africa           21330
Asia              4218
North America     2626
Europe            2049
South America      840
Oceania            115
Aggregate          107
Name: count, dtype: int64

countries without continent: <StringArray>
[]
Length: 0, dtype: str

### **7. Classify Geographic Levels and keep the sub-national place**

In [105]:
df = world_food_loss

nat_pattern = r"national|whole country|all regions|average"
is_nat = df["region"].isna() | df["region"].str.contains(nat_pattern, case=False, na=False)

df["geo_level"] = np.where(is_nat, "National", "Subnational")
df.loc[df["is_aggregate"], "geo_level"] = "Aggregate"
df["subnational_region"] = df["region"].where(df["geo_level"].eq("Subnational"))
df = df.drop(columns="region")

world_food_loss = df
display(world_food_loss["geo_level"].value_counts())
display(world_food_loss["subnational_region"].value_counts().head(10))

geo_level
National       29179
Subnational     1999
Aggregate        107
Name: count, dtype: int64

subnational_region
Western Cape Province                               59
Comilla                                             45
Uttarakhand                                         42
Bawku, Wa Tamale, Yendi , Techiman, and Kintampo    36
Rangpur and Dinazpur district                       36
Mbire District                                      35
North Hwanghae, South Pyongan and Pongyang City     33
Mymensingh                                          30
Guruve District                                     30
Dinajpur                                            29
Name: count, dtype: Int64

### **8. Handle names of treatment and cause_of_loss**
> العمودين نصوص حرة (700+ قيمة)، فبنوحّد بس الحروف الكبيرة/الصغيرة (اتعملت في الخطوة 2). مش هنعمل mapping يدوي.

In [106]:
display(world_food_loss["treatment"].value_counts().head(10))
display(world_food_loss["cause_of_loss"].value_counts().head(10))

treatment
Major Season            99
Minor Season            66
Aman rice               63
Boro rice               63
Aus rice                54
Maize on cobs           23
Shelled maize           23
Japonica rice           19
Indica rice             18
At 30 degree celsius    18
Name: count, dtype: Int64

cause_of_loss
Physical Losses                                                                                                                                                                                                      88
Insect pest damage                                                                                                                                                                                                   54
main causes of this were a mismatch in supply and demand or cosmetic and quality related                                                                                                                             41
Mechanical Damage                                                                                                                                                                                                    37
Decay                                                                                                                                                                                                                30
Rodents                                                                                                                                                                                                              26
Improper Harvesting And Transportation Methods, Unsuitable Storage Of Products After Harvest, Poor Sorting, Improper Packaging And Distribution. Losses Also Occur During Retail Sale, Consumption And Processing    24
Sourced from Jha et al. (2015                                                                                                                                                                                        22
Insect damage                                                                                                                                                                                                        19
Decay, Mechanic Damage, Sorting                                                                                                                                                                                      18
Name: count, dtype: Int64

### **9. Standardize Food Supply Stages (fill from `activity`) and classify Measurement Scope**

In [107]:
df = world_food_loss

print("missing stage before:", int(df["food_supply_stage"].isna().sum()))

stage_map = {
    "Farm": "Farm/Harvest", "Harvest": "Farm/Harvest",
    "Trader": "Wholesale/Market", "Wholesale": "Wholesale/Market", "Market": "Wholesale/Market",
    "Collector": "Wholesale/Market", "Distribution": "Wholesale/Market",
    "Packing": "Packing/Grading", "Grading": "Packing/Grading", "Stacking": "Packing/Grading",
}
df["food_supply_stage"] = df["food_supply_stage"].replace(stage_map)

KEYWORDS = [
    (r"stor",                                    "Storage"),
    (r"transport",                               "Transport"),
    (r"retail",                                  "Retail"),
    (r"consum|household",                        "Households"),
    (r"wholesale|market|trad|distribut|collect", "Wholesale/Market"),
    (r"process|mill|extract|grind|parboil",      "Processing"),
    (r"pack|grading",                            "Packing/Grading"),
    (r"export",                                  "Export"),
    (r"harvest|thresh|dry|shell|winnow|farm|field|reap|cut|clean", "Farm/Harvest"),
]
def activity_to_stage(text):
    if pd.isna(text):
        return pd.NA
    found = set()
    for token in re.split(r"[,;/&]|\band\b", str(text).lower()):
        for pat, stage in KEYWORDS:
            if re.search(pat, token):
                found.add(stage); break
    if len(found) == 1: return found.pop()
    if len(found) > 1:  return "Multiple stages"
    return pd.NA

miss = df["food_supply_stage"].isna()
df.loc[miss, "food_supply_stage"] = df.loc[miss, "activity"].map(activity_to_stage)
df["food_supply_stage"] = df["food_supply_stage"].fillna("Unknown stage")

df["measurement_scope"] = np.select(
    [df["food_supply_stage"].eq("Whole supply chain"),
     df["food_supply_stage"].eq("Post-harvest"),
     df["food_supply_stage"].eq("Multiple stages"),
     df["food_supply_stage"].eq("Unknown stage")],
    ["Whole chain", "Post-harvest (aggregate)", "Multi-stage", "Unknown"],
    default="Single stage"
)

world_food_loss = df
whole_chain_world_food_waste = world_food_loss[world_food_loss["measurement_scope"].eq("Whole chain")]
stage_world_food_waste       = world_food_loss[world_food_loss["measurement_scope"].eq("Single stage")]

print("missing stage after:", int((df["food_supply_stage"] == "Unknown stage").sum()))
display(df["food_supply_stage"].value_counts())
display(df["measurement_scope"].value_counts())

missing stage before: 3391
missing stage after: 46

food_supply_stage
Farm/Harvest          17593
Whole supply chain     6005
Storage                3212
Transport              2090
Retail                  747
Wholesale/Market        579
Processing              437
Households              247
Post-harvest            168
Packing/Grading          64
Export                   50
Unknown stage            46
Pre-harvest              24
Food Services            23
Name: count, dtype: Int64

measurement_scope
Single stage                25066
Whole chain                  6005
Post-harvest (aggregate)      168
Unknown                        46
Name: count, dtype: int64

### **10. Commodity group from the CPC code**
> كود CPC مش كله بيبدأ بصفر: `01x` محاصيل، `02x` حيوانات ومنتجات خام، و`21` لـ `24` منتجات مصنّعة (لحوم، ألبان، طحين...).

In [108]:
def cpc_group(code):
    c = str(code)
    crops = {"011": "Cereals", "012": "Vegetables", "013": "Fruits & nuts", "014": "Oilseeds",
             "015": "Roots & tubers", "016": "Beverage & spice crops", "017": "Pulses",
             "018": "Sugar crops", "019": "Other crops"}
    if c[:3] in crops:      return crops[c[:3]]
    if c.startswith("02"):  return "Animal products (raw)"
    if c.startswith("21"):  return "Meat, fish & oils (processed)"
    if c.startswith("22"):  return "Dairy & eggs (processed)"
    if c.startswith("23"):  return "Grain mill & other processed food"
    if c.startswith("24"):  return "Beverages & sugar (processed)"
    return "Other"

world_food_loss["commodity_group"] = world_food_loss["cpc_code"].map(cpc_group)
display(world_food_loss["commodity_group"].value_counts())

commodity_group
Cereals                              22947
Fruits & nuts                         2492
Vegetables                            2280
Roots & tubers                        1008
Oilseeds                               584
Pulses                                 498
Animal products (raw)                  446
Meat, fish & oils (processed)          410
Grain mill & other processed food      272
Beverage & spice crops                 184
Sugar crops                             88
Dairy & eggs (processed)                44
Other                                   16
Other crops                             13
Beverages & sugar (processed)            3
Name: count, dtype: int64

### **11. Flags: suspect year, zero loss, extreme values, literature outliers**
> **ليه flag ومش حذف؟** النسبة العالية مش بالضرورة غلط (فاقد الفاكهة في الحر ممكن يوصل 40%)، فبنعلّم ونسيب القرار في التحليل.

In [109]:
df = world_food_loss

df["is_suspect_year"] = df["year"] > 2025
df["is_zero_loss"]    = df["loss_percentage"].eq(0)
df["loss_percentage_clean"] = df["loss_percentage"].mask(df["is_zero_loss"])
df["is_modelled"]     = df["method_data_collection"].str.contains("model", case=False, na=False)

# extreme value = above Q3 + 3*IQR inside its own commodity + scope (needs 20+ rows, countries only)
base = df.loc[~df["is_aggregate"]]
grp  = base.groupby(["commodity", "measurement_scope"])["loss_percentage"]
q3   = grp.transform(lambda x: x.quantile(0.75))
iqr  = grp.transform(lambda x: x.quantile(0.75) - x.quantile(0.25))
n    = grp.transform("size")
extreme = (n >= 20) & (base["loss_percentage"] > q3 + 3 * iqr)
df["is_extreme_value"] = extreme.reindex(df.index, fill_value=False)
df["is_lit_outlier"]   = df["is_extreme_value"] & df["method_data_collection"].eq("Literature Review")

world_food_loss = df
print(df[["is_suspect_year", "is_zero_loss", "is_modelled", "is_extreme_value", "is_lit_outlier"]].sum())

is_suspect_year         5
is_zero_loss           60
is_modelled         19494
is_extreme_value      742
is_lit_outlier        117
dtype: Int64

### **Show result yet**

In [110]:
world_food_loss.shape

(31285, 36)

In [111]:
world_food_loss.columns.tolist()

['m49_code',
 'country',
 'cpc_code',
 'commodity',
 'year',
 'loss_percentage',
 'loss_percentage_original',
 'activity',
 'food_supply_stage',
 'treatment',
 'cause_of_loss',
 'method_data_collection',
 'reference',
 'url',
 'notes',
 'sample_size_n',
 'sample_size_text',
 'loss_quantity_text',
 'loss_tonnes',
 'loss_tonnes_per_ha',
 'quantity_is_rate',
 'quantity_unit_assumed',
 'is_range_value',
 'is_pct_mismatch',
 'is_aggregate',
 'continent',
 'geo_level',
 'subnational_region',
 'measurement_scope',
 'commodity_group',
 'is_suspect_year',
 'is_zero_loss',
 'loss_percentage_clean',
 'is_modelled',
 'is_extreme_value',
 'is_lit_outlier']

In [112]:
quality_report = pd.DataFrame(index=world_food_loss.columns)
quality_report["dtype"] = world_food_loss.dtypes.astype(str)
quality_report["total_rows"] = len(world_food_loss)
quality_report["missing_count"] = world_food_loss.isna().sum()
quality_report["missing_pct"] = (world_food_loss.isna().mean() * 100).round(2)
quality_report["unique_count"] = world_food_loss.nunique(dropna=True)
quality_report["unique_pct"] = (world_food_loss.nunique(dropna=True) / max(len(world_food_loss), 1) * 100).round(2)
quality_report["duplicate_row_count"] = world_food_loss.duplicated().sum()
display(quality_report)

,dtype,total_rows,missing_count,missing_pct,unique_count,unique_pct,duplicate_row_count
m49_code,int64,31285,0,0.00,157,0.50,1
country,str,31285,0,0.00,157,0.50,1
cpc_code,string,31285,0,0.00,196,0.63,1
commodity,str,31285,0,0.00,196,0.63,1
year,int64,31285,0,0.00,27,0.09,1
loss_percentage,float64,31285,0,0.00,4629,14.80,1
loss_percentage_original,string,31285,0,0.00,5995,19.16,1
activity,string,31285,7206,23.03,180,0.58,1
food_supply_stage,string,31285,0,0.00,14,0.04,1
treatment,string,31285,29502,94.30,754,2.41,1
cause_of_loss,string,31285,30195,96.52,395,1.26,1
method_data_collection,string,31285,36,0.12,11,0.04,1
reference,string,31285,73,0.23,326,1.04,1
url,string,31285,9324,29.80,948,3.03,1
notes,string,31285,29752,95.10,580,1.85,1
sample_size_n,Float64,31285,29463,94.18,160,0.51,1
sample_size_text,string,31285,29448,94.13,264,0.84,1
loss_quantity_text,string,31285,26235,83.86,3429,10.96,1
loss_tonnes,Float64,31285,26353,84.24,3260,10.42,1
loss_tonnes_per_ha,Float64,31285,31254,99.90,30,0.10,1
quantity_is_rate,boolean,31285,0,0.00,2,0.01,1
quantity_unit_assumed,boolean,31285,0,0.00,2,0.01,1
is_range_value,boolean,31285,0,0.00,2,0.01,1
is_pct_mismatch,boolean,31285,0,0.00,1,0.00,1
is_aggregate,bool,31285,0,0.00,2,0.01,1
continent,str,31285,0,0.00,7,0.02,1
geo_level,str,31285,0,0.00,3,0.01,1
subnational_region,string,31285,29286,93.61,367,1.17,1
measurement_scope,str,31285,0,0.00,4,0.01,1
commodity_group,str,31285,0,0.00,15,0.05,1
is_suspect_year,bool,31285,0,0.00,2,0.01,1
is_zero_loss,bool,31285,0,0.00,2,0.01,1
loss_percentage_clean,float64,31285,60,0.19,4628,14.79,1
is_modelled,boolean,31285,0,0.00,2,0.01,1
is_extreme_value,bool,31285,0,0.00,2,0.01,1
is_lit_outlier,boolean,31285,3,0.01,2,0.01,1

# **Step 2: Finalize the dataset (flags + missing values + validation + save)**

### **1. Detect copies and suspicious values, without deleting suspicious records**
> نفس فكرة مصر (New Valley وزيتون 2014)، بس معمّمة: صف محلي مطابق لصف قومي لنفس الدولة، وقيمة بعيدة 5 أضعاف عن وسيط نفس الدولة والمحصول في السلسلة الكاملة.

In [113]:
df = world_food_loss

# --- subnational row identical to a national row of the same country (probably copied)
key = ["country", "commodity", "year", "food_supply_stage", "loss_percentage"]
national_idx = pd.MultiIndex.from_frame(df.loc[df["geo_level"].eq("National"), key])
df["is_subnational_copy"] = (df["geo_level"].eq("Subnational")
                             & pd.MultiIndex.from_frame(df[key]).isin(national_idx))

# --- whole-chain value 5x higher/lower than the median of the same country + commodity (3+ rows)
whole = df["food_supply_stage"].eq("Whole supply chain") & ~df["is_aggregate"]
g     = df.loc[whole].groupby(["country", "commodity"])["loss_percentage"]
med   = g.transform("median")
cnt   = g.transform("size")
ratio = df.loc[whole, "loss_percentage"] / med
flag  = (cnt >= 3) & (med > 0) & ((ratio < 0.2) | (ratio > 5))
df["is_suspect_value"] = flag.reindex(df.index, fill_value=False)

world_food_loss = df
print(df[["is_subnational_copy", "is_suspect_value"]].sum())
display(df.loc[df["is_subnational_copy"] | df["is_suspect_value"],
               ["country", "commodity", "year", "food_supply_stage", "subnational_region", "loss_percentage"]].head(20))

is_subnational_copy    48
is_suspect_value       70
dtype: int64

,country,commodity,year,food_supply_stage,subnational_region,loss_percentage
999,Canada,Oats,2008,Whole supply chain,<NA>,0.00
1007,Canada,Oats,2007,Whole supply chain,<NA>,0.00
1040,Canada,Barley,2006,Whole supply chain,<NA>,0.00
1042,Canada,Oats,2006,Whole supply chain,<NA>,0.00
1075,Canada,Barley,2005,Whole supply chain,<NA>,0.00
1077,Canada,Oats,2005,Whole supply chain,<NA>,0.00
1221,Canada,Oats,2001,Whole supply chain,<NA>,0.33
2030,China,Wheat,2015,Storage,Jiangxi,1.86
2082,China,Rice,2015,Storage,Jilin,0.92
2098,China,Rice,2015,Storage,Liaoning,0.92
2689,Cuba,Pomelos and grapefruits,2007,Whole supply chain,<NA>,0.07
2709,Cuba,Plantains and others,2005,Whole supply chain,<NA>,5.78
2711,Cuba,Pomelos and grapefruits,2005,Whole supply chain,<NA>,0.00
2720,Cuba,Plantains and others,2004,Whole supply chain,<NA>,15.06
2731,Cuba,Plantains and others,2003,Whole supply chain,<NA>,15.07
2742,Cuba,Plantains and others,2002,Whole supply chain,<NA>,15.07
3659,Ecuador,Green garlic,2001,Whole supply chain,<NA>,2.21
3664,Ecuador,"Groundnuts, excluding shelled",2001,Whole supply chain,<NA>,14.07
3672,Ecuador,Oats,2000,Whole supply chain,<NA>,0.10
3698,Ethiopia,"Beans, dry",2022,Wholesale/Market,Amhara,0.38

### **2. Handle missing values**
| Column | Why missing | Action |
|---|---|---|
| `treatment`, `cause_of_loss` | معظم الدراسات مسجلتهمش (94 لـ 97%) | fill with label **"Not specified"** |
| `subnational_region` | الصف قومي أو aggregate | fill with label **"Not applicable"** |
| `notes`, `activity`, `url`, `reference` | مفيش قيمة في المصدر | labels: **"No note" / "No activity" / "No url" / "No reference"** |
| `method_data_collection` | 36 صف | label **"Unknown"** |
| `loss_tonnes`, `loss_tonnes_per_ha`, `sample_size_n` | المصدر ماذكرهاش | **keep NaN** + indicator column |
| `loss_percentage_clean` | zero values turned into NaN | **keep NaN** |

Numeric columns are NOT imputed (mean/median would invent loss quantities that no source reported).

In [114]:
df = world_food_loss

df["has_loss_tonnes"]        = df["loss_tonnes"].notna()
df["has_loss_tonnes_per_ha"] = df["loss_tonnes_per_ha"].notna()
df["has_sample_size"]        = df["sample_size_n"].notna()
df["has_cause_of_loss"]      = df["cause_of_loss"].notna()

fill_labels = {
    "treatment": "Not specified", "cause_of_loss": "Not specified", "sample_size_text": "Not specified",
    "notes": "No note", "activity": "No activity", "url": "No url", "reference": "No reference",
    "subnational_region": "Not applicable", "method_data_collection": "Unknown",
}
for col, label in fill_labels.items():
    df[col] = df[col].fillna(label)

# reliable = not a suspect year / copy / suspect value / zero / mismatch
# (literature + extreme values are NOT excluded: valid but lower-quality, so keep them flagged)
df["is_reliable"] = ~(df["is_suspect_year"] | df["is_subnational_copy"] | df["is_suspect_value"]
                      | df["is_zero_loss"] | df["is_pct_mismatch"])
df["is_analysis_ready"] = df["is_reliable"] & ~df["is_aggregate"]

world_food_loss = df
print("Reliable rows:", int(df["is_reliable"].sum()), "of", len(df))
print("Analysis-ready rows (reliable + not aggregate):", int(df["is_analysis_ready"].sum()))
display(df.isna().sum()[lambda s: s > 0])

Reliable rows: 31119 of 31285
Analysis-ready rows (reliable + not aggregate): 31012

sample_size_n            29463
loss_quantity_text       26235
loss_tonnes              26353
loss_tonnes_per_ha       31254
loss_percentage_clean       60
is_lit_outlier               3
dtype: int64

### **3. Types, column order, validation**

In [115]:
df = world_food_loss

cat_cols = ["country", "continent", "commodity", "commodity_group", "food_supply_stage",
            "measurement_scope", "geo_level", "subnational_region", "treatment",
            "method_data_collection", "reference"]
for c in cat_cols:
    df[c] = df[c].astype("category")

final_cols = [
    # what / when / where
    "country", "m49_code", "continent", "geo_level", "subnational_region",
    "cpc_code", "commodity", "commodity_group", "year",
    # stage
    "food_supply_stage", "measurement_scope", "activity", "treatment", "cause_of_loss",
    # values
    "loss_percentage", "loss_percentage_clean", "loss_percentage_original",
    "loss_tonnes", "has_loss_tonnes", "loss_tonnes_per_ha", "has_loss_tonnes_per_ha",
    "quantity_unit_assumed", "quantity_is_rate", "loss_quantity_text",
    "sample_size_n", "has_sample_size", "sample_size_text", "has_cause_of_loss",
    # quality flags
    "is_analysis_ready", "is_reliable", "is_aggregate", "is_suspect_year", "is_lit_outlier",
    "is_subnational_copy", "is_suspect_value", "is_zero_loss", "is_pct_mismatch",
    "is_range_value", "is_extreme_value", "is_modelled",
    # source
    "method_data_collection", "reference", "url", "notes",
]
df = df[final_cols]
for c in df.select_dtypes("boolean").columns:
    df[c] = df[c].fillna(False).astype(bool)
for c in df.select_dtypes("Float64").columns:
    df[c] = df[c].astype("float64")
n_dup = int(df.duplicated().sum())            # duplicates created by unifying country/commodity names
df = df.drop_duplicates().reset_index(drop=True)
print("duplicates removed after name unification:", n_dup)

# ---- validation (will raise an error if something is wrong) ----
assert df.duplicated().sum() == 0,                       "duplicate rows found"
assert df["loss_percentage"].between(0, 100).all(),      "loss_percentage out of 0-100"
cpc_ok = df["cpc_code"].str.fullmatch(r"\d{4,6}[A-Za-z]?(?:\.\d{1,2})?", na=False)   # 02351f, 021116i, 21111.01
if not cpc_ok.all():
    print("Unusual cpc_code values:"); print(df.loc[~cpc_ok, "cpc_code"].value_counts().head(20))
assert cpc_ok.all(),                                     "bad cpc_code format"
assert df["year"].between(2000, 2026).all(),             "year out of range"
key_cols = ["country", "cpc_code", "commodity", "year", "loss_percentage", "food_supply_stage",
            "measurement_scope", "geo_level", "method_data_collection", "reference"]
assert df[key_cols].notna().all().all(),                 "missing values in key columns"
assert df["country"].nunique() > 100,                    "countries were lost!"
print("All checks passed.", df.shape, "| countries:", df.loc[~df["is_aggregate"], "country"].nunique())

world_food_loss_final = df
display(df.head())

duplicates removed after name unification: 1
All checks passed. (31284, 44) | countries: 143

,country,m49_code,continent,geo_level,subnational_region,cpc_code,commodity,commodity_group,year,food_supply_stage,...,is_suspect_value,is_zero_loss,is_pct_mismatch,is_range_value,is_extreme_value,is_modelled,method_data_collection,reference,url,notes
0,World,1,Aggregate,Aggregate,Not applicable,0111,Wheat,Cereals,2022,Processing,...,False,False,False,False,False,False,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",No url,Derived product is wheat flour
1,World,1,Aggregate,Aggregate,Not applicable,0112,Maize (corn),Cereals,2022,Processing,...,False,False,False,False,False,False,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",No url,Derived product is maize flour.
2,World,1,Aggregate,Aggregate,Not applicable,0112,Maize (corn),Cereals,2022,Processing,...,False,False,False,False,False,False,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",No url,Derived product is Maize (corn) grits.
3,World,1,Aggregate,Aggregate,Not applicable,0112,Maize (corn),Cereals,2022,Processing,...,False,False,False,False,False,False,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",No url,Derived product is Maize (corn) grits flaked.
4,World,1,Aggregate,Aggregate,Not applicable,0112,Maize (corn),Cereals,2022,Processing,...,False,False,False,False,False,False,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",No url,Derived product is corn starch.

### **4. Save the final data**
| الملف | السؤال التحليلي الأساسي |
| :--- | :--- |
| **World-food-waste_final.csv** | إيه كل البيانات المتاحة بعد التنظيف؟ |
| **World-whole-chain.csv** | إزاي نقارن نسب الفقد بين المحاصيل والدول على مستوى السلسلة بالكامل؟ |
| **World-stage-level.csv** | إيه مراحل الفقد المسجلة لكل محصول ودولة (مرحلة واحدة)؟ |
| **World-unknown-scope.csv** | الصفوف اللي مرحلتها مجهولة، للمراجعة اليدوية |
| **World-country-commodity.csv** | إزاي نقارن الدول ببعض من غير ما الدول الكبيرة (أمريكا، الهند، إثيوبيا...) تسيطر على المتوسط؟ (median لكل دولة × محصول × نطاق) |

In [116]:
OUT_DIR = Path("../final-data-set/world")
OUT_DIR.mkdir(parents=True, exist_ok=True)

world_food_loss_final.to_csv(OUT_DIR / "World-food-waste_final.csv", index=False)

# ready-made subsets for Step 3 (analysis): reliable country rows only
ready = world_food_loss_final[world_food_loss_final["is_analysis_ready"]]
ready[ready["measurement_scope"] == "Whole chain"].to_csv(OUT_DIR / "World-whole-chain.csv", index=False)
ready[ready["measurement_scope"] == "Single stage"].to_csv(OUT_DIR / "World-stage-level.csv", index=False)
world_food_loss_final[world_food_loss_final["measurement_scope"] == "Unknown"] \
    .to_csv(OUT_DIR / "World-unknown-scope.csv", index=False)

country_commodity = (ready.groupby(["country", "continent", "commodity", "commodity_group", "measurement_scope"],
                                   observed=True)
                          .agg(median_loss_pct=("loss_percentage", "median"),
                               mean_loss_pct=("loss_percentage", "mean"),
                               n_rows=("loss_percentage", "size"),
                               n_years=("year", "nunique"))
                          .reset_index())
country_commodity.to_csv(OUT_DIR / "World-country-commodity.csv", index=False)
print("Saved 5 files in", OUT_DIR.resolve(), "|", country_commodity.shape)

Saved 5 files in D:\My_projects\data-engineer\waste-food-project\final-data-set\world | (1895, 9)

# ***Final Analysis***

In [117]:
quality_report = pd.DataFrame(index=world_food_loss_final.columns)
quality_report["dtype"] = world_food_loss_final.dtypes.astype(str)
quality_report["total_rows"] = len(world_food_loss_final)
quality_report["missing_count"] = world_food_loss_final.isna().sum()
quality_report["missing_pct"] = (world_food_loss_final.isna().mean() * 100).round(2)
quality_report["unique_count"] = world_food_loss_final.nunique(dropna=True)
quality_report["unique_pct"] = (world_food_loss_final.nunique(dropna=True) / max(len(world_food_loss_final), 1) * 100).round(2)
quality_report["duplicate_row_count"] = world_food_loss_final.duplicated().sum()
quality_report["memory_bytes"] = world_food_loss_final.memory_usage(deep=True).iloc[1:].values
display(quality_report)

,dtype,total_rows,missing_count,missing_pct,unique_count,unique_pct,duplicate_row_count,memory_bytes
country,category,31284,0,0.00,157,0.50,0,76069
m49_code,int64,31284,0,0.00,157,0.50,0,250272
continent,category,31284,0,0.00,7,0.02,0,31985
geo_level,category,31284,0,0.00,3,0.01,0,31459
subnational_region,category,31284,0,0.00,368,1.18,0,88517
cpc_code,string,31284,0,0.00,196,0.63,0,1671936
commodity,category,31284,0,0.00,196,0.63,0,75854
commodity_group,category,31284,0,0.00,15,0.05,0,32262
year,int64,31284,0,0.00,27,0.09,0,250272
food_supply_stage,category,31284,0,0.00,14,0.04,0,32128
measurement_scope,category,31284,0,0.00,4,0.01,0,31706
activity,string,31284,0,0.00,181,0.58,0,1930856
treatment,category,31284,0,0.00,755,2.41,0,151981
cause_of_loss,string,31284,0,0.00,396,1.27,0,2049122
loss_percentage,float64,31284,0,0.00,4629,14.80,0,250272
loss_percentage_clean,float64,31284,60,0.19,4628,14.79,0,250272
loss_percentage_original,string,31284,0,0.00,5995,19.16,0,1671029
loss_tonnes,float64,31284,26352,84.23,3260,10.42,0,250272
has_loss_tonnes,bool,31284,0,0.00,2,0.01,0,31284
loss_tonnes_per_ha,float64,31284,31253,99.90,30,0.10,0,250272
has_loss_tonnes_per_ha,bool,31284,0,0.00,2,0.01,0,31284
quantity_unit_assumed,bool,31284,0,0.00,2,0.01,0,31284
quantity_is_rate,bool,31284,0,0.00,2,0.01,0,31284
loss_quantity_text,string,31284,26234,83.86,3429,10.96,0,1742317
sample_size_n,float64,31284,29463,94.18,160,0.51,0,250272
has_sample_size,bool,31284,0,0.00,2,0.01,0,31284
sample_size_text,string,31284,0,0.00,265,0.85,0,2037596
has_cause_of_loss,bool,31284,0,0.00,2,0.01,0,31284
is_analysis_ready,bool,31284,0,0.00,2,0.01,0,31284
is_reliable,bool,31284,0,0.00,2,0.01,0,31284
is_aggregate,bool,31284,0,0.00,2,0.01,0,31284
is_suspect_year,bool,31284,0,0.00,2,0.01,0,31284
is_lit_outlier,bool,31284,0,0.00,2,0.01,0,31284
is_subnational_copy,bool,31284,0,0.00,2,0.01,0,31284
is_suspect_value,bool,31284,0,0.00,2,0.01,0,31284
is_zero_loss,bool,31284,0,0.00,2,0.01,0,31284
is_pct_mismatch,bool,31284,0,0.00,1,0.00,0,31284
is_range_value,bool,31284,0,0.00,2,0.01,0,31284
is_extreme_value,bool,31284,0,0.00,2,0.01,0,31284
is_modelled,bool,31284,0,0.00,2,0.01,0,31284
method_data_collection,category,31284,0,0.00,12,0.04,0,32078
reference,category,31284,0,0.00,327,1.05,0,138362
url,string,31284,0,0.00,949,3.03,0,3560231
notes,string,31284,0,0.00,581,1.86,0,2000880

## Coverage check (الداتا مش متوازنة بين الدول)

In [118]:
ready = world_food_loss_final[world_food_loss_final["is_analysis_ready"]]
coverage = (ready.groupby("country", observed=True)
                 .agg(rows=("loss_percentage", "size"), commodities=("commodity", "nunique"), years=("year", "nunique"))
                 .sort_values("rows", ascending=False))
coverage["share_pct"] = (coverage["rows"] / coverage["rows"].sum() * 100).round(2)
display(coverage.head(10))
print("Top 5 countries hold", round(coverage["share_pct"].head(5).sum(), 1), "% of all rows")
print("Countries with fewer than 5 rows:", int((coverage["rows"] < 5).sum()))

                          rows  commodities  years  share_pct
country
United States of America  1575           89     22       5.08
India                     1425           56     18       4.60
Ethiopia                  1145           32     23       3.69
Kenya                     1044           19     22       3.37
Ghana                      916           28     22       2.95
Uganda                     879           11     22       2.83
Burkina Faso               767            7     22       2.47
Zambia                     766            6     22       2.47
Malawi                     765            7     22       2.47
Senegal                    749            6     22       2.42

Top 5 countries hold 19.7 % of all rows
Countries with fewer than 5 rows: 17

## Data dictionary (قاموس الأعمدة النهائي)

| # | العمود | النوع | معناه | قراءة الأرقام (من الداتا الحقيقية) |
| -- | -- | -- | -- | -- |
| 1 | `country` | `category` | اسم الدولة أو الإقليم | 143 دولة + 14 اسم aggregate (World وAfrica...) |
| 2 | `m49_code` | `int64` | كود الدولة (UN M49) | كود واحد لكل اسم دولة (بعد توحيد UK وTaiwan) |
| 3 | `continent` | `category` | القارة | Africa أكتر قارة (حوالي 68% من الصفوف)، وAggregate للصفوف المجمعة |
| 4 | `geo_level` | `category` | المستوى الجغرافي: National أو Subnational أو Aggregate | 29,179 قومي و1,998 محلي و107 aggregate |
| 5 | `subnational_region` | `category` | المكان جوه الدولة (مقاطعة، district...) | Not applicable لو الصف قومي |
| 6 | `cpc_code` | `string` | كود المنتج في تصنيف CPC (نص) | 196 كود. مش كله بيبدأ بصفر (لحوم وألبان بتبدأ بـ 2) |
| 7 | `commodity` | `category` | اسم المحصول أو المنتج | 196 منتج بعد توحيد الأسماء |
| 8 | `commodity_group` | `category` | مجموعة المنتج من كود CPC | 15 مجموعة، والحبوب 73% من الصفوف |
| 9 | `year` | `int64` | سنة الدراسة | من 2000 لـ 2026، 27 سنة |
| 10 | `food_supply_stage` | `category` | مرحلة سلسلة الإمداد | 14 مرحلة بعد الدمج وملء الناقص من activity |
| 11 | `measurement_scope` | `category` | نطاق القياس: Whole chain / Single stage / Post-harvest / Unknown | 4 قيم. 6,005 سلسلة كاملة و25,065 مرحلة واحدة |
| 12 | `activity` | `string` | النشاط زي ما اتكتب في المصدر | نص حر، استخدمناه نملى المرحلة الناقصة |
| 13 | `treatment` | `category` | الطريقة أو الظرف المستخدم (نص حر) | 755 قيمة، و94.3% Not specified |
| 14 | `cause_of_loss` | `string` | سبب الفقد (نص حر) | موجود في 1,089 صف بس |
| 15 | `loss_percentage` | `float64` | **نسبة الفاقد %، العمود الرئيسي** | من 0 لـ 65، الوسيط 2.65% |
| 16 | `loss_percentage_clean` | `float64` | نفس النسبة والأصفار NaN | ناقص 60 صف (الأصفار) |
| 17 | `loss_percentage_original` | `string` | النسبة زي ما اتكتبت في المصدر (مرجع بس) | 5,995 قيمة، منها 890 مدى زي `5% - 9%` |
| 18 | `loss_tonnes` | `float64` | كمية الفاقد بالطن | موجودة في 4,932 صف، وناقصة 26,352 (84.2%) |
| 19 | `has_loss_tonnes` | `bool` | هل الكمية موجودة؟ | 4,932 True و26,352 False |
| 20 | `loss_tonnes_per_ha` | `float64` | الفاقد بالطن لكل هكتار | موجودة في 31 صف بس |
| 21 | `has_loss_tonnes_per_ha` | `bool` | هل طن/هكتار موجودة؟ | 31 True |
| 22 | `quantity_unit_assumed` | `bool` | الكمية رقم من غير وحدة (افترضنا طن) | 4,537 صف، استبعدها لو عايز كميات مؤكدة |
| 23 | `quantity_is_rate` | `bool` | الكمية معدل أو عدد (kg/quintal، head...) مش إجمالي | 87 صف، loss_tonnes فيهم فاضية |
| 24 | `loss_quantity_text` | `string` | الكمية زي ما اتكتبت في المصدر | مرجع للمراجعة |
| 25 | `sample_size_n` | `float64` | حجم العينة كرقم | موجود في 1,821 صف بس |
| 26 | `has_sample_size` | `bool` | هل حجم العينة موجود؟ | 1,821 True |
| 27 | `sample_size_text` | `string` | حجم العينة زي ما اتكتب | نص أصلي |
| 28 | `has_cause_of_loss` | `bool` | هل سبب الفقد موجود؟ | 1,089 True |
| 29 | `is_analysis_ready` | `bool` | **صف سليم ومش aggregate: استخدمه في التحليل** | 31,011 صف من 31,284 |
| 30 | `is_reliable` | `bool` | مش سنة مشكوك ولا نسخة ولا قيمة مشكوك ولا صفر ولا mismatch | 31,118 True |
| 31 | `is_aggregate` | `bool` | صف World أو إقليم مجمع | 107 صف، استبعده من تحليل الدول |
| 32 | `is_suspect_year` | `bool` | هل السنة مشكوك فيها (بعد 2025)؟ | 5 صف (طماطم مصر 2026) |
| 33 | `is_lit_outlier` | `bool` | قيمة متطرفة جوه محصولها ومصدرها Literature Review | 117 صف (علّمها ومتحذفهاش) |
| 34 | `is_subnational_copy` | `bool` | صف محلي مطابق لصف قومي لنفس الدولة | 48 صف (ممكن تكون نسخ) |
| 35 | `is_suspect_value` | `bool` | قيمة بعيدة 5 أضعاف عن وسيط نفس الدولة والمحصول (سلسلة كاملة) | 70 صف، راجعها |
| 36 | `is_zero_loss` | `bool` | هل النسبة صفر؟ | 60 صف |
| 37 | `is_pct_mismatch` | `bool` | النص الأصلي مش بيطابق الرقم | 0 صف |
| 38 | `is_range_value` | `bool` | القيمة الأصلية مدى (مثلاً 5% - 9%) | 890 صف، والرقم في loss_percentage هو الوسط |
| 39 | `is_extreme_value` | `bool` | فوق Q3 + 3*IQR جوه محصولها ونطاقها (20 صف أو أكتر) | 742 صف، تحذير بس (ممكن تكون حقيقية) |
| 40 | `is_modelled` | `bool` | التقدير من موديل (زي APHLIS) مش قياس | 19,494 صف (62.3%). حللها لوحدها |
| 41 | `method_data_collection` | `category` | طريقة جمع البيانات | 12 طريقة. Modelled Estimates أكترها |
| 42 | `reference` | `category` | المرجع العلمي الكامل | 327 مرجع |
| 43 | `url` | `string` | رابط المصدر | No url لو مفيش |
| 44 | `notes` | `string` | ملاحظات المصدر | 95.1% No note |

## Checklist قبل Step 3
1. الصفوف النهائية **31,284** (31,465 ناقص 180 مكرر ناقص 1 ظهر بعد توحيد الأسماء).
2. **143 دولة** + 14 اسم aggregate (107 صف).
3. كل أكواد CPC بتتحفظ نص زي ما هي (مفيش صفر بيتضاف).
4. `is_modelled` حوالي 62%: حلل المقاسة والمقدّرة كل واحدة لوحدها.
5. للمقارنات العالمية استخدم `World-country-commodity.csv` بدل كل الصفوف.
6. اذكر في التقرير إن FAO مش بتضمن صحة الداتا (مصادر خارجية).

In [120]:
egypt_food_waste = pd.read_csv('../final-data-set/world/World-food-waste_final.csv');
egypt_food_waste.head()

,country,m49_code,continent,geo_level,subnational_region,cpc_code,commodity,commodity_group,year,food_supply_stage,...,is_suspect_value,is_zero_loss,is_pct_mismatch,is_range_value,is_extreme_value,is_modelled,method_data_collection,reference,url,notes
0,World,1,Aggregate,Aggregate,Not applicable,0111,Wheat,Cereals,2022,Processing,...,False,False,False,False,False,False,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",No url,Derived product is wheat flour
1,World,1,Aggregate,Aggregate,Not applicable,0112,Maize (corn),Cereals,2022,Processing,...,False,False,False,False,False,False,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",No url,Derived product is maize flour.
2,World,1,Aggregate,Aggregate,Not applicable,0112,Maize (corn),Cereals,2022,Processing,...,False,False,False,False,False,False,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",No url,Derived product is Maize (corn) grits.
3,World,1,Aggregate,Aggregate,Not applicable,0112,Maize (corn),Cereals,2022,Processing,...,False,False,False,False,False,False,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",No url,Derived product is Maize (corn) grits flaked.
4,World,1,Aggregate,Aggregate,Not applicable,0112,Maize (corn),Cereals,2022,Processing,...,False,False,False,False,False,False,Survey,"Aintzane Esturo, (2022), Cereals Extraction Ra...",No url,Derived product is corn starch.